Repository conda-forge/staged-recipes, pull requests merged in 2018-05, with the labels that each got.

#4995 added r-ca
  recipes/r-ca/bld.bat
  recipes/r-ca/build.sh
  recipes/r-ca/meta.yaml
Labels: R

#5774 Add pigar
  recipes/pigar/meta.yaml
Labels: Package request

#5798 Readd skijumpdesign
  recipes/skijumpdesign/meta.yaml
Labels: readd

#5866 Reuse Github token in `repo_exists`
  .travis_scripts/create_feedstocks.py
Labels: maintenance

#5867 Readd conda-smithy dev converted recipes
  recipes/cc-plugin-ugrid/meta.yaml
  recipes/dask-jobqueue/meta.yaml
  recipes/editdistance/LICENSE
  recipes/editdistance/meta.yaml
  recipes/gast/LICENSE
  recipes/gast/meta.yaml
  recipes/geckodriver/bld.bat
  recipes/geckodriver/build.sh
  recipes/geckodriver/meta.yaml
  recipes/geckodriver/mpl-2.0.txt
  recipes/go-archiver/bld.bat
  recipes/go-archiver/build.sh
  recipes/go-archiver/meta.yaml
  recipes/gpflow/meta.yaml
  recipes/jeepney/meta.yaml
  recipes/lammps/LICENSE
  recipes/lammps/build.sh
  recipes/lammps/meta.yaml
  recipes/ldc/bld.bat
  recipes/ldc/bld2.bat
  recipes/ldc/build.sh
  recipes/ldc/meta.yaml
  recipes/ldc/use_md.patch
  recipes/nose2/meta.yaml
  recipes/numina/meta.yaml
  recipes/progressbar33/meta.yaml
  recipes/pytest-console-scripts/LICENSE
  recipes/pytest-console-scripts/meta.yaml
Labels: maintenance

#5868 Readd sphinx-releases [ci skip]
  recipes/sphinx-releases/meta.yaml
Labels: readd

#5912 Ignore JetBrains IDE project files
  .gitignore
Labels: maintenance

#5869 Docker build fixes
  .circleci/build_steps.sh
  .circleci/run_docker_build.sh
Labels: maintenance

#5925 Create dummy noarch index for conda on Linux
  .circleci/build_steps.sh
Labels: maintenance

#5926 Use `conda`'s quiet option when installing
  .circleci/build_steps.sh
Labels: maintenance

#5903 [R2M] Package jaydebeapi
  recipes/jaydebeapi/meta.yaml
Labels: Package request

#5130 Add Metsim Recipe
  recipes/metsim/LICENSE
  recipes/metsim/meta.yaml
Labels: Awaiting author contribution
