Repository conda-forge/staged-recipes, pull requests merged in 2018-08, with the labels that each got.

#6426 Add r-biclust.
  recipes/r-biclust/bld.bat
  recipes/r-biclust/build.sh
  recipes/r-biclust/meta.yaml
Labels: in progress

#6441 Add srm
  recipes/srm/build.sh
  recipes/srm/meta.yaml
Labels: Package request

#6454 Add wabt
  recipes/wabt/bld.bat
  recipes/wabt/build.sh
  recipes/wabt/meta.yaml
Labels: Package request

#6534 Remove `py-graphviz` [ci skip]
  recipes/py-graphviz/meta.yaml
Labels: maintenance

#6599 Fix version checks in xmitgcm
  recipes/xmitgcm/meta.yaml
Labels: maintenance

#6598 Add dask-image
  recipes/dask-image/meta.yaml
Labels: Package request
