Repository conda-forge/staged-recipes, pull requests merged in 2018-04, with the labels that each got.

#5560 update pip description [skip ci] [ci skip]
  README.md
Labels: docs

#5612 Revert "Pin conda to 4.3 in feedstock conversion"
  .travis_scripts/create_feedstocks
Labels: maintenance

#5671 Package (Python) lz4
  recipes/lz4/meta.yaml
Labels: Package request

#5674 Readd some recipes that failed conversion [ci skip]
  recipes/d3ploy/meta.yaml
  recipes/logging_exceptions/meta.yaml
  recipes/lz4/meta.yaml
  recipes/molvs/meta.yaml
  recipes/pdal/build.sh
  recipes/pdal/meta.yaml
  recipes/pscript/meta.yaml
Labels: readd

#5701 Fold Travis build trigger into create_feedstocks
  .travis.yml
  .travis_scripts/create_feedstocks
Labels: maintenance

#5744 Ignore `.swp` files
  .gitignore
Labels: maintenance
