Repository conda-forge/staged-recipes, pull requests merged in 2018-02, with the labels that each got.

#4874 added r-qiimer
  recipes/r-qiimer/bld.bat
  recipes/r-qiimer/build.sh
  recipes/r-qiimer/meta.yaml
Labels: R

#4919 Add r-gghighlight.
  recipes/r-gghighlight/bld.bat
  recipes/r-gghighlight/build.sh
  recipes/r-gghighlight/meta.yaml
Labels: R

#5260 Temporarily disable trace of shell commands
  .travis_scripts/create_feedstocks
Labels: maintenance

#5219 Add flock
  recipes/flock/build.sh
  recipes/flock/meta.yaml
Labels: Package request

#2520 added dummydata recipe
  recipes/dummydata/meta.yaml
Labels: Awaiting author contribution
