Repository conda-forge/staged-recipes, pull requests merged in 2019-10, with the labels that each got.

#5069 [WIP] Add summa
  recipes/summa/LICENSE.txt
  recipes/summa/build.sh
  recipes/summa/meta.yaml
  recipes/summa/remove_pg.patch
Labels: pangeo-sprint

#9694 Add NCCL
  recipes/nccl/PR_220.patch
  recipes/nccl/build.sh
  recipes/nccl/meta.yaml
Labels: Package request

#9802 Config docker image in CI
  .azure-pipelines/azure-pipelines-linux.yml
  .circleci/run_docker_build.sh
Labels: maintenance

#9860 Run `setup_conda_rc` as part of all builds
  .appveyor.yml
  .azure-pipelines/azure-pipelines-win.yml
  .circleci/build_steps.sh
  .circleci/run_docker_build.sh
Labels: maintenance

#9959 Add CuPy
  recipes/cupy/meta.yaml
  recipes/cupy/run_test.py
Labels: Package request
