Repository conda-forge/staged-recipes, pull requests merged in 2022-04, with the labels that each got.

#17888 Add napari-pyclesperanto-assistant recipe
  recipes/napari-pyclesperanto-assistant/meta.yaml
  recipes/napari-pyclesperanto-assistant/yum_requirements.txt
Labels: bug

#17892 Add napari-itk-io recipe
  recipes/napari-itk-io/meta.yaml
  recipes/napari-itk-io/yum_requirements.txt
Labels: Work in progress - don't review yet

#17893 Add devbio-napari recipe
  recipes/devbio-napari/meta.yaml
  recipes/devbio-napari/yum_requirements.txt
Labels: Work in progress - don't review yet

#17935 Add soxr recipe
  recipes/soxr/bld.bat
  recipes/soxr/build.sh
  recipes/soxr/meta.yaml
Labels: c-cpp

#18015 Adding TVIPS tools
  recipes/tvips-tools/01-setenv.patch
  recipes/tvips-tools/02-version.patch
  recipes/tvips-tools/03-warnings.patch
  recipes/tvips-tools/LICENSE
  recipes/tvips-tools/build.sh
  recipes/tvips-tools/meta.yaml
Labels: c-cpp

#18580 Adding digen
  recipes/digen/meta.yaml
Labels: python

#18493 Add clpeak
  recipes/clpeak/build.sh
  recipes/clpeak/meta.yaml
Labels: staged-recipes, review-requested

#18397 Add bladerf and soapysdr-module-bladerf
  recipes/bladerf/0001-Add-required-ad9361-files-directly.patch
  recipes/bladerf/0002-Rename-bladeRF.dll-to-bladeRF-2.dll-on-Windows.patch
  recipes/bladerf/0003-Add-special-case-for-loading-windows-DLL-in-python.patch
  recipes/bladerf/0004-Modify-Python-bindings-to-load-major-versioned-libbl.patch
  recipes/bladerf/0005-Add-an-option-for-bundling-external-libraries-on-Win.patch
  recipes/bladerf/0006-Fix-test-linking-with-rt-when-glibc-2.17-is-used.patch
  recipes/bladerf/bld.bat
  recipes/bladerf/build.sh
  recipes/bladerf/install.bat
  recipes/bladerf/install.sh
  recipes/bladerf/meta.yaml
  recipes/bladerf/post-link.sh
  recipes/soapysdr-module-bladerf/0001-Adding-support-for-PLL-reference-clock.patch
  recipes/soapysdr-module-bladerf/bld.bat
  recipes/soapysdr-module-bladerf/build.sh
  recipes/soapysdr-module-bladerf/meta.yaml
Labels: c-cpp

#18635 Adding `pdoc` from PyPI
  recipes/pdoc/meta.yaml
Labels: staged-recipes, review-requested

#18641 Adding SQcircuit recipe
  recipes/sqcircuit/meta.yaml
Labels: review-requested, python

#18649 Adding finlogic from PyPI
  recipes/finlogic/meta.yaml
Labels: staged-recipes, review-requested

#18659 Adding astroedu package
  recipes/astroedu/meta.yaml
Labels: review-requested, python

#18657 Added delayed_assert as a package.
  recipes/delayed-assert/meta.yaml
Labels: staged-recipes, review-requested

#18651 adding lenstronomy
  recipes/lenstronomy/meta.yaml
Labels: review-requested, python

#18598 Adding geospatial-ml recipe
  recipes/geospatial-ml/meta.yaml
Labels: review-requested, python

#18668 Add pptree
  recipes/pptree/LICENSE.txt
  recipes/pptree/meta.yaml
Labels: review-requested, python

#18676 DOC: Reword PR template to encourage autolabel action use [ci skip]
  .github/pull_request_template.md
Labels: staged-recipes, review-requested

#18682 Added recipe for Pandemy version 1.0.0
  recipes/pandemy/meta.yaml
Labels: staged-recipes, review-requested

#18351 Add recipe for dict2css
  recipes/dict2css/meta.yaml
Labels: staged-recipes, review-requested

#18663 Added pygod as a package.
  recipes/pygod/meta.yaml
Labels: staged-recipes, review-requested

#18552 Adding unicorn-binance-trailing-stop-loss
  recipes/unicorn-binance-trailing-stop-loss/meta.yaml
Labels: staged-recipes, review-requested

#18696 Added graphistry as a package
  recipes/graphistry/meta.yaml
Labels: staged-recipes, review-requested

#18034 Add MyST-NB-Bokeh recipe
  recipes/myst-nb-bokeh/meta.yaml
Labels: staged-recipes, review-requested

#18689 Package rich-rst
  recipes/rich-rst/meta.yaml
Labels: review-requested, python

#18702 Add conflowgen
  recipes/conflowgen/meta.yaml
Labels: review-requested, python

#18666 Adding ml-research
  recipes/ml-research/meta.yaml
Labels: staged-recipes, review-requested

#18684 finetuning-scheduler recipe
  recipes/finetuning-scheduler/meta.yaml
Labels: review-requested, python

#18704 Nbpreview
  recipes/nbpreview/meta.yaml
Labels: staged-recipes, review-requested, python

#18703 Added pigeon-jupyter as a package
  recipes/pigeon-jupyter/meta.yaml
Labels: staged-recipes, review-requested

#18701 Added jupyterlab-stickyland as a package
  recipes/jupyterlab-stickyland/meta.yaml
Labels: staged-recipes, review-requested

#18638 add libdwarf
  recipes/libdwarf/build.sh
  recipes/libdwarf/meta.yaml
  recipes/libdwarf/patches/0001-add-enable_libdwarf-and-enable_dwarfdump-to-configur.patch
  recipes/libdwarf/patches/0001-use-PATH-resolution-when-testing-dwarfdump.patch
Labels: staged-recipes, review-requested

#18618 Add nwbinspector
  recipes/nwbinspector/meta.yaml
Labels: staged-recipes, review-requested

#17101 Add Jupyterlab_email
  recipes/jupyterlab_email/meta.yaml
Labels: review-requested, python

#18633 Add python-vxi11 recipe
  recipes/python-vxi11/meta.yaml
Labels: review-requested

#18685 Add chopin2 recipe
  recipes/chopin2/meta.yaml
Labels: review-requested, python

#18700 Add splinecalib
  recipes/splinecalib/LICENSE
  recipes/splinecalib/meta.yaml
Labels: review-requested, python

#18686 Add cmakelang recipe (package renamed from cmake-format).
  recipes/cmakelang/LICENSE
  recipes/cmakelang/meta.yaml
  recipes/cmakelang/patch/0001-Fix-setup.py.patch
Labels: staged-recipes, review-requested

#18611 Adds coiled-runtime
  recipes/coiled-runtime/LICENSE
  recipes/coiled-runtime/meta.yaml
Labels: staged-recipes, review-requested

#18712 Testslide
  recipes/testslide/meta.yaml
Labels: staged-recipes, review-requested

#18664 Add aerobulk-python
  recipes/aerobulk-python/meta.yaml
Labels: staged-recipes, review-requested

#18723 This PR adds recipes for epics-alh.
  recipes/epics-alh/build.sh
  recipes/epics-alh/meta.yaml
Labels: staged-recipes, review-requested

#18725 add jupyterlab-webrtc-docprovider 0.1.0
  recipes/jupyterlab-webrtc-docprovider/meta.yaml
Labels: staged-recipes, review-requested, python

#18715 add memray package
  recipes/memray/meta.yaml
Labels: review-requested, python, python-c

#17349 Add three recipes for asdf schema
  recipes/asdf-coordinates-schemas/meta.yaml
  recipes/asdf-transform-schemas/meta.yaml
  recipes/asdf-wcs-schemas/meta.yaml
Labels: review-requested, python

#18743 Add recipe for r-islr
  recipes/r-islr/bld.bat
  recipes/r-islr/build.sh
  recipes/r-islr/meta.yaml
Labels: R, review-requested

#18740 Add recipe for r-juliacall
  recipes/r-juliacall/bld.bat
  recipes/r-juliacall/build.sh
  recipes/r-juliacall/meta.yaml
Labels: R, review-requested

#18732 Adding `datajudge`.
  recipes/datajudge/meta.yaml
Labels: staged-recipes, review-requested

#18717 Add recipe for whey-pth
  recipes/whey-pth/meta.yaml
Labels: review-requested, python

#18716 Create first conda-forge 2.2.2 fine recipe
  recipes/fine/LICENSE.txt
  recipes/fine/meta.yaml
Labels: staged-recipes, review-requested

#18718 Adding recipe for seismon
  recipes/seismon/meta.yaml
Labels: staged-recipes, review-requested

#18726 First attempt to release catalystcoop.pudl_catalog on conda-forge
  recipes/catalystcoop.pudl_catalog/meta.yaml
Labels: review-requested, python

#17051 Add osmium-tool
  recipes/osmium-tool/bld.bat
  recipes/osmium-tool/build.sh
  recipes/osmium-tool/meta.yaml
Labels: review-requested, c-cpp

#18752 Add eeglabio
  recipes/eeglabio/LICENCE
  recipes/eeglabio/meta.yaml
Labels: staged-recipes, review-requested

#18764 Adding ubtsl
  recipes/ubtsl/meta.yaml
Labels: staged-recipes, review-requested

#17256 MTN add alphacsc recipee
  recipes/alphacsc/meta.yaml
  recipes/alphacsc/patches/001-remove_sporco_files_from_package.patch
Labels: review-requested, python-c

#18754 Add pytest-fail-slow
  recipes/pytest-fail-slow/meta.yaml
Labels: review-requested, python

#18714 Adding sketchnu recipe
  recipes/sketchnu/meta.yaml
Labels: staged-recipes, review-requested

#18773 Add recipe for `decorit`
  recipes/decorit/meta.yaml
Labels: staged-recipes, review-requested

#18761 Create first GeoKit recipe
  recipes/geokit/MIT-LICENSE.txt
  recipes/geokit/meta.yaml
Labels: staged-recipes, review-requested

#18763 Add hdlib recipe
  recipes/hdlib/LICENSE
  recipes/hdlib/meta.yaml
Labels: staged-recipes, review-requested

#18749 Add server-thread
  recipes/server-thread/meta.yaml
Labels: review-requested, python

#18781 Add jupyterlab-search-replace
  recipes/jupyterlab-search-replace/meta.yaml
Labels: review-requested, python

#18363 add pdftopng
  recipes/pdftopng/0001-fix-setup.patch
  recipes/pdftopng/bld.bat
  recipes/pdftopng/build.sh
  recipes/pdftopng/meta.yaml
  recipes/pdftopng/setOverprintPreview.patch
Labels: review-requested, python-c

#18736 Add palantir-sdk recipe
  recipes/palantir-sdk/meta.yaml
Labels: review-requested, python

#18785 Add django-large-image
  recipes/django-large-image/meta.yaml
Labels: staged-recipes, review-requested, python

#18176 Add dyff, a go binary.
  recipes/dyff/conda_build_config.yaml
  recipes/dyff/meta.yaml
Labels: staged-recipes, review-requested, go

#17843 Add recipe for ytree package.
  recipes/ytree/meta.yaml
Labels: review-requested, python

#17995 Adding dpd-components
  recipes/dpd-components/LICENSE.txt
  recipes/dpd-components/meta.yaml
Labels: review-requested, python

#18107 Add recipe for lsd
  recipes/lsdeluxe/bld.bat
  recipes/lsdeluxe/build.sh
  recipes/lsdeluxe/meta.yaml
Labels: review-requested, c-cpp, rust

#18336 Add flask_request_id and wsgi-request-id via grayskull
  recipes/flask_request_id/meta.yaml
  recipes/wsgi-request-id/meta.yaml
Labels: review-requested, python

#18507 Adding cnmaps
  recipes/cnmaps/meta.yaml
Labels: review-requested, python

#17540 initial commit for alb dependencies
  recipes/qudida/meta.yaml
Labels: Awaiting author contribution, python

#18772 add meta.yaml for dustgoggles
  recipes/dustgoggles/meta.yaml
Labels: staged-recipes, review-requested

#18753 Add pydevtool
  recipes/pydevtool/meta.yaml
Labels: Awaiting author contribution, python

#18787 Added mlnotify as a package
  recipes/mlnotify/meta.yaml
Labels: staged-recipes, review-requested

#18728 Add_openspoor
  recipes/openspoor/meta.yaml
Labels: review-requested, python

#18793 Added pynomaly as a package
  recipes/pynomaly/LICENSE.txt
  recipes/pynomaly/meta.yaml
Labels: staged-recipes, review-requested

#18782 Add recipe for `prettypyplot`
  recipes/prettypyplot/meta.yaml
Labels: review-requested, python

#18706 Type annotations for LibreOffice UNO Script
  recipes/types-uno-script/meta.yaml
Labels: staged-recipes, review-requested

#18699 Type annotations for LibreOffice API
  recipes/types-unopy/meta.yaml
Labels: staged-recipes, review-requested

#18799 add opendap-protocol
  recipes/opendap-protocol/meta.yaml
Labels: staged-recipes, review-requested

#18548 Add recipe for pyRMSD
  recipes/pyrmsd/cxx11-narrowing.patch
  recipes/pyrmsd/meta.yaml
  recipes/pyrmsd/msvc-compile.patch
  recipes/pyrmsd/run_test.py
Labels: review-requested, python, python-c

#18796 Add recipe for flake8-requirements
  recipes/flake8-requirements/meta.yaml
Labels: staged-recipes, review-requested

#18805 add PyRAMS recipe
  recipes/pyrams/meta.yaml
Labels: review-requested, python

#18804 Adding ezgooey
  recipes/ezgooey/meta.yaml
Labels: review-requested, python

#18800 Add dvclive
  recipes/dvclive/meta.yaml
Labels: review-requested, python

#18801 Semi ate project database
  recipes/semi-ate-project-database/meta.yaml
Labels: review-requested, python
