Repository conda-forge/staged-recipes, pull requests merged in 2022-10, with the labels that each got.

#20603 Added receipe for py-modelrunner
  recipes/py-modelrunner/meta.yaml
Labels: review-requested, python

#19360 add espnet and dependencies
  recipes/ci-sdr/meta.yaml
  recipes/ctc-segmentation/meta.yaml
  recipes/espnet-tts-frontend/meta.yaml
  recipes/espnet/meta.yaml
  recipes/fast-bss-eval/meta.yaml
  recipes/jamo/LICENSE
  recipes/jamo/meta.yaml
  recipes/kaldiio/meta.yaml
  recipes/pytorch-wpe/LICENSE
  recipes/pytorch-wpe/meta.yaml
  recipes/torch-complex/LICENSE
  recipes/torch-complex/meta.yaml
Labels: review-requested, python, python-c

#20610 adding jaxtyping to conda-forge
  recipes/jaxtyping/meta.yaml
Labels: review-requested, python

#20613 Adding `sqlathanor`
  recipes/sqlathanor/meta.yaml
Labels: review-requested, python

#18524 Add new recipe for lux-feedstock
  recipes/lux/meta.yaml
Labels: Awaiting author contribution, stale, python

#18896 Adding elapid
  recipes/elapid/meta.yaml
Labels: Awaiting author contribution, staged-recipes

#20585 Add recipe for gz-math
  recipes/gz-math/bld_cxx.bat
  recipes/gz-math/bld_py.bat
  recipes/gz-math/build_cxx.sh
  recipes/gz-math/build_py.sh
  recipes/gz-math/meta.yaml
  recipes/gz-math/standalone_bindings.patch
Labels: review-requested, c-cpp, python-c

#20620 Add hydrosignatures
  recipes/hydrosignatures/meta.yaml
Labels: review-requested, python

#20215 Adding omsl - OpenModelica Modelica Standard Language
  recipes/omsl/LICENSE.txt
  recipes/omsl/build.sh
  recipes/omsl/meta.yaml
  recipes/omsl/run_test.py
Labels: staged-recipes, review-requested

#20626 add csvinsight
  recipes/csvinsight/meta.yaml
Labels: staged-recipes, review-requested

#20629 add pycobertura
  recipes/pycobertura/meta.yaml
Labels: staged-recipes, review-requested

#20633 add face-recognition
  recipes/face-recognition/meta.yaml
Labels: staged-recipes, review-requested

#20630 Add fastapi-mail
  recipes/fastapi-mail/meta.yaml
Labels: staged-recipes, review-requested

#20640 Add jsonschema-default
  recipes/jsonschema-default/meta.yaml
Labels: review-requested, python

#20627 Add recipe for gz-common
  recipes/gz-common/bld_cxx.bat
  recipes/gz-common/build_cxx.sh
  recipes/gz-common/librt_linkage.patch
  recipes/gz-common/macro_path_binary_relocation.patch
  recipes/gz-common/meta.yaml
Labels: review-requested, c-cpp

#20611 Add recipe for gz-tools
  recipes/gz-tools/bld_cxx.bat
  recipes/gz-tools/build_cxx.sh
  recipes/gz-tools/meta.yaml
Labels: review-requested, c-cpp

#20520 Add r-icu feedstock
  recipes/r-ricu/bld.bat
  recipes/r-ricu/build.sh
  recipes/r-ricu/meta.yaml
Labels: staged-recipes, review-requested

#20651 Add mastercard-client-encryption
  recipes/mastercard-client-encryption/meta.yaml
Labels: review-requested, python

#20650 Add mastercard-oauth1-signer
  recipes/mastercard-oauth1-signer/meta.yaml
Labels: review-requested, python

#20657 Add recipe for metadata-inspector to inspect cliamte data.
  recipes/metadata-inspector/meta.yaml
Labels: staged-recipes, review-requested, python

#20632 Adding datarobot-bp-workshop
  recipes/datarobot-bp-workshop/meta.yaml
Labels: review-requested, python

#19683 Add Package: bigdft-suite
  recipes/bigdft/LICENSE
  recipes/bigdft/activate.sh
  recipes/bigdft/backup_variables.py
  recipes/bigdft/build.sh
  recipes/bigdft/conda.rc
  recipes/bigdft/conda_build_config.yaml
  recipes/bigdft/deactivate.sh
  recipes/bigdft/licenses/GaIN.copying
  recipes/bigdft/licenses/atlab.copying
  recipes/bigdft/licenses/bigdft.copying
  recipes/bigdft/licenses/chess.copying
  recipes/bigdft/licenses/futile.copying
  recipes/bigdft/licenses/libabinit.copying
  recipes/bigdft/licenses/psolver.copying
  recipes/bigdft/licenses/pybigdft.copying
  recipes/bigdft/licenses/spred.copying
  recipes/bigdft/meta.yaml
  recipes/bigdft/patches/output.patch
  recipes/bigdft/patches/utils.patch
  recipes/bigdft/run_test.sh
  recipes/bigdft/test.py
Labels: staged-recipes, review-requested, python-c

#20429 Add recipe for lie-group-controllers
  recipes/lie-group-controllers/bld.bat
  recipes/lie-group-controllers/build.sh
  recipes/lie-group-controllers/meta.yaml
Labels: review-requested, c-cpp

#20437 Add recipe for pytinyrenderer
  recipes/pytinyrenderer/devendor.patch
  recipes/pytinyrenderer/do_not_add_flags.patch
  recipes/pytinyrenderer/meta.yaml
Labels: review-requested, python-c

#20666 Add bdsim
  recipes/bdsim/10.patch
  recipes/bdsim/RELEASE
  recipes/bdsim/meta.yaml
  recipes/bdsim/yum_requirements.txt
Labels: review-requested, python

#20667 Add pandaboxlib recipe
  recipes/pandaboxlib/meta.yaml
Labels: review-requested, python

#20665 Add machinevision-toolbox-python
  recipes/machinevision-toolbox-python/meta.yaml
  recipes/machinevision-toolbox-python/yum_requirements.txt
  recipes/mvtb-data/LICENSE
  recipes/mvtb-data/meta.yaml
Labels: review-requested, python

#20567 Adding pysjef package
  recipes/pysjef/meta.yaml
Labels: review-requested, python-c

#20614 Add hwinfo and libx86emu
  recipes/hwinfo/build.sh
  recipes/hwinfo/meta.yaml
  recipes/hwinfo/use_flex_instead_of_lex.patch
  recipes/libx86emu/build.sh
  recipes/libx86emu/meta.yaml
Labels: c-cpp

#19798 feat: add diode
  recipes/diode/LICENSE
  recipes/diode/meta.yaml
  recipes/diode/vendor-licenses/pybind11
Labels: review-requested, python-c

#20264 Add Sophus
  recipes/sophus/build.sh
  recipes/sophus/meta.yaml
Labels: Awaiting author contribution, staged-recipes, c-cpp

#20670 Add accessible-pygments recipe
  recipes/accessible-pygments/meta.yaml
Labels: review-requested, python

#20647 add r-alpaca
  recipes/r-alpaca/bld.bat
  recipes/r-alpaca/build.sh
  recipes/r-alpaca/meta.yaml
Labels: staged-recipes, review-requested

#20625 Add recipe for gz-transport
  recipes/gz-transport/bld_cxx.bat
  recipes/gz-transport/build_cxx.sh
  recipes/gz-transport/meta.yaml
Labels: review-requested, c-cpp

#20628 Add recipe for gz-fuel-tools
  recipes/gz-fuel-tools/bld_cxx.bat
  recipes/gz-fuel-tools/build_cxx.sh
  recipes/gz-fuel-tools/meta.yaml
Labels: review-requested, c-cpp

#20623 Add recipe for gz-plugin
  recipes/gz-plugin/bld_cxx.bat
  recipes/gz-plugin/build_cxx.sh
  recipes/gz-plugin/meta.yaml
Labels: review-requested, c-cpp

#20512 Adding koopmans-kcp
  recipes/koopmans-kcp/build.sh
  recipes/koopmans-kcp/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#20683 add mup
  recipes/mup/meta.yaml
Labels: review-requested, python

#20652 Adding CyRSoXS
  recipes/cyrsoxs/build.sh
  recipes/cyrsoxs/meta.yaml
Labels: review-requested, c-cpp

#20705 torch-fidelity
  recipes/torch-fidelity/meta.yaml
Labels: review-requested, python

#20710 add jupyterlab-deck 0.1.0
  recipes/jupyterlab-deck/meta.yaml
Labels: staged-recipes, review-requested

#20714 add sphinx-tags
  recipes/sphinx-tags/meta.yaml
Labels: staged-recipes, review-requested

#20675 Adding sparsestack package
  recipes/sparsestack/meta.yaml
Labels: Awaiting author contribution, python

#20700 pybytebuffer: add recipe for v1.0.5
  recipes/pybytebuffer/LICENSE.md
  recipes/pybytebuffer/meta.yaml
  recipes/pybytebuffer/run_test.py
Labels: review-requested, python

#20703 pypsexec: add recipe for v0.3.0
  recipes/pypsexec/meta.yaml
Labels: review-requested, python

#20707 pyrogram: add recipe for v2.0.57
  recipes/pyrogram/meta.yaml
Labels: review-requested, python

#20671 Add recipe for gz-rendering
  recipes/gz-rendering/activate.bat
  recipes/gz-rendering/activate.sh
  recipes/gz-rendering/bld_cxx.bat
  recipes/gz-rendering/build_cxx.sh
  recipes/gz-rendering/conda_build_config.yaml
  recipes/gz-rendering/deactivate.bat
  recipes/gz-rendering/deactivate.sh
  recipes/gz-rendering/meta.yaml
Labels: review-requested, c-cpp

#20656 Adding conda_envfile
  recipes/conda_envfile/meta.yaml
Labels: review-requested, python

#20721 Adding pyqstrat
  recipes/pyqstrat/meta.yaml
Labels: staged-recipes, review-requested

#20415 Add the `rpy2-arrow` package.
  recipes/rpy2-arrow/meta.yaml
Labels: Awaiting author contribution, R, review-requested, python

#20724 Requesting a feedstock for the `Semi-ATE-Installer` package
  recipes/Semi-ATE-Installer/meta.yaml
Labels: staged-recipes, review-requested

#20727 Adding pymolpro
  recipes/pymolpro/meta.yaml
Labels: staged-recipes, review-requested

#20557 Add tango-atk-panel and tango-atk-tuning recipes
  recipes/tango-atk-panel/LICENSE
  recipes/tango-atk-panel/atkpanel.bat
  recipes/tango-atk-panel/bld.bat
  recipes/tango-atk-panel/build.sh
  recipes/tango-atk-panel/meta.yaml
  recipes/tango-atk-tuning/LICENSE
  recipes/tango-atk-tuning/atktuning.bat
  recipes/tango-atk-tuning/bld.bat
  recipes/tango-atk-tuning/build.sh
  recipes/tango-atk-tuning/meta.yaml
Labels: review-requested, java

#20730 add asdf-unit-schemas recipe
  recipes/asdf-unit-schemas/meta.yaml
Labels: staged-recipes, review-requested

#19910 Added gtdownloader recipe
  recipes/gtdownloader/meta.yaml
Labels: review-requested, python

#20411 Add recipe for brax
  recipes/brax/meta.yaml
Labels: review-requested, python

#20637 Add PtychoNN package
  recipes/ptychonn/meta.yaml
Labels: Awaiting author contribution, python

#20736 add slurm recipe
  recipes/slurm/build.sh
  recipes/slurm/meta.yaml
Labels: staged-recipes, review-requested

#20745 Adding ttkwidgets packet.
  recipes/ttkwidgets/LICENSE.txt
  recipes/ttkwidgets/meta.yaml
Labels: staged-recipes, review-requested

#20672 Add recipe for gz-physics
  recipes/gz-physics/bld_cxx.bat
  recipes/gz-physics/build_cxx.sh
  recipes/gz-physics/conda_build_config.yaml
  recipes/gz-physics/disable_fake_install.patch
  recipes/gz-physics/disable_integration_tests.patch
  recipes/gz-physics/meta.yaml
Labels: review-requested, c-cpp

#20685 Add recipe for gz-gui
  recipes/gz-gui/bld_cxx.bat
  recipes/gz-gui/build_cxx.sh
  recipes/gz-gui/conda_build_config.yaml
  recipes/gz-gui/meta.yaml
  recipes/gz-gui/yum_requirements.txt
Labels: review-requested, c-cpp

#20747 Add recipe for gz-sensors
  recipes/gz-sensors/bld_cxx.bat
  recipes/gz-sensors/build_cxx.sh
  recipes/gz-sensors/conda_build_config.yaml
  recipes/gz-sensors/meta.yaml
Labels: review-requested, c-cpp

#20740 Adding mcpl
  recipes/mcpl/build.sh
  recipes/mcpl/meta.yaml
Labels: staged-recipes, review-requested

#20738 Add pylat recipe
  recipes/pylat/build.sh
  recipes/pylat/meta.yaml
Labels: review-requested, python

#20755 Adding nanobind recipe
  recipes/nanobind/meta.yaml
Labels: review-requested, python

#20753 PKG: Add latex-rubber
  recipes/latex-rubber/meta.yaml
Labels: review-requested, python

#20758 Added inline-sql as a package
  recipes/inline-sql/meta.yaml
Labels: staged-recipes, review-requested

#20391 Added starlite-sessions
  recipes/starlite-sessions/meta.yaml
Labels: staged-recipes, review-requested

#20762 Added refurb as a package
  recipes/refurb/meta.yaml
Labels: staged-recipes, review-requested

#20761 Added fast-soup as a package
  recipes/fast-soup/meta.yaml
Labels: staged-recipes, review-requested

#20760 Added soupy as a package
  recipes/soupy/meta.yaml
Labels: staged-recipes, review-requested

#20684 Add cmplxfoil recipe
  recipes/cmplxfoil/FC-config-linux.patch
  recipes/cmplxfoil/build.sh
  recipes/cmplxfoil/meta.yaml
Labels: review-requested, python

#20697 pyjq: add recipe for v2.6.0
  recipes/pyjq/0001-Use-pre-built-external-deps.patch
  recipes/pyjq/meta.yaml
Labels: review-requested, python-c

#20759 Added minestrone as a package
  recipes/minestrone/LICENSE
  recipes/minestrone/meta.yaml
Labels: staged-recipes, review-requested

#20751 Add Terraform Provider Databricks
  recipes/terraform-provider-databricks/conda_build_config.yaml
  recipes/terraform-provider-databricks/meta.yaml
Labels: staged-recipes, review-requested

#20777 Add katago
  recipes/katago/bld.bat
  recipes/katago/build.sh
  recipes/katago/meta.yaml
  recipes/katago/osx-cmake.patch
Labels: review-requested, c-cpp

#20757 Added r-ISLR2 as a pacakge
  recipes/r-islr2/bld.bat
  recipes/r-islr2/build.sh
  recipes/r-islr2/meta.yaml
Labels: staged-recipes, review-requested

#20729 Add r-survtmle
  recipes/r-survtmle/bld.bat
  recipes/r-survtmle/build.sh
  recipes/r-survtmle/meta.yaml
Labels: R, review-requested

#20788 Add mat73
  recipes/mat73/meta.yaml
Labels: review-requested, python

#20793 Adding jacobi package
  recipes/jacobi/meta.yaml
Labels: review-requested, python

#20796 Drop unused variables
  .ci_support/build_all.py
Labels: maintenance

#20768 Added r-secret as a pacakge
  recipes/r-secret/bld.bat
  recipes/r-secret/build.sh
  recipes/r-secret/meta.yaml
Labels: staged-recipes, review-requested

#20767 R grates
  recipes/r-grates/bld.bat
  recipes/r-grates/build.sh
  recipes/r-grates/meta.yaml
Labels: staged-recipes, review-requested

#20763 Added r-maybe as a package
  recipes/r-maybe/bld.bat
  recipes/r-maybe/build.sh
  recipes/r-maybe/meta.yaml
Labels: staged-recipes, review-requested

#20799 Add Glaes Package
  recipes/glaes/meta.yaml
Labels: staged-recipes, review-requested

#20805 added recipe for `pymedio`
  recipes/pymedio/meta.yaml
Labels: staged-recipes, review-requested, python

#20803 ENH add the shredder and friends
  recipes/des-fitvd/meta.yaml
  recipes/fofx/meta.yaml
  recipes/mof/meta.yaml
  recipes/shredder/meta.yaml
  recipes/shredx/meta.yaml
Labels: staged-recipes, review-requested

#20792 Add recipe for fars-cleaner package
  recipes/fars-cleaner/meta.yaml
Labels: review-requested, python

#20527 Add recipe and dependencies for the ufmt code formatter / import sorter
  recipes/stdlibs/meta.yaml
  recipes/trailrunner/meta.yaml
  recipes/ufmt/meta.yaml
  recipes/usort/meta.yaml
Labels: staged-recipes, review-requested, python

#20783 Adding `cpp_comment_format`
  recipes/cpp_comment_format/meta.yaml
Labels: Awaiting author contribution, python

#20806 Add wslink package
  recipes/wslink/meta.yaml
Labels: staged-recipes, review-requested

#20752 Add recipe for libunicycle-footstep-planner
  recipes/libunicycle-footstep-planner/bld.bat
  recipes/libunicycle-footstep-planner/build.sh
  recipes/libunicycle-footstep-planner/meta.yaml
Labels: review-requested, c-cpp

#20608 Added recipe for Perl module Moo and its deps
  recipes/perl-class-method-modifiers/bld.bat
  recipes/perl-class-method-modifiers/build.sh
  recipes/perl-class-method-modifiers/meta.yaml
  recipes/perl-moo/bld.bat
  recipes/perl-moo/build.sh
  recipes/perl-moo/meta.yaml
  recipes/perl-role-tiny/bld.bat
  recipes/perl-role-tiny/build.sh
  recipes/perl-role-tiny/meta.yaml
  recipes/perl-sub-quote/bld.bat
  recipes/perl-sub-quote/build.sh
  recipes/perl-sub-quote/meta.yaml
  recipes/perl-test-fatal/bld.bat
  recipes/perl-test-fatal/build.sh
  recipes/perl-test-fatal/meta.yaml
Labels: review-requested, perl

#20780 Adding carto-auth recipe
  recipes/carto-auth/LICENSE
  recipes/carto-auth/meta.yaml
Labels: review-requested, python

#20031 Adding `skops` and `modelcards` from PyPI
  recipes/modelcards/65.patch
  recipes/modelcards/LICENSE
  recipes/modelcards/meta.yaml
  recipes/skops/meta.yaml
Labels: review-requested, python

#20824 feat: :sparkles: Add sphinxcontrib-seqdiag plugin
  recipes/blockdiag/meta.yaml
  recipes/seqdiag/meta.yaml
  recipes/sphinxcontrib-seqdiag/meta.yaml
Labels: review-requested, python

#20812 Add libhdbpp-timescale recipe
  recipes/libhdbpp-timescale/build.sh
  recipes/libhdbpp-timescale/meta.yaml
Labels: review-requested, c-cpp

#20813 Add hdbpp-cm and hdbpp-es Tango device servers recipes
  recipes/hdbpp-cm/build.sh
  recipes/hdbpp-cm/meta.yaml
  recipes/hdbpp-es/build.sh
  recipes/hdbpp-es/meta.yaml
Labels: review-requested, c-cpp

#20802 Add pycspade 0.6.6
  recipes/pycspade/LICENSE
  recipes/pycspade/meta.yaml
  recipes/pycspade/setup.patch
Labels: review-requested, python-c

#20791 Add jive recipe
  recipes/jive/LICENSE
  recipes/jive/bld.bat
  recipes/jive/build.sh
  recipes/jive/jive.bat
  recipes/jive/meta.yaml
Labels: staged-recipes, review-requested

#19656 add yaqd-labjack
  recipes/yaqd-labjack/meta.yaml
Labels: review-requested, python

#19543 Add nvitop.
  recipes/nvitop/meta.yaml
Labels: review-requested, python

#20808 adds r-sftime
  recipes/r-sftime/LICENSE
  recipes/r-sftime/bld.bat
  recipes/r-sftime/build.sh
  recipes/r-sftime/meta.yaml
Labels: staged-recipes, review-requested

#20810 R chronicler
  recipes/r-chronicler/bld.bat
  recipes/r-chronicler/build.sh
  recipes/r-chronicler/meta.yaml
Labels: staged-recipes, review-requested

#20764 Added r-encryptedRmd as a package
  recipes/r-encryptedrmd/bld.bat
  recipes/r-encryptedrmd/build.sh
  recipes/r-encryptedrmd/meta.yaml
Labels: staged-recipes, review-requested

#20826 Add Circuitbreaker from PyPI
  recipes/circuitbreaker/meta.yaml
Labels: review-requested, python

#20797 Added recipe perl-b-cow for Perl module B::COW
  recipes/perl-b-cow/bld.bat
  recipes/perl-b-cow/build.sh
  recipes/perl-b-cow/meta.yaml
Labels: review-requested, perl

#20664 Add recipe for quickjs
  recipes/python-quickjs/LICENSE-quickjs
  recipes/python-quickjs/bld.bat
  recipes/python-quickjs/build.sh
  recipes/python-quickjs/conda_build_config.yaml
  recipes/python-quickjs/meta.yaml
  recipes/python-quickjs/setup.patch
  recipes/python-quickjs/test_quickjs.py
Labels: review-requested, python-c

#20827 add recipe for forestplot
  recipes/forestplot/LICENSE
  recipes/forestplot/meta.yaml
Labels: staged-recipes, review-requested

#20825 Adding translators
  recipes/pyexecjs/meta.yaml
  recipes/translators/meta.yaml
Labels: review-requested, python

#20836 add recipe for napari-threedee
  recipes/napari-threedee/meta.yaml
  recipes/napari-threedee/yum_requirements.txt
Labels: staged-recipes, review-requested

#20861 Add recipe for PartSeg-smfish python package
  recipes/PartSeg-smfish/meta.yaml
Labels: review-requested, python

#20439 Add hoomd-dlext
  recipes/hoomd-dlext/build.sh
  recipes/hoomd-dlext/meta.yaml
Labels: staged-recipes, review-requested, python-c

#20874 Add recipe for odc-dscache
  recipes/odc-dscache/meta.yaml
Labels: staged-recipes, review-requested

#20858 Adding recipe for eodatasets3
  recipes/eodatasets3/meta.yaml
Labels: staged-recipes, review-requested

#20873 Add recipe for odc-cloud
  recipes/odc-cloud/meta.yaml
Labels: staged-recipes, review-requested

#20865 adding funsor recipe
  recipes/funsor/LICENSE.md
  recipes/funsor/meta.yaml
Labels: staged-recipes, review-requested

#20853 Add cryotypes recipe
  recipes/cryotypes/meta.yaml
Labels: staged-recipes, review-requested

#20838 Add koopa-viz recipe
  recipes/koopa-viz/meta.yaml
  recipes/koopa-viz/yum_requirements.txt
Labels: staged-recipes, review-requested

#20859 Add pogo recipe
  recipes/pogo/bld.bat
  recipes/pogo/build.sh
  recipes/pogo/meta.yaml
  recipes/pogo/pogo.bat
  recipes/pogo/preferences/Pogo.site_properties
  recipes/pogo/preferences/cmake_common_target.opt
  recipes/pogo/preferences/cmake_tango.opt
  recipes/pogo/preferences/common_target.opt
  recipes/pogo/preferences/tango.opt
Labels: staged-recipes, review-requested

#20875 adding ridgeplot-py recipe
  recipes/ridgeplot-py/LICENSE.txt
  recipes/ridgeplot-py/meta.yaml
Labels: staged-recipes, review-requested, python

#20884 add pyfunctional
  recipes/pyfunctional/meta.yaml
Labels: review-requested, python

#20888 add jsf 0.4.0
  recipes/jsf/0000-setup-py-utf8.patch
  recipes/jsf/meta.yaml
Labels: staged-recipes, review-requested, python

#20889 add evotorch
  recipes/evotorch/meta.yaml
Labels: review-requested, python

#20866 Add chafer recipe
  recipes/chafer/meta.yaml
Labels: staged-recipes, review-requested

#20883 Add symlink-exe-substitue
  recipes/symlink-exe-substitute/LICENSE-conda-forge.txt
  recipes/symlink-exe-substitute/LICENSE-conda-recipes.txt
  recipes/symlink-exe-substitute/LICENSE-setuptools-new.txt
  recipes/symlink-exe-substitute/LICENSE-setuptools-old.txt
  recipes/symlink-exe-substitute/LICENSE.txt
  recipes/symlink-exe-substitute/bld-build.bat
  recipes/symlink-exe-substitute/build-symlink-exe.bat
  recipes/symlink-exe-substitute/build-symlink-exe.sh
  recipes/symlink-exe-substitute/meta.yaml
  recipes/symlink-exe-substitute/symlink-exe.c
Labels: review-requested

#20871 Add pystardb recipe
  recipes/pystardb/meta.yaml
Labels: staged-recipes, review-requested

#20781 Add pydeck-carto recipe
  recipes/pydeck-carto/LICENSE
  recipes/pydeck-carto/meta.yaml
Labels: review-requested, python

#20885 add streamlit-aggrid
  recipes/streamlit-aggrid/meta.yaml
Labels: review-requested, python

#20911 adds twarc
  recipes/twarc/meta.yaml
Labels: staged-recipes, review-requested

#20898 Add recipe for odc-apps-dc-tools
  recipes/odc-apps-dc-tools/meta.yaml
Labels: staged-recipes, review-requested

#20910 Add `libthermo` and `pythermo` recipes
  recipes/libthermo/build_libthermo.bat
  recipes/libthermo/build_libthermo.sh
  recipes/libthermo/libthermo.patch
  recipes/libthermo/meta.yaml
Labels: review-requested, c-cpp, python

#20915 Add scriptengine-tasks-hpc package
  recipes/scriptengine-tasks-hpc/meta.yaml
Labels: review-requested, python

#20913 add pydistcheck
  recipes/pydistcheck/meta.yaml
Labels: Awaiting author contribution, python

#20734 Add r-tsstudio with deps (r-hts,r-thief,r-forecasthybrid)
  recipes/r-forecasthybrid/bld.bat
  recipes/r-forecasthybrid/build.sh
  recipes/r-forecasthybrid/meta.yaml
  recipes/r-hts/bld.bat
  recipes/r-hts/build.sh
  recipes/r-hts/meta.yaml
  recipes/r-thief/bld.bat
  recipes/r-thief/build.sh
  recipes/r-thief/meta.yaml
  recipes/r-tsstudio/bld.bat
  recipes/r-tsstudio/build.sh
  recipes/r-tsstudio/meta.yaml
Labels: R, review-requested

#20686 Add recipe for gz-sim
  recipes/gz-sim/1763.patch
  recipes/gz-sim/bld_cxx.bat
  recipes/gz-sim/bld_py.bat
  recipes/gz-sim/build_cxx.sh
  recipes/gz-sim/build_py.sh
  recipes/gz-sim/meta.yaml
  recipes/gz-sim/standalone_bindings.patch
  recipes/gz-sim/yum_requirements.txt
Labels: review-requested, c-cpp

#20920 Add eudist
  recipes/eudist/meta.yaml
Labels: review-requested, python-c

#20891 Add molgrid
  recipes/molgrid/build.sh
  recipes/molgrid/meta.yaml
  recipes/molgrid/python-install-no-git.patch
Labels: review-requested, c-cpp

#20924 Add recipe for liquid-babel
  recipes/liquid-babel/meta.yaml
Labels: review-requested, python

#20930 Add hfradarpy to conde-forge
  recipes/hfradarpy/meta.yaml
Labels: staged-recipes, review-requested, python

#20929 Adding Minisom
  recipes/minisom/LICENSE
  recipes/minisom/meta.yaml
Labels: review-requested, python

#20413 Initial Commit for Nyxus Recipe
  recipes/nyxus/0001-fix-filesystem-issue.patch
  recipes/nyxus/0002-Fix-CUDA-Kernel-Issue.patch
  recipes/nyxus/bld.bat
  recipes/nyxus/build.sh
  recipes/nyxus/meta.yaml
Labels: review-requested, c-cpp

#18765 Adding denoptim
  recipes/denoptim/bld.bat
  recipes/denoptim/build.sh
  recipes/denoptim/meta.yaml
Labels: staged-recipes, review-requested, java

#20231 Add parallelio
  recipes/parallelio/build.sh
  recipes/parallelio/conda_build_config.yaml
  recipes/parallelio/meta.yaml
Labels: review-requested, c-cpp

#20931 add nh3 0.2.0
  recipes/nh3/bld.bat
  recipes/nh3/build.sh
  recipes/nh3/meta.yaml
Labels: review-requested, python

#20925 Add optree.
  recipes/optree/conda_build_config.yaml
  recipes/optree/meta.yaml
Labels: review-requested, python-c

#20749 Add recipe for gz-launch
  recipes/gz-launch/204.patch
  recipes/gz-launch/bld_cxx.bat
  recipes/gz-launch/build_cxx.sh
  recipes/gz-launch/meta.yaml
  recipes/gz-launch/unvendor_backward.patch
Labels: review-requested, c-cpp

#20855 Add openpulse, openqasm3, oqpy
  recipes/openpulse/meta.yaml
  recipes/openqasm3/meta.yaml
  recipes/oqpy/meta.yaml
Labels: review-requested, python

#20909 Add recipe for Perl module Devel::NYTProf
  recipes/perl-devel-nytprof/bld.bat
  recipes/perl-devel-nytprof/build.sh
  recipes/perl-devel-nytprof/meta.yaml
  recipes/perl-test-differences/bld.bat
  recipes/perl-test-differences/build.sh
  recipes/perl-test-differences/meta.yaml
Labels: review-requested, perl

#20776 Adding r-ravedash and R dependencies
  recipes/r-dipsaus/bld.bat
  recipes/r-dipsaus/build.sh
  recipes/r-dipsaus/meta.yaml
  recipes/r-edfreader/bld.bat
  recipes/r-edfreader/build.sh
  recipes/r-edfreader/meta.yaml
  recipes/r-filearray/bld.bat
  recipes/r-filearray/build.sh
  recipes/r-filearray/meta.yaml
  recipes/r-freesurferformats/bld.bat
  recipes/r-freesurferformats/build.sh
  recipes/r-freesurferformats/meta.yaml
  recipes/r-gifti/bld.bat
  recipes/r-gifti/build.sh
  recipes/r-gifti/meta.yaml
  recipes/r-oro.nifti/bld.bat
  recipes/r-oro.nifti/build.sh
  recipes/r-oro.nifti/meta.yaml
  recipes/r-pkgfilecache/bld.bat
  recipes/r-pkgfilecache/build.sh
  recipes/r-pkgfilecache/meta.yaml
  recipes/r-ravedash/bld.bat
  recipes/r-ravedash/build.sh
  recipes/r-ravedash/meta.yaml
  recipes/r-raveio/bld.bat
  recipes/r-raveio/build.sh
  recipes/r-raveio/meta.yaml
  recipes/r-ravetools/bld.bat
  recipes/r-ravetools/build.sh
  recipes/r-ravetools/meta.yaml
  recipes/r-rpymat/LICENSE.md
  recipes/r-rpymat/bld.bat
  recipes/r-rpymat/build.sh
  recipes/r-rpymat/meta.yaml
  recipes/r-shidashi/bld.bat
  recipes/r-shidashi/build.sh
  recipes/r-shidashi/meta.yaml
  recipes/r-shinyvalidate/bld.bat
  recipes/r-shinyvalidate/build.sh
  recipes/r-shinyvalidate/meta.yaml
  recipes/r-startup/bld.bat
  recipes/r-startup/build.sh
  recipes/r-startup/meta.yaml
  recipes/r-threebrain/bld.bat
  recipes/r-threebrain/build.sh
  recipes/r-threebrain/meta.yaml
Labels: R, review-requested
