Repository conda-forge/staged-recipes, pull requests merged in 2022-06, with the labels that each got.

#19122 Add jpf
  recipes/jpf/meta.yaml
Labels: staged-recipes, review-requested

#18932 Add recipe for tblite Python bindings
  recipes/tblite-python/build.sh
  recipes/tblite-python/meta.yaml
Labels: review-requested, python, python-c

#18849 Add OpenMC Plotter
  recipes/openmc-plotter/meta.yaml
  recipes/openmc-plotter/yum_requirements.txt
Labels: Awaiting author contribution, python

#19033 Add recipe for meson-python
  recipes/meson-python/meta.yaml
  recipes/meson-python/ninja-overdep.patch
Labels: review-requested, python

#19100 Adding `deadlink` from PyPI
  recipes/deadlink/meta.yaml
Labels: Awaiting author contribution, python

#19020 add fenics-dolfinx
  recipes/fenics-dolfinx/0001-cpp-test-remove-extra-semicolon.patch
  recipes/fenics-dolfinx/build-dolfinx.sh
  recipes/fenics-dolfinx/build-libdolfinx.sh
  recipes/fenics-dolfinx/conda_build_config.yaml
  recipes/fenics-dolfinx/meta.yaml
  recipes/fenics-dolfinx/test-dolfinx.sh
  recipes/fenics-dolfinx/test-libdolfinx.sh
Labels: review-requested, python-c

#19129 Add atap_widgets recipe
  recipes/atap_widgets/LICENSE.txt
  recipes/atap_widgets/meta.yaml
Labels: staged-recipes, review-requested

#19124 add espaloma
  recipes/espaloma/meta.yaml
Labels: staged-recipes, review-requested

#19036 Support using channel_urls from conda_build_config.yaml
  .ci_support/build_all.py
Labels: staged-recipes, review-requested

#19121 Add r-sen2r conda recipe
  recipes/r-sen2r/bld.bat
  recipes/r-sen2r/build.sh
  recipes/r-sen2r/meta.yaml
Labels: R, review-requested

#19132 Cleanup `.travis_scripts`
  .github/workflows/create_feedstocks.yml
  .github/workflows/scripts/create_feedstocks
  .github/workflows/scripts/create_feedstocks.py
  .travis_scripts/build_all
Labels: maintenance

#18952 Add superstore and finance-enums
  recipes/finance-enums/meta.yaml
  recipes/superstore/meta.yaml
Labels: review-requested, python

#18964 add jupyterlab-nbconvert-nocode
  recipes/jupyterlab-nbconvert-nocode/build_base.bat
  recipes/jupyterlab-nbconvert-nocode/build_base.sh
  recipes/jupyterlab-nbconvert-nocode/meta.yaml
Labels: review-requested, python

#19142 Adding srt
  recipes/isosurfaces/LICENSE
  recipes/isosurfaces/meta.yaml
  recipes/srt/meta.yaml
Labels: staged-recipes, review-requested

#19146 Add recipe for sphinx-fortran
  recipes/sphinx-fortran/meta.yaml
Labels: review-requested, python

#19137 Add recipe for apeye-core
  recipes/apeye-core/meta.yaml
Labels: review-requested, python

#19151 [skip lint] use miniforge in windows
  .azure-pipelines/azure-pipelines-win.yml
Labels: staged-recipes, review-requested

#19150 Add recursivenodes
  recipes/recursivenodes/LICENSE
  recipes/recursivenodes/meta.yaml
Labels: review-requested, python

#19131 adding gitsummary
  recipes/gitsummary/meta.yaml
Labels: review-requested, python

#19152 Add aio-executor
  recipes/aio-executor/LICENSE
  recipes/aio-executor/meta.yaml
Labels: review-requested, python

#19082 Adding precession package to conda-forge
  recipes/precession/LICENSE.txt
  recipes/precession/meta.yaml
Labels: review-requested, python

#19062 NEW: Add recipe for ptychodus
  recipes/ptychodus/meta.yaml
  recipes/ptychodus/yum_requirements.txt
Labels: review-requested, python

#19144 added colorhash recipe
  recipes/colorhash/LICENSE.txt
  recipes/colorhash/meta.yaml
Labels: staged-recipes, review-requested

#19123 Adding jupyter_events
  recipes/jupyter_events/meta.yaml
Labels: review-requested, python

#19111 Add pygis recipe
  recipes/pygis/meta.yaml
Labels: review-requested, python

#19148 NEW: Cache packages when building locally
  .ci_support/build_all.py
  .scripts/build_steps.sh
Labels: staged-recipes, review-requested

#19154 Add pynamodb-encoder
  recipes/pynamodb-encoder/meta.yaml
Labels: review-requested, python

#19155 Add mailbits
  recipes/mailbits/meta.yaml
Labels: staged-recipes, review-requested

#19110 Add cpppo and greenery recipes
  recipes/cpppo/COPYING
  recipes/cpppo/meta.yaml
  recipes/cpppo/remove_getattr_entrypoint.diff
  recipes/greenery/LICENSE.txt
  recipes/greenery/meta.yaml
Labels: Awaiting author contribution, python

#19128 Adding featurewiz
  recipes/featurewiz/LICENSE.txt
  recipes/featurewiz/meta.yaml
Labels: Awaiting author contribution, python

#19104 Add lodepng recipe
  recipes/lodepng/CMakeLists.txt
  recipes/lodepng/bld.bat
  recipes/lodepng/build.sh
  recipes/lodepng/meta.yaml
Labels: Awaiting author contribution, c-cpp

#19153 add cleopatra & geostatista packages
  recipes/cleopatra/meta.yaml
  recipes/geostatista/meta.yaml
Labels: review-requested, python

#18544 Add Boost.MPI recipe
  recipes/libboost-mpi/5eff1ecc8413b0dc93a1ab047d7fed751e6cb40e.patch
  recipes/libboost-mpi/bld.bat
  recipes/libboost-mpi/build.sh
  recipes/libboost-mpi/conda_build_config.yaml
  recipes/libboost-mpi/meta.yaml
Labels: review-requested, c-cpp

#17499 add prolif
  recipes/prolif/meta.yaml
Labels: staged-recipes, review-requested

#19173 Add LSPOpt
  recipes/lspopt/meta.yaml
Labels: staged-recipes, review-requested

#19172 Add pyRiemann
  recipes/pyriemann/LICENSE
  recipes/pyriemann/meta.yaml
Labels: staged-recipes, review-requested

#19114 Adding napari-annotatorj package
  recipes/napari-annotatorj/meta.yaml
  recipes/napari-annotatorj/yum_requirements.txt
Labels: Awaiting author contribution, python

#18963 Add parquet-python
  recipes/parquet-python/LICENSE
  recipes/parquet-python/meta.yaml
Labels: Awaiting author contribution, python

#19178 add digitalearth package
  recipes/digitalearth/meta.yaml
Labels: staged-recipes, review-requested

#19186 Add yasa
  recipes/yasa/meta.yaml
Labels: staged-recipes, review-requested

#19169 Add recipe for hatch-vcs
  recipes/hatch-vcs/meta.yaml
Labels: review-requested, python

#19188 Add ipywidgets-jsonschema recipe to conda-forge
  recipes/ipywidgets-jsonschema/meta.yaml
Labels: review-requested, python

#19156 Add xcb-util-image and xcb-util-renderutil for linux
  recipes/xcb-util-image/COPYING
  recipes/xcb-util-image/build.sh
  recipes/xcb-util-image/meta.yaml
  recipes/xcb-util-renderutil/COPYING
  recipes/xcb-util-renderutil/build.sh
  recipes/xcb-util-renderutil/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#19166 Add multivisor recipe
  recipes/multivisor/build_core.sh
  recipes/multivisor/meta.yaml
  recipes/multivisor/setup-exclude-tests.patch
Labels: review-requested, python

#19067 Add `pyturbo` recipe
  recipes/pyturbo/meta.yaml
Labels: Awaiting author contribution, python

#19185 ENH add DES pipeline packages imsupport, despyfits, despyastro, despymisc, and pixcorrect
  recipes/des-despyastro/meta.yaml
  recipes/des-despyfits/LICENSE.md
  recipes/des-despyfits/activate.sh
  recipes/des-despyfits/build.sh
  recipes/des-despyfits/deactivate.sh
  recipes/des-despyfits/fix-patches.py
  recipes/des-despyfits/libload.patch
  recipes/des-despyfits/libload_again.patch
  recipes/des-despyfits/meta.yaml
  recipes/des-despymisc/meta.yaml
  recipes/des-imsupport/LICENSE.md
  recipes/des-imsupport/build-dev.sh
  recipes/des-imsupport/meta.yaml
  recipes/des-pixcorrect/activate.sh
  recipes/des-pixcorrect/build.sh
  recipes/des-pixcorrect/deactivate.sh
  recipes/des-pixcorrect/mask_sat.patch
  recipes/des-pixcorrect/meta.yaml
Labels: staged-recipes, review-requested

#19209 Add afwizard-library recipe
  recipes/afwizard-library/meta.yaml
Labels: review-requested, python

#19210 Add jsonmerge recipe to conda-forge
  recipes/jsonmerge/meta.yaml
Labels: review-requested, python

#19162 Adding support for river via river-cpp/river-py packages
  recipes/river-cpp/bld.bat
  recipes/river-cpp/build.sh
  recipes/river-cpp/meta.yaml
  recipes/river-py/bld.bat
  recipes/river-py/build.sh
  recipes/river-py/meta.yaml
Labels: Awaiting author contribution, c-cpp

#19204 Add recipe for gcn-kafka
  recipes/gcn-kafka/meta.yaml
Labels: python

#16670 NEW: Add recipe for astra-toolbox
  recipes/astra-toolbox/bld.bat
  recipes/astra-toolbox/build.sh
  recipes/astra-toolbox/meta.yaml
Labels: staged-recipes, review-requested, python-c

#19219 Add django-permissionedforms
  recipes/django-permissionedforms/meta.yaml
Labels: review-requested, python

#18882 Add poetry-dynamic-versioning-plugin
  recipes/poetry-dynamic-versioning-plugin/conda_build_config.yaml
  recipes/poetry-dynamic-versioning-plugin/meta.yaml
Labels: review-requested, python

#19212 Add AFwizard to conda-forge
  recipes/afwizard/conda_build_config.yaml
  recipes/afwizard/meta.yaml
Labels: python

#19214 Add sphinx-basic-ng package
  recipes/sphinx-basic-ng/conda_build_config.yml
  recipes/sphinx-basic-ng/meta.yaml
Labels: python

#19216 add polylib package
  recipes/polylib/build.sh
  recipes/polylib/meta.yaml
Labels: review-requested, c-cpp

#19221 Add recipe for bmi_wavewatch3 package
  recipes/bmi-wavewatch3/meta.yaml
Labels: Awaiting author contribution, python

#19273 Adding stac-validator recipe
  recipes/stac-validator/meta.yaml
Labels: review-requested, python

#19279 Add recipe for r-utility
  recipes/r-utility/bld.bat
  recipes/r-utility/build.sh
  recipes/r-utility/meta.yaml
Labels: R, review-requested

#19217 Adding taospy
  recipes/taospy/meta.yaml
Labels: Awaiting author contribution, python

#18234 Add yarp recipe
  recipes/yarp/2852.patch
  recipes/yarp/activate.msh
  recipes/yarp/bld_cxx.bat
  recipes/yarp/bld_py.bat
  recipes/yarp/build_cxx.sh
  recipes/yarp/build_py.sh
  recipes/yarp/deactivate.msh
  recipes/yarp/meta.yaml
Labels: review-requested, c-cpp

#19280 Add pip-system-certs
  recipes/pip-system-certs/meta.yaml
  recipes/pip-system-certs/run_test.py
Labels: review-requested, python

#19282 adding microtc
  recipes/microtc/meta.yaml
Labels: staged-recipes, review-requested, python

#19277 Adding stac-check recipe
  recipes/stac-check/meta.yaml
Labels: Awaiting author contribution, python

#19275 Adding `xplique` from PyPI
  recipes/xplique/meta.yaml
Labels: Awaiting author contribution, python

#16951 Add ncvue
  recipes/ncvue/meta.yaml
  recipes/ncvue/ncvue_icon.png
Labels: staged-recipes, review-requested, python

#19081 conda-forge recipe for the OpenMM ATMMetaForce plugin
  recipes/openmm-atmmetaforce-plugin/build.sh
  recipes/openmm-atmmetaforce-plugin/meta.yaml
Labels: Awaiting author contribution, staged-recipes, c-cpp, python-c

#18968 adding openmmtorchplugin
  recipes/openmmtorchplugin/build.sh
  recipes/openmmtorchplugin/meta.yaml
  recipes/openmmtorchplugin/run_test.sh
Labels: Awaiting author contribution, c-cpp, python-c

#19140 Add a recipe for pypi package refcount 0.9.4
  recipes/refcount/meta.yaml
Labels: staged-recipes, review-requested

#19167 add album-runner recipe
  recipes/album-runner/meta.yaml
Labels: review-requested, python

#19309 Adding beamngpy
  recipes/beamngpy/meta.yaml
Labels: staged-recipes, review-requested

#19329 Add quimb
  recipes/quimb/meta.yaml
Labels: staged-recipes, review-requested

#16213 add header-only library type_safe
  recipes/debug_assert/0001-Remove-DEBUG_ASSERT_PURE_FUNCTION.patch
  recipes/debug_assert/bld.bat
  recipes/debug_assert/build.sh
  recipes/debug_assert/meta.yaml
  recipes/type_safe/bld.bat
  recipes/type_safe/build.sh
  recipes/type_safe/meta.yaml
Labels: c-cpp

#19049 Add mujoco recipe
  recipes/mujoco/bld_cxx.bat
  recipes/mujoco/bld_py.bat
  recipes/mujoco/build_cxx.sh
  recipes/mujoco/build_py.sh
  recipes/mujoco/ccd_vec3_origin_link_problem.patch
  recipes/mujoco/cxx_devendor.patch
  recipes/mujoco/disable_copy_cxx_files_in_python_package.patch
  recipes/mujoco/disable_gcc_pragma.patch
  recipes/mujoco/do_not_install_via_pip.patch
  recipes/mujoco/meta.yaml
  recipes/mujoco/python_devendor.patch
  recipes/mujoco/python_remove_avx.patch
  recipes/mujoco/python_remove_werror.patch
Labels: review-requested, c-cpp, python-c

#19356 Add recipe for getCalspec package
  recipes/getCalspec/meta.yaml
Labels: staged-recipes, review-requested

#19315 Adding m3gnet
  recipes/m3gnet/meta.yaml
Labels: staged-recipes, review-requested

#19345 add picwriter
  recipes/picwriter/LICENSE
  recipes/picwriter/meta.yaml
Labels: staged-recipes, review-requested

#18759 add nagios core
  recipes/nagios/meta.yaml
Labels: Awaiting author contribution, c-cpp

#19367 Add oracledb
  recipes/oracledb/0001-fix-osx-arch.patch
  recipes/oracledb/meta.yaml
Labels: review-requested, python-c

#19373 Add r-rasterdiv conda recipe
  recipes/r-rasterdiv/bld.bat
  recipes/r-rasterdiv/build.sh
  recipes/r-rasterdiv/meta.yaml
Labels: R, review-requested

#19335 Add pyqt-stubs
  recipes/pyqt-stubs/meta.yaml
Labels: review-requested, python

#19365 Add pytoolconfig
  recipes/pytoolconfig/LICENSE
  recipes/pytoolconfig/meta.yaml
Labels: staged-recipes, review-requested

#19364 add etils (shallow package)
  recipes/etils/meta.yaml
Labels: review-requested, python

#19352 Add pyproject-metadata recipe (renamed from pep621)
  recipes/pyproject-metadata/meta.yaml
Labels: review-requested, python

#19376 Create pytest-factoryboy feedstock
  recipes/pytest-factoryboy/meta.yaml
Labels: review-requested, python

#19359 Add openconnect-sso
  recipes/openconnect-sso/meta.yaml
  recipes/openconnect-sso/yum_requirements.txt
Labels: review-requested, python

#19391 Tidypandas
  recipes/tidypandas/meta.yaml
Labels: staged-recipes, review-requested

#19390 Added texthero as a package
  recipes/texthero/LICENSE
  recipes/texthero/meta.yaml
Labels: staged-recipes, review-requested

#19389 Add the cleantext package
  recipes/cleantext/meta.yaml
Labels: staged-recipes, review-requested

#19388 Added sourcetypes as a package
  recipes/sourcetypes/LICENSE
  recipes/sourcetypes/meta.yaml
Labels: staged-recipes, review-requested

#19386 Added mangum as a package
  recipes/mangum/meta.yaml
Labels: staged-recipes, review-requested

#19394 Added miniboss as a package
  recipes/miniboss/meta.yaml
Labels: staged-recipes, review-requested

#19297 Adding stactools recipe
  recipes/stactools/meta.yaml
Labels: Awaiting author contribution, python

#19392 Add python package unzip_http
  recipes/unzip-http/meta.yaml
Labels: review-requested, python

#19381 Adding wslPath
  recipes/wskPath/meta.yaml
Labels: review-requested, python

#19355 Add recipe for mechaSVG
  recipes/mechasvg/meta.yaml
  recipes/mechasvg/readme-path.patch
Labels: review-requested, python

#19298 Release Pycrostates
  recipes/pycrostates/meta.yaml
Labels: review-requested, python

#19377 creating recipe for strawberry-graphql
  recipes/strawberry-graphql/meta.yaml
Labels: Awaiting author contribution, python

#19353 add pyglider
  recipes/pyglider/meta.yaml
Labels: review-requested, python

#19395 Added sqladmin as a package
  recipes/sqladmin/meta.yaml
Labels: staged-recipes, review-requested

#19396 Added konsole as a package
  recipes/konsole/meta.yaml
Labels: staged-recipes, review-requested

#19397 Added pyccolo as a package
  recipes/pyccolo/meta.yaml
Labels: staged-recipes, review-requested

#19398 Added tinygp as a package
  recipes/tinygp/meta.yaml
Labels: staged-recipes, review-requested

#19401 Added jesth as a package
  recipes/jesth/meta.yaml
Labels: staged-recipes, review-requested

#19402 Added subrun as a package
  recipes/subrun/meta.yaml
Labels: staged-recipes, review-requested

#19403 Added kurl as a package
  recipes/kurl/meta.yaml
Labels: staged-recipes, review-requested

#19384 Add ogre-next
  recipes/ogre-next/add_OGRE_USE_NEW_PROJECT_NAME_cmake_option.patch
  recipes/ogre-next/add_suffix_in_install_also_for_runtime.patch
  recipes/ogre-next/backport_hlms_bugfix.patch
  recipes/ogre-next/bld.bat
  recipes/ogre-next/build.sh
  recipes/ogre-next/change_header_install_from_OGRE_to_OGRE-Next.patch
  recipes/ogre-next/change_plugin_installs_from_OGRE_to_OGRE-Next.patch
  recipes/ogre-next/disable_cmake_modules_install.patch
  recipes/ogre-next/fix_pc_files_generation.patch
  recipes/ogre-next/meta.yaml
Labels: review-requested, c-cpp

#19412 .DS_Store files cause build_locally to break on Mac
  .ci_support/build_all.py
Labels: staged-recipes, review-requested

#19220 Add recipe for skprogs
  recipes/skprogs/build.sh
  recipes/skprogs/meta.yaml
  recipes/skprogs/no-python.patch
  recipes/sktools/meta.yaml
Labels: review-requested, c-cpp

#19267 Adding Anuga
  recipes/anuga/meta.yaml
Labels: review-requested, python-c

#19393 Added mystic as a package.
  recipes/mystic/meta.yaml
Labels: staged-recipes, review-requested, python

#19408 Add recipe for traceml
  recipes/traceml/meta.yaml
Labels: staged-recipes, review-requested

#19425 Added python-batch-runner as a package
  recipes/python-batch-runner/LICENSE
  recipes/python-batch-runner/meta.yaml
Labels: staged-recipes, review-requested

#19423 Added litedao as a package
  recipes/litedao/meta.yaml
Labels: staged-recipes, review-requested

#19422 Adde buildver as a package
  recipes/buildver/meta.yaml
Labels: staged-recipes, review-requested

#19421 Added hackernote as a package
  recipes/hackernote/meta.yaml
Labels: staged-recipes, review-requested

#19349 Adding `unionml` from PyPI
  recipes/unionml/meta.yaml
Labels: Awaiting author contribution, python

#19434 Fix build_all
  .ci_support/build_all.py
Labels: staged-recipes, review-requested

#19415 Added python-rex as a package
  recipes/python-rex/LICENSE
  recipes/python-rex/meta.yaml
Labels: staged-recipes, review-requested

#19366 add nzgeom package to conda-forge
  recipes/nzgeom/meta.yaml
Labels: staged-recipes, review-requested

#19417 Initial packaging of Spotipy2
  recipes/spotipy2/LICENSE.txt
  recipes/spotipy2/meta.yaml
Labels: review-requested, python

#19372 Add recipe for fmrib-unpack-fmrib-config
  recipes/fmrib-unpack-fmrib-config/LICENSE
  recipes/fmrib-unpack-fmrib-config/meta.yaml
  recipes/fmrib-unpack-fmrib-config/run_test.py
Labels: staged-recipes, review-requested

#19344 Add rule-engine recipe
  recipes/rule-engine/meta.yaml
Labels: Awaiting author contribution, python

#19411 Package ipybertin
  recipes/ipybertin/meta.yaml
Labels: review-requested, python

#19420 Added threadom as a package
  recipes/threadom/meta.yaml
  recipes/threadom/yum_requirements.txt
Labels: staged-recipes, review-requested

#19418 Added tkstyle as a package
  recipes/tkstyle/meta.yaml
  recipes/tkstyle/yum_requirements.txt
Labels: staged-recipes, review-requested

#19399 Litemark
  recipes/litemark/conda-forge.yml
  recipes/litemark/meta.yaml
  recipes/litemark/yum_requirements.txt
Labels: review-requested, python

#19454 Added nosqlapi as a package
  recipes/nosqlapi/meta.yaml
Labels: staged-recipes, review-requested

#19419 Added tkutil as a package
  recipes/tkutil/meta.yaml
  recipes/tkutil/yum_requirements.txt
Labels: staged-recipes, review-requested

#19456 Added updater as a package.
  recipes/updater/LICENSE
  recipes/updater/meta.yaml
Labels: staged-recipes, review-requested

#19378 Adding openmm-dlext recipe
  recipes/openmm-dlext/build.sh
  recipes/openmm-dlext/meta.yaml
Labels: staged-recipes, review-requested

#19457 Adding `bentoml` and `simple-di` from PyPI
  recipes/bentoml/meta.yaml
  recipes/simple-di/meta.yaml
Labels: review-requested, python

#19350 Add recipe for mopac
  recipes/mopac/bld.bat
  recipes/mopac/build.sh
  recipes/mopac/meta.yaml
  recipes/mopac/mopac-bz.patch
Labels: review-requested, c-cpp

#19354 Add nutpie
  recipes/nutpie/meta.yaml
Labels: Awaiting author contribution, python-c

#19464 Tetraframework
  recipes/tetraframework/LICENSE
  recipes/tetraframework/meta.yaml
Labels: staged-recipes, review-requested, python

#19287 Add skillbridge recipe
  recipes/skillbridge/build.sh
  recipes/skillbridge/meta.yaml
  recipes/skillbridge/skillbridge.init.il
Labels: Awaiting author contribution, python

#19462 Added conda recipe for maicos
  recipes/maicos/meta.yaml
Labels: staged-recipes, review-requested

#19469 Added svg.py as a package
  recipes/svg.py/meta.yaml
Labels: staged-recipes, review-requested

#19468 Adding nb_conda_store_kernels 0.1.3
  recipes/nb_conda_store_kernels/build.sh
  recipes/nb_conda_store_kernels/meta.yaml
  recipes/nb_conda_store_kernels/post-link.sh
  recipes/nb_conda_store_kernels/pre-unlink.sh
Labels: review-requested, python

#18601 add recipe for tiled
  recipes/tiled/bld-tiled.bat
  recipes/tiled/build-tiled.sh
  recipes/tiled/meta.yaml
Labels: Awaiting author contribution, python

#19371 Add recipe for LBFGSpp
  recipes/lbfgspp/bld.bat
  recipes/lbfgspp/build.sh
  recipes/lbfgspp/meta.yaml
Labels: review-requested, c-cpp

#19487 Add hpgeom recipe.
  recipes/hpgeom/meta.yaml
Labels: review-requested, python

#19489 Adding `nashpy` from PyPI
  recipes/nashpy/meta.yaml
Labels: review-requested, python

#19483 Adding nannos
  recipes/nannos/LICENSE.txt
  recipes/nannos/meta.yaml
  recipes/nannos/yum_requirements.txt
Labels: staged-recipes, review-requested

#19432 Add lvis via grayskull
  recipes/lvis/LICENSE
  recipes/lvis/meta.yaml
  recipes/lvis/requirements.txt
  recipes/lvis/yum_requirements.txt
Labels: Awaiting author contribution, python

#19458 Plurmy recipe
  recipes/plurmy/meta.yaml
Labels: review-requested, python

#19300 DOC: Add note about static libraries [ci skip]
  .github/pull_request_template.md
Labels: staged-recipes, review-requested
