Repository conda-forge/staged-recipes, pull requests merged in 2022-05, with the labels that each got.

#18808 Add hashids
  recipes/hashids/meta.yaml
Labels: review-requested, python

#18809 Add blueqat, qforce and pycolt
  recipes/blueqat/LICENSE
  recipes/blueqat/meta.yaml
  recipes/pycolt/meta.yaml
  recipes/qforce/LICENCE
  recipes/qforce/meta.yaml
Labels: staged-recipes, review-requested

#18786 Add recipe for Sella
  recipes/sella/meta.yaml
Labels: review-requested, python

#18774 Add kenlm recipe
  recipes/kenlm/build.sh
  recipes/kenlm/conda_build_config.yaml
  recipes/kenlm/meta.yaml
Labels: staged-recipes, review-requested

#18631 Add recipe for Sparrow Python bindings
  recipes/scine-sparrow-python/build.sh
  recipes/scine-sparrow-python/meta.yaml
  recipes/scine-sparrow-python/skip_library_build.patch
Labels: review-requested, python

#18632 Add recipe for readuct
  recipes/scine-readuct/build.sh
  recipes/scine-readuct/meta.yaml
Labels: review-requested, c-cpp

#18650 Add recipe for Scine wrapper
  recipes/scine-xtb/build.sh
  recipes/scine-xtb/meta.yaml
  recipes/scine-xtb/pkgconfig.patch
Labels: review-requested, c-cpp

#18707 Add recipe for sphinx-jinja2-compat
  recipes/sphinx-jinja2-compat/meta.yaml
Labels: review-requested, python

#18720 Added osdatahub meta.yaml
  recipes/osdatahub/meta.yaml
Labels: review-requested, python

#18731 Add `ibis-heavyai`
  recipes/ibis-heavyai/meta.yaml
Labels: review-requested, python

#18811 Add sqloxide
  recipes/sqloxide/meta.yaml
Labels: review-requested, python, python-c

#18539 Add include-what-you-use
  recipes/iwyu/build.sh
  recipes/iwyu/meta.yaml
Labels: Awaiting author contribution, c-cpp

#18826 Add EZyRB
  recipes/ezyrb/meta.yaml
Labels: staged-recipes, review-requested

#18733 Add marspylib recipe
  recipes/marspylib/meta.yaml
Labels: Awaiting author contribution, python

#18828 Adding isbnlib
  recipes/isbnlib/meta.yaml
Labels: python

#18690 Added pelican-bibliography.
  recipes/pelican-bibliography/meta.yaml
Labels: Awaiting author contribution, python

#18776 adding xnemogcm
  recipes/xnemogcm/LICENSE
  recipes/xnemogcm/meta.yaml
Labels: review-requested, python

#18832 Add energymon recipe
  recipes/energymon/meta.yaml
Labels: staged-recipes, review-requested

#18830 Add recipe for sphinx-toolbox
  recipes/sphinx-toolbox/meta.yaml
Labels: review-requested, python

#18829 Add recipe for sdjson
  recipes/sdjson/meta.yaml
Labels: review-requested, python

#18827 Add cxroots
  recipes/cxroots/meta.yaml
Labels: review-requested, python

#18838 add muspinsim recipe
  recipes/muspinsim/meta.yaml
Labels: review-requested, python

#18788 New py2dm recipe from PyPI w/ version specific edits
  recipes/py2dm/meta.yaml
  recipes/py2dm/run_test.py
Labels: review-requested, python, python-c

#18842 Add qiskit-ibmq-provider
  recipes/qiskit-ibmq-provider/meta.yaml
Labels: review-requested, python

#18845 Add qiskit-finance
  recipes/qiskit-finance/meta.yaml
Labels: review-requested, python

#18821 Add pycdlib-v1.12.0
  recipes/pycdlib/meta.yaml
Labels: review-requested, python

#18807 Adding recipe for mkdocs-graphviz
  recipes/mkdocs-graphviz/meta.yaml
Labels: Awaiting author contribution, python

#18819 Adding `yt-dlg`
  recipes/yt-dlg/meta.yaml
Labels: Awaiting author contribution, python

#18846 Add qiskit-ignis
  recipes/qiskit-ignis/611.patch
  recipes/qiskit-ignis/meta.yaml
Labels: review-requested, python

#18852 added recipe for semi-ate-testers
  recipes/semi-ate-testers/meta.yaml
Labels: staged-recipes, review-requested

#18803 Adding MicroED tools
  recipes/microed-data/bld.bat
  recipes/microed-data/build.sh
  recipes/microed-data/conda_build_config.yaml
  recipes/microed-data/meta.yaml
  recipes/microed-tools/01-setenv.patch
  recipes/microed-tools/02-version.patch
  recipes/microed-tools/03-install.patch
  recipes/microed-tools/04-iconv.patch
  recipes/microed-tools/05-disable-libR.patch
  recipes/microed-tools/06-err_h.patch
  recipes/microed-tools/07-windows.patch
  recipes/microed-tools/08-gcc.patch
  recipes/microed-tools/09-cmake.patch
  recipes/microed-tools/10-warnings.patch
  recipes/microed-tools/bld.bat
  recipes/microed-tools/build.sh
  recipes/microed-tools/conda_build_config.yaml
  recipes/microed-tools/meta.yaml
  recipes/microed-tools/run_test.bat
  recipes/microed-tools/run_test.sh
Labels: review-requested, c-cpp

#18851 Recipe for PyPI package empiricaldist
  recipes/empiricaldist/meta.yaml
Labels: staged-recipes, review-requested, python

#18870 Add recipe for aiosmtpd
  recipes/aiosmtpd/meta.yaml
Labels: review-requested, python

#18872 Add bigearthnet-gdf-builder & bigearthnet-patch-interface
  recipes/bigearthnet-gdf-builder/meta.yaml
  recipes/bigearthnet-patch-interface/meta.yaml
Labels: staged-recipes, review-requested

#18874 Add quacc
  recipes/atomate2/meta.yaml
  recipes/quacc/meta.yaml
Labels: staged-recipes, review-requested

#18854 added recipe for semi-ate-apps-common
  recipes/semi-ate-apps-common/meta.yaml
Labels: staged-recipes, review-requested

#18859 Adding inept
  recipes/inept/meta.yaml
Labels: review-requested, python

#18867 Add pyscript-cli
  recipes/pyscript-cli/meta.yaml
Labels: review-requested, python

#18864 Semi ate master app
  recipes/semi-ate-master-app/meta.yaml
Labels: staged-recipes, review-requested

#18865 Semi ate test app
  recipes/semi-ate-test-app/meta.yaml
Labels: staged-recipes, review-requested

#18841 Add recipe for `mosaic-clustering`
  recipes/mosaic-clustering/meta.yaml
Labels: Awaiting author contribution, python

#18697 add hexwatershed to conda forge
  recipes/hexwatershed/meta.yaml
Labels: staged-recipes, review-requested

#16240 Add r-httpgd
  recipes/r-httpgd/bld.bat
  recipes/r-httpgd/build.sh
  recipes/r-httpgd/meta.yaml
Labels: R, review-requested

#18878 Added recipe for `wsidicom`
  recipes/wsidicom/LICENSE
  recipes/wsidicom/meta.yaml
Labels: staged-recipes, review-requested

#18881 Add bigearthnet-encoder
  recipes/bigearthnet-encoder/meta.yaml
Labels: staged-recipes, review-requested

#18840 add spacy-models 3.3.0
  recipes/spacy-models/_update_spacy_recipe.py
  recipes/spacy-models/meta.yaml
  recipes/spacy-models/meta.yaml.j2
Labels: staged-recipes, review-requested

#18839 Adding hyperbox-brain recipe
  recipes/hyperbox-brain/meta.yaml
Labels: review-requested, python

#18855 added recipe for semi-ate-control-app
  recipes/semi-ate-control-app/meta.yaml
Labels: staged-recipes, review-requested

#18876 add webdataset
  recipes/webdataset/meta.yaml
Labels: review-requested, python

#18471 Add flakeheaven
  recipes/flakeheaven/meta.yaml
Labels: Awaiting author contribution, python

#18879 Add turbo-seti and blimpy
  recipes/blimpy/cython.patch
  recipes/blimpy/meta.yaml
  recipes/turbo-seti/meta.yaml
Labels: staged-recipes, review-requested, python

#18887 Add MNE-ICALabel
  recipes/mne-icalabel/meta.yaml
Labels: staged-recipes, review-requested

#18883 Add ddsketch package
  recipes/ddsketch/meta.yaml
Labels: staged-recipes, review-requested

#18848 Add stestr
  recipes/stestr/meta.yaml
Labels: review-requested, python

#18886 Add esbonio
  recipes/esbonio/meta.yaml
Labels: review-requested, python

#18893 Add recipe for junitparser
  recipes/junitparser/conda-forge.yml
  recipes/junitparser/meta.yaml
Labels: python

#18654 Add py-hunspell recipe
  recipes/pyhunspell/build.sh
  recipes/pyhunspell/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#18683 Add microfilm recipe
  recipes/microfilm/meta.yaml
Labels: review-requested, python

#18910 Adding r-wdm
  recipes/r-wdm/bld.bat
  recipes/r-wdm/build.sh
  recipes/r-wdm/meta.yaml
Labels: staged-recipes, review-requested

#18912 Adding r-rvinecopulib
  recipes/r-rvinecopulib/bld.bat
  recipes/r-rvinecopulib/build.sh
  recipes/r-rvinecopulib/meta.yaml
Labels: staged-recipes, review-requested

#18853 added recipe for semi-ate-spyder
  recipes/semi-ate-spyder/meta.yaml
Labels: Awaiting author contribution, staged-recipes, python

#17217 Add zerorpc recipe
  recipes/zerorpc-python/LICENSE
  recipes/zerorpc-python/meta.yaml
Labels: Awaiting author contribution, python-c

#18775 Adding gsw-xarray
  recipes/gsw-xarray/meta.yaml
Labels: Awaiting author contribution, python

#18875 Adding `Pyload-ng` , `flask-themes2` and `bitmath`
  recipes/bitmath/meta.yaml
  recipes/flask-themes2/meta.yaml
  recipes/pyload-ng/conda_build_config.yaml
  recipes/pyload-ng/meta.yaml
Labels: Awaiting author contribution, python

#18387 added mosquitto package
  recipes/mosquitto/bld.bat
  recipes/mosquitto/build.sh
  recipes/mosquitto/conda-forge.yml
  recipes/mosquitto/meta.yaml
Labels: Awaiting author contribution, staged-recipes, c-cpp

#18889 add sparsearray
  recipes/sparsearray/meta.yaml
Labels: review-requested, python

#18936 Adding recipe for r-msaR
  recipes/r-msar/LICENSE.txt
  recipes/r-msar/bld.bat
  recipes/r-msar/build.sh
  recipes/r-msar/meta.yaml
Labels: R, review-requested

#18894 Add pennylane-honeywell
  recipes/pennylane-honeywell/meta.yaml
Labels: review-requested, python

#18890 add independent fenics-ufl
  recipes/fenics-ufl/meta.yaml
Labels: review-requested, python

#18857 Add pds4_tools
  recipes/pds4_tools/meta.yaml
Labels: Awaiting author contribution, python

#18755 adding quantlib-python
  recipes/quantlib-python/bld.bat
  recipes/quantlib-python/build.sh
  recipes/quantlib-python/meta.yaml
  recipes/quantlib-python/quantlib.hpp
Labels: Awaiting author contribution, python-c

#18948 Add r-mopa package
  recipes/r-mopa/bld.bat
  recipes/r-mopa/build.sh
  recipes/r-mopa/meta.yaml
Labels: R, review-requested

#18947 Add r-loader.2nc package
  recipes/r-loader.2nc/bld.bat
  recipes/r-loader.2nc/build.sh
  recipes/r-loader.2nc/meta.yaml
Labels: R, review-requested

#18946 Add r-climate4r.udg package
  recipes/r-climate4r.udg/bld.bat
  recipes/r-climate4r.udg/build.sh
  recipes/r-climate4r.udg/meta.yaml
Labels: R, review-requested

#18945 Add r-loader.java package
  recipes/r-loader.java/bld.bat
  recipes/r-loader.java/build.sh
  recipes/r-loader.java/meta.yaml
Labels: R, review-requested

#18898 Adding streamad
  recipes/streamad/meta.yaml
Labels: review-requested, python

#18934 add rdflib-sqlalchemy 0.5.1
  recipes/rdflib-sqlalchemy/meta.yaml
  recipes/rdflib-sqlalchemy/run_test.py
Labels: staged-recipes, review-requested, python

#18933 Add alchemlyb
  recipes/alchemlyb/meta.yaml
Labels: staged-recipes, review-requested

#18944 Add flake8-noqa
  recipes/flake8-noqa/meta.yaml
Labels: Awaiting author contribution, python

#17863 Add napari-yolov5 recipe
  recipes/napari-yolov5/meta.yaml
  recipes/napari-yolov5/yum_requirements.txt
Labels: Awaiting author contribution

#18908 adl2pydm -- new recipe created from grayskull
  recipes/adl2pydm/meta.yaml
Labels: staged-recipes, review-requested

#18922 add polygon-api-client and finnhub-python
  recipes/finnhub-python/LICENSE
  recipes/finnhub-python/meta.yaml
  recipes/polygon-api-client/LICENSE
  recipes/polygon-api-client/meta.yaml
Labels: staged-recipes, review-requested

#18907 add wirerope and methodtools
  recipes/methodtools/meta.yaml
  recipes/wirerope/meta.yaml
Labels: Awaiting author contribution, python

#18895 Add blue
  recipes/blue/meta.yaml
Labels: review-requested, python

#18792 add Spidermonkey recipe
  recipes/spidermonkey/0000-fix-config.patch
  recipes/spidermonkey/0001-va-args.patch
  recipes/spidermonkey/build.sh
  recipes/spidermonkey/conda_build_config.yaml
  recipes/spidermonkey/install_bin.sh
  recipes/spidermonkey/install_lib.sh
  recipes/spidermonkey/meta.yaml
Labels: staged-recipes, review-requested, c-cpp, rust

#18959 add r-gbj recipe
  recipes/r-gbj/bld.bat
  recipes/r-gbj/build.sh
  recipes/r-gbj/meta.yaml
Labels: staged-recipes, review-requested

#18931 Add r5py to conda-forge
  recipes/r5py/LICENSE
  recipes/r5py/licenses/GPL-3.0-or-later
  recipes/r5py/licenses/MIT
  recipes/r5py/meta.yaml
Labels: staged-recipes, review-requested, python

#18900 add ipyleaflet-gl-vector-layer-plugin
  recipes/ipyleaflet-gl-vector-layer-plugin/meta.yaml
Labels: staged-recipes, review-requested, python

#18901 add atmosphere-virtual-lab
  recipes/atmosphere-virtual-lab/conda-forge.yml
  recipes/atmosphere-virtual-lab/meta.yaml
  recipes/atmosphere-virtual-lab/yum_requirements.txt
Labels: staged-recipes, review-requested

#18957 Add r-loader.ecoms package
  recipes/r-loader.ecoms/LICENSE.txt
  recipes/r-loader.ecoms/bld.bat
  recipes/r-loader.ecoms/build.sh
  recipes/r-loader.ecoms/meta.yaml
Labels: R, review-requested

#18748 Adding NCAR/geocat-viz package
  recipes/geocat-viz/meta.yaml
Labels: staged-recipes, review-requested, python

#18917 Add apphb recipe
  recipes/apphb/meta.yaml
Labels: review-requested, python

#18923 Adding `exchange_calendars`
  recipes/exchange-calendars/meta.yaml
Labels: review-requested, python

#18979 add dataclasses-jsonschema 2.15.1
  recipes/dataclasses-jsonschema/meta.yaml
Labels: staged-recipes, review-requested, python

#18721 Add httpauth
  recipes/httpauth/LICENSE
  recipes/httpauth/meta.yaml
Labels: staged-recipes, review-requested

#18971 Add r-convertr package
  recipes/r-convertr/bld.bat
  recipes/r-convertr/build.sh
  recipes/r-convertr/meta.yaml
Labels: R, review-requested

#18680 Add expertai-extract
  recipes/expertai-extract/meta.yaml
Labels: Awaiting author contribution, python

#18974 Add r-drought4r package
  recipes/r-drought4r/bld.bat
  recipes/r-drought4r/build.sh
  recipes/r-drought4r/meta.yaml
Labels: R, review-requested

#18997 adding pdr recipe
  recipes/pdr/meta.yaml
Labels: staged-recipes, review-requested

#18970 Add r-climate4r.indices package
  recipes/r-climate4r.indices/LICENSE.txt
  recipes/r-climate4r.indices/bld.bat
  recipes/r-climate4r.indices/build.sh
  recipes/r-climate4r.indices/meta.yaml
Labels: R, review-requested

#18981 Add r-visualizer package
  recipes/r-visualizer/LICENSE.txt
  recipes/r-visualizer/bld.bat
  recipes/r-visualizer/build.sh
  recipes/r-visualizer/meta.yaml
Labels: R, review-requested

#18973 Add r-downscaler package
  recipes/r-deepnet/bld.bat
  recipes/r-deepnet/build.sh
  recipes/r-deepnet/meta.yaml
  recipes/r-downscaler/bld.bat
  recipes/r-downscaler/build.sh
  recipes/r-downscaler/meta.yaml
  recipes/r-sticky/LICENSE
  recipes/r-sticky/bld.bat
  recipes/r-sticky/build.sh
  recipes/r-sticky/meta.yaml
Labels: R, review-requested

#18942 Adding fABBA_package
  recipes/fABBA/meta.yaml
  recipes/fABBA/run_test.py
Labels: Awaiting author contribution, python-c

#18915 Add pyscicat
  recipes/pyscicat/meta.yaml
Labels: review-requested, python

#18320 add rstudio-desktop recipe
  recipes/rstudio/0001-fix-soci.patch
  recipes/rstudio/0002-no-static-linking.patch
  recipes/rstudio/build-desktop.sh
  recipes/rstudio/conda_build_config.yaml
  recipes/rstudio/meta.yaml
  recipes/rstudio/sigstksz_gcc11.patch
  recipes/rstudio/yum_requirements.txt
Labels: R, review-requested, c-cpp

#18916 Adding my ternary-diagram package:v2.1.0
  recipes/ternary-diagram/meta.yaml
Labels: review-requested, python

#18995 add dissutils recipe
  recipes/r-dissutils/bld.bat
  recipes/r-dissutils/build.sh
  recipes/r-dissutils/meta.yaml
Labels: R, review-requested

#19009 adding evodag
  recipes/evodag/meta.yaml
Labels: staged-recipes, review-requested, python

#19011 Add ibis-substrait package
  recipes/ibis-substrait/meta.yaml
Labels: review-requested, python

#18953 add jdot project
  recipes/jdot/meta.yaml
Labels: review-requested, python

#19006 add r-emstreer conda recipe
  recipes/r-emstreer/bld.bat
  recipes/r-emstreer/build.sh
  recipes/r-emstreer/meta.yaml
Labels: R, review-requested

#18994 add geometa recipe
  recipes/r-geometa/bld.bat
  recipes/r-geometa/build.sh
  recipes/r-geometa/meta.yaml
Labels: R, review-requested

#18899 Adding yieldfrom recipe
  recipes/yieldfrom/meta.yaml
Labels: review-requested, python

#19012 add deprecat
  recipes/deprecat/meta.yaml
Labels: staged-recipes, review-requested

#18958 add fenics-ffcx
  recipes/fenics-ffcx/build-ufcx.sh
  recipes/fenics-ffcx/meta.yaml
  recipes/fenics-ffcx/test-ffcx/test_ffcx.py
  recipes/fenics-ffcx/test-ufcx.sh
  recipes/fenics-ffcx/test-ufcx/CMakeLists.txt
  recipes/fenics-ffcx/test-ufcx/test-ufcx.cpp
Labels: review-requested, python-c

#18975 Add r-firedanger package
  recipes/r-firedanger/LICENSE.txt
  recipes/r-firedanger/bld.bat
  recipes/r-firedanger/build.sh
  recipes/r-firedanger/meta.yaml
Labels: R, review-requested

#18980 Add r-value package
  recipes/r-value/LICENSE.txt
  recipes/r-value/bld.bat
  recipes/r-value/build.sh
  recipes/r-value/meta.yaml
Labels: R, review-requested

#18977 Add r-geoprocessor package
  recipes/r-geoprocessor/LICENSE.txt
  recipes/r-geoprocessor/bld.bat
  recipes/r-geoprocessor/build.sh
  recipes/r-geoprocessor/meta.yaml
Labels: R, review-requested

#19024 add fonticon-materialdesignicons6
  recipes/fonticon-materialdesignicons6/meta.yaml
Labels: review-requested, python

#19027 Added recipe for `ACSConv`
  recipes/acsconv/LICENSE
  recipes/acsconv/meta.yaml
Labels: staged-recipes, review-requested

#19028 add fonticon-fontawesome5
  recipes/fonticon-fontawesome5/meta.yaml
Labels: review-requested, python

#19039 Add r-downscaler.keras package
  recipes/r-downscaler.keras/bld.bat
  recipes/r-downscaler.keras/build.sh
  recipes/r-downscaler.keras/meta.yaml
Labels: R, review-requested

#18999 Add r-climate4r.value package
  recipes/r-climate4r.value/bld.bat
  recipes/r-climate4r.value/build.sh
  recipes/r-climate4r.value/meta.yaml
Labels: R, review-requested

#19013 Adding `chalk-diagrams` from PyPI
  recipes/chalk-diagrams/LICENSE
  recipes/chalk-diagrams/meta.yaml
Labels: review-requested, python

#19018 Add sqlalchemy-heavyai
  recipes/sqlalchemy-heavyai/meta.yaml
Labels: Awaiting author contribution, python

#19047 Add `go-sqlcmd`
  recipes/go-sqlcmd/meta.yaml
Labels: staged-recipes, review-requested

#19037 Adding my element-recognition package.
  recipes/element-recognition/meta.yaml
Labels: Awaiting author contribution, python

#18985 New recipe for climlab-cam3-radiation
  recipes/climlab-cam3-radiation/meta.yaml
Labels: review-requested, python

#18998 Adding G2Aero to conda-forge
  recipes/g2aero/meta.yaml
Labels: Awaiting author contribution, python

#18757 Adding PyTFA
  recipes/pytfa/meta.yaml
Labels: Awaiting author contribution, python

#19016 Adding biobox
  recipes/biobox/meta.yaml
Labels: review-requested, python-c

#19026 add llspy-slm
  recipes/llspy-slm/meta.yaml
Labels: Awaiting author contribution, python

#18834 Add r-olinkanalyze recipe
  recipes/r-olinkanalyze/bld.bat
  recipes/r-olinkanalyze/build.sh
  recipes/r-olinkanalyze/meta.yaml
Labels: R, review-requested

#18961 Add looseversion Python package
  recipes/looseversion/meta.yaml
Labels: review-requested, python

#19050 Add windfreak
  recipes/windfreak/LICENSE
  recipes/windfreak/meta.yaml
Labels: review-requested, python

#18926 Add lcensemble
  recipes/lcensemble/meta.yaml
Labels: Awaiting author contribution, python

#18737 Add dasel
  recipes/dasel/meta.yaml
Labels: review-requested, go

#19003 Add emsarray-core recipe
  recipes/emsarray/build_base.sh
  recipes/emsarray/meta.yaml
Labels: Awaiting author contribution, python

#19002 pyaez package added to the conda forge
  recipes/pyaez/LICENSE
  recipes/pyaez/meta.yaml
Labels: staged-recipes, review-requested

#19059 Add nequip
  recipes/e3nn/meta.yaml
  recipes/nequip/LICENSE
  recipes/nequip/meta.yaml
  recipes/opt_einsum_fx/meta.yaml
  recipes/torch-ema/LICENSE
  recipes/torch-ema/meta.yaml
  recipes/torch-runstats/meta.yaml
Labels: staged-recipes, review-requested

#19066 Added ruyaml package
  recipes/ruyaml/meta.yaml
Labels: staged-recipes, review-requested

#19068 Added lineapy as a package
  recipes/lineapy/meta.yaml
Labels: staged-recipes, review-requested

#19030 Add pydarm PyPI package to conda-forge
  recipes/pydarm/meta.yaml
Labels: staged-recipes, review-requested

#19072 Offset
  recipes/offset/LICENSE
  recipes/offset/meta.yaml
Labels: staged-recipes, review-requested

#19069 add dggridr conda recipe
  recipes/r-dggridr/bld.bat
  recipes/r-dggridr/build.sh
  recipes/r-dggridr/meta.yaml
Labels: R, review-requested

#19071 Added nannyml as a package
  recipes/nannyml/meta.yaml
Labels: staged-recipes, review-requested

#19048 Add tptp lark parser
  recipes/tptp-lark-parser/meta.yaml
Labels: staged-recipes, review-requested

#19042 Add hatch_jupyter_builder
  recipes/hatch-jupyter-builder/meta.yaml
Labels: staged-recipes, review-requested

#19053 Add qiskit-experiments
  recipes/qiskit-experiments/meta.yaml
Labels: review-requested, python

#19005 Add deepface, retina-face
  recipes/deepface/meta.yaml
  recipes/deepface/yum_requirements.txt
  recipes/retina-face/meta.yaml
Labels: review-requested, python
