Repository conda-forge/staged-recipes, pull requests merged in 2023-10, with the labels that each got.

#24111 add medchem (generated with grayskull)
  recipes/medchem/meta.yaml
Labels: review-requested, python

#24103 Add VocalPy recipe
  recipes/vocalpy/meta.yaml
Labels: review-requested, python

#24095 New recipe for namex
  recipes/namex/meta.yaml
Labels: review-requested, python

#24022 adding SMiPoly
  recipes/smipoly/meta.yaml
Labels: review-requested, python

#24108 Add packaging for the ASSIST n-body integrator
  recipes/assist/meta.yaml
Labels: staged-recipes, review-requested

#23080 add xgrads
  recipes/xgrads/meta.yaml
Labels: Awaiting author contribution, python

#24124 Add minijinja
  recipes/minijinja/meta.yaml
Labels: review-requested, python

#24110 Add tzfpy
  recipes/tzfpy/meta.yaml
Labels: review-requested, python, rust

#24122 Add css_inline
  recipes/css_inline/LICENSE
  recipes/css_inline/meta.yaml
Labels: review-requested, python

#24133 Add pyvitae
  recipes/pyvitae/LICENSE.md
  recipes/pyvitae/meta.yaml
Labels: review-requested, python

#24132 Add lightly recipe
  recipes/lightly-utils/LICENSE.txt
  recipes/lightly-utils/meta.yaml
  recipes/lightly/meta.yaml
Labels: review-requested, python

#24054 Add openfe-analysis
  recipes/openfe-analysis/meta.yaml
Labels: review-requested, python

#24135 Add stanio from PyPI
  recipes/stanio/meta.yaml
Labels: review-requested, python

#24037 add geo-skeletons package
  recipes/geo-skeletons/meta.yaml
Labels: review-requested, python

#24136 add pytest-mypy-testing 0.1.1
  recipes/pytest-mypy-testing/meta.yaml
Labels: staged-recipes, review-requested, python

#23838 Add freesas recipe
  recipes/freesas/meta.yaml
Labels: review-requested, python-c

#22455 Add gradio-client
  recipes/gradio-client/LICENSE
  recipes/gradio-client/meta.yaml
Labels: review-requested, python

#23976 add gofit
  recipes/GOFit/meta.yaml
Labels: review-requested, python

#24101 Adding `fractal-client`
  recipes/fractal-client/meta.yaml
Labels: review-requested, python

#24123 Add Endstate correction
  recipes/endstate_correction/LICENSE.txt
  recipes/endstate_correction/meta.yaml
Labels: review-requested, python

#24141 add pyconify recipe
  recipes/pyconify/meta.yaml
Labels: review-requested, python

#24045 Add tophu package
  recipes/tophu/meta.yaml
Labels: review-requested, python

#24157 Add `fractal-tasks-core`
  recipes/fractal-tasks-core/meta.yaml
Labels: review-requested, python

#24153 Add schedview recipe
  recipes/schedview/meta.yaml
Labels: review-requested, python

#24152 add types-beautifulsoup4, types-pygments, types-html5lib
  recipes/types-beautifulsoup4/meta.yaml
  recipes/types-html5lib/meta.yaml
  recipes/types-pygments/meta.yaml
Labels: staged-recipes, review-requested, python

#24160 add attrmap package by YiqunChen1999
  recipes/attrmap/meta.yaml
Labels: review-requested, python

#24172 Adding gotm
  recipes/gotm/bld.bat
  recipes/gotm/build.sh
  recipes/gotm/cross-linux.cmake
  recipes/gotm/meta.yaml
Labels: staged-recipes, review-requested

#24174 add psiflow
  recipes/psiflow/meta.yaml
Labels: staged-recipes, review-requested

#24178 Add Knapsack recipe
  recipes/knapsack/meta.yaml
Labels: review-requested, python

#24179 add lenstest
  recipes/lenstest/meta.yaml
Labels: review-requested, python

#24180 Adding apng
  recipes/apng/LICENSE
  recipes/apng/meta.yaml
Labels: review-requested, python

#24181 django-tenant-users
  recipes/django-tenant-users/meta.yaml
Labels: staged-recipes, review-requested

#24182 django-dbbackup
  recipes/django-dbbackup/meta.yaml
Labels: staged-recipes, review-requested

#24183 django-hosts
  recipes/django-hosts/meta.yaml
Labels: staged-recipes, review-requested

#24184 Add django-revproxy
  recipes/diazo/meta.yaml
  recipes/django-revproxy/meta.yaml
Labels: staged-recipes, review-requested

#24188 Add recipe for pyasyncore
  recipes/pyasyncore/meta.yaml
Labels: staged-recipes, review-requested

#24173 Adding py-rattler
  recipes/py-rattler/LICENSE
  recipes/py-rattler/build_base.bat
  recipes/py-rattler/build_base.sh
  recipes/py-rattler/meta.yaml
Labels: review-requested, python

#24198 Add xee package
  recipes/xee/meta.yaml
Labels: review-requested, python

#22625 adding nlpannotator
  recipes/nlpannotator/meta.yaml
Labels: staged-recipes, review-requested

#24202 Add recipe for package alfasim-sdk
  recipes/alfasim-sdk/meta.yaml
Labels: review-requested, python

#24077 adding clarabel
  recipes/clarabel/example_qp.py
  recipes/clarabel/example_sdp.py
  recipes/clarabel/meta.yaml
Labels: review-requested, python

#24206 add veros
  recipes/veros/meta.yaml
Labels: staged-recipes, review-requested

#24176 Adding kernax
  recipes/kernax/meta.yaml
Labels: review-requested, python

#24203 add pycoare
  recipes/pycoare/meta.yaml
Labels: staged-recipes, review-requested

#24208 add rbeast
  recipes/rbeast/meta.yaml
Labels: staged-recipes, review-requested

#24207 add mlo-co2
  recipes/mlo-co2/LICENSE
  recipes/mlo-co2/meta.yaml
Labels: staged-recipes, review-requested

#24205 add bathyreq
  recipes/BathyReq/meta.yaml
Labels: staged-recipes, review-requested

#22773 Adding `discid`
  recipes/discid/meta.yaml
Labels: review-requested, python

#24220 Add searoute
  recipes/searoute/meta.yaml
Labels: review-requested, python

#24214 Adds swifttools v3.0.16
  recipes/swifttools/meta.yaml
Labels: review-requested, python

#24165 Add torchapp v0.3.6
  recipes/torchapp/meta.yaml
Labels: review-requested, python

#24219 Add geoai package
  recipes/geoai/meta.yaml
Labels: review-requested, python

#24210 added cctk
  recipes/cctk/meta.yaml
Labels: staged-recipes, review-requested

#24222 Add swiftbat-0.1.4
  recipes/swiftbat/meta.yaml
Labels: review-requested, python

#24223 Add Qbatch 2.3
  recipes/qbatch/meta.yaml
Labels: review-requested, python

#24212 Add BatAnalysis v1.0.2
  recipes/batanalysis/meta.yaml
Labels: review-requested, python

#24224 Add daft with Grayskull
  recipes/daft/meta.yaml
Labels: review-requested, python

#24228 Add drf-pydantic
  recipes/drf-pydantic/meta.yaml
Labels: staged-recipes, review-requested

#24221 Add recipe for qt-collapsible-section-pyside6
  recipes/qt-collapsible-section-pyside6/meta.yaml
  recipes/qt-collapsible-section-pyside6/yum_requirements.txt
Labels: review-requested, python

#24234 Add django-tree-queries
  recipes/ django-tree-queries/meta.yaml
Labels: staged-recipes, review-requested

#24233 Add django-groups-manager
  recipes/django-groups-manager/meta.yaml
Labels: staged-recipes, review-requested

#24232 Add Django-mptt2
  recipes/django-mptt2/meta.yaml
Labels: staged-recipes, review-requested

#24235 Add django-mptt-tree-editor
  recipes/django-mptt-tree-editor/meta.yaml
Labels: staged-recipes, review-requested

#24236 Add django-orghierarchy
  recipes/django-orghierarchy/meta.yaml
Labels: staged-recipes, review-requested

#24247 Add Vizro
  recipes/vizro/meta.yaml
Labels: staged-recipes, review-requested

#24008 Add CNSR package
  recipes/cnsr/meta.yaml
Labels: review-requested, python

#24150 Kerberos
  recipes/kerberos/LICENSE.txt
  recipes/kerberos/meta.yaml
Labels: staged-recipes, review-requested

#24216 add veros-extra-setups
  recipes/veros-extra-setups/meta.yaml
  recipes/veros-extra-setups/req.patch
Labels: staged-recipes, review-requested

#24238 Add r-bigsparser from CRAN using conda_r_skeleton_helper
  recipes/r-bigsparser/bld.bat
  recipes/r-bigsparser/build.sh
  recipes/r-bigsparser/meta.yaml
Labels: R, review-requested

#24239 Add r-bigutilsr from CRAN using conda_r_skeleton_helper
  recipes/r-bigutilsr/bld.bat
  recipes/r-bigutilsr/build.sh
  recipes/r-bigutilsr/meta.yaml
Labels: R, review-requested

#24240 Add r-runonce from CRAN using conda_r_skeleton_helper
  recipes/r-runonce/bld.bat
  recipes/r-runonce/build.sh
  recipes/r-runonce/meta.yaml
Labels: R, review-requested

#24252 add jsonschema-path 0.3.1
  recipes/jsonschema-path/meta.yaml
Labels: staged-recipes, review-requested, python

#24249 add nanoSCULPT
  recipes/nanoSCULPT/Example.nsparam
  recipes/nanoSCULPT/build.sh
  recipes/nanoSCULPT/make.patch
  recipes/nanoSCULPT/meta.yaml
  recipes/nanoSCULPT/teddy_scaled.obj
Labels: staged-recipes, review-requested

#24259 Create verlib2
  recipes/verlib2/meta.yaml
Labels: staged-recipes, review-requested

#24230 adds r-ordinalnet
  recipes/r-ordinalnet/bld.bat
  recipes/r-ordinalnet/build.sh
  recipes/r-ordinalnet/meta.yaml
Labels: R, review-requested

#24231 add `r-fastglm`
  recipes/r-fastglm/bld.bat
  recipes/r-fastglm/build.sh
  recipes/r-fastglm/meta.yaml
Labels: R, review-requested

#24213 Add `r-rxode2` and dependencies
  recipes/r-rxode2/bld.bat
  recipes/r-rxode2/build.sh
  recipes/r-rxode2/meta.yaml
  recipes/r-rxode2et/bld.bat
  recipes/r-rxode2et/build.sh
  recipes/r-rxode2et/meta.yaml
  recipes/r-rxode2ll/bld.bat
  recipes/r-rxode2ll/build.sh
  recipes/r-rxode2ll/meta.yaml
  recipes/r-rxode2parse/bld.bat
  recipes/r-rxode2parse/build.sh
  recipes/r-rxode2parse/meta.yaml
  recipes/r-rxode2random/bld.bat
  recipes/r-rxode2random/build.sh
  recipes/r-rxode2random/meta.yaml
Labels: R, review-requested

#24237 sorcha-addons: the community addons for sorcha
  recipes/sorcha-addons/meta.yaml
Labels: staged-recipes, review-requested

#24258 Add recipe for cornice package.
  recipes/cornice/meta.yaml
Labels: review-requested, python

#24257 Add lmdbm
  recipes/lmdbm/LICENSE
  recipes/lmdbm/meta.yaml
Labels: staged-recipes, review-requested

#21974 Added festival text-to-speech package with a sample voice
  recipes/festival/build.sh
  recipes/festival/install.sh
  recipes/festival/install_devel.sh
  recipes/festival/install_static.sh
  recipes/festival/meta.yaml
  recipes/festlex-cmu/build.sh
  recipes/festlex-cmu/meta.yaml
  recipes/festlex-poslex/build.sh
  recipes/festlex-poslex/meta.yaml
  recipes/festvox-kallpc16k/build.sh
  recipes/festvox-kallpc16k/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#24253 Adding plaid
  recipes/plaid/meta.yaml
Labels: review-requested, python

#24254 add recipe: 'cognite-sdk'
  recipes/cognite-sdk/meta.yaml
Labels: staged-recipes, review-requested

#24260 ENH add lsstdesc-diffsky
  recipes/lsstdesc-diffsky/meta.yaml
Labels: staged-recipes, review-requested

#24261 Muscat split
  recipes/Muscat/bld_core.bat
  recipes/Muscat/build_core.sh
  recipes/Muscat/meta.yaml
Labels: staged-recipes, review-requested

#24255 Add recipe for sagemaker-kernel-wrapper package
  recipes/sagemaker-kernel-wrapper/meta.yaml
Labels: review-requested, python

#24276 Add pyiron_workflow
  recipes/pyiron_workflow/meta.yaml
  recipes/pyiron_workflow/versioneer.patch
Labels: staged-recipes, review-requested

#24275 Add pyiron_potentialfit
  recipes/pyiron_potentialfit/meta.yaml
Labels: staged-recipes, review-requested

#24271 Add MNE-LSL
  recipes/mne-lsl/meta.yaml
Labels: review-requested, python

#24093 New recipe sparc-x-api
  recipes/sparc-x-api/meta.yaml
Labels: staged-recipes, review-requested, python

#24266 add verapdf 1.25.72
  recipes/verapdf/builder.py
  recipes/verapdf/meta.yaml
  recipes/verapdf/run_test.py
Labels: staged-recipes, review-requested, java

#23909 Adding pestpp
  recipes/pestpp/bld.bat
  recipes/pestpp/build.sh
  recipes/pestpp/meta.yaml
  recipes/pestpp/vendor-licenses/LICENSE
Labels: review-requested, c-cpp

#24281 Add pytorch-msssim 1.0.0
  recipes/pytorch-msssim/meta.yaml
Labels: staged-recipes, review-requested

#24273 Adding r-fastshap
  recipes/r-fastshap/bld.bat
  recipes/r-fastshap/build.sh
  recipes/r-fastshap/meta.yaml
Labels: Awaiting author contribution, R, review-requested

#24274 Adding in r-abcanalysis
  recipes/r-abcanalysis/bld.bat
  recipes/r-abcanalysis/build.sh
  recipes/r-abcanalysis/meta.yaml
Labels: R, review-requested

#24250 Initial commit of r-flowml to conda-forge
  recipes/r-flowml/bld.bat
  recipes/r-flowml/build.sh
  recipes/r-flowml/meta.yaml
Labels: R, review-requested

#24282 Add recipe for aws-glue-sessions python package
  recipes/aws-glue-sessions/meta.yaml
Labels: review-requested, python

#22932 Add pypromice
  recipes/pypromice/meta.yaml
Labels: review-requested, python

#24279 Added pyfabm
  recipes/pyfabm/bld.bat
  recipes/pyfabm/build.sh
  recipes/pyfabm/ersem.patch
  recipes/pyfabm/meta.yaml
Labels: review-requested, python

#24284 new recipe conda-forge for package xsarsea
  recipes/xsarsea/meta.yaml
Labels: staged-recipes, review-requested

#24017 initial feedstock for hypertab via PyPI using grayskull
  recipes/hypertab/LICENSE.txt
  recipes/hypertab/meta.yaml
Labels: review-requested, python

#24293 Adds `r-pcadapt` and dep `r-mmapcharr`
  recipes/r-mmapcharr/bld.bat
  recipes/r-mmapcharr/build.sh
  recipes/r-mmapcharr/meta.yaml
  recipes/r-pcadapt/bld.bat
  recipes/r-pcadapt/build.sh
  recipes/r-pcadapt/meta.yaml
Labels: R, review-requested

#24297 Add SageMaker JupyterLab extensions recipes
  recipes/sagemaker-jupyterlab-emr-extension/meta.yaml
  recipes/sagemaker-jupyterlab-extension-common/meta.yaml
  recipes/sagemaker-jupyterlab-extension/meta.yaml
Labels: review-requested, python

#24130 adding staged-recipes for r-glmmadaptive from conda_r_helper
  recipes/r-glmmadaptive/bld.bat
  recipes/r-glmmadaptive/build.sh
  recipes/r-glmmadaptive/meta.yaml
Labels: R, review-requested

#24277 Adding Facit
  recipes/facit/meta.yaml
Labels: review-requested, python

#24283 new recipe for slcwindinversion
  recipes/slcwindinversion/meta.yaml
Labels: staged-recipes, review-requested

#24296 Add `quartodoc` recipe
  recipes/quartodoc/meta.yaml
Labels: review-requested, python

#24246 Added dtumathtools
  recipes/dtumathtools/meta.yaml
Labels: review-requested, python

#24242 recipe for sagemaker-headless-execution-driver
  recipes/sagemaker-headless-execution-driver/meta.yaml
Labels: review-requested, python

#24307 Adds `r-dbitest`
  recipes/r-dbitest/bld.bat
  recipes/r-dbitest/build.sh
  recipes/r-dbitest/meta.yaml
Labels: R, review-requested

#24294 Add AMReX
  recipes/amrex/3599.patch
  recipes/amrex/bld.bat
  recipes/amrex/build.sh
  recipes/amrex/meta.yaml
Labels: review-requested, c-cpp

#24318 Package pycrdt
  recipes/pycrdt/meta.yaml
Labels: review-requested, python

#24310 PR For Stable Release of NTNU SmallSat HYPSO
  recipes/hypso/meta.yaml
Labels: review-requested, python

#23989 Adding ctre (c++ compile time regular expressions)
  recipes/ctre/bld.bat
  recipes/ctre/build.sh
  recipes/ctre/conda-forge.yml
  recipes/ctre/meta.yaml
Labels: review-requested, c-cpp

#23908 Add pyclesperanto
  recipes/pyclesperanto/meta.yaml
Labels: review-requested, c-cpp

#23957 Add libmirisdr
  recipes/libmirisdr/0001-miri_fm-Don-t-define-round-for-MSVC-use-version-prov.patch
  recipes/libmirisdr/0002-Rename-mirisdr.dll-to-mirisdr-4.dll-on-Windows.patch
  recipes/libmirisdr/bld.bat
  recipes/libmirisdr/build.sh
  recipes/libmirisdr/meta.yaml
  recipes/libmirisdr/post-link.sh
Labels: review-requested, c-cpp

#24308 Add recipe for amazon-codewhisperer-jupyterlab-ext
  recipes/amazon-codewhisperer-jupyterlab-ext/meta.yaml
Labels: staged-recipes, review-requested

#23007 feat: add b3sum
  recipes/b3sum/bld.bat
  recipes/b3sum/build.sh
  recipes/b3sum/meta.yaml
Labels: staged-recipes, review-requested

#22675 angle-grinder: add recipe
  recipes/angle-grinder/build.sh
  recipes/angle-grinder/meta.yaml
Labels: staged-recipes, review-requested

#22677 as-tree: add recipe
  recipes/as-tree/bld.bat
  recipes/as-tree/build.sh
  recipes/as-tree/meta.yaml
Labels: staged-recipes, review-requested

#22678 atuin: add recipe
  recipes/atuin/build.sh
  recipes/atuin/meta.yaml
Labels: staged-recipes, review-requested

#24262 Adding 'python-libdiscid'
  recipes/python-libdiscid/meta.yaml
Labels: review-requested, python-c

#24331 Add grheat
  recipes/grheat/meta.yaml
Labels: review-requested, python

#24185 Adding prettydiff
  recipes/prettydiff/LICENSE
  recipes/prettydiff/meta.yaml
Labels: staged-recipes, review-requested

#23764 Add `reverse-argparse` recipe
  recipes/reverse-argparse/meta.yaml
Labels: review-requested, python

#24196 Adding sardana-ni660x
  recipes/sardana-ni660x/meta.yaml
Labels: review-requested, python

#21177 add gto
  recipes/gto/meta.yaml
Labels: review-requested, python

#24005 add plate-model-manager recipe
  recipes/plate-model-manager/LICENSE
  recipes/plate-model-manager/meta.yaml
Labels: review-requested, python

#24333 Adding mmgp package
  recipes/mmgp/meta.yaml
Labels: review-requested, python

#24338 Add modelx-cython recipe
  recipes/modelx-cython/meta.yaml
Labels: staged-recipes, review-requested

#24131 New recipe `keras-core`
  recipes/keras-core/LICENSE
  recipes/keras-core/meta.yaml
Labels: review-requested, python

#24341 Add ghstack
  recipes/ghstack/meta.yaml
Labels: review-requested, python

#24342 Add lintrunner
  recipes/lintrunner/conda-forge.yml
  recipes/lintrunner/meta.yaml
Labels: staged-recipes, review-requested

#24330 A python only class library for programatic html document construction -- first conda upload for both this package and me
  recipes/ja-webutils/meta.yaml
Labels: review-requested, python

#23818 Adding MGIS (MFrontGenericInterfaceSupport) by tfel
  recipes/mgis/build.sh
  recipes/mgis/conda_build_config.yaml
  recipes/mgis/meta.yaml
Labels: review-requested, python-c

#24344 Adding mtpy-v2
  recipes/mtpy-v2/meta.yaml
Labels: review-requested, python

#24011 Adding REEF3D and DIVEMesh
  recipes/divemesh/build.sh
  recipes/divemesh/meta.yaml
  recipes/reef3d/build.sh
  recipes/reef3d/conda_build_config.yaml
  recipes/reef3d/meta.yaml
Labels: review-requested, c-cpp

#24021 Adding TorchMD-NET
  recipes/torchmd-net/build.sh
  recipes/torchmd-net/meta.yaml
Labels: staged-recipes, review-requested, python-c

#24298 Add pyAMReX
  recipes/pyamrex/203.patch
  recipes/pyamrex/bld.bat
  recipes/pyamrex/build.sh
  recipes/pyamrex/meta.yaml
  recipes/pyamrex/test.bat
  recipes/pyamrex/test.sh
Labels: review-requested, python-c

#24349 Add `r-latexpdf`
  recipes/r-latexpdf/bld.bat
  recipes/r-latexpdf/build.sh
  recipes/r-latexpdf/meta.yaml
Labels: R, review-requested

#23897 add subarch-select
  recipes/subarch-select/build.sh
  recipes/subarch-select/makefile_tweaks.patch
  recipes/subarch-select/meta.yaml
Labels: Awaiting author contribution, c-cpp

#24311 Add mubody recipe
  recipes/mubody/meta.yaml
Labels: review-requested, python

#23306 Add proxy-tools pure python package
  recipes/proxy-tools/meta.yaml
Labels: staged-recipes, review-requested, python

#23804 Adding r5py.sampledata.sao_paulo
  recipes/r5py.sampledata.sao_paulo/GPL-3.0-or-later
  recipes/r5py.sampledata.sao_paulo/LICENSE
  recipes/r5py.sampledata.sao_paulo/MIT
  recipes/r5py.sampledata.sao_paulo/meta.yaml
Labels: review-requested, python

#23803 Adding r5py.sampledata.helsinki
  recipes/r5py.sampledata.helsinki/GPL-3.0-or-later
  recipes/r5py.sampledata.helsinki/LICENSE
  recipes/r5py.sampledata.helsinki/MIT
  recipes/r5py.sampledata.helsinki/meta.yaml
Labels: review-requested, python

#24357 add lintrunner-adapters 0.11.0
  recipes/lintrunner-adapters/meta.yaml
Labels: staged-recipes, review-requested, python

#24356 Added plotms
  recipes/plotms/build.sh
  recipes/plotms/meta.yaml
Labels: staged-recipes, review-requested

#24365 Adding Augmentor
  recipes/Augmentor/meta.yaml
Labels: review-requested, python

#23762 Add a new package called mp_pytorch from pypi
  recipes/mp_pytorch/meta.yaml
Labels: staged-recipes, review-requested

#24229 Add pyefd recipe
  recipes/pyefd/meta.yaml
  recipes/pyefd/setup.patch
Labels: staged-recipes, review-requested
