Repository conda-forge/staged-recipes, pull requests merged in 2023-02, with the labels that each got.

#21637 Package hatch-regex-commit
  recipes/hatch-regex-commit/meta.yaml
  recipes/hatch-regex-commit/pyproject.patch
Labels: review-requested, python

#21758 Package jupyter_server_xarray_leaflet
  recipes/jupyter_server_xarray_leaflet/meta.yaml
Labels: review-requested, python

#21642 Adds crowdin-api-client
  recipes/crowdin-api-client/meta.yaml
Labels: review-requested, python

#21643 Adds copier-templates-extensions
  recipes/copier-templates-extensions/meta.yaml
Labels: review-requested, python

#21727 add recipe for morphys
  recipes/morphys/meta.yaml
Labels: review-requested, python

#21699 Add rosbags
  recipes/rosbags/meta.yaml
Labels: review-requested, python

#21728 add recipe for py-geth
  recipes/py-geth/meta.yaml
Labels: review-requested, python

#21892 Added speech_tools package
  recipes/libestools/build.sh
  recipes/libestools/meta.yaml
Labels: review-requested, c-cpp

#21715 Add pycolmap
  recipes/pycolmap/68_91.patch
  recipes/pycolmap/fix-win-build.patch
  recipes/pycolmap/meta.yaml
  recipes/pycolmap/use-conda-pybind11.patch
  recipes/pycolmap/yum_requirements.txt
Labels: review-requested, python-c

#21269 Add r-metamix
  recipes/r-metamix/bld.bat
  recipes/r-metamix/build.sh
  recipes/r-metamix/meta.yaml
  recipes/r-metamix/yum_requirements.txt
Labels: R, review-requested

#21654 add pygadm lib
  recipes/pygadm/meta.yaml
Labels: Awaiting author contribution, python

#21582 Adding pdal-parallelizer recipe
  recipes/pdal-parallelizer/meta.yaml
Labels: Awaiting author contribution, python

#21691 add interpret and interpret-core to conda-forge
  recipes/interpret-core/LICENSE
  recipes/interpret-core/meta.yaml
  recipes/interpret/LICENSE
  recipes/interpret/meta.yaml
Labels: staged-recipes, review-requested

#21668 Add animatplot-ng
  recipes/animatplot-ng/meta.yaml
Labels: Awaiting author contribution, python

#21588 Add Grafana-client recipe
  recipes/grafana-client/meta.yaml
Labels: Awaiting author contribution, python

#21926 Add felyx-report recipe
  recipes/felyx-report/meta.yaml
Labels: staged-recipes, review-requested, python

#21556 Add recipe for delta-spark library
  recipes/delta-spark/meta.yaml
Labels: Awaiting author contribution, python

#21925 Add felyx-processor recipe
  recipes/felyx-processor/meta.yaml
Labels: staged-recipes, review-requested, python

#21876 Add trame
  recipes/trame-client/meta.yaml
  recipes/trame-components/meta.yaml
  recipes/trame-deckgl/meta.yaml
  recipes/trame-markdown/meta.yaml
  recipes/trame-matplotlib/meta.yaml
  recipes/trame-plotly/meta.yaml
  recipes/trame-rca/meta.yaml
  recipes/trame-router/meta.yaml
  recipes/trame-server/meta.yaml
  recipes/trame-simput/meta.yaml
  recipes/trame-vega/meta.yaml
  recipes/trame-vtk/meta.yaml
  recipes/trame-vuetify/meta.yaml
  recipes/trame/meta.yaml
Labels: review-requested, python

#21886 Add PyPI package reportseff
  recipes/reportseff/meta.yaml
Labels: review-requested, python

#21928 Added colourmap as a package
  recipes/colourmap/meta.yaml
Labels: staged-recipes, review-requested

#21631 Add readthedocs-sphinx-ext
  recipes/readthedocs-sphinx-ext/meta.yaml
Labels: review-requested, python

#21929 Add dash_bootstrap_templates
  recipes/dash-bootstrap-templates/meta.yaml
Labels: staged-recipes, review-requested, python

#21950 Add sixelcrop
  recipes/sixelcrop/meta.yaml
Labels: staged-recipes, review-requested

#21961 Add cerberecontrib-s3 recipe
  recipes/cerberecontrib-s3/meta.yaml
Labels: staged-recipes, review-requested, python

#21937 Add recipe for buf
  recipes/buf/conda-forge.yml
  recipes/buf/conda_build_config.yaml
  recipes/buf/meta.yaml
Labels: staged-recipes, review-requested

#21964 add types-openpyxl 3.0.4.5
  recipes/types-openpyxl/meta.yaml
Labels: staged-recipes, review-requested, python

#21968 Added starlette-testclient as a package
  recipes/starlette-testclient/meta.yaml
Labels: staged-recipes, review-requested

#21888 Add pyceres
  recipes/pyceres/fix-cmake.patch
  recipes/pyceres/fix-glog-init.patch
  recipes/pyceres/fix-win-build.patch
  recipes/pyceres/fixup-version-number.patch
  recipes/pyceres/meta.yaml
Labels: review-requested, python-c

#21970 Adding SDGym
  recipes/sdgym/meta.yaml
Labels: staged-recipes, review-requested

#21969 Added flet-core as a package
  recipes/flet-core/LICENSE
  recipes/flet-core/meta.yaml
Labels: staged-recipes, review-requested

#21941 Add recipe for CausalEGM
  recipes/CausalEGM/meta.yaml
Labels: review-requested, python

#21956 adding geohexviz
  recipes/geohexviz/meta.yaml
Labels: review-requested, python

#21960 Added recipe for sphinxcontrib-youtube.
  recipes/sphinxcontrib-youtube/meta.yaml
Labels: review-requested, python

#21973 Adding actinia-python-client package
  recipes/actinia-python-client/meta.yaml
Labels: review-requested, python

#21971 Adding refinitiv-data library recipe
  recipes/refinitiv-data/meta.yaml
Labels: review-requested, python

#21936 Add recipe for tableschema-to-template
  recipes/tableschema-to-template/meta.yaml
Labels: review-requested, python

#21880 Adding HWS package recipe
  recipes/hws/meta.yaml
Labels: review-requested, python

#21942 Adding fast_matrix_market
  recipes/fast_matrix_market/meta.yaml
Labels: review-requested, python

#21906 Add publicsuffixlist
  recipes/publicsuffixlist/meta.yaml
Labels: review-requested, python

#21883 add zppy + zstash to conda-forge
  recipes/zppy/meta.yaml
  recipes/zppy/patches/fix-setup-py.patch
  recipes/zstash/meta.yaml
  recipes/zstash/patches/fix-setup-py.patch
Labels: review-requested, python

#21978 Add recipe for hdx-python-utilities
  recipes/hdx-python-utilities/meta.yaml
Labels: review-requested, python

#21889 Adding dargparser
  recipes/dargparser/meta.yaml
Labels: review-requested, python

#21912 Add python-zlib-ng recipe
  recipes/python-zlib-ng/meta.yaml
Labels: review-requested, python

#21743 Adding pudu recipe
  recipes/pudu/meta.yaml
Labels: review-requested, python

#21667 Add libde265 h.265 video codec
  recipes/libde265/bld.bat
  recipes/libde265/build.sh
  recipes/libde265/meta.yaml
Labels: review-requested, c-cpp

#21884 Add recipe for `ap_features`
  recipes/ap_features/meta.yaml
Labels: review-requested, python-c

#21962 adding cmpitool for climate model performance indicies
  recipes/cmpitool/meta.yaml
Labels: review-requested, python

#21879 Add gradio recipe
  recipes/gradio/meta.yaml
Labels: review-requested, python

#21890 Adding gettsim
  recipes/gettsim/meta.yaml
Labels: review-requested, python

#20976 Add dhall
  recipes/dhall-python/meta.yaml
Labels: Awaiting author contribution, python, python-c

#21981 Added alphalens recipe
  recipes/alphalens-reloaded/meta.yaml
Labels: review-requested, python

#21980 Added pyfolio recipe
  recipes/pyfolio-reloaded/meta.yaml
Labels: review-requested, python

#21979 add pyxpcm
  recipes/pyxpcm/LICENSE.txt
  recipes/pyxpcm/meta.yaml
Labels: staged-recipes, review-requested

#21984 Add recipe for hdx-python-country
  recipes/hdx-python-country/meta.yaml
Labels: review-requested, python

#16235 Add SIRIUS ms software to conda-forge
  recipes/sirius-ms/Kaempferol.ms
  recipes/sirius-ms/bld.bat
  recipes/sirius-ms/build.sh
  recipes/sirius-ms/meta.yaml
  recipes/sirius-ms/run_test.bat
  recipes/sirius-ms/run_test.sh
Labels: review-requested, c-cpp, java

#21983 Add mamonca
  recipes/mamonca/meta.yaml
Labels: staged-recipes, review-requested

#21652 Add ConservedWaterSearch and WaterNetworkAnalysis recepies
  recipes/ConservedWaterSearch/meta.yaml
  recipes/WaterNetworkAnalysis/meta.yaml
Labels: review-requested, python

#21987 Add recipe for hdx-python-api
  recipes/hdx-python-api/meta.yaml
Labels: review-requested, python

#21885 Adding pyiron_ontology package
  recipes/pyiron_ontology/meta.yaml
Labels: review-requested, python

#21996 Add rvc3python
  recipes/rvc3python/meta.yaml
Labels: review-requested, python

#21997 Add recipe for rst-to-myst and its missing dependencies
  recipes/mdformat-deflist/meta.yaml
  recipes/mdformat-frontmatter/meta.yaml
  recipes/mdformat-myst/meta.yaml
  recipes/mdformat-tables/meta.yaml
  recipes/rst-to-myst/meta.yaml
Labels: review-requested, python

#22005 Create recipe for r-ggspatial
  recipes/r-ggspatial/bld.bat
  recipes/r-ggspatial/build.sh
  recipes/r-ggspatial/meta.yaml
Labels: R, staged-recipes, review-requested

#21990 Add r-intrinsic (with dep r-salso)
  recipes/r-intrinsic/bld.bat
  recipes/r-intrinsic/build.sh
  recipes/r-intrinsic/meta.yaml
  recipes/r-salso/bld.bat
  recipes/r-salso/build.sh
  recipes/r-salso/meta.yaml
Labels: R, review-requested

#15717 Add openEO recipe
  recipes/openeo/meta.yaml
Labels: staged-recipes, review-requested

#22000 Adding trackintel
  recipes/trackintel/meta.yaml
Labels: review-requested, python

#21999 Add recipe for `modelparameters`
  recipes/modelparameters/meta.yaml
Labels: review-requested, python

#21882 add dolfinx_mpc
  recipes/dolfinx_mpc/build-cpp.sh
  recipes/dolfinx_mpc/build-py.sh
  recipes/dolfinx_mpc/conda_build_config.yaml
  recipes/dolfinx_mpc/meta.yaml
  recipes/dolfinx_mpc/yum_requirements.txt
Labels: review-requested, python-c

#22008 add autodoc-traits 1.1.0
  recipes/autodoc-traits/meta.yaml
Labels: staged-recipes, review-requested, python

#22011 add pyodide-build 0.22.1 and dependencies
  recipes/auditwheel-emscripten/meta.yaml
  recipes/leb128/meta.yaml
  recipes/pyodide-build/0000-no-cmake-from-pip.patch
  recipes/pyodide-build/meta.yaml
  recipes/pyodide-cli/meta.yaml
Labels: staged-recipes, review-requested, python

#21672 add scenepic
  recipes/scenepic/meta.yaml
Labels: staged-recipes, review-requested, python-c

#22010 Add a recipe for sphinx-multiversion
  recipes/sphinx-multiversion/LICENSE
  recipes/sphinx-multiversion/meta.yaml
Labels: review-requested, python

#22002 Adding protex
  recipes/protex/meta.yaml
Labels: review-requested, python

#22012 Add recipe for gotran
  recipes/gotran/meta.yaml
Labels: review-requested, python

#22015 Add recipe for google-cloud-dataflow-client
  recipes/google-cloud-dataflow-client/meta.yaml
Labels: review-requested, python

#22007 add nautilus-sampler
  recipes/nautilus-sampler/meta.yaml
Labels: staged-recipes, review-requested, python

#21804 Add opentelemetry-distro package
  recipes/opentelemetry-distro/LICENSE
  recipes/opentelemetry-distro/meta.yaml
Labels: review-requested, python

#21404 Add qiskit-aer (and muparserx)
  recipes/muparserx/build.sh
  recipes/muparserx/meta.yaml
  recipes/qiskit-aer/0001-Drop-setup_requires.patch
  recipes/qiskit-aer/meta.yaml
Labels: review-requested, c-cpp, python-c

#22023 Adding pyLBL package
  recipes/pyLBL/meta.yaml
Labels: review-requested, python-c

#22034 ENH add conda-forge-feedstock-check-solvable
  recipes/conda_forge_feedstock_check_solvable/meta.yaml
Labels: staged-recipes, review-requested

#22009 add dbscan
  recipes/dbscan/meta.yaml
Labels: review-requested, python-c

#22040 Adding BitVector
  recipes/BitVector/LICENSE
  recipes/BitVector/meta.yaml
Labels: review-requested, python

#22039 add grand and MDRestraintsGenerator
  recipes/MDRestraintsGenerator/meta.yaml
  recipes/grand/meta.yaml
Labels: review-requested, python

#22037 feat: Add python package itksn
  recipes/itksn/meta.yaml
Labels: review-requested, python

#21862 Add pyspf
  recipes/pyspf/LICENSE.txt
  recipes/pyspf/meta.yaml
Labels: review-requested, python

#21864 Add publicsuffix
  recipes/publicsuffix/meta.yaml
Labels: review-requested, python

#22043 Added cubo recipe
  recipes/cubo/meta.yaml
Labels: review-requested, python

#22048 Add asyncache
  recipes/asyncache/meta.yaml
Labels: Awaiting author contribution, python

#21998 Add openff-nagl
  recipes/openff-nagl/meta.yaml
Labels: Awaiting author contribution, python

#21622 Add arrow-adbc packages
  recipes/arrow-adbc/build-cpp.bat
  recipes/arrow-adbc/build-cpp.sh
  recipes/arrow-adbc/build-python.bat
  recipes/arrow-adbc/build-python.sh
  recipes/arrow-adbc/conda_build_config.yaml
  recipes/arrow-adbc/meta.yaml
Labels: review-requested, python-c

#22063 adding qibolab
  recipes/qibolab/meta.yaml
Labels: review-requested, python

#22058 Adding Python package auto-intersphinx
  recipes/auto-intersphinx/meta.yaml
Labels: review-requested, python

#22053 Add cuda-version recipe
  recipes/cuda-version/meta.yaml
Labels: staged-recipes, review-requested

#22049 Adding tacco package
  recipes/tacco/meta.yaml
Labels: review-requested, python

#22038 Create recipe for quetz-sql-authenticator
  recipes/quetz-sql-authenticator/meta.yaml
Labels: review-requested, python

#20941 Add mitmproxy_wireguard
  recipes/mitmproxy_wireguard/meta.yaml
Labels: Awaiting author contribution, staged-recipes, python-c

#22070 ENH added montara
  recipes/montara/meta.yaml
Labels: staged-recipes, review-requested

#21893 Add recipe for libvulkan-loader package
  recipes/vulkan-loader/bld.bat
  recipes/vulkan-loader/build.sh
  recipes/vulkan-loader/disable_macos_framework.patch
  recipes/vulkan-loader/meta.yaml
Labels: review-requested, c-cpp

#22055 Adding XYMOL
  recipes/xymol/LICENSE
  recipes/xymol/meta.yaml
Labels: staged-recipes, review-requested

#21982 Add libheif - a HEIF and AVIF (AV1 Image File Format) file format decoder and encoder
  recipes/libheif/bld.bat
  recipes/libheif/build.sh
  recipes/libheif/conda_build_config.yaml
  recipes/libheif/meta.yaml
Labels: review-requested, c-cpp

#22022 Added datamodel-code-generator as a package
  recipes/datamodel-code-generator/meta.yaml
Labels: staged-recipes, review-requested

#22081 Add riccati
  recipes/riccati/meta.yaml
Labels: staged-recipes, review-requested

#22087 Add Openphase
  recipes/openphase/build.sh
  recipes/openphase/conda_build_config.yaml
  recipes/openphase/make.patch
  recipes/openphase/meta.yaml
Labels: staged-recipes, review-requested

#22090 Add r-sever package
  recipes/r-sever/bld.bat
  recipes/r-sever/build.sh
  recipes/r-sever/meta.yaml
Labels: R, review-requested

#22088 add r-multilevelmod 1.0.0
  recipes/r-multilevelmod/bld.bat
  recipes/r-multilevelmod/build.sh
  recipes/r-multilevelmod/meta.yaml
Labels: R, review-requested

#22098 Add units
  recipes/units/meta.yaml
Labels: staged-recipes, review-requested

#21842 Add recipe for uWebSockets C++ library
  recipes/libuwebsockets/CMakeLists.txt
  recipes/libuwebsockets/bld.bat
  recipes/libuwebsockets/build.sh
  recipes/libuwebsockets/meta.yaml
Labels: review-requested, c-cpp

#21823 Add rathole
  recipes/rathole/meta.yaml
Labels: review-requested, c-cpp

#22065 add xformers
  recipes/pyre-extensions/meta.yaml
  recipes/xformers/meta.yaml
Labels: staged-recipes, review-requested

#22118 Add recipe for sse2neon
  recipes/sse2neon/bld.bat
  recipes/sse2neon/build.sh
  recipes/sse2neon/meta.yaml
Labels: staged-recipes, review-requested

#22021 Added dbt-artifacts-parser as package
  recipes/dbt-artifacts-parser/meta.yaml
Labels: staged-recipes, review-requested

#22104 Add snax recipe
  recipes/snax/meta.yaml
Labels: staged-recipes, review-requested

#22140 Add oxDNA-analysis-tools
  recipes/oxDNA-analysis-tools/LICENSE
  recipes/oxDNA-analysis-tools/meta.yaml
Labels: staged-recipes, review-requested

#22119 Adding cascade
  recipes/cascade/bld.bat
  recipes/cascade/build.sh
  recipes/cascade/conda_build_config.yaml
  recipes/cascade/meta.yaml
Labels: staged-recipes, review-requested

#22135 Add djantic
  recipes/djantic/meta.yaml
Labels: staged-recipes, review-requested

#22137 add pyngo
  recipes/pyngo/meta.yaml
Labels: staged-recipes, review-requested

#22155 Add eo-harvest recipe
  recipes/eo-harvest/meta.yaml
Labels: staged-recipes, review-requested, python

#22153 add pydantic-sqlalchemy
  recipes/pydantic-sqlalchemy/meta.yaml
Labels: staged-recipes, review-requested

#22152 Add ydata-synthetic 0.9
  recipes/ydata-synthetic/meta.yaml
Labels: staged-recipes, review-requested

#22151 Added nestd as a pacakge
  recipes/nestd/LICENCE.md
  recipes/nestd/meta.yaml
Labels: staged-recipes, review-requested

#22150 Add ydata-quality 0.1
  recipes/ydata-quality/meta.yaml
Labels: staged-recipes, review-requested

#22149 Add Ydata-Profiling 4
  recipes/ydata-profiling/meta.yaml
Labels: staged-recipes, review-requested

#22145 Add tox-poetry-installer
  recipes/tox-poetry-installer/meta.yaml
Labels: staged-recipes, review-requested

#22144 Add djangorestframework-dataclasses
  recipes/djangorestframework-dataclasses/meta.yaml
Labels: staged-recipes, review-requested

#22057 Add s2geography
  recipes/s2geography/bld.bat
  recipes/s2geography/build.sh
  recipes/s2geography/meta.yaml
Labels: review-requested, c-cpp

#22094 Add recipe for wilds
  recipes/wilds/LICENSE
  recipes/wilds/meta.yaml
Labels: staged-recipes, review-requested
