Repository conda-forge/staged-recipes, pull requests merged in 2023-03, with the labels that each got.

#22126 Add recipe for brie
  recipes/baked-brie/meta.yaml
Labels: staged-recipes, review-requested

#22187 Add django-safedelete
  newfile.txt
  recipes/django-safedelete/meta.yaml
Labels: staged-recipes, review-requested

#22163 Adding ecodata
  recipes/ecodata/meta.yaml
Labels: review-requested, python

#22182 Add conda recipe for barrier3d
  recipes/barrier3d/meta.yaml
Labels: staged-recipes, review-requested

#22026 add kartograf
  recipes/kartograf/meta.yaml
Labels: review-requested, python

#22059 adding repytah package
  recipes/repytah/meta.yaml
  recipes/repytah/yum_requirements.txt
Labels: review-requested, python

#22080 Add mkdocs-include-markdown-plugin
  recipes/mkdocs-include-markdown-plugin/meta.yaml
Labels: review-requested, python

#22079 add miss-hit (matlab/octave linter)
  recipes/miss-hit-core/LICENSE
  recipes/miss-hit-core/meta.yaml
  recipes/miss-hit/LICENSE.APGL
  recipes/miss-hit/meta.yaml
Labels: review-requested, python

#21602 Add qiskit-metal
  recipes/qiskit-metal/meta.yaml
  recipes/qiskit-metal/yum_requirements.txt
Labels: Awaiting author contribution, python

#21896 Add ratarmount
  recipes/ratarmount/meta.yaml
  recipes/ratarmount/yum_requirements.txt
Labels: Awaiting author contribution, python

#22089 add DE-ForceFields
  recipes/de-forcefields/meta.yaml
Labels: review-requested, python

#22154 add StrEnum
  recipes/strenum/meta.yaml
Labels: review-requested, python

#22176 Adding clapper
  recipes/clapper/meta.yaml
Labels: review-requested, python

#22200 Added rodeometric
  recipes/rodeometric/meta.yaml
Labels: staged-recipes, review-requested

#21683 Add dbt-spark
  recipes/dbt-spark/License.md
  recipes/dbt-spark/meta.yaml
Labels: staged-recipes, review-requested

#22160 add r-mclogit
  recipes/r-mclogit/bld.bat
  recipes/r-mclogit/build.sh
  recipes/r-mclogit/meta.yaml
Labels: R, review-requested

#22202 add xsarslc meta.yaml for condaforge automation
  recipes/xsarslc/meta.yaml
Labels: review-requested, python

#22170 Add Spox
  recipes/spox/meta.yaml
Labels: review-requested, python

#21786 Add libtinyiiod package
  recipes/libtinyiiod/bld.bat
  recipes/libtinyiiod/build.sh
  recipes/libtinyiiod/meta.yaml
Labels: review-requested, c-cpp

#22223 Add reactivex recipe
  recipes/reactivex/meta.yaml
Labels: review-requested, python

#22046 Add recipe for bayes-filters-lib C++ library
  recipes/bayes-filters-lib/bld.bat
  recipes/bayes-filters-lib/build.sh
  recipes/bayes-filters-lib/meta.yaml
Labels: review-requested, c-cpp

#22209 Add jupyterlab-spreadsheet-editor
  recipes/jupyterlab-spreadsheet-editor/meta.yaml
Labels: review-requested, python

#22217 Add recipe for PyPI package pyeditdistance
  recipes/pyeditdistance/meta.yaml
Labels: review-requested, python

#22093 Add Priori
  recipes/priori/meta.yaml
Labels: review-requested, python

#22245 add hydra-colorlog and read-version
  recipes/hydra-colorlog/LICENSE
  recipes/hydra-colorlog/meta.yaml
  recipes/read-version/meta.yaml
Labels: staged-recipes, review-requested

#22106 Adding pygplates
  recipes/pygplates/bld.bat
  recipes/pygplates/build.sh
  recipes/pygplates/conda_build_config.yaml
  recipes/pygplates/meta.yaml
  recipes/pygplates/yum_requirements.txt
Labels: review-requested, python-c

#22256 Adding netgraph
  recipes/netgraph/meta.yaml
Labels: Awaiting author contribution, python

#22190 Add pythresh
  recipes/pythresh/meta.yaml
Labels: review-requested, python

#22210 Add Python noarch: get-annotations
  recipes/get-annotations/meta.yaml
Labels: review-requested, python

#22001 Add recipe for airss
  recipes/airss/airss-bin.txt
  recipes/airss/build_airss.sh
  recipes/airss/build_default.sh
  recipes/airss/meta.yaml
  recipes/airss/patches/makefile.patch
  recipes/airss/patches/no-symmol.patch
  recipes/airss/scripts/airss.sh
Labels: review-requested, c-cpp

#22117 recipe for ckmeans-1d-dp
  recipes/ckmeans-1d-dp/meta.yaml
Labels: review-requested, python-c

#22114 add recipe for marching_cubes package
  recipes/marching_cubes/0001-ssize_t-in-parallel-fors-for-windows.patch
  recipes/marching_cubes/bld.bat
  recipes/marching_cubes/build.sh
  recipes/marching_cubes/meta.yaml
Labels: review-requested, python-c

#22091 Add libebm, the native library for the conda-forge package interpret
  recipes/libebm/meta.yaml
Labels: review-requested, c-cpp

#22264 Add recipe for pyflowchart
  recipes/pyflowchart/meta.yaml
Labels: staged-recipes, review-requested

#22244 Adding robot_descriptions recipe
  recipes/robot_descriptions/meta.yaml
Labels: review-requested, python

#22247 Add lightning-cloud
  recipes/lightning-cloud/meta.yaml
Labels: review-requested, python

#22253 Adding watex- machine learning research in water exploration package
  recipes/watex/LICENSE
  recipes/watex/meta.yaml
Labels: Awaiting author contribution, python

#21348 Add pynsee pkg
  recipes/pynsee/meta.yaml
Labels: staged-recipes, review-requested

#22254 Add openff-nagl-models
  recipes/openff-nagl-models/meta.yaml
Labels: review-requested, python

#22240 Add Parsita
  recipes/parsita/meta.yaml
Labels: Awaiting author contribution, python

#22265 BUG remake ngmix
  recipes/ngmix/meta.yaml
Labels: staged-recipes, review-requested

#22236 NEW: Add ABI compliance checker
  recipes/abi-compliance-checker/meta.yaml
  recipes/abi-dumper/meta.yaml
Labels: review-requested, c-cpp, perl

#22234 Add transformer-smaller-training-vocab
  recipes/transformer-smaller-training-vocab/meta.yaml
Labels: Awaiting author contribution, python

#22250 Add fastapi-azure-auth conda recipe
  recipes/fastapi-azure-auth/meta.yaml
Labels: Awaiting author contribution, python

#22115 Add kfp-tekton-server-api recipe
  recipes/kfp-tekton-server-api/LICENSE
  recipes/kfp-tekton-server-api/meta.yaml
Labels: review-requested, python

#22061 Provide asimov feedstock
  recipes/asimov/meta.yaml
Labels: staged-recipes, review-requested

#22268 Package asphalt-web
  recipes/asphalt-web/meta.yaml
Labels: review-requested, python

#22111 Adding lilio
  recipes/lilio/meta.yaml
Labels: review-requested, python

#22121 add fortecubeview
  recipes/fortecubeview/meta.yaml
Labels: review-requested, python

#22131 Adding pybads package
  recipes/pybads/meta.yaml
Labels: review-requested, python

#22096 Adding django-json-widget
  recipes/django_json_widget/meta.yaml
Labels: Awaiting author contribution, python

#22112 Add python-pypi-mirror
  recipes/python-pypi-mirror/LICENSE
  recipes/python-pypi-mirror/meta.yaml
Labels: Awaiting author contribution, python

#22270 add docparse
  recipes/docparse/meta.yaml
Labels: review-requested, python

#22083 Added recipe for jp-noui (jupyter labextension)
  recipes/jp-noui/meta.yaml
Labels: nodejs, review-requested

#22271 add autoclick
  recipes/autoclick/meta.yaml
Labels: review-requested, python

#22283 Add recipe for vw-executor
  recipes/vw-executor/meta.yaml
Labels: staged-recipes, review-requested

#22288 Add genai recipe
  recipes/genai/meta.yaml
Labels: staged-recipes, review-requested, python

#22284 Add evals, tiktoken
  recipes/evals/meta.yaml
  recipes/tiktoken/meta.yaml
Labels: review-requested, python, rust

#22143 Add jupyterlab_rise
  recipes/jupyterlab_rise/meta.yaml
Labels: review-requested, python

#22073 Adding R package Rvcg
  recipes/r-rvcg/bld.bat
  recipes/r-rvcg/build.sh
  recipes/r-rvcg/meta.yaml
Labels: R, review-requested

#22266 Add Quantiphy
  recipes/quantiphy/LICENSE.txt
  recipes/quantiphy/meta.yaml
Labels: review-requested, python

#22168 Adding qibocal
  recipes/qibocal/meta.yaml
Labels: review-requested, python

#22294 Add python-lsp-ruff 1.2.0
  recipes/python-lsp-ruff/meta.yaml
Labels: staged-recipes, review-requested, python

#22211 Adding caf.space
  recipes/caf.space/meta.yaml
Labels: review-requested, python

#22147 Adding r-rlemon interface to C++ LEMON graph library
  recipes/r-rlemon/LICENSE.txt
  recipes/r-rlemon/bld.bat
  recipes/r-rlemon/build.sh
  recipes/r-rlemon/meta.yaml
Labels: R, review-requested

#22161 add molcomplib
  recipes/molcomplib/LICENSE
  recipes/molcomplib/meta.yaml
Labels: review-requested, python

#21958 adding georouting recipe
  recipes/georouting/meta.yaml
Labels: staged-recipes, review-requested

#22181 Add pygeoops
  recipes/pygeoops/meta.yaml
Labels: review-requested, python

#21868 Adding my command line toolbox - cltoolbox
  recipes/cltoolbox/meta.yaml
Labels: staged-recipes, review-requested

#22092 Add ipyaggrid
  recipes/ipyaggrid/meta.yaml
Labels: review-requested, python

#22166 feat: Add gpkgstatus
  recipes/gpkgstatus/meta.yaml
Labels: staged-recipes, review-requested, python

#22235 Add new_conda_env to conda-forge
  recipes/new_conda_env/meta.yaml
Labels: review-requested, python

#22141 Add ood-metrics recipe
  recipes/ood-metrics/meta.yaml
Labels: review-requested, python

#22183 Add predictr package
  recipes/predictr/meta.yaml
Labels: review-requested, python

#22221 add signalr-client-aio, timple, fastf1
  recipes/fastf1/meta.yaml
  recipes/signalr-client-aio/LICENSE
  recipes/signalr-client-aio/meta.yaml
  recipes/timple/meta.yaml
Labels: review-requested, python

#22191 Add recipe for 'climada'
  recipes/climada/meta.yaml
Labels: review-requested, python

#22185 Add paseos
  recipes/paseos/meta.yaml
Labels: review-requested, python

#22169 Add mplsignal
  recipes/mplsignal/meta.yaml
Labels: review-requested, python

#22201 Adding gridtk package
  recipes/gridtk/meta.yaml
Labels: review-requested, python

#22158 Add ACwater
  recipes/acwater/meta.yaml
Labels: review-requested, python

#22146 Adding xvec
  recipes/xvec/meta.yaml
Labels: review-requested, python

#22305 Add recipe for ast-decompiler
  recipes/ast-decompiler/meta.yaml
Labels: staged-recipes, review-requested

#22148 Add hapiclient recipe
  recipes/hapiclient/meta.yaml
Labels: review-requested, python

#22159 Add base64io
  recipes/base64io/meta.yaml
Labels: review-requested, python

#22157 Added `neptune` package
  recipes/neptune/meta.yaml
Labels: review-requested, python

#22179 Add factor-analyzer package
  recipes/factor-analyzer/meta.yaml
Labels: review-requested, python

#22192 added recipe for ilastik-feature-selection
  recipes/ilastik-feature-selection/meta.yaml
Labels: review-requested, python

#22218 Add lmoments3 recipe
  recipes/lmoments3/meta.yaml
Labels: review-requested, python

#22307 Adding `tensordict` from PyPI
  recipes/tensordict/meta.yaml
Labels: review-requested, python

#22180 Add oasis-deconv
  recipes/oasis-deconv/meta.yaml
Labels: review-requested, python-c

#22225 adding palantir-oauth-client package
  recipes/palantir-oauth-client/meta.yaml
Labels: review-requested, python

#22304 adding gocart
  recipes/gocart/meta.yaml
Labels: review-requested, python

#22113 Add recipe for aws-encryption-sdk
  recipes/aws-encryption-sdk/meta.yaml
Labels: review-requested, python

#22350 add poetry-plugin-tweak-dependencies-version 1.3.0
  recipes/poetry-plugin-tweak-dependencies-version/meta.yaml
Labels: staged-recipes, review-requested, python

#21573 add paraprobe-toolbox
  recipes/paraprobe/LICENSE
  recipes/paraprobe/VORO_LICENSE
  recipes/paraprobe/build.sh
  recipes/paraprobe/conda_build_config.yaml
  recipes/paraprobe/meta.yaml
  recipes/paraprobe/paraprobe.patch
Labels: Awaiting author contribution, staged-recipes

#22364 add py-serializable 0.12.0
  recipes/py-serializable/meta.yaml
Labels: staged-recipes, review-requested, python

#22359 Add recipe for pydantic-core
  recipes/pydantic-core/0001-build-Use-PYTHON-to-determine-the-correct-python-exe.patch
  recipes/pydantic-core/meta.yaml
Labels: staged-recipes, review-requested

#22340 Adding mapwidget package
  recipes/mapwidget/meta.yaml
Labels: review-requested, python

#22352 Added sen2nbar recipe
  recipes/sen2nbar/meta.yaml
Labels: review-requested, python

#22287 Add pavo
  recipes/pavo/meta.yaml
Labels: review-requested, python

#22356 Add recipe for napari-ui-tracer
  recipes/napari-ui-tracer/meta.yaml
  recipes/napari-ui-tracer/yum_requirements.txt
Labels: review-requested, python

#22290 Adding TSDB from PyPI
  recipes/tsdb/meta.yaml
Labels: review-requested, python

#22317 add morphosamplers recipe
  recipes/morphosamplers/meta.yaml
Labels: review-requested, python

#22321 add migen
  recipes/migen/meta.yaml
Labels: review-requested, python

#22339 Adding PyCorruptor from PyPI
  recipes/pycorruptor/meta.yaml
Labels: review-requested, python

#22354 Add enpt_enmapboxapp.
  recipes/enpt_enmapboxapp/meta.yaml
Labels: review-requested, python

#22322 add amaranth / nmigen
  recipes/amaranth/meta.yaml
  recipes/amaranth/patches/0001-fix-extras.patch
Labels: review-requested, python

#22376 Add django sequences recipe
  recipes/django-sequences/meta.yaml
Labels: staged-recipes, review-requested

#18615 Eigency recipe
  recipes/eigency/0001-User-can-use-system-eigen.patch
  recipes/eigency/meta.yaml
Labels: review-requested, python-c

#21891 Add recipe for libgazebo-yarp-plugins package
  recipes/gazebo-yarp-plugins/activate.msh
  recipes/gazebo-yarp-plugins/bld.bat
  recipes/gazebo-yarp-plugins/build.sh
  recipes/gazebo-yarp-plugins/conda_build_config.yaml
  recipes/gazebo-yarp-plugins/deactivate.msh
  recipes/gazebo-yarp-plugins/meta.yaml
  recipes/gazebo-yarp-plugins/yum_requirements.txt
Labels: review-requested, c-cpp

#22029 Add recipe for goss
  recipes/goss/build-cpp.sh
  recipes/goss/build-py.sh
  recipes/goss/meta.yaml
Labels: review-requested, python-c

#22324 add foundry-dev-tools recipe
  recipes/foundry-dev-tools/meta.yaml
Labels: staged-recipes, review-requested

#22371 add ml_dtypes & pyink
  recipes/ml_dtypes/meta.yaml
  recipes/pyink/meta.yaml
Labels: review-requested, python-c

#22378 ENH add mockmpi and parallel_statistics
  newfile.txt
  recipes/mockmpi/meta.yaml
  recipes/parallel_statistics/meta.yaml
Labels: staged-recipes, review-requested

#22027 add libefp
  recipes/libefp/bld.bat
  recipes/libefp/build.sh
  recipes/libefp/meta.yaml
  recipes/libefp/test_pylibefp.py
Labels: Awaiting author contribution, python-c

#22379 ENH add pzflow
  recipes/pzflow/meta.yaml
Labels: staged-recipes, review-requested

#22358 Add do-mpc recipe
  recipes/do-mpc/meta.yaml
Labels: review-requested, python

#22381 Add molfeat
  recipes/molfeat/meta.yaml
Labels: staged-recipes, review-requested

#22380 ENH add lsstdesc-dc2-dm-data
  recipes/ddc2d/meta.yaml
Labels: staged-recipes, review-requested

#22361 Adding gplately and platetectonictools
  recipes/gplately/LICENSE
  recipes/gplately/meta.yaml
  recipes/gplately/yum_requirements.txt
  recipes/platetectonictools/meta.yaml
  recipes/platetectonictools/yum_requirements.txt
Labels: review-requested, python

#22357 add graphormer-pretrained
  recipes/graphormer_pretrained/meta.yaml
Labels: review-requested, python-c

#19324 Adding mmg, iscd tools
  recipes/Advection/bld.bat
  recipes/Advection/build.sh
  recipes/Advection/meta.yaml
  recipes/Commons/bld.bat
  recipes/Commons/build.sh
  recipes/Commons/meta.yaml
  recipes/LinearElasticity/bld.bat
  recipes/LinearElasticity/build.sh
  recipes/LinearElasticity/meta.yaml
  recipes/Mshdist/bld.bat
  recipes/Mshdist/build.sh
  recipes/Mshdist/meta.yaml
  recipes/NavierStokes/bld.bat
  recipes/NavierStokes/build.sh
  recipes/NavierStokes/meta.yaml
  recipes/mmg/bld.bat
  recipes/mmg/build.sh
  recipes/mmg/meta.yaml
Labels: Awaiting author contribution, staged-recipes, c-cpp

#22343 add r-monotone
  recipes/r-monotone/bld.bat
  recipes/r-monotone/build.sh
  recipes/r-monotone/meta.yaml
Labels: R, review-requested

#22289 Adding `PyPOTS` from PyPI
  recipes/pypots/meta.yaml
Labels: review-requested, python

#22347 Adding nectarchain package
  recipes/nectarchain/meta.yaml
Labels: review-requested, python

#20846 Add napari-label-interpolator recipe
  recipes/napari-label-interpolator/meta.yaml
Labels: review-requested

#22394 Add structuretoolkit
  recipes/structuretoolkit/meta.yaml
Labels: staged-recipes, review-requested

#22388 fast-query-parsers 0.3.1
  recipes/fast-query-parsers/0000-no-runtime-maturin.patch
  recipes/fast-query-parsers/bld.bat
  recipes/fast-query-parsers/build.sh
  recipes/fast-query-parsers/meta.yaml
Labels: R, staged-recipes, review-requested, python

#22402 add mdutils
  recipes/mdutils/meta.yaml
Labels: staged-recipes, review-requested

#22400 Added DeFiLlama-Curl recipe
  recipes/defillama-curl/meta.yaml
Labels: staged-recipes, review-requested

#22385 Adding remotior-sensus package
  recipes/remotior-sensus/meta.yaml
Labels: staged-recipes, review-requested, python

#22398 Add recipe for `dcTMD`.
  recipes/dcTMD/meta.yaml
Labels: review-requested, python

#22407 add numpydoc_decorator
  recipes/numpydoc_decorator/meta.yaml
Labels: staged-recipes, review-requested

#22406 Adding sympy_plot_backends
  recipes/sympy_plot_backends/meta.yaml
Labels: review-requested, python

#22411 Add fsl-pipe package
  recipes/fsl-pipe/meta.yaml
Labels: staged-recipes, review-requested

#22412 add: ChessAnalysisPipeline recipe
  recipes/ChessAnalysisPipeline/meta.yaml
Labels: staged-recipes, review-requested

#22377 Initial dadi-cli-feedstock request
  recipes/dadi-cli/meta.yaml
Labels: review-requested, python

#21087 Add docbook-xsl-1.79.2
  recipes/docbook-xsl/bld.bat
  recipes/docbook-xsl/build.sh
  recipes/docbook-xsl/meta.yaml
  recipes/docbook-xsl/post-link.bat
  recipes/docbook-xsl/post-link.sh
  recipes/docbook-xsl/pre-unlink.bat
  recipes/docbook-xsl/pre-unlink.sh
  recipes/docbook-xsl/run_test.bat
  recipes/docbook-xsl/run_test.sh
Labels: Awaiting author contribution, staged-recipes

#22291 Add molmass
  recipes/molmass/meta.yaml
  recipes/molmass/yum_requirements.txt
Labels: review-requested, python

#22387 add r-bde
  recipes/r-bde/bld.bat
  recipes/r-bde/build.sh
  recipes/r-bde/meta.yaml
Labels: R, review-requested

#22424 Add flake8-pyproject
  recipes/flake8-pyproject/meta.yaml
Labels: staged-recipes, review-requested

#22433 add pysipfenn and pysmartdl
  recipes/pysipfenn/meta.yaml
  recipes/pysmartdl/meta.yaml
Labels: staged-recipes, review-requested

#22432 Adding geodatasets
  recipes/geodatasets/meta.yaml
Labels: review-requested, python

#22425 Add aiida-optimize (noarch python)
  recipes/aiida-optimize/install_requires.patch
  recipes/aiida-optimize/meta.yaml
Labels: review-requested, python

#22417 Add pymc-sphinx-theme
  recipes/pymc-sphinx-theme/meta.yaml
Labels: review-requested, python

#21904 Add napari-macrokit recipe
  recipes/napari-macrokit/meta.yaml
  recipes/napari-macrokit/yum_requirements.txt
Labels: staged-recipes, review-requested

#22233 Add napari-meshio recipe
  recipes/napari-meshio/meta.yaml
Labels: staged-recipes, review-requested

#22172 Add napari-wsi recipe
  recipes/napari-wsi/meta.yaml
  recipes/napari-wsi/yum_requirements.txt
Labels: staged-recipes, review-requested

#22173 Add napari-qrcode recipe
  recipes/napari-qrcode/meta.yaml
Labels: staged-recipes, review-requested

#21845 Add napari-solarized recipe
  recipes/napari-solarized/meta.yaml
Labels: staged-recipes, review-requested
