Repository conda-forge/staged-recipes, pull requests merged in 2023-06, with the labels that each got.

#22979 Add insightface
  recipes/insightface/LICENSE
  recipes/insightface/meta.yaml
  recipes/insightface/yum_requirements.txt
Labels: staged-recipes, review-requested

#22990 Add large_image_source_rasterio
  recipes/large_image_source_rasterio/meta.yaml
Labels: staged-recipes, review-requested

#22997 Adding termtosvg
  recipes/termtosvg/meta.yaml
Labels: review-requested, python

#22993 Add `ipyreact`
  recipes/ipyreact/meta.yaml
Labels: review-requested, python

#22988 Add numba-progress
  recipes/numba-progress/meta.yaml
Labels: review-requested, python

#22999 Add Pytest-Excel
  recipes/pytest-excel/meta.yaml
Labels: staged-recipes, review-requested

#23006 Added pyscreenshot as a package
  recipes/pyscreenshot/meta.yaml
Labels: staged-recipes, review-requested

#22955 Adding 'GooseEPM'
  recipes/gooseepm/install.bat
  recipes/gooseepm/install.sh
  recipes/gooseepm/install_python.bat
  recipes/gooseepm/install_python.sh
  recipes/gooseepm/meta.yaml
Labels: review-requested, python-c

#23011 Added flask-minify from pypi
  recipes/Flask-Minify/meta.yaml
Labels: review-requested, python

#23033 add ncvis (renamed ncvis-climate due to conflict in conda-forge)
  recipes/ncvis-climate/build.sh
  recipes/ncvis-climate/meta.yaml
  recipes/ncvis-climate/patches/fix-resources-path.patch
Labels: review-requested, c-cpp

#22493 Add trompeloeil
  recipes/trompeloeil/bld.bat
  recipes/trompeloeil/build.sh
  recipes/trompeloeil/meta.yaml
  recipes/trompeloeil/test/CMakeLists.txt
  recipes/trompeloeil/test/main.cpp
Labels: review-requested, c-cpp

#23050 Add pyobjc-framework-SystemConfiguration
  recipes/pyobjc-framework-SystemConfiguration/meta.yaml
Labels: staged-recipes, review-requested

#23058 Add azure-synapse-nspkg
  recipes/azure-synapse-nspkg/LICENSE.txt
  recipes/azure-synapse-nspkg/meta.yaml
Labels: staged-recipes, review-requested

#23054 Add pyapacheatlas
  recipes/pyapacheatlas/LICENSE
  recipes/pyapacheatlas/meta.yaml
Labels: staged-recipes, review-requested

#23052 Add Interpret-community
  recipes/interpret-community/meta.yaml
Labels: staged-recipes, review-requested

#23042 add lilly-medchem-rules
  recipes/lilly-medchem-rules/bld.bat
  recipes/lilly-medchem-rules/build.sh
  recipes/lilly-medchem-rules/compile.patch
  recipes/lilly-medchem-rules/meta.yaml
Labels: review-requested, c-cpp

#22844 Add go-task
  recipes/go-task/meta.yaml
Labels: staged-recipes, review-requested

#23064 Responsibleai
  recipes/responsibleai/meta.yaml
Labels: staged-recipes, review-requested

#23069 Add raitracker
  recipes/raitracker/meta.yaml
Labels: staged-recipes, review-requested

#23051 Add Pypac Proxy auto-config for Python
  recipes/pypac/meta.yaml
Labels: staged-recipes, review-requested

#23070 Add raimitigations
  recipes/raimitigations/meta.yaml
  recipes/researchpy/meta.yaml
Labels: review-requested, python

#23065 Azure synapse spark
  recipes/azure-synapse-spark/LICENSE
  recipes/azure-synapse-spark/meta.yaml
Labels: staged-recipes, review-requested

#23068 Adding `buildkite-test-collector`
  recipes/buildkite-test-collector/meta.yaml
Labels: review-requested, python

#23076 add ory-client
  recipes/ory-client/meta.yaml
Labels: review-requested, python

#23077 Add pkce
  recipes/pkce/meta.yaml
Labels: review-requested, python

#23049 Add emdfile
  recipes/emdfile/meta.yaml
Labels: staged-recipes, review-requested

#22930 Adding cost733class
  recipes/cost733class/bld.bat
  recipes/cost733class/build.sh
  recipes/cost733class/meta.yaml
  recipes/cost733class/run_test.bat
  recipes/cost733class/run_test.sh
Labels: staged-recipes, review-requested

#23014 Add pymablock
  recipes/pymablock/meta.yaml
Labels: review-requested, python

#22936 Add hydra-submitit-launcher recipe
  recipes/hydra-submitit-launcher/LICENSE
  recipes/hydra-submitit-launcher/meta.yaml
Labels: review-requested, python

#22995 add `xarray-safe-rcm`
  recipes/xarray-safe-rcm/meta.yaml
Labels: review-requested, python

#22749 create a new conda-forge recipe for python library `slcl1butils`
  recipes/slcl1butils/meta.yaml
Labels: review-requested, python

#23093 Add crispy-bootstrap5
  recipes/crispy-bootstrap5/meta.yaml
Labels: staged-recipes, review-requested

#22874 Add hloc and pixsfm
  recipes/hloc/meta.yaml
  recipes/pixsfm/build.sh
  recipes/pixsfm/fix-install-location.patch
  recipes/pixsfm/fix-osx.patch
  recipes/pixsfm/meta.yaml
  recipes/pixsfm/unvendor.patch
Labels: review-requested, python-c

#23101 add pyrootutils
  recipes/pyrootutils/meta.yaml
Labels: staged-recipes, review-requested

#22721 Add ultralytics package
  recipes/ultralytics/meta.yaml
  recipes/ultralytics/yum_requirements.txt
Labels: review-requested, python

#22956 add vale 2.27.0
  recipes/vale/bld.bat
  recipes/vale/build.sh
  recipes/vale/build_win.sh
  recipes/vale/conda_build_config.yaml
  recipes/vale/meta.yaml
Labels: staged-recipes, review-requested, go

#23072 Add valida
  recipes/valida/LICENSE.txt
  recipes/valida/meta.yaml
Labels: review-requested, python

#23109 Add Gita
  recipes/gita/meta.yaml
Labels: staged-recipes, review-requested

#23097 Add pystack recipe
  recipes/pystack/meta.yaml
Labels: review-requested, python-c

#23083 Add cwltest
  recipes/cwltest/meta.yaml
Labels: review-requested, python

#23114 Add pytest-click
  recipes/pytest-click/meta.yaml
Labels: staged-recipes, review-requested

#23108 add pyscal3
  recipes/pyscal3/meta.yaml
Labels: staged-recipes, review-requested

#23107 add pyscal-rdf
  recipes/pyscal-rdf/meta.yaml
Labels: staged-recipes, review-requested

#23119 Add panel-jstree
  recipes/panel-jstree/meta.yaml
Labels: staged-recipes, review-requested

#23146 Add recipe for cargo-patch
  recipes/cargo-patch/build.sh
  recipes/cargo-patch/meta.yaml
Labels: staged-recipes, review-requested

#22900 recipe for xroms
  recipes/xroms/meta.yaml
Labels: review-requested, python

#23005 Add recipe for ANTs
  recipes/ants/bld.bat
  recipes/ants/build.sh
  recipes/ants/meta.yaml
Labels: review-requested, c-cpp

#22845 Add synced_collections
  recipes/synced_collections/meta.yaml
Labels: review-requested, python

#23140 Add guidance
  recipes/guidance/meta.yaml
Labels: review-requested, python

#23150 Add recipe for rlPyCairo
  recipes/rlpycairo/LICENSE.txt
  recipes/rlpycairo/meta.yaml
Labels: review-requested, python

#23113 add recipe for gw_eccentricity
  recipes/gw_eccentricity/meta.yaml
Labels: review-requested, python

#23127 Add encor recipe
  recipes/encor/meta.yaml
Labels: staged-recipes, review-requested

#23154 Add recipe for syntheseus
  recipes/syntheseus/meta.yaml
Labels: review-requested, python

#23159 Add recipe for libpulsar
  recipes/libpulsar/build.sh
  recipes/libpulsar/meta.yaml
Labels: staged-recipes, review-requested

#23153 Add recipe for cppitertools C++ header-only library
  recipes/cppitertools/bld.bat
  recipes/cppitertools/build.sh
  recipes/cppitertools/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#23158 Add Apache Ignite Python Client
  recipes/pyignite/meta.yaml
Labels: staged-recipes, review-requested

#23160 Add appose
  recipes/appose/meta.yaml
Labels: review-requested, python

#23118 recipe for my tidal anaylsis program called tappy
  recipes/tappy/meta.yaml
Labels: review-requested, python

#22659 [new] new recipe for the NCEP interpolation library
  recipes/nceplibs-ip/bld.bat
  recipes/nceplibs-ip/build.sh
  recipes/nceplibs-ip/cross-linux.cmake
  recipes/nceplibs-ip/meta.yaml
Labels: staged-recipes, review-requested

#23163 Add shillelagh
  recipes/shillelagh/meta.yaml
Labels: staged-recipes, review-requested

#23162 Add recipe for pyramid_session_redis
  recipes/pyramid_session_redis/meta.yaml
Labels: review-requested, python

#22814 Add rav1e
  recipes/rav1e/bld.bat
  recipes/rav1e/build.sh
  recipes/rav1e/conda-forge.yml
  recipes/rav1e/meta.yaml
Labels: review-requested, rust

#23165 Add clspv
  recipes/clspv/build.sh
  recipes/clspv/conda_build_config.yaml
  recipes/clspv/meta.yaml
  recipes/clspv/patches/0001-LLVM-16-fixes.patch
  recipes/clspv/patches/0002-Fix-cmake-build.patch
Labels: staged-recipes, review-requested

#23169 adds `r-common`
  recipes/r-common/bld.bat
  recipes/r-common/build.sh
  recipes/r-common/meta.yaml
Labels: R, review-requested

#23174 Add recipe for sphinx-data-viewer
  recipes/sphinx-data-viewer/meta.yaml
Labels: review-requested, python

#23039 Add Optuna-Integration
  recipes/optuna-integration/meta.yaml
Labels: review-requested, python

#23156 Add recipe for aws-request-signer
  recipes/aws-request-signer/meta.yaml
Labels: review-requested, python

#22885 Add package power-grid-model-io
  recipes/power-grid-model-io/meta.yaml
Labels: review-requested, python

#23175 Add r-cuperdec
  recipes/r-cuperdec/bld.bat
  recipes/r-cuperdec/build.sh
  recipes/r-cuperdec/meta.yaml
Labels: R, review-requested

#23180 Add recipe for python-jsonpath
  recipes/python-jsonpath/meta.yaml
Labels: review-requested, python

#23179 Add recipe for sphinxcontrib-plantuml
  recipes/sphinxcontrib-plantuml/meta.yaml
Labels: review-requested, python

#23173 Add recipe for sphinx-needs
  recipes/sphinx-needs/meta.yaml
Labels: review-requested, python

#22904 Add napari-imagej
  recipes/napari-imagej/meta.yaml
Labels: review-requested, python

#23184 add asyncpg-listen 0.0.6
  recipes/asyncpg-listen/meta.yaml
Labels: staged-recipes, review-requested, python

#23181 Add recipe for asyncio-atexit
  recipes/asyncio-atexit/meta.yaml
Labels: review-requested, python

#22838 Add mmsegmentation
  recipes/mmsegmentation/LICENSE
  recipes/mmsegmentation/meta.yaml
  recipes/mmsegmentation/yum_requirements.txt
Labels: review-requested, python

#23141 Add `scVelo` meta.yml
  recipes/scvelo/meta.yaml
Labels: review-requested, python

#23170 Add casa-formats-io to conda-forge
  recipes/casa_formats_io/meta.yaml
Labels: review-requested, python-c

#23166 Add vulkan-tools
  recipes/vulkan-tools/bld.bat
  recipes/vulkan-tools/build.sh
  recipes/vulkan-tools/meta.yaml
Labels: review-requested

#23117 Adding learn-python-test recipe
  recipes/learn-python-ceg-test/meta.yaml
Labels: review-requested, python

#22843 Add databricks-sdk package
  recipes/databricks-sdk/meta.yaml
Labels: review-requested, python

#23195 initial recipe for grib2io-interp
  recipes/grib2io-interp/meta.yaml
Labels: review-requested, python

#23194 Add recipe for pulsar-client
  recipes/pulsar-client/build.sh
  recipes/pulsar-client/meta.yaml
Labels: staged-recipes, review-requested

#23200 Add jupyter-pluto-proxy package
  recipes/jupyter-pluto-proxy/meta.yaml
Labels: review-requested, python

#22793 Add mpi-serial
  recipes/mpi_serial/0001-Rearrange-code-and-other-minor-fixes-needed-for-comp.patch
  recipes/mpi_serial/bld.bat
  recipes/mpi_serial/build.sh
  recipes/mpi_serial/fix-makefile.patch
  recipes/mpi_serial/meta.yaml
Labels: staged-recipes, review-requested

#23183 Add jupyterlab-accessible-themes
  recipes/jupyterlab-accessible-themes/meta.yaml
Labels: staged-recipes, review-requested

#23176 Add recipe for kr8s
  recipes/kr8s/meta.yaml
Labels: review-requested, python

#23199 Add torchlie
  recipes/torchlie/meta.yaml
Labels: review-requested, python

#23204 Add Djlint - Include Dependencies cssbeautifier, html-tag-names, html-void-elements
  recipes/cssbeautifier/LICENSE
  recipes/cssbeautifier/meta.yaml
  recipes/djlint/meta.yaml
  recipes/html-tag-names/meta.yaml
  recipes/html-void-elements/meta.yaml
Labels: staged-recipes, review-requested

#23089 Add allure-python
  recipes/allure-pytest/install.sh
  recipes/allure-pytest/meta.yaml
Labels: review-requested, python

#23206 Add urdf-parser-py and torchkin
  recipes/torchkin/meta.yaml
  recipes/urdf-parser-py/LICENSE
  recipes/urdf-parser-py/meta.yaml
Labels: review-requested, python

#23205 Add google-cloud-scheduler
  recipes/google-cloud-scheduler/meta.yaml
Labels: staged-recipes, review-requested

#23104 Add pyo-oracle v0.0.1
  recipes/pyo-oracle/meta.yaml
Labels: review-requested, python

#23208 Add kedro-vertexai
  recipes/kedro-vertexai/meta.yaml
Labels: staged-recipes, review-requested

#23210 Create conda recipe recipe for the python bindings of the LoadProfile…
  recipes/pyloadprofilegenerator/meta.yaml
Labels: review-requested, python

#23142 Added decimal128 as a package
  recipes/decimal128/meta.yaml
Labels: staged-recipes, review-requested

#23063 Add recipe for bunnet
  recipes/bunnet/meta.yaml
Labels: review-requested, python

#23211 Add fs.googledrivefs
  recipes/fs.googledrivefs/meta.yaml
Labels: staged-recipes, review-requested
