Repository conda-forge/staged-recipes, pull requests merged in 2023-12, with the labels that each got.

#24632 Add unidep: Unified Conda and Pip Dependency Management
  recipes/unidep/meta.yaml
Labels: review-requested, python

#24639 adds `r-wfe`
  recipes/r-wfe/bld.bat
  recipes/r-wfe/build.sh
  recipes/r-wfe/meta.yaml
Labels: R, review-requested

#24418 Add libhidapi
  recipes/libhidapi/bld.bat
  recipes/libhidapi/build.sh
  recipes/libhidapi/conda_build_config.yaml
  recipes/libhidapi/meta.yaml
Labels: review-requested, c-cpp

#24438 Add sinabs-exodus
  recipes/sinabs-exodus/build.sh
  recipes/sinabs-exodus/fix-hardcoded-compiler.patch
  recipes/sinabs-exodus/meta.yaml
Labels: review-requested, python-c

#20243 Add tabulous recipe
  recipes/tabulous/meta.yaml
  recipes/tabulous/yum_requirements.txt
Labels: staged-recipes, review-requested

#24627 Add flake8-no-pep420
  recipes/flake8-no-pep420/meta.yaml
Labels: staged-recipes, review-requested

#24626 Add Flake8-tidy-imports
  recipes/flake8-tidy-imports/meta.yaml
Labels: staged-recipes, review-requested

#24607 Add ollama to conda-forge
  recipes/ollama/meta.yaml
Labels: staged-recipes, review-requested

#24609 Gekko - Machine learning and optimization for dynamic systems
  recipes/gekko/LICENSE
  recipes/gekko/meta.yaml
Labels: staged-recipes, review-requested

#24575 Add domb recipe
  recipes/domb/meta.yaml
Labels: staged-recipes, review-requested

#24404 Add napari-convpaint recipe
  recipes/napari-convpaint/meta.yaml
  recipes/napari-convpaint/yum_requirements.txt
Labels: staged-recipes, review-requested

#24360 Add pygeodesic recipe
  recipes/pygeodesic/flat_triangular_mesh.txt
  recipes/pygeodesic/meta.yaml
  recipes/pygeodesic/ptr.patch
  recipes/pygeodesic/run_test.py
Labels: staged-recipes, review-requested

#22963 Add napari-indices recipe
  recipes/napari-indices/meta.yaml
  recipes/napari-indices/qtpy.patch
  recipes/napari-indices/yum_requirements.txt
Labels: Awaiting author contribution, staged-recipes, review-requested

#22968 Add tiledb-bioimg recipe
  recipes/tiledb-bioimg/meta.yaml
  recipes/tiledb-bioimg/setup.patch
Labels: Awaiting author contribution, staged-recipes, review-requested

#24372 Add darth-d recipe
  recipes/darth-d/meta.yaml
  recipes/darth-d/yum_requirements.txt
Labels: staged-recipes, review-requested

#19900 Add napari-serialcellpose recipe
  recipes/napari-serialcellpose/meta.yaml
  recipes/napari-serialcellpose/yum_requirements.txt
Labels: staged-recipes, review-requested

#22970 Add gemspa-spt recipe
  recipes/gemspa-spt/meta.yaml
Labels: Awaiting author contribution, staged-recipes, review-requested

#23848 Add spots-in-yeasts recipe
  recipes/spots-in-yeasts/meta.yaml
  recipes/spots-in-yeasts/yum_requirements.txt
Labels: staged-recipes, review-requested

#20284 Add napari-merge-stardist-masks recipe
  recipes/napari-merge-stardist-masks/meta.yaml
  recipes/napari-merge-stardist-masks/yum_requirements.txt
Labels: staged-recipes, review-requested

#24641 Added fastui as a package
  recipes/fastui/meta.yaml
Labels: staged-recipes, review-requested

#24617 [ready] Add recipe for mim-solvers package
  recipes/mim-solvers/build.sh
  recipes/mim-solvers/meta.yaml
Labels: review-requested, c-cpp

#24586 add recipe for nbwipers
  recipes/nbwipers/bld.bat
  recipes/nbwipers/build.sh
  recipes/nbwipers/meta.yaml
Labels: staged-recipes, review-requested

#24621 add pyspartn recipe
  recipes/pyspartn/meta.yaml
Labels: review-requested, python

#24662 Add recipe for libml_dtypes-headers
  recipes/libml_dtypes-headers/bld.bat
  recipes/libml_dtypes-headers/build.sh
  recipes/libml_dtypes-headers/conda-forge.yml
  recipes/libml_dtypes-headers/meta.yaml
Labels: staged-recipes, review-requested

#24622 Add `litecli`
  recipes/litecli/meta.yaml
Labels: review-requested, python

#24564 Adding openseries
  recipes/openseries/meta.yaml
Labels: review-requested, python

#24658 add chgnet
  recipes/chgnet/meta.yaml
Labels: staged-recipes, review-requested, python, python-c

#24638 adds PyPI package `cloupy`
  recipes/cloupy/meta.yaml
Labels: review-requested, python

#23987 Add `tsml-eval` as a package
  recipes/tsml-eval/meta.yaml
Labels: review-requested, python

#24636 Add recipe for `spams-cython`
  recipes/spams-cython/meta.yaml
Labels: review-requested, python

#24625 Add invert4geom
  recipes/invert4geom/LICENSE
  recipes/invert4geom/meta.yaml
Labels: review-requested, python

#24565 Add xesn python package
  recipes/xesn/meta.yaml
Labels: review-requested, python

#24670 Fix failure in `create_feedstocks` [skip lint]
  .github/workflows/scripts/create_feedstocks
Labels: maintenance

#24600 Adding package OpenRAFT to conda-forge
  recipes/openraft/meta.yaml
Labels: review-requested, python

#24611 feat: :sparkles: Add meilisearch-python-async to conda-forge
  recipes/camel-converter/meta.yaml
  recipes/meilisearch-python-async/meta.yaml
Labels: review-requested, python

#24614 feat: :sparkles: Add socksio
  recipes/socksio/meta.yaml
Labels: review-requested, python

#24613 feat: :sparkles: Add Replicate client
  recipes/replicate/meta.yaml
Labels: review-requested, python

#22872 add recipe for pyx
  recipes/pyx/LICENSE
  recipes/pyx/meta.yaml
Labels: review-requested, python

#24616 Add plotmol
  recipes/plotmol/meta.yaml
Labels: review-requested, python

#24596 Added recipes for smqtk's dataprovider, image-io, descriptors, classifier and detection
  recipes/smqtk-classifier/meta.yaml
  recipes/smqtk-dataprovider/meta.yaml
  recipes/smqtk-descriptors/meta.yaml
  recipes/smqtk-detection/meta.yaml
  recipes/smqtk-image-io/meta.yaml
Labels: review-requested, python

#24618 Adds python-ipware
  recipes/python-ipware/meta.yaml
Labels: review-requested, python

#24602 Adding delft_fiat
  recipes/delft_fiat/conda_build_config.yaml
  recipes/delft_fiat/meta.yaml
Labels: review-requested, python

#24674 add: libdicom
  recipes/libdicom/build.sh
  recipes/libdicom/meta.yaml
Labels: review-requested, c-cpp

#24676 Add recipe for azure-mgmt-cosmosdb
  recipes/azure-mgmt-cosmosdb/meta.yaml
Labels: review-requested, python

#24644 Add recipe for program Genesis 4
  recipes/genesis4/build.sh
  recipes/genesis4/conda_build_config.yaml
  recipes/genesis4/meta.yaml
Labels: review-requested, c-cpp

#24610 Add hostess to conda-forge
  recipes/hostess/meta.yaml
Labels: staged-recipes, review-requested

#24407 create recipe for mlsauce
  recipes/mlsauce/conda-forge-.yml
  recipes/mlsauce/meta.yaml
Labels: staged-recipes, review-requested

#24666 Add gnuradio-funcube
  recipes/gnuradio-funcube/bld.bat
  recipes/gnuradio-funcube/build.sh
  recipes/gnuradio-funcube/meta.yaml
Labels: review-requested, c-cpp

#24531 Add cherab-inversion recipe
  recipes/cherab-inversion/bld.bat
  recipes/cherab-inversion/build.sh
  recipes/cherab-inversion/meta.yaml
Labels: review-requested, python-c

#24637 Add libcramjam
  recipes/libcramjam/LICENSE
  recipes/libcramjam/bld.bat
  recipes/libcramjam/build.sh
  recipes/libcramjam/meta.yaml
Labels: staged-recipes, review-requested, rust

#24509 add vnu-validator 23.4.11
  recipes/vnu-validator/bld.bat
  recipes/vnu-validator/build.sh
  recipes/vnu-validator/conda-forge.yml
  recipes/vnu-validator/meta.yaml
  recipes/vnu-validator/run_test.py
Labels: staged-recipes, review-requested, java

#24688 Add Django-CMS
  recipes/django-classy-tags/meta.yaml
  recipes/django-cms/meta.yaml
  recipes/django-formtools/meta.yaml
  recipes/django-sekizai/meta.yaml
Labels: staged-recipes, review-requested

#24684 add pycnite
  recipes/pycnite/meta.yaml
Labels: review-requested, python

#24673 Adding `PanoplyJ`
  recipes/panoply/bld.bat
  recipes/panoply/build.sh
  recipes/panoply/meta.yaml
Labels: staged-recipes, review-requested, java

#24678 Add winfiletime
  recipes/winfiletime/0001-utc.patch
  recipes/winfiletime/meta.yaml
Labels: review-requested, python

#24681 feat: :sparkles: Add ripgrepy to conda-forge
  recipes/ripgrepy/LICENSE
  recipes/ripgrepy/meta.yaml
Labels: review-requested, python

#24680 Added recipe for pybsm
  recipes/pybsm/meta.yaml
  recipes/pybsm/yum_requirements.txt
Labels: review-requested, python

#24679 Added recipe for xaitk-saliency
  recipes/xaitk-saliency/meta.yaml
Labels: review-requested, python

#24505 Add eip712
  recipes/eip712/meta.yaml
Labels: review-requested, python

#24504 Add qsimcirq recipe
  recipes/qsimcirq/meta.yaml
Labels: review-requested, c-cpp, python

#24709 Add recipe for vl-convert
  recipes/vl-convert/build.sh
  recipes/vl-convert/conda_build_config.yaml
  recipes/vl-convert/meta.yaml
Labels: staged-recipes, review-requested

#24701 Adding pytest-golden
  recipes/pytest-golden/meta.yaml
Labels: review-requested, python

#24703 Add `directory-tree` to conda-forge
  recipes/directory-tree/LICENSE
  recipes/directory-tree/meta.yaml
Labels: review-requested, python

#24725 feat: Add Terraform Opensearch Provider
  recipes/terraform-provider-opensearch/conda_build_config.yaml
  recipes/terraform-provider-opensearch/meta.yaml
Labels: staged-recipes, review-requested

#24727 Package pycrdt-websocket
  recipes/pycrdt-websocket/meta.yaml
Labels: review-requested, python

#24705 Add parallel-numpy-rng
  recipes/parallel-numpy-rng/meta.yaml
Labels: staged-recipes, review-requested

#19259 Add napari-stress recipe
  recipes/napari-stress/meta.yaml
  recipes/napari-stress/yum_requirements.txt
Labels: staged-recipes, review-requested

#24651 Add logutils recipe
  recipes/logutils/meta.yaml
Labels: staged-recipes, review-requested

#24728 feat: Add Terraform RestAPI Provider
  recipes/terraform-provider-restapi/conda_build_config.yaml
  recipes/terraform-provider-restapi/meta.yaml
Labels: staged-recipes, review-requested

#22597 Add steinbock recipe
  recipes/steinbock/meta.yaml
Labels: Awaiting author contribution, staged-recipes, review-requested

#24561 Add morphodynamics recipe
  recipes/morphodynamics/meta.yaml
Labels: staged-recipes, review-requested

#23774 Add commlib-py
  recipes/commlib-py/meta.yaml
Labels: review-requested, python

#24457 Added NumCpp
  recipes/numcpp/build.sh
  recipes/numcpp/meta.yaml
Labels: review-requested, c-cpp

#24420 Add kernel-tuner and python-constraint2
  recipes/kernel-tuner/meta.yaml
  recipes/python-constraint2/meta.yaml
Labels: review-requested, python-c

#24553 add recipe for compas_libigl
  recipes/compas_libigl/meta.yaml
Labels: staged-recipes, review-requested

#24649 Add hexdump recipe
  recipes/hexdump/LICENSE.txt
  recipes/hexdump/meta.yaml
Labels: staged-recipes, review-requested

#24712 adding opendatasets
  recipes/opendatasets/LICENSE.txt
  recipes/opendatasets/meta.yaml
Labels: review-requested, python

#24699 contribute causal-learn
  recipes/causal-learn/LICENSE
  recipes/causal-learn/meta.yaml
Labels: staged-recipes, review-requested

#24691 Add djangocms-text-ckeditor
  recipes/djangocms-text-ckeditor/meta.yaml
Labels: staged-recipes, review-requested

#24734 Add Jinja2-simple-tags
  recipes/jinja2-simple-tags/meta.yaml
Labels: staged-recipes, review-requested

#24345 Add rocket-fft recipe
  recipes/rocket-fft/meta.yaml
Labels: staged-recipes, review-requested

#24736 Add mat4py recipe
  recipes/mat4py/meta.yaml
Labels: staged-recipes, review-requested

#23324 Add napari-superres recipe
  recipes/napari-superres/meta.yaml
  recipes/napari-superres/yum_requirements.txt
Labels: staged-recipes, review-requested

#24648 Add umetrix recipe
  recipes/umetrix/meta.yaml
Labels: staged-recipes, review-requested

#21276 Add napari-steinpose recipe
  recipes/napari-steinpose/meta.yaml
  recipes/napari-steinpose/yum_requirements.txt
Labels: staged-recipes, review-requested

#24543 Add napari-morphodynamics recipe
  recipes/napari-morphodynamics/meta.yaml
  recipes/napari-morphodynamics/yum_requirements.txt
Labels: staged-recipes, review-requested

#24650 Add rainbow-logging-handler recipe
  recipes/rainbow-logging-handler/meta.yaml
Labels: staged-recipes, review-requested

#24729 Add continuedev to conda-forge
  recipes/continuedev/LICENSE
  recipes/continuedev/dependencies.patch
  recipes/continuedev/meta.yaml
Labels: review-requested, python

#23790 Add hdwallets
  recipes/hdwallets/fix_mpz_utils.py.patch
  recipes/hdwallets/fix_undefined_pubkey_bip32.py.patch
  recipes/hdwallets/meta.yaml
Labels: review-requested, python

#23789 Add safe-pysha3
  recipes/safe-pysha3/meta.yaml
Labels: review-requested, python-c

#24740 Add loki-logger-handler
  recipes/loki-logger-handler/meta.yaml
Labels: staged-recipes, review-requested

#24739 Data wizard
  recipes/data-wizard/meta.yaml
  recipes/html-json-forms/meta.yaml
  recipes/itertable/meta.yaml
  recipes/natural-keys/meta.yaml
Labels: staged-recipes, review-requested

#24738 Add rest-pandas
  recipes/rest-pandas/meta.yaml
Labels: staged-recipes, review-requested

#24697 Add pytorch-3dunet
  recipes/pytorch-3dunet/meta.yaml
Labels: review-requested, python

#24732 Add gguf to conda-forge
  recipes/gguf/meta.yaml
Labels: review-requested, python

#24512 Add MetGem
  recipes/metgem/meta.yaml
  recipes/metgem/yum_requirements.txt
Labels: review-requested, python

#24193 Adding sardana-alba plugins
  recipes/sardana-alba/meta.yaml
Labels: review-requested, python

#24201 Adding sardana-adlink
  recipes/sardana-adlink/meta.yaml
Labels: review-requested, python

#24733 Add plateletanalysis recipe
  recipes/plateletanalysis/meta.yaml
  recipes/plateletanalysis/yum_requirements.txt
Labels: staged-recipes, review-requested

#24743 Add ndsplines
  recipes/ndsplines/meta.yaml
Labels: review-requested, python

#24747 Add actions-toolkit
  recipes/actions-toolkit/meta.yaml
Labels: staged-recipes, review-requested

#24748 add pycocoevalcap
  recipes/pycocoevalcap/LICENSE
  recipes/pycocoevalcap/license.txt
  recipes/pycocoevalcap/meta.yaml
Labels: review-requested, python

#24698 Add acgc recipe
  recipes/acgc/meta.yaml
Labels: review-requested, python

#24606 add kerrgeopy
  recipes/kerrgeopy/meta.yaml
Labels: review-requested, python

#24754 added spheroidal
  recipes/spheroidal/meta.yaml
Labels: review-requested, python

#22875 Adds pyCycle
  recipes/pycycle/LICENSE.txt
  recipes/pycycle/meta.yaml
  recipes/pycycle/run_test.py
  recipes/pycycle/yum_requirements.txt
Labels: review-requested, python

#24755 recipe for "deco", "mesa-viz-tornado"
  recipes/deco/LICENSE
  recipes/deco/meta.yaml
  recipes/mesa-viz-tornado/LICENSE
  recipes/mesa-viz-tornado/meta.yaml
Labels: review-requested, python

#24767 Add full-fred
  recipes/full-fred/meta.yaml
Labels: staged-recipes, review-requested

#24759 Add Optimas
  recipes/optimas/meta.yaml
Labels: review-requested, python

#24758 Add FBPIC
  recipes/fbpic/meta.yaml
Labels: review-requested, python

#24752 Add axiprop
  recipes/axiprop/meta.yaml
Labels: review-requested, python

#24773 add kanaries-track recipe
  recipes/kanaries-track/meta.yaml
Labels: review-requested, python

#24715 first version of conda forge recipe for `cdsodatacli` python lib
  recipes/cdsodatacli/meta.yaml
Labels: staged-recipes, review-requested

#24775 Add wannier90io
  recipes/wannier90io/meta.yaml
Labels: staged-recipes, review-requested

#24768 Add langchain-core recipe
  recipes/langchain-core/LICENSE
  recipes/langchain-core/meta.yaml
Labels: review-requested, python

#24781 Add r-baseset recipe
  recipes/r-baseset/bld.bat
  recipes/r-baseset/build.sh
  recipes/r-baseset/meta.yaml
Labels: R, review-requested

#24656 Adding jupysql-plugin
  recipes/jupysql-plugin/conda-forge.yml
  recipes/jupysql-plugin/meta.yaml
Labels: staged-recipes, review-requested

#24786 Add recipe for dep-logic
  recipes/dep-logic/meta.yaml
Labels: staged-recipes, review-requested

#24783 Add LASY
  recipes/lasy/meta.yaml
Labels: review-requested, python

#24793 add yaqd-ni
  recipes/yaqd-ni/meta.yaml
Labels: staged-recipes, review-requested

#24716 recipe for lm_eval
  recipes/lm_eval/meta.yaml
Labels: review-requested, python

#24769 Add langchain-community package
  recipes/langchain-community/LICENSE
  recipes/langchain-community/meta.yaml
Labels: review-requested, python

#24766 add recipe for skrub
  recipes/skrub/meta.yaml
Labels: review-requested, python

#19348 added colour-demosaicing to the conda-forge
  recipes/colour-demosaicing/meta.yaml
Labels: Awaiting author contribution, staged-recipes

#24791 add pemja recipe
  recipes/pemja/meta.yaml
Labels: review-requested, python

#24582 Add `citric` PyPI package
  recipes/citric/meta.yaml
Labels: review-requested, python

#24797 Add recipe for libduckdb and duckdb-cli
  recipes/duckdb-split/0001-Dynamically-link-the-cli.patch
  recipes/duckdb-split/build.sh
  recipes/duckdb-split/conda_build_config.yaml
  recipes/duckdb-split/install-cli.sh
  recipes/duckdb-split/install-headers.sh
  recipes/duckdb-split/install-lib.sh
  recipes/duckdb-split/meta.yaml
Labels: staged-recipes, review-requested

#24799 Adding package cocopye
  recipes/cocopye/meta.yaml
Labels: review-requested, python

#24792 add runstats recipe
  recipes/runstats/meta.yaml
Labels: review-requested, python-c

#24802 Add recipe for demumble
  recipes/demumble/bld.bat
  recipes/demumble/build.sh
  recipes/demumble/meta.yaml
Labels: staged-recipes, review-requested

#24805 Add Django-Codemirror6
  recipes/django-codemirror6/meta.yaml
Labels: staged-recipes, review-requested

#24804 Add django-sesame
  recipes/django-sesame/meta.yaml
Labels: staged-recipes, review-requested

#22755 Add gds-dmt and gds-monitor-apps
  recipes/gds-dmt/COPYING
  recipes/gds-dmt/build.sh
  recipes/gds-dmt/meta.yaml
  recipes/gds-monitor-apps/COPYING
  recipes/gds-monitor-apps/build.sh
  recipes/gds-monitor-apps/meta.yaml
Labels: staged-recipes, review-requested

#24750 OpenVINO tokenizers
  recipes/openvino-tokenizers/conda_build_config.yaml
  recipes/openvino-tokenizers/meta.yaml
  recipes/openvino-tokenizers/samples/CMakeLists.txt
  recipes/openvino-tokenizers/samples/main.cpp
Labels: review-requested, c-cpp

#24761 Add APtools
  recipes/aptools/meta.yaml
Labels: review-requested, python

#24458 Add Python package veerer
  recipes/veerer/meta.yaml
Labels: review-requested, python-c

#24772 Add neuromorphic-drivers
  recipes/neuromorphic-drivers/conda_build_config.yaml
  recipes/neuromorphic-drivers/meta.yaml
Labels: review-requested, c-cpp

#24167 Add recipe for cpprate
  recipes/cpprate/LICENSE_bxzstr
  recipes/cpprate/LICENSE_cxxargs
  recipes/cpprate/build.sh
  recipes/cpprate/meta.yaml
Labels: review-requested, c-cpp

#21662 Adding openmm-nonbonded-slicing
  recipes/openmm-nonbonded-slicing/build.sh
  recipes/openmm-nonbonded-slicing/cmakelists.patch
  recipes/openmm-nonbonded-slicing/meta.yaml
  recipes/openmm-nonbonded-slicing/patch_osx_tests.py
Labels: staged-recipes, review-requested

#24107 Adding jimtcl
  recipes/jimtcl/bld.bat
  recipes/jimtcl/build.sh
  recipes/jimtcl/meta.yaml
Labels: review-requested, c-cpp

#24765 Adding haystack_bm25
  recipes/haystack_bm25/meta.yaml
Labels: staged-recipes, review-requested

#24778 Add symbolite recipe
  recipes/symbolite/meta.yaml
Labels: review-requested, python

#24809 Add h2o-wave
  recipes/h2o-wave/meta.yaml
Labels: staged-recipes, review-requested

#24807 Add matgl
  recipes/matgl/meta.yaml
Labels: staged-recipes, review-requested

#24687 Add recipe for mlx
  recipes/mlx/build.sh
  recipes/mlx/conda_build_config.yaml
  recipes/mlx/meta.yaml
Labels: staged-recipes, review-requested

#24794 add-r-bvar
  recipes/r-bvar/bld.bat
  recipes/r-bvar/build.sh
  recipes/r-bvar/meta.yaml
Labels: R

#23732 add espsim and resp
  recipes/espsim/meta.yaml
  recipes/espsim/setup-py.patch
  recipes/resp/meta.yaml
  recipes/resp/versions.patch
Labels: review-requested, python

#24784 add-r-tsdyn
  recipes/r-tsdyn/bld.bat
  recipes/r-tsdyn/build.sh
  recipes/r-tsdyn/meta.yaml
Labels: R

#24806 Add recipe for ecoinvent_interface
  recipes/ecoinvent_interface/meta.yaml
Labels: review-requested, python

#24817 Add cyclopts as a package
  recipes/cyclopts/meta.yaml
Labels: staged-recipes, review-requested
