Repository conda-forge/staged-recipes, pull requests merged in 2023-05, with the labels that each got.

#22718 Adds `r-emoa`
  recipes/r-emoa/bld.bat
  recipes/r-emoa/build.sh
  recipes/r-emoa/meta.yaml
Labels: R, review-requested

#22714 Adds `r-plottools`
  recipes/r-plottools/bld.bat
  recipes/r-plottools/build.sh
  recipes/r-plottools/meta.yaml
Labels: R, review-requested

#22717 Adds `r-rgenoud`
  recipes/r-rgenoud/bld.bat
  recipes/r-rgenoud/build.sh
  recipes/r-rgenoud/meta.yaml
Labels: R, review-requested

#22710 Add `emojis` package
  recipes/emojis/meta.yaml
Labels: staged-recipes, review-requested

#22639 fmjpeg2koj recipe
  recipes/fmjpeg2koj/bld.bat
  recipes/fmjpeg2koj/build.sh
  recipes/fmjpeg2koj/meta.yaml
Labels: review-requested, c-cpp

#22360 Add pennylane-lightning-kokkos recipe.
  recipes/pennylane-lightning-kokkos/0001-setup.patch
  recipes/pennylane-lightning-kokkos/0002-setup.patch
  recipes/pennylane-lightning-kokkos/meta.yaml
Labels: review-requested, c-cpp

#22445 Add libmetgem
  recipes/libmetgem/meta.yaml
Labels: review-requested, python-c

#22483 Add ms-gsl
  recipes/ms-gsl/bld.bat
  recipes/ms-gsl/build.sh
  recipes/ms-gsl/meta.yaml
  recipes/ms-gsl/test/CMakeLists.txt
  recipes/ms-gsl/test/main.cpp
Labels: review-requested, c-cpp

#22490 Add fast_float
  recipes/fast_float/bld.bat
  recipes/fast_float/build.sh
  recipes/fast_float/meta.yaml
  recipes/fast_float/test/CMakeLists.txt
  recipes/fast_float/test/main.cpp
Labels: review-requested, c-cpp

#22719 add cmap package
  recipes/cmap/meta.yaml
Labels: review-requested, python

#22731 Add zulip recipe
  recipes/zulip/meta.yaml
Labels: staged-recipes, review-requested

#22712 add perspective-parquet
  recipes/perspective-parquet/meta.yaml
Labels: review-requested, python

#22737 Add `kkcalc` package
  recipes/kkcalc/meta.yaml
Labels: staged-recipes, review-requested

#22736 add doitoml 0.1.1
  recipes/doitoml/meta.yaml
Labels: staged-recipes, review-requested, python

#22520 Add mold
  recipes/mold/build.sh
  recipes/mold/conda_build_config.yaml
  recipes/mold/meta.yaml
Labels: review-requested, c-cpp

#22739 Add gpcam, fvgp and hgdl
  recipes/fvgp/dep.patch
  recipes/fvgp/meta.yaml
  recipes/gpcam/dep.patch
  recipes/gpcam/meta.yaml
  recipes/gpcam/zmq.patch
  recipes/hgdl/dep.patch
  recipes/hgdl/meta.yaml
Labels: staged-recipes, review-requested

#22738 added cnmfsns package
  recipes/cnmfsns/meta.yaml
Labels: staged-recipes, review-requested

#22453 Add mne-gui-addons
  recipes/mne-gui-addons/meta.yaml
  recipes/mne-gui-addons/yum_requirements.txt
Labels: review-requested, python

#21336 add proxy.py 2.4.3
  recipes/proxy-py/meta.yaml
Labels: staged-recipes, review-requested, python

#22569 Adding junifer
  recipes/junifer/meta.yaml
Labels: review-requested, python

#22707 Add jupyterlab-daw
  recipes/jupyterlab-daw/meta.yaml
Labels: review-requested, python

#22743 Add tl2cgen feedstock
  recipes/tl2cgen/bld.bat
  recipes/tl2cgen/build.sh
  recipes/tl2cgen/meta.yaml
Labels: staged-recipes, review-requested

#22723 Add django-oauth-toolkit package
  recipes/django-oauth-toolkit/meta.yaml
Labels: review-requested, python

#22727 Add napari-zulip recipe
  recipes/napari-zulip/meta.yaml
Labels: staged-recipes, review-requested

#22726 Add napari-sam4is recipe
  recipes/napari-sam4is/meta.yaml
  recipes/napari-sam4is/yum_requirements.txt
Labels: staged-recipes, review-requested

#21831 Add oneat recipe
  recipes/oneat/meta.yaml
  recipes/oneat/yum_requirements.txt
Labels: staged-recipes, review-requested

#22754 Adding Python package "crepes"
  recipes/crepes/meta.yaml
Labels: review-requested, python

#22485 Add napari-segment-anything recipe
  recipes/napari-segment-anything/meta.yaml
  recipes/napari-segment-anything/yum_requirements.txt
Labels: staged-recipes, review-requested

#22742 Add local-migrator feedstock
  recipes/local-migrator/meta.yaml
Labels: review-requested, python

#22621 Add napari-sam recipe
  recipes/napari-sam/meta.yaml
  recipes/napari-sam/yum_requirements.txt
Labels: staged-recipes, review-requested

#22767 Fix comment about line number for URL in example/meta.yml
  recipes/example/meta.yaml
Labels: staged-recipes, review-requested

#22763 add pyduktape2 0.4.3
  recipes/pyduktape2/000-no-cython-runtime.patch
  recipes/pyduktape2/001-no-import-tests.patch
  recipes/pyduktape2/meta.yaml
Labels: review-requested, c-cpp, python-c

#22768 Add data-morph-ai recipe (Python).
  recipes/data-morph-ai/meta.yaml
Labels: review-requested, python

#22769 Add python markdownify recipe.
  recipes/markdownify/meta.yaml
Labels: review-requested, python

#22751 Adding xarray-safe-s1
  recipes/xarray-safe-s1/meta.yaml
Labels: staged-recipes, review-requested, python

#22776 Add trends_earth_algorithms recipe
  recipes/trends_earth_algorithms/meta.yaml
Labels: staged-recipes, review-requested, python

#22786 add robotframework-dependencylibrary 4.0.1
  recipes/robotframework-dependencylibrary/meta.yaml
Labels: staged-recipes, review-requested, python

#22757 Adding multiple python packages (module-utilities, analphipy, cmomy, tmmc-lnpy, thermoextrap)
  recipes/analphipy/meta.yaml
  recipes/cmomy/meta.yaml
  recipes/module-utilities/meta.yaml
  recipes/thermoextrap/meta.yaml
  recipes/tmmc-lnpy/meta.yaml
Labels: review-requested, python

#22568 Add xcb-util-cursor
  recipes/xcb-util-cursor/build.sh
  recipes/xcb-util-cursor/meta.yaml
Labels: review-requested, c-cpp

#22578 adding `libevalhyd` `evalhyd-python` `evalhyd-cli` `r-evalhyd`
  recipes/evalhyd-cli/bld.bat
  recipes/evalhyd-cli/build.sh
  recipes/evalhyd-cli/meta.yaml
  recipes/evalhyd-python/meta.yaml
  recipes/libevalhyd/bld.bat
  recipes/libevalhyd/build.sh
  recipes/libevalhyd/meta.yaml
  recipes/r-evalhyd/bld.bat
  recipes/r-evalhyd/build.sh
  recipes/r-evalhyd/build_win.sh
  recipes/r-evalhyd/meta.yaml
Labels: review-requested, python-c

#22336 initial commit of my tsgettoolbox package to download time-series
  recipes/tsgettoolbox/meta.yaml
Labels: staged-recipes, review-requested

#22688 Add pCrunch to conda-forge
  recipes/pcrunch/meta.yaml
Labels: Awaiting author contribution, review-requested, python

#22212 Add demcmc recipe
  recipes/demcmc/meta.yaml
Labels: review-requested, python

#22760 Adding zcollection
  recipes/zcollection/meta.yaml
Labels: review-requested, python

#22764 add scylla-driver
  recipes/scylla-driver/meta.yaml
Labels: review-requested, python

#22796 Adding asimov-gwdata
  recipes/asimov-gwdata/meta.yaml
Labels: review-requested, python

#22775 Add package lpython_emulation
  recipes/lpython_emulation/meta.yaml
Labels: review-requested, python

#22759 Adding `doped`
  recipes/doped/meta.yaml
Labels: review-requested, python

#22798 Add `dkist` package
  recipes/dkist/meta.yaml
Labels: review-requested, python

#22810 Adding `rouge-score` from PyPI
  recipes/rouge-score/LICENSE
  recipes/rouge-score/meta.yaml
Labels: review-requested, python

#22745 Add r-mirtcat recipe
  recipes/r-mirtcat/bld.bat
  recipes/r-mirtcat/build.sh
  recipes/r-mirtcat/meta.yaml
Labels: R, review-requested

#22811 Add sphinxext-altair
  recipes/sphinxext-altair/meta.yaml
Labels: review-requested, python

#22794 Add wayland-protocols
  recipes/wayland-protocols/build.sh
  recipes/wayland-protocols/meta.yaml
Labels: staged-recipes, review-requested

#21541 Add nomad
  recipes/nomad/build.sh
  recipes/nomad/conda-forge.yml
  recipes/nomad/conda_build_config.yaml
  recipes/nomad/meta.yaml
Labels: Awaiting author contribution, review-requested

#22822 Add pycrystal
  recipes/pycrystal/LICENSE
  recipes/pycrystal/bs4.patch
  recipes/pycrystal/meta.yaml
Labels: staged-recipes, review-requested

#22431 Add rsirius client to conda-forge
  recipes/r-sirius-ms/Kaempferol.ms
  recipes/r-sirius-ms/bld.bat
  recipes/r-sirius-ms/build.sh
  recipes/r-sirius-ms/meta.yaml
  recipes/r-sirius-ms/run_test.bat
  recipes/r-sirius-ms/run_test.sh
  recipes/r-sirius-ms/test_script.R
Labels: staged-recipes, review-requested

#22824 Add pyxtal
  recipes/pyxtal/meta.yaml
Labels: staged-recipes, review-requested

#22711 ENH add batoid
  recipes/batoid/meta.yaml
Labels: staged-recipes, review-requested

#22615 Adding libleidenalg
  recipes/libleidenalg/001-cmake-fix-link-libraries.patch
  recipes/libleidenalg/bld.bat
  recipes/libleidenalg/build.sh
  recipes/libleidenalg/meta.yaml
  recipes/libleidenalg/run_test.sh
  recipes/libleidenalg/test.cpp
Labels: review-requested, c-cpp

#22805 Adding recipe for O365
  recipes/o365/meta.yaml
Labels: review-requested, python

#22795 tpot2 from Moorelab initial upload
  recipes/tpot2/meta.yaml
Labels: review-requested, python

#22833 ENH add danish
  recipes/danish/meta.yaml
Labels: staged-recipes, review-requested

#22782 Adding LPython
  recipes/lpython/bld.bat
  recipes/lpython/build.sh
  recipes/lpython/macos_clock.patch
  recipes/lpython/meta.yaml
  recipes/lpython/msvc_static.patch
  recipes/lpython/version.patch
  recipes/lpython/win_tests.patch
Labels: review-requested, c-cpp

#22818 Add package power-grid-model
  recipes/power-grid-model/conda_build_config.yaml
  recipes/power-grid-model/meta.yaml
Labels: review-requested, python-c

#22819 Adding macha
  recipes/macha/meta.yaml
Labels: review-requested, python

#22821 Add package for Thalassa
  recipes/thalassa/meta.yaml
Labels: review-requested, python

#22778 Adding DSSAT R package as r-dssat
  recipes/r-dssat/bld.bat
  recipes/r-dssat/build.sh
  recipes/r-dssat/meta.yaml
Labels: Awaiting author contribution

#22847 Adds `r-smdocker`
  recipes/r-smdocker/bld.bat
  recipes/r-smdocker/build.sh
  recipes/r-smdocker/meta.yaml
Labels: R, review-requested

#22848 Adds `r-clustmixtype`
  recipes/r-clustmixtype/bld.bat
  recipes/r-clustmixtype/build.sh
  recipes/r-clustmixtype/meta.yaml
Labels: R, review-requested

#22850 add traefik 2.10.1
  recipes/traefik/build.sh
  recipes/traefik/meta.yaml
Labels: staged-recipes, review-requested, go

#22830 Dymoval: first attempt ever in making a conda-forge package
  recipes/dymoval/meta.yaml
Labels: staged-recipes, review-requested

#22826 add unifdef
  recipes/unifdef/build.sh
  recipes/unifdef/meta.yaml
Labels: review-requested, c-cpp

#22797 Adding PE-configurator
  recipes/pe-configurator/meta.yaml
Labels: review-requested, python

#22835 ENH add batoid-rubin
  recipes/batoid-rubin/meta.yaml
Labels: staged-recipes, review-requested

#22846 ENH add borneo
  recipes/borneo/meta.yaml
Labels: staged-recipes, review-requested

#22864 add agemo
  recipes/agemo/LICENSE
  recipes/agemo/meta.yaml
Labels: staged-recipes, review-requested

#22868 add etcdpy 0.0.0.2, python-consul2 0.1.5
  recipes/etcdpy/meta.yaml
  recipes/python-consul2/meta.yaml
Labels: staged-recipes, review-requested, python

#22859 Add Anthropic
  recipes/anthropic/LICENSE
  recipes/anthropic/meta.yaml
Labels: review-requested, python

#21532 Add mmhash3 recipe
  recipes/mmhash3/meta.yaml
Labels: staged-recipes, review-requested

#22701 Add openmetadata-sqllineage
  recipes/openmetadata-sqllineage/meta.yaml
Labels: staged-recipes, review-requested

#22878 Add flux-restful-client
  recipes/flux-restful-api/meta.yaml
Labels: staged-recipes, review-requested

#21627 Amundsen metadata
  recipes/amundsen-metadata/LICENSE
  recipes/amundsen-metadata/meta.yaml
Labels: staged-recipes, review-requested

#21629 Add amundsen-search
  recipes/amundsen-search/LICENSE
  recipes/amundsen-search/meta.yaml
Labels: staged-recipes, review-requested

#21628 Added amundsen-databuilder
  recipes/amundsen-databuilder/LICENSE
  recipes/amundsen-databuilder/meta.yaml
Labels: staged-recipes, review-requested

#22648 Add perl-uri recipe from bioconda
  recipes/perl-uri/bld.bat
  recipes/perl-uri/build.sh
  recipes/perl-uri/meta.yaml
Labels: review-requested, perl

#22884 add `r-ggblend`
  recipes/r-ggblend/bld.bat
  recipes/r-ggblend/build.sh
  recipes/r-ggblend/conda_build_config.yaml
  recipes/r-ggblend/meta.yaml
Labels: R, review-requested

#22890 Add OnStove recipe
  recipes/onstove/meta.yaml
Labels: staged-recipes, review-requested

#22909 Add json-stream-rs-tokenizer
  recipes/json-stream-rs-tokenizer/meta.yaml
Labels: staged-recipes, review-requested

#21894 Add recipe for adam-robotics Python package
  recipes/adam-robotics/40.patch
  recipes/adam-robotics/meta.yaml
  recipes/adam-robotics/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#22908 Add suxarray
  recipes/suxarray/meta.yaml
Labels: review-requested, python

#22842 add recipe for PyPythia
  recipes/PyPythia/meta.yaml
Labels: review-requested, python

#22921 Add recipe for hclfmt
  recipes/hclfmt/meta.yaml
Labels: staged-recipes, review-requested

#22903 BUG: Missing cuda keys
  .ci_support/linux64.yaml
  .ci_support/linux64_cuda102.yaml
  .ci_support/linux64_cuda110.yaml
  .ci_support/linux64_cuda111.yaml
  .ci_support/linux64_cuda112.yaml
Labels: staged-recipes, review-requested, core

#22862 add polly
  recipes/polly/build.sh
  recipes/polly/meta.yaml
Labels: staged-recipes, review-requested

#22910 Add Json_Stream
  recipes/json_stream/meta.yaml
Labels: staged-recipes, review-requested

#22870 Add jupyterhub-traefik-proxy 1.0.0 (mk2)
  recipes/jupyterhub-traefik-proxy/000-ipv4-localhost.diff
  recipes/jupyterhub-traefik-proxy/meta.yaml
  recipes/jupyterhub-traefik-proxy/run_test_all.py
Labels: review-requested, python

#22928 Add recipe for bitsandbytes
  recipes/bitsandbytes/build.sh
  recipes/bitsandbytes/meta.yaml
Labels: staged-recipes, review-requested

#22924 Add recipe for InstructorEmbedding
  recipes/InstructorEmbedding/meta.yaml
Labels: staged-recipes, review-requested

#21195 add recipe for Polygon3
  recipes/Polygon3/GPC-license.txt
  recipes/Polygon3/LICENSE.txt
  recipes/Polygon3/meta.yaml
Labels: review-requested, python-c

#21947 Adding new DGGRID tool package
  recipes/dggrid/bld.bat
  recipes/dggrid/build.sh
  recipes/dggrid/meta.yaml
Labels: review-requested, c-cpp

#22286 Add PCMSolver
  recipes/pcmsolver/0001-update-cmake-adapt-for-win-add-licenses.patch
  recipes/pcmsolver/bld.bat
  recipes/pcmsolver/build.sh
  recipes/pcmsolver/meta.yaml
  recipes/pcmsolver/molecule.inp
Labels: review-requested, c-cpp

#22856 Add sphinx-versioned-docs
  recipes/sphinx-versioned-docs/meta.yaml
Labels: review-requested, python

#22032 Add helix editor
  recipes/helix/build.sh
  recipes/helix/meta.yaml
Labels: staged-recipes, review-requested

#22300 Add wrk
  recipes/wrk/build.sh
  recipes/wrk/meta.yaml
Labels: staged-recipes, review-requested

#22888 add dace
  recipes/dace/meta.yaml
Labels: staged-recipes, review-requested

#22573 Adding `arraymap` package
  recipes/arraymap/meta.yaml
Labels: review-requested, python-c

#22934 Add maxvolpy
  recipes/maxvolpy/meta.yaml
Labels: staged-recipes, review-requested

#22454 add recipe for aitch
  recipes/aitch/bld.bat
  recipes/aitch/build.sh
  recipes/aitch/conda_build_config.yaml
  recipes/aitch/meta.yaml
Labels: staged-recipes, review-requested

#22940 Add `r-finetune`
  recipes/r-finetune/bld.bat
  recipes/r-finetune/build.sh
  recipes/r-finetune/meta.yaml
Labels: R, review-requested

#22941 Add `r-discrim`
  recipes/r-discrim/bld.bat
  recipes/r-discrim/build.sh
  recipes/r-discrim/meta.yaml
Labels: R, review-requested

#22943 Openlineage python v0.26
  recipes/openlineage-python/LICENSE
  recipes/openlineage-python/meta.yaml
Labels: staged-recipes, review-requested

#22898 Add tomocupy recipy
  recipes/tomocupy/meta.yaml
Labels: review-requested, python-c

#22939 Add types-tqdm and types-pywin32
  recipes/types-pywin32/LICENSE
  recipes/types-pywin32/meta.yaml
  recipes/types-tqdm/LICENSE
  recipes/types-tqdm/meta.yaml
Labels: review-requested, python

#22929 Add recipe for nomad-driver-podman
  recipes/nomad-podman-driver/meta.yaml
Labels: staged-recipes, review-requested

#22974 add `r-ergm.multi`
  recipes/r-ergm.multi/bld.bat
  recipes/r-ergm.multi/build.sh
  recipes/r-ergm.multi/meta.yaml
Labels: R, review-requested

#22975 add: cw2 cluster management package
  recipes/cw2/meta.yaml
Labels: review-requested, python

#22977 Add ttopt
  recipes/ttopt/meta.yaml
Labels: staged-recipes, review-requested
