Repository conda-forge/staged-recipes, pull requests merged in 2023-01, with the labels that each got.

#21267 Add awkward-cpp
  recipes/awkward-cpp/meta.yaml
Labels: review-requested, python

#21605 Antlr4 tools
  recipes/antlr4-tools/LICENSE
  recipes/antlr4-tools/meta.yaml
Labels: staged-recipes, review-requested

#21646 Recipe for forbiddenfruit
  recipes/forbiddenfruit/meta.yaml
Labels: staged-recipes, review-requested

#21645 add gitflow
  recipes/gitflow/meta.yaml
Labels: staged-recipes, review-requested

#21632 Adding earth-osm
  recipes/earth-osm/meta.yaml
Labels: review-requested, python

#21647 Adding river-ingester package
  recipes/river-ingester/build.sh
  recipes/river-ingester/conda_build_config.yaml
  recipes/river-ingester/meta.yaml
Labels: staged-recipes, review-requested

#18364 Add git-annex-remote-rclone
  recipes/git-annex-remote-rclone/meta.yaml
Labels: staged-recipes, review-requested

#21544 Add soapysdr-module-redpitaya
  recipes/soapysdr-module-redpitaya/bld.bat
  recipes/soapysdr-module-redpitaya/build.sh
  recipes/soapysdr-module-redpitaya/meta.yaml
Labels: review-requested, c-cpp

#21074 Add VeloxChem package
  recipes/veloxchem/activate.bat
  recipes/veloxchem/bld.bat
  recipes/veloxchem/build.sh
  recipes/veloxchem/conda_build_config.yaml
  recipes/veloxchem/deactivate.bat
  recipes/veloxchem/meta.yaml
  recipes/veloxchem/patches/geometric-as-posix.patch
Labels: review-requested, python-c

#21566 add pyg-lib
  recipes/pyg-lib/bld.bat
  recipes/pyg-lib/build.sh
  recipes/pyg-lib/cmake_compat.patch
  recipes/pyg-lib/meta.yaml
Labels: Awaiting author contribution, python-c

#21650 Add pytest-update-test-results plugin to conda-forge.
  recipes/pytest-update-test-results/meta.yaml
Labels: review-requested, python

#21665 Adding planetary-coverage
  recipes/planetary-coverage/meta.yaml
Labels: staged-recipes, review-requested

#21666 Add pypdf
  recipes/pypdf/meta.yaml
Labels: review-requested, python

#21669 adds r-xefun
  recipes/r-xefun/bld.bat
  recipes/r-xefun/build.sh
  recipes/r-xefun/meta.yaml
Labels: R, review-requested

#21664 Add r-xefun
  recipes/r-xefun/bld.bat
  recipes/r-xefun/build.sh
  recipes/r-xefun/meta.yaml
Labels: R, review-requested

#21640 adds r-ggsurvfit
  recipes/r-ggsurvfit/bld.bat
  recipes/r-ggsurvfit/build.sh
  recipes/r-ggsurvfit/meta.yaml
Labels: R, review-requested

#21583 Add prefect-aws recipe
  recipes/prefect-aws/meta.yaml
Labels: review-requested, python

#21684 Add sqlparams
  recipes/sqlparams/meta.yaml
Labels: staged-recipes, review-requested

#21677 Adding `shakenbreak`
  recipes/shakenbreak/meta.yaml
Labels: review-requested, python

#21676 adds r-future.callr
  recipes/r-future.callr/bld.bat
  recipes/r-future.callr/build.sh
  recipes/r-future.callr/meta.yaml
Labels: R, review-requested

#21685 Add airflow-dbt
  recipes/airflow-dbt/meta.yaml
Labels: staged-recipes, review-requested

#21620 Adding conda-forge recipe for diffpy.pdfgui
  recipes/diffpy.pdfgui/meta.yaml
Labels: review-requested, python

#21692 Add oschmod
  recipes/oschmod/meta.yaml
Labels: staged-recipes, review-requested

#21644 Add hdxms datasets
  recipes/hdxms-datasets/meta.yaml
Labels: staged-recipes, review-requested

#21653 Aimrocks
  recipes/aimrocks/LICENSE
  recipes/aimrocks/build.sh
  recipes/aimrocks/conda_build_config.yaml
  recipes/aimrocks/meta.yaml
  recipes/aimrocks/setup_rocksdb.patch
Labels: review-requested, python-c

#21651 add aim-ui
  recipes/aim-ui/LICENSE
  recipes/aim-ui/meta.yaml
Labels: review-requested, python

#21687 Add pyxsim
  recipes/pyxsim/meta.yaml
Labels: staged-recipes, review-requested

#21695 quera-ahs-utils 0.0.6 initial staging.
  recipes/quera-ahs-utils/meta.yaml
Labels: staged-recipes, review-requested

#21678 Adding KinBot package.
  recipes/kinbot/meta.yaml
Labels: review-requested, python

#18843 Adds causalimpact recipe
  recipes/causalimpact/LICENSE.md
  recipes/causalimpact/meta.yaml
Labels: staged-recipes, review-requested

#21702 add urllib3_secure_extra
  recipes/urllib3-secure-extra/LICENSE
  recipes/urllib3-secure-extra/meta.yaml
Labels: staged-recipes, review-requested

#20882 Add graalpy package to make Graalpy available as a Python implementation
  recipes/graalpy/LICENSE
  recipes/graalpy/build_graalpy.sh
  recipes/graalpy/conda_build_config.yaml
  recipes/graalpy/meta.yaml
  recipes/graalpy/patches/graalpy-fix-lzma.patch
  recipes/graalpy/patches/graalpy-graalvm-version-tag.patch
  recipes/graalpy/patches/graalpy-honour-sysroot.patch
  recipes/graalpy/patches/graalpy-reduce-image-build-xmx.patch
  recipes/graalpy/patches/mx-keep-rpath-origin-variable.patch
  recipes/graalpy/patches/mx-pypy-support.patch
  recipes/graalpy/patches/sulong-disable-tests.patch
  recipes/graalpy/patches/sulong-relative-rpath.patch
Labels: review-requested, python, python-c

#21709 adds r-hotelling
  recipes/r-hotelling/bld.bat
  recipes/r-hotelling/build.sh
  recipes/r-hotelling/meta.yaml
Labels: R, review-requested

#21703 adds r-tgp
  recipes/r-tgp/bld.bat
  recipes/r-tgp/build.sh
  recipes/r-tgp/meta.yaml
Labels: R, review-requested

#21714 Adding autogluon.common package
  recipes/autogluon.common/meta.yaml
Labels: review-requested, python

#21686 Add recipe for nifti-mrs (generated with grayskull).
  recipes/nifti-mrs/meta.yaml
Labels: review-requested, python

#21724 Adding autogluon.features package
  recipes/autogluon.features/meta.yaml
Labels: review-requested, python

#21725 Adding autogluon.core package
  recipes/autogluon.core/meta.yaml
Labels: review-requested, python

#21354 Add py-triangle
  recipes/py-triangle/meta.yaml
Labels: review-requested, python-c

#21405 Added libpcsclite as a package
  recipes/libpcsclite/conda-forge.yml
  recipes/libpcsclite/meta.yaml
Labels: review-requested, c-cpp

#21619 Add libunrar
  recipes/libunrar/0001-REMOVE-HARDCODED-MAKEFILE-ENV.patch
  recipes/libunrar/0002-REMOVE-INSTALL-OPTION.patch
  recipes/libunrar/0003-CHANGE-DYLIB-EXTENSION.patch
  recipes/libunrar/bld.bat
  recipes/libunrar/build.sh
  recipes/libunrar/meta.yaml
Labels: review-requested, c-cpp

#21726 Adding autogluon.tabular package
  recipes/autogluon.tabular/meta.yaml
Labels: review-requested, python

#21734 Add synthetic-data
  recipes/synthetic-data/meta.yaml
Labels: staged-recipes, review-requested

#21641 add serapeum_utils package
  recipes/serapeum_utils/meta.yaml
Labels: Awaiting author contribution, python

#21720 Adding pytorch-metric-learning package
  recipes/pytorch-metric-learning/meta.yaml
Labels: Awaiting author contribution, python

#21721 Adding autocfg package
  recipes/autocfg/LICENSE
  recipes/autocfg/meta.yaml
Labels: review-requested, python

#21595 Add naiad-commons recipe
  recipes/naiad-commons/meta.yaml
Labels: review-requested, python

#21655 add Cerbere recipe
  recipes/cerbere/meta.yaml
Labels: review-requested, python

#21722 Adding gluonts package
  recipes/gluonts/LICENSE
  recipes/gluonts/NOTICE
  recipes/gluonts/meta.yaml
Labels: review-requested, python

#21648 Add expelliarmus via grayskull
  recipes/expelliarmus/meta.yaml
Labels: Awaiting author contribution, python-c

#21747 conda recipe of r CRAN package OptM
  recipes/r-optm/bld.bat
  recipes/r-optm/build.sh
  recipes/r-optm/meta.yaml
Labels: staged-recipes, review-requested

#21746 add picobox recipe
  recipes/picobox/meta.yaml
Labels: staged-recipes, review-requested

#21589 Add Naiad recipe
  recipes/naiad/meta.yaml
Labels: staged-recipes, review-requested, python

#21594 add eo-dataflow-manager recipe
  recipes/eo-dataflow-manager/meta.yaml
Labels: review-requested, python

#21717 Add eo-dataflow-report recipe
  recipes/eo-dataflow-report/LICENSE
  recipes/eo-dataflow-report/meta.yaml
Labels: staged-recipes, review-requested, python

#21718 Add eo-dataflow-ui recipe
  recipes/eo-dataflow-ui/LICENSE
  recipes/eo-dataflow-ui/meta.yaml
Labels: review-requested, python

#21760 Added sqeleton as a package
  recipes/sqeleton/meta.yaml
Labels: staged-recipes, review-requested

#21736 Adding gluoncv package
  recipes/gluoncv/meta.yaml
Labels: staged-recipes, review-requested

#21764 Add jobard-api recipe
  recipes/jobard-api/meta.yaml
Labels: staged-recipes, review-requested, python

#21767 Add jobard-remote-dask recipe
  recipes/jobard-remote-dask/meta.yaml
Labels: staged-recipes, review-requested, python

#21769 Add felyxcontribs-metrics-base recipe
  recipes/felyxcontribs-metrics-base/meta.yaml
Labels: staged-recipes, review-requested, python

#21771 Add felyxcontrib-metrics-ghrsst recipe
  recipes/felyxcontrib-metrics-ghrsst/meta.yaml
Labels: staged-recipes, review-requested, python

#21765 Add jobard-daemon recipe
  recipes/jobard-daemon/meta.yaml
Labels: staged-recipes, review-requested, python

#21770 Add felyxcontrib-metrics-workflow recipe
  recipes/felyxcontrib-metrics-workflow/meta.yaml
Labels: staged-recipes, review-requested, python

#21766 Add jobard-client recipe
  recipes/jobard-client/meta.yaml
Labels: staged-recipes, review-requested, python

#21762 Added ipfn as a package
  recipes/ipfn/meta.yaml
Labels: staged-recipes, review-requested

#21585 Added klongpy as a package
  recipes/klongpy/meta.yaml
Labels: staged-recipes, review-requested

#21768 Add jobard-worker-dask recipe
  recipes/jobard-worker-dask/meta.yaml
Labels: staged-recipes, review-requested, python

#21693 Add scitacean
  recipes/scitacean/meta.yaml
Labels: review-requested, python

#21737 Adding model-index package
  recipes/model-index/meta.yaml
Labels: review-requested, python

#21738 Adding openmim package
  recipes/openmim/LICENSE
  recipes/openmim/meta.yaml
Labels: staged-recipes, review-requested

#21711 Adding miniful recipe
  recipes/miniful/LICENSE
  recipes/miniful/meta.yaml
Labels: review-requested, python

#21110 Add recipe for r-changepoints
  recipes/r-changepoints/bld.bat
  recipes/r-changepoints/build.sh
  recipes/r-changepoints/meta.yaml
Labels: staged-recipes, review-requested

#17129 package torchtext
  recipes/revtok/LICENSE
  recipes/revtok/meta.yaml
  recipes/torchtext/LICENSE
  recipes/torchtext/meta.yaml
  recipes/torchtext/patches/0001-do-not-build-third_party-libs.patch
  recipes/torchtext/patches/0002-fix-some-CMake-arguments-for-our-infrastructure.patch
  recipes/torchtext/patches/0003-remove-unnecessary-installation-requirements.patch
  recipes/torchtext/patches/0004-load-library-from-correct-place.patch
  recipes/torchtext/patches/0005-must-use-C-17-to-match-abseil.patch
Labels: staged-recipes, review-requested

#21801 add pyproject-fmt 0.5.0
  recipes/pyproject-fmt/meta.yaml
Labels: staged-recipes, review-requested, python

#21799 add ipyforcegraph 0.1.0
  recipes/ipyforcegraph/meta.yaml
Labels: staged-recipes, review-requested, python

#21806 Add Vapoursynth
  recipes/vapoursynth/build.sh
  recipes/vapoursynth/meta.yaml
Labels: review-requested, python-c

#21246 Add qdax using grayskull
  recipes/qdax/meta.yaml
Labels: review-requested, python

#21776 Adding autogluon.multimodal package
  recipes/autogluon.multimodal/meta.yaml
Labels: review-requested, python

#21739 Adding autogluon.timeseries package
  recipes/autogluon.timeseries/meta.yaml
Labels: staged-recipes, review-requested

#21609 Add ratarmountcore
  recipes/ratarmountcore/meta.yaml
Labels: review-requested, python

#21794 Add ZFEL
  recipes/zfel/meta.yaml
Labels: staged-recipes, review-requested

#21803 Adding `eeharvest` package
  recipes/eeharvest/meta.yaml
Labels: staged-recipes, review-requested

#21812 Adding anywidget package
  recipes/anywidget/meta.yaml
Labels: review-requested, python

#21712 Added simpful recipe using grayskull
  recipes/simpful/meta.yaml
Labels: review-requested, python

#21621 Add Fastapi healthcheck recipe
  recipes/fastapi_healthcheck/meta.yaml
Labels: review-requested, python

#21809 add r-tlmoments
  recipes/r-tlmoments/bld.bat
  recipes/r-tlmoments/build.sh
  recipes/r-tlmoments/meta.yaml
Labels: R, review-requested

#21716 add KaHIP graph partitioner
  recipes/kahip/0001-install-python-component.patch
  recipes/kahip/build-kahip-python.sh
  recipes/kahip/build-kahip.sh
  recipes/kahip/conda_build_config.yaml
  recipes/kahip/meta.yaml
Labels: review-requested, python-c

#21520 Add recipe for Perl module Moose and its dependencies
  recipes/perl-b-hooks-endofscope/bld.bat
  recipes/perl-b-hooks-endofscope/build.sh
  recipes/perl-b-hooks-endofscope/meta.yaml
  recipes/perl-class-load-xs/bld.bat
  recipes/perl-class-load-xs/build.sh
  recipes/perl-class-load-xs/meta.yaml
  recipes/perl-class-load/bld.bat
  recipes/perl-class-load/build.sh
  recipes/perl-class-load/meta.yaml
  recipes/perl-devel-overloadinfo/bld.bat
  recipes/perl-devel-overloadinfo/build.sh
  recipes/perl-devel-overloadinfo/meta.yaml
  recipes/perl-eval-closure/bld.bat
  recipes/perl-eval-closure/build.sh
  recipes/perl-eval-closure/meta.yaml
  recipes/perl-file-pushd/bld.bat
  recipes/perl-file-pushd/build.sh
  recipes/perl-file-pushd/meta.yaml
  recipes/perl-module-runtime-conflicts/bld.bat
  recipes/perl-module-runtime-conflicts/build.sh
  recipes/perl-module-runtime-conflicts/meta.yaml
  recipes/perl-moose/bld.bat
  recipes/perl-moose/build.sh
  recipes/perl-moose/meta.yaml
  recipes/perl-namespace-clean/bld.bat
  recipes/perl-namespace-clean/build.sh
  recipes/perl-namespace-clean/meta.yaml
  recipes/perl-test-cleannamespaces/bld.bat
  recipes/perl-test-cleannamespaces/build.sh
  recipes/perl-test-cleannamespaces/meta.yaml
Labels: review-requested, perl

#21824 add fuzzytm and dependencies
  recipes/fst-pso/LICENSE
  recipes/fst-pso/meta.yaml
  recipes/fuzzytm/meta.yaml
  recipes/pyfume/LICENSE
  recipes/pyfume/meta.yaml
Labels: review-requested

#21705 Added empyrical recipe
  recipes/empyrical-reloaded/meta.yaml
Labels: review-requested, python

#21624 adding itslive to conda-forge
  recipes/itslive/meta.yaml
Labels: review-requested, python

#21649 Add recipe for uSockets C/C++ library
  recipes/libusockets/CMakeLists.txt
  recipes/libusockets/bld.bat
  recipes/libusockets/build.sh
  recipes/libusockets/conda_build_config.yaml
  recipes/libusockets/disable_ssl_tests.patch
  recipes/libusockets/meta.yaml
  recipes/libusockets/use_libuv.patch
Labels: review-requested, c-cpp

#21587 Add dvc-studio-client
  recipes/dvc-studio-client/meta.yaml
Labels: review-requested, python

#21821 Added wrappy as a package
  recipes/wrappy/meta.yaml
Labels: staged-recipes, review-requested

#21816 Added recipe for flexmod 0.1.1
  recipes/flexmod/meta.yaml
Labels: staged-recipes, review-requested

#21822 Added shaffle as a package
  recipes/shaffle/meta.yaml
Labels: staged-recipes, review-requested

#20936 Adding Radis
  recipes/radis/meta.yaml
Labels: staged-recipes, review-requested, python-c

#21847 Add sqlalchemy-views package
  recipes/sqlalchemy-views/meta.yaml
Labels: review-requested, python

#21311 Add dm_control recipe
  recipes/dm_control/meta.yaml
  recipes/dm_control/yum_requirements.txt
Labels: review-requested, python

#21810 Add word-forms
  recipes/word-forms/LICENSE
  recipes/word-forms/meta.yaml
Labels: staged-recipes, review-requested

#21811 Add timer
  recipes/timer/meta.yaml
Labels: staged-recipes, review-requested

#21814 Added swapper as a package
  recipes/swapper/meta.yaml
Labels: staged-recipes, review-requested

#21657 Adding pyshepseg
  recipes/pyshepseg/meta.yaml
Labels: staged-recipes, review-requested

#21852 add open-clip-torch
  recipes/open-clip-torch/meta.yaml
Labels: staged-recipes, review-requested

#21853 add safetensors
  recipes/safetensors/LICENSE
  recipes/safetensors/meta.yaml
Labels: staged-recipes, review-requested

#21775 Adding autogluon.vision package
  recipes/autogluon.vision/meta.yaml
  recipes/autogluon.vision/yum_requirements.txt
Labels: review-requested, python

#21777 Adding autogluon.text package
  recipes/autogluon.text/meta.yaml
Labels: staged-recipes, review-requested

#21848 Adding PyPulse: a Python package to handle PSRFITS files
  recipes/pypulse/meta.yaml
Labels: review-requested, python

#21579 Add recipe for pyirf
  recipes/pyirf/meta.yaml
Labels: review-requested, python

#21863 Add py3dns
  recipes/py3dns/meta.yaml
Labels: review-requested, python

#21719 Add recipe for pygad
  recipes/pygad/152.patch
  recipes/pygad/meta.yaml
Labels: review-requested, python

#21855 Add sdformat-mjcf package
  recipes/sdformat-mjcf/meta.yaml
Labels: review-requested, python

#21849 add imaginAIry
  recipes/imaginairy/meta.yaml
  recipes/imaginairy/yum_requirements.txt
Labels: staged-recipes, review-requested

#21871 Marquez python
  recipes/marquez-python/LICENSE
  recipes/marquez-python/meta.yaml
Labels: staged-recipes, review-requested

#21866 Add PINT-pal: A long-lived repository for NANOGrav Pulsar Timing analysis work.
  recipes/pint-pal/meta.yaml
Labels: review-requested, python

#21638 Add scikit-fda recipe.
  recipes/scikit-fda/meta.yaml
Labels: review-requested, python

#21780 Adding autogluon package
  recipes/autogluon/meta.yaml
Labels: review-requested, python

#21869 Adding NARDINI sequence analysis package
  recipes/nardini/meta.yaml
Labels: review-requested, python

#21881 ✨ Add virtual-glob python package
  recipes/virtual-glob/meta.yaml
Labels: review-requested, python

#21706 Added bcolz-reloaded recipe
  recipes/bcolz-zipline/meta.yaml
Labels: review-requested, python

#21865 Add authres
  recipes/authres/meta.yaml
Labels: review-requested, python

#21805 Adding ratingcurve
  recipes/ratingcurve/meta.yaml
Labels: staged-recipes, review-requested

#21610 Add recipe for basicauth
  recipes/basicauth/meta.yaml
Labels: review-requested, python

#21898 Add timerit
  recipes/timerit/meta.yaml
Labels: staged-recipes, review-requested

#21899 Add recipe for samsungtvws
  recipes/samsungtvws/meta.yaml
Labels: staged-recipes, review-requested

#21910 add jyg 0.1.1
  recipes/jyg/meta.yaml
Labels: staged-recipes, review-requested, python

#21779 add glab (gitlab-cli) 1.24.1
  recipes/glab/bld.bat
  recipes/glab/build.sh
  recipes/glab/build_win.sh
  recipes/glab/conda_build_config.yaml
  recipes/glab/meta.yaml
Labels: staged-recipes, review-requested, go

#21785 Adding solvation_analysis v0.1.5 to conda-forge
  recipes/solvation_analysis/meta.yaml
Labels: review-requested, python
