Repository conda-forge/staged-recipes, pull requests merged in 2023-07, with the labels that each got.

#23212 ROBERT v1.0.0
  recipes/robert/meta.yaml
Labels: staged-recipes, review-requested

#23213 add eralchemy2 1.3.7
  recipes/eralchemy2/meta.yaml
Labels: staged-recipes, review-requested, python

#23216 Added pandas-dq as a package
  recipes/pandas-dq/meta.yaml
Labels: staged-recipes, review-requested

#22918 Add recipe for chemdyg
  recipes/chemdyg/meta.yaml
Labels: review-requested, python

#23224 Adding sphractal package
  recipes/sphractal/LICENSE
  recipes/sphractal/meta.yaml
Labels: staged-recipes, review-requested, python

#23220 New recipe for django-easy-logging==0.60
  recipes/django-easy-logging/meta.yaml
Labels: review-requested, python

#23219 Hll - Fast HyperLogLog for Python.
  recipes/hll/LICENSE
  recipes/hll/meta.yaml
Labels: staged-recipes, review-requested

#23218 Add Apache DataSketches Library for Python
  recipes/datasketches/meta.yaml
Labels: staged-recipes, review-requested

#23231 add: pydantic-settings
  recipes/pydantic-settings/meta.yaml
Labels: review-requested, python

#23024 Add bincopy module
  recipes/argparse-addons/meta.yaml
Labels: staged-recipes, review-requested

#23236 Add tftest from pypi (using grayskull)
  recipes/tftest/meta.yaml
Labels: review-requested, python

#23235 Add recipe for tox-current-env
  recipes/tox-current-env/meta.yaml
Labels: staged-recipes, review-requested

#23237 Package textual-dev
  recipes/textual-dev/meta.yaml
Labels: review-requested, python

#23233 Adding h5coro package
  recipes/h5coro/meta.yaml
Labels: review-requested, python

#22931 Add a recipe for flynt
  recipes/flynt/meta.yaml
Labels: review-requested, python

#22653 Added ipyflow-core as a package
  recipes/ipyflow-core/meta.yaml
Labels: staged-recipes, review-requested

#23269 Add recipe for opentelemetry-exporter-otlp-proto-common (a newly introduced opentelemetry dep)
  recipes/opentelemetry-exporter-otlp-proto-common/meta.yaml
Labels: review-requested, python

#23273 Adds `r-clarify`
  recipes/r-clarify/bld.bat
  recipes/r-clarify/build.sh
  recipes/r-clarify/meta.yaml
Labels: R, review-requested

#21797 Add recipe for libpnetcdf
  recipes/libpnetcdf/build.sh
  recipes/libpnetcdf/conda_build_config.yaml
  recipes/libpnetcdf/meta.yaml
Labels: review-requested, c-cpp

#23289 Add grayskull-generated mujoco-python-viewer recipe
  recipes/mujoco-python-viewer/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#23291 Add covalent
  recipes/covalent/meta.yaml
Labels: staged-recipes, review-requested

#23209 Added recipe for astropy-iers-data
  recipes/astropy-iers-data/meta.yaml
Labels: review-requested, python

#23234 Adding ktch
  recipes/ktch/meta.yaml
Labels: review-requested, python

#23293 Windows Implementation Libraries (WIL)
  recipes/wil/bld.bat
  recipes/wil/meta.yaml
Labels: review-requested, c-cpp

#23203 Add timescoring pypi package
  recipes/timescoring/meta.yaml
Labels: review-requested, python

#23295 Add grayskull-generated liecasadi recipe
  recipes/liecasadi/meta.yaml
Labels: staged-recipes, review-requested, python

#23296 Add grayskull-generated jax-dataclasses recipe
  recipes/jax-dataclasses/meta.yaml
Labels: staged-recipes, review-requested, python

#23222 Piano fingering
  recipes/piano_fingering/meta.yaml
Labels: staged-recipes, review-requested

#22982 Add kalpy recipe
  recipes/kalpy/bld.bat
  recipes/kalpy/build.sh
  recipes/kalpy/meta.yaml
Labels: review-requested, python-c

#23299 Added flet-runtime as a package
  recipes/flet-runtime/LICENSE
  recipes/flet-runtime/meta.yaml
Labels: staged-recipes, review-requested

#23282 New tfv conda-forge package
  recipes/tfv/meta.yaml
Labels: review-requested, python

#22804 Adding pytest_parallel_mpi package
  recipes/pytest_parallel_mpi/meta.yaml
Labels: review-requested, python

#23303 Adding omicverse
  recipes/omicverse/meta.yaml
Labels: staged-recipes, review-requested

#23312 Add gmailsorter
  recipes/gmailsorter/meta.yaml
Labels: staged-recipes, review-requested

#23300 Adding segment-lidar
  recipes/segment-lidar/meta.yaml
Labels: staged-recipes, review-requested

#23207 Adding Disperse
  recipes/disperse/build.sh
  recipes/disperse/meta.yaml
Labels: review-requested, c-cpp

#23315 Add split-file-reader
  recipes/split-file-reader/meta.yaml
Labels: review-requested, python

#23325 add sarif-tools 1.0.0
  recipes/sarif-tools/meta.yaml
Labels: staged-recipes, review-requested, python

#23305 Add grayskull-generated recipe for tyro package
  recipes/tyro/meta.yaml
Labels: staged-recipes, review-requested, python

#23301 Adding fsl-pipe-gui
  recipes/fsl-pipe-gui/meta.yaml
Labels: review-requested, python

#23307 Add recipe for pyobjc-framework-security
  recipes/pyobjc-framework-security/meta.yaml
Labels: staged-recipes, review-requested, python-c

#22987 Add h5pulsar, a package to put Pulsar data into HDF5 files
  recipes/h5pulsar/meta.yaml
Labels: review-requested, python

#23331 Package jupyter-kernel-provisioner-proxy
  recipes/jupyter-kernel-provisioner-proxy/meta.yaml
Labels: review-requested, python

#23330 add r-manhattanly
  recipes/r-manhattanly/bld.bat
  recipes/r-manhattanly/build.sh
  recipes/r-manhattanly/meta.yaml
Labels: R, review-requested

#23327 initial implementation of grib2io package
  recipes/grib2io/meta.yaml
Labels: review-requested, python

#23285 Add r-admm
  recipes/r-admm/bld.bat
  recipes/r-admm/build.sh
  recipes/r-admm/meta.yaml
Labels: R, review-requested

#23188 Add napari-mzarr recipe
  recipes/napari-mzarr/meta.yaml
  recipes/napari-mzarr/yum_requirements.txt
Labels: staged-recipes, review-requested

#19830 Add napari-nlm recipe
  recipes/napari-nlm/meta.yaml
  recipes/napari-nlm/yum_requirements.txt
Labels: staged-recipes, review-requested

#23343 Add `trio-typing`
  recipes/trio-typing/meta.yaml
Labels: review-requested, python

#23037 add mp-pyrho
  recipes/mp-pyrho/0001-fix-requires-python.patch
  recipes/mp-pyrho/meta.yaml
Labels: review-requested, python

#23335 Add recipes for molecule-generation and tf2-gnn
  recipes/molecule-generation/meta.yaml
  recipes/tf2-gnn/LICENSE
  recipes/tf2-gnn/meta.yaml
Labels: review-requested, python

#23336 Adding album-solution-api recipe
  recipes/album-solution-api/meta.yaml
Labels: review-requested, python

#23346 Add recipe for stamina
  recipes/stamina/meta.yaml
Labels: staged-recipes, review-requested, python

#23341 Adding seaduck to conda-forge
  recipes/seaduck/meta.yaml
Labels: review-requested, python

#23342 Add `tricycle`
  recipes/tricycle/meta.yaml
Labels: review-requested, python

#23357 Add `aioguest`
  recipes/aioguest/meta.yaml
Labels: review-requested, python

#23356 add intake-dataframe-catalog
  recipes/intake-dataframe-catalog/meta.yaml
Labels: staged-recipes, review-requested

#23355 Add anaconda-catalogs
  recipes/anaconda-catalogs/meta.yaml
Labels: staged-recipes, review-requested

#23364 Add recipe for google-cloud-storage-transfer
  recipes/google-cloud-storage-transfer/meta.yaml
Labels: staged-recipes, review-requested, python

#23214 Add recipe for beanie-batteries-queue
  recipes/beanie-batteries-queue/meta.yaml
Labels: review-requested, python

#23138 Adding package idiap-devtools
  recipes/idiap-devtools/meta.yaml
Labels: review-requested, python

#23371 ENH: Add asv_runner
  recipes/asv_runner/LICENSE.md
  recipes/asv_runner/meta.yaml
Labels: review-requested, python

#23373 add xstate-python 0.0.1
  recipes/xstate-python/0000-no-docs-deps.diff
  recipes/xstate-python/meta.yaml
Labels: staged-recipes, review-requested, python

#23361 Add python-pins package
  recipes/python-pins/meta.yaml
Labels: review-requested, python

#23320 Add napari-workshop-browser recipe
  recipes/napari-workshop-browser/meta.yaml
  recipes/napari-workshop-browser/yum_requirements.txt
Labels: staged-recipes, review-requested

#23135 Add sybil.
  recipes/sybil/meta.yaml
Labels: review-requested, python

#23020 Adding mariadb-connector-c
  recipes/mariadb-connector-c/bld.bat
  recipes/mariadb-connector-c/build.sh
  recipes/mariadb-connector-c/meta.yaml
Labels: review-requested, c-cpp

#23245 Add pytorch3d
  recipes/pytorch3d/meta.yaml
Labels: review-requested, python-c

#23349 Add dbus-fast
  recipes/dbus-fast/meta.yaml
Labels: review-requested, python

#23380 Add robotframework-excellib
  recipes/robotframework-excellib/LICENSE
  recipes/robotframework-excellib/meta.yaml
Labels: staged-recipes, review-requested

#23182 Adding photochem
  recipes/photochem/LICENSE
  recipes/photochem/build.sh
  recipes/photochem/meta.yaml
Labels: review-requested, python-c

#22430 Adds Dymos
  recipes/dymos/meta.yaml
  recipes/dymos/run_test.py
  recipes/dymos/yum_requirements.txt
Labels: review-requested, python

#23372 Add xpystac
  recipes/xpystac/meta.yaml
Labels: review-requested, python

#23384 Add substring package
  recipes/substring/LICENSE
  recipes/substring/meta.yaml
Labels: review-requested, python

#22907 Add GroundingDINO and supervision packages
  recipes/groundingdino/meta.yaml
  recipes/groundingdino/yum_requirements.txt
  recipes/supervision/meta.yaml
  recipes/supervision/yum_requirements.txt
Labels: review-requested, python

#23395 Add r-nglviewer
  recipes/r-nglviewer/build.sh
  recipes/r-nglviewer/meta.yaml
Labels: staged-recipes, review-requested

#23393 Add r-archive
  recipes/r-archive/build.sh
  recipes/r-archive/meta.yaml
Labels: staged-recipes, review-requested

#23396 Add r-oaqc
  recipes/r-oaqc/bld.bat
  recipes/r-oaqc/build.sh
  recipes/r-oaqc/meta.yaml
Labels: staged-recipes, review-requested

#23402 Add r-shinytitle
  recipes/r-shinytitle/bld.bat
  recipes/r-shinytitle/build.sh
  recipes/r-shinytitle/meta.yaml
Labels: staged-recipes, review-requested

#23398 Add r-downloadthis
  recipes/r-downloadthis/bld.bat
  recipes/r-downloadthis/build.sh
  recipes/r-downloadthis/meta.yaml
Labels: staged-recipes, review-requested

#23397 Add r-hdci
  recipes/r-hdci/bld.bat
  recipes/r-hdci/build.sh
  recipes/r-hdci/meta.yaml
Labels: staged-recipes, review-requested

#23399 Add r-directpa
  recipes/r-directpa/bld.bat
  recipes/r-directpa/build.sh
  recipes/r-directpa/meta.yaml
Labels: staged-recipes, review-requested

#23400 Add r-remacor
  recipes/r-remacor/bld.bat
  recipes/r-remacor/build.sh
  recipes/r-remacor/meta.yaml
Labels: staged-recipes, review-requested

#23403 Add r-ssc
  recipes/r-ssc/bld.bat
  recipes/r-ssc/build.sh
  recipes/r-ssc/meta.yaml
Labels: staged-recipes, review-requested

#23405 Add r-azureauth
  recipes/r-azureauth/bld.bat
  recipes/r-azureauth/build.sh
  recipes/r-azureauth/meta.yaml
Labels: staged-recipes, review-requested

#23407 R azuregraph
  recipes/r-azuregraph/bld.bat
  recipes/r-azuregraph/build.sh
  recipes/r-azuregraph/meta.yaml
Labels: staged-recipes, review-requested

#23409 Add r-azurermr
  recipes/r-azurermr/bld.bat
  recipes/r-azurermr/build.sh
  recipes/r-azurermr/meta.yaml
Labels: staged-recipes, review-requested

#23406 Add r-wrswor
  recipes/r-wrswor/bld.bat
  recipes/r-wrswor/build.sh
  recipes/r-wrswor/meta.yaml
Labels: staged-recipes, review-requested

#23394 Add r-azurestor
  recipes/r-azurestor/build.sh
  recipes/r-azurestor/meta.yaml
Labels: staged-recipes, review-requested

#23410 Adding daggerpy
  recipes/daggerpy/meta.yaml
Labels: review-requested, python

#23198 Add `CellRank`
  recipes/cellrank/meta.yaml
Labels: review-requested, python

#23392 Add newrelic_telemetry_sdk Recipe
  recipes/newrelic-telemetry-sdk-python/meta.yaml
Labels: review-requested, python

#23389 Adding py4D-browser
  recipes/py4D-browser/meta.yaml
  recipes/py4D-browser/yum_requirements.txt
Labels: staged-recipes, review-requested

#23408 add recipe to build ctaplot package
  recipes/ctaplot/license.rst
  recipes/ctaplot/meta.yaml
Labels: review-requested, python

#23416 adds supermorecado recipe
  recipes/supermorecado/meta.yaml
Labels: review-requested, python

#23422 add recipe to build epiweeks package
  recipes/epiweeks/meta.yaml
Labels: review-requested, python

#23429 Add recipe for lstchain
  recipes/lstchain/LICENSE
  recipes/lstchain/meta.yaml
Labels: review-requested, python

#23413 Add `solara`
  recipes/solara/meta.yaml
Labels: review-requested, python

#23419 Adding pyunormalize
  recipes/pyunormalize/meta.yaml
Labels: review-requested, python

#23418 Add descriptastorus
  recipes/descriptastorus/meta.yaml
Labels: staged-recipes, review-requested

#23428 add recipe to build pywatershed package
  recipes/pywatershed/meta.yaml
Labels: review-requested, python

#23383 Add Neuralprophet recipe
  recipes/neuralprophet/meta.yaml
Labels: review-requested, python

#23417 Adding pesviewer package.
  recipes/pesviewer/meta.yaml
Labels: staged-recipes, review-requested

#22123 Adding pydantic-config recipe
  recipes/pydantic-config/meta.yaml
Labels: review-requested, python

#23420 Adding recipe for Sorcha
  recipes/sorcha/meta.yaml
Labels: review-requested, python

#23436 Bump CUDA to 11.2+
  .azure-pipelines/azure-pipelines-linux.yml
  .ci_support/linux64_cuda102.yaml
  .ci_support/linux64_cuda110.yaml
  .ci_support/linux64_cuda111.yaml
Labels: maintenance

#23437 Cleanup unneeded content from Azure Linux image
  .azure-pipelines/azure-pipelines-linux.yml
Labels: maintenance

#23438 Add cosmopy recipe
  recipes/cosmopy/meta.yaml
Labels: review-requested, python

#23439 Add recipe for google-re2
  recipes/google-re2/LICENSE
  recipes/google-re2/meta.yaml
Labels: review-requested, python-c

#23441 Add recipes for alibabacloud-*
  recipes/alibabacloud-adb20211201/meta.yaml
  recipes/alibabacloud-credentials/LICENSE
  recipes/alibabacloud-credentials/meta.yaml
  recipes/alibabacloud-endpoint-util/LICENSE
  recipes/alibabacloud-endpoint-util/meta.yaml
  recipes/alibabacloud-gateway-spi/LICENSE
  recipes/alibabacloud-gateway-spi/meta.yaml
  recipes/alibabacloud-openapi-util/LICENSE
  recipes/alibabacloud-openapi-util/meta.yaml
  recipes/alibabacloud-tea-openapi/LICENSE
  recipes/alibabacloud-tea-openapi/meta.yaml
  recipes/alibabacloud-tea-util/LICENSE
  recipes/alibabacloud-tea-util/meta.yaml
  recipes/alibabacloud-tea-xml/LICENSE
  recipes/alibabacloud-tea-xml/meta.yaml
  recipes/alibabacloud-tea/LICENSE
  recipes/alibabacloud-tea/meta.yaml
Labels: review-requested, python

#23443 Add kalepy
  recipes/kalepy/meta.yaml
Labels: review-requested, python

#23329 Add maotai
  recipes/r-maotai/bld.bat
  recipes/r-maotai/build.sh
  recipes/r-maotai/meta.yaml
  recipes/r-maotai/yum_requirements.txt
Labels: R, review-requested

#23350 build: add biobear recipe
  recipes/biobear/meta.yaml
Labels: review-requested, python-c

#23445 Add natpy
  recipes/natpy/meta.yaml
Labels: review-requested, python

#23444 Add kdepy
  recipes/kdepy/meta.yaml
Labels: review-requested, python

#23447 Add zfit_interface recipe
  recipes/zfit_interface/meta.yaml
Labels: review-requested, python

#23451 add robotframework-faker 5.0.0
  recipes/robotframework-faker/meta.yaml
Labels: staged-recipes, review-requested, python

#21577 Add pyRingGW package
  recipes/pyRingGW/meta.yaml
Labels: review-requested, python, python-c

#23454 Add `mknotebooks`
  recipes/mknotebooks/meta.yaml
Labels: review-requested, python

#23426 Add pybtexnbib
  recipes/pybtexnbib/meta.yaml
Labels: review-requested, python

#22367 Adding mosec
  recipes/mosec/build.sh
  recipes/mosec/meta.yaml
Labels: Awaiting author contribution, python-c

#22873 Add floatcsep
  recipes/floatcsep/LICENSE
  recipes/floatcsep/meta.yaml
Labels: review-requested, python

#23374 Add recipe for micro_sam
  recipes/micro_sam/meta.yaml
  recipes/yum_requirements.txt
Labels: review-requested, python

#23460 Package greenletio
  recipes/greenletio/meta.yaml
Labels: review-requested, python

#23456 Add r-ragtop
  recipes/r-ragtop/bld.bat
  recipes/r-ragtop/build.sh
  recipes/r-ragtop/meta.yaml
Labels: R, review-requested

#23087 add sliceable-dict
  recipes/sliceable-dict/LICENSE
  recipes/sliceable-dict/meta.yaml
Labels: review-requested, python

#23462 Add abacusutils
  recipes/abacusutils/meta.yaml
Labels: staged-recipes, review-requested

#23475 Add starlette-admin recipe
  recipes/starlette-admin/meta.yaml
Labels: staged-recipes, review-requested

#23479 Add recipe for package wsinfer-zoo
  recipes/wsinfer-zoo/meta.yaml
Labels: staged-recipes, review-requested

#23483 Add sphinx-pdj-theme
  recipes/sphinx-pdj-theme/meta.yaml
Labels: staged-recipes, review-requested

#23482 Add vermouth
  recipes/vermouth/meta.yaml
Labels: staged-recipes, review-requested

#23484 Add lobsterpy
  recipes/lobsterpy/meta.yaml
  recipes/lobsterpy/setup.patch
Labels: staged-recipes, review-requested

#22269 Add pytorch_tabular
  recipes/pytorch_tabular/build_base.sh
  recipes/pytorch_tabular/meta.yaml
Labels: review-requested, python

#22171 Add HiPACE++
  recipes/hipace/bld.bat
  recipes/hipace/build.sh
  recipes/hipace/meta.yaml
  recipes/hipace/test.bat
  recipes/hipace/test.sh
Labels: review-requested, c-cpp, python-c

#22882 adding gdma
  recipes/gdma/0001-add-CMake-library-pymod-IO-git-avoidance.patch
  recipes/gdma/bld-cxx.bat
  recipes/gdma/bld-py.bat
  recipes/gdma/build-cxx.sh
  recipes/gdma/build-py.sh
  recipes/gdma/meta.yaml
Labels: review-requested, c-cpp

#22981 Add Visp recipe
  recipes/visp/bld.bat
  recipes/visp/build.sh
  recipes/visp/meta.yaml
  recipes/visp/patches/0001-Fix-invalid-usage-of-OGRE_DIR-in-CMakeLists.txt.patch
  recipes/visp/patches/0002-Disable-AVX-and-AVX2-for-Simd-embedded-lib.patch
  recipes/visp/yum_requirements.txt
Labels: review-requested, c-cpp

#23022 Add rosettasciio recipe
  recipes/rosettasciio/meta.yaml
Labels: review-requested, python-c

#23498 Ebcdic parser
  recipes/ebcdic-parser/meta.yaml
Labels: staged-recipes, review-requested

#23495 Add s1reader
  recipes/s1reader/meta.yaml
Labels: staged-recipes, review-requested

#23506 add mordredcommunity recipe
  recipes/mordredcommunity/meta.yaml
Labels: review-requested, python

#23133 Create py2uml recipe
  recipes/py2puml/meta.yaml
Labels: review-requested, python

#23502 Add materials-learning-algorithms
  recipes/materials-learning-algorithms/meta.yaml
Labels: staged-recipes, review-requested

#23505 Package asphalt-sqlalchemy
  recipes/asphalt-sqlalchemy/meta.yaml
Labels: review-requested, python

#22947 Openlineage sql
  recipes/openlineage-sql/LICENSE
  recipes/openlineage-sql/meta.yaml
Labels: staged-recipes, review-requested

#23511 Added html5tagger as a pacakge
  recipes/html5tagger/meta.yaml
Labels: staged-recipes, review-requested

#23513 Add pyfda
  recipes/pyfda/0001-Only-install-the-pyfda-package-and-not-any-extra-dir.patch
  recipes/pyfda/meta.yaml
Labels: review-requested, python

#23507 Openlineage integration common v0.30.1
  recipes/openlineage-integration-common/LICENSE
  recipes/openlineage-integration-common/meta.yaml
Labels: staged-recipes, review-requested

#23512 Added tracerite as a package
  recipes/tracerite/meta.yaml
Labels: staged-recipes, review-requested

#23518 Openlineage dbt
  recipes/openlineage-dbt/LICENSE
  recipes/openlineage-dbt/meta.yaml
Labels: staged-recipes, review-requested

#23520 Add Grunner
  recipes/grunnur/meta.yaml
Labels: staged-recipes, review-requested
