Repository conda-forge/staged-recipes, pull requests merged in 2023-11, with the labels that each got.

#24390 Add ruff-lsp
  recipes/ruff-lsp/meta.yaml
Labels: review-requested, python

#24395 add yaqd-omega
  recipes/yaqd-omega/meta.yaml
Labels: review-requested, python

#24387 Add Kedro-Boot
  recipes/kedro-boot/meta.yaml
Labels: staged-recipes, review-requested

#24392 Add recipe for pymongo_inmemory
  recipes/pymongo_inmemory/meta.yaml
Labels: review-requested, python

#24391 Adding conda-poetry-liaison
  recipes/conda-poetry-liaison/LICENSE
  recipes/conda-poetry-liaison/meta.yaml
Labels: staged-recipes, review-requested

#23973 Add grayskull-generated recipe for `distrax` Python package
  recipes/distrax/01-exclude-examples.patch
  recipes/distrax/meta.yaml
Labels: staged-recipes, review-requested, python

#24396 adds `r-spam64`
  recipes/r-spam64/bld.bat
  recipes/r-spam64/build.sh
  recipes/r-spam64/meta.yaml
Labels: R, review-requested

#24401 build files for r-cmdstanr
  recipes/r-cmdstanr/bld.bat
  recipes/r-cmdstanr/build.sh
  recipes/r-cmdstanr/meta.yaml
Labels: R, review-requested

#24393 Add Fscan python package
  recipes/fscan/meta.yaml
Labels: staged-recipes, review-requested

#24405 Add ethos_penalps recipe
  recipes/ethos_penalps/meta.yaml
Labels: review-requested, python

#24394 Add djangorestframework-guardian2 python package
  recipes/djangorestframework-guardian2/meta.yaml
Labels: review-requested, python

#24414 add splito
  recipes/splito/meta.yaml
Labels: review-requested, python

#24397 Add recipe for `ribasim`
  recipes/ribasim/meta.yaml
Labels: review-requested, python

#24400 add `r-nlmixr2` and supporting dependencies
  recipes/r-nlmixr2/bld.bat
  recipes/r-nlmixr2/build.sh
  recipes/r-nlmixr2/meta.yaml
  recipes/r-nlmixr2data/bld.bat
  recipes/r-nlmixr2data/build.sh
  recipes/r-nlmixr2data/meta.yaml
  recipes/r-nlmixr2est/bld.bat
  recipes/r-nlmixr2est/build.sh
  recipes/r-nlmixr2est/meta.yaml
  recipes/r-nlmixr2extra/bld.bat
  recipes/r-nlmixr2extra/build.sh
  recipes/r-nlmixr2extra/meta.yaml
  recipes/r-nlmixr2plot/bld.bat
  recipes/r-nlmixr2plot/build.sh
  recipes/r-nlmixr2plot/meta.yaml
  recipes/r-xgxr/bld.bat
  recipes/r-xgxr/build.sh
  recipes/r-xgxr/meta.yaml
Labels: R, review-requested

#24309 adding recipe for r-jmbayes2via conda_r_skeleton_helper
  recipes/r-jmbayes2/bld.bat
  recipes/r-jmbayes2/build.sh
  recipes/r-jmbayes2/meta.yaml
Labels: R, review-requested

#24416 Adding types-lxml
  recipes/types-lxml/meta.yaml
Labels: review-requested, python

#24355 added recipe for zope.sqlalchemy
  recipes/zope.sqlalchemy/meta.yaml
Labels: review-requested, python

#24399 Adding PyHeatDemand Recipe
  recipes/pyheatdemand/meta.yaml
Labels: review-requested, python

#24428 Add nomad-camels-driver
  recipes/nomad-camels-driver-PID/meta.yaml
  recipes/nomad-camels-driver-agilent-34401a/meta.yaml
  recipes/nomad-camels-driver-demo-instrument/meta.yaml
  recipes/nomad-camels-driver-keithley-2000/meta.yaml
  recipes/nomad-camels-driver-keithley-220/meta.yaml
  recipes/nomad-camels-driver-keithley-237/meta.yaml
  recipes/nomad-camels-driver-keysight-b2912a/meta.yaml
  recipes/nomad-camels-driver-keysight-e5270b/meta.yaml
  recipes/nomad-camels-driver-ni-daq/meta.yaml
  recipes/nomad-camels-driver-voltcraft-pps/meta.yaml
Labels: staged-recipes, review-requested

#24426 Add canopen and pytrinamic
  recipes/canopen/meta.yaml
  recipes/pytrinamic/meta.yaml
Labels: staged-recipes, review-requested

#24424 Add dagster-libs 0.21.6
  recipes/dagster-libs/meta.yaml
Labels: staged-recipes, review-requested, python

#24421 add recipe for pandora-geno
  recipes/pandora-geno/meta.yaml
Labels: review-requested, python

#23813 add anyscale
  recipes/anyscale/meta.yaml
Labels: review-requested, python

#24423 add coreforecast
  recipes/coreforecast/LICENSE
  recipes/coreforecast/meta.yaml
  recipes/coreforecast/test_scalers.py
Labels: staged-recipes, review-requested

#24430 add pywinbox v0.3
  recipes/pymonctl/conda-forge.yml
  recipes/pymonctl/meta.yaml
  recipes/pymonctl/yum_requirements.txt
  recipes/pywinbox/conda-forge.yml
  recipes/pywinbox/meta.yaml
  recipes/pywinbox/yum_requirements.txt
  recipes/pywinctl/conda-forge.yml
  recipes/pywinctl/meta.yaml
  recipes/pywinctl/yum_requirements.txt
Labels: review-requested, python

#24439 ENH add umachine-pyio
  recipes/umachine-pyio/meta.yaml
Labels: staged-recipes, review-requested

#24383 Add containers-sugar package
  recipes/containers-sugar/meta.yaml
Labels: review-requested, python

#24443 Add rio-vrt receipt
  recipes/rio-vrt/LICENSE
  recipes/rio-vrt/meta.yaml
Labels: review-requested, python

#24442 Adding PyET
  recipes/pyet/meta.yaml
Labels: review-requested, python

#24382 Add makim package
  recipes/makim/meta.yaml
Labels: review-requested, python

#24446 CI register without cirun
  .github/workflows/scripts/create_feedstocks.py
Labels: staged-recipes, review-requested

#24456 Add lonboard package
  recipes/lonboard/meta.yaml
Labels: review-requested, python

#24455 Adding napari-trackpy
  recipes/napari-trackpy/meta.yaml
  recipes/napari-trackpy/yum_requirements.txt
Labels: staged-recipes, review-requested

#24450 add opera-utils
  recipes/opera-utils/meta.yaml
Labels: review-requested, python

#24460 Add recipe for pyarrow-hotfix
  recipes/pyarrow-hotfix/meta.yaml
Labels: staged-recipes, review-requested

#24459 Add globus-identity-mapping
  recipes/globus-identity-mapping/meta.yaml
Labels: staged-recipes, review-requested

#24461 Add tosholi
  recipes/tosholi/meta.yaml
Labels: staged-recipes, review-requested

#24462 Add `primod` to conda-forge
  recipes/primod/meta.yaml
Labels: review-requested, python

#24463 Add dask-databricks
  recipes/dask-databricks/meta.yaml
Labels: review-requested, python

#24464 add lenskit-implicit package
  recipes/lenskit-implicit/meta.yaml
Labels: review-requested, python

#24468 Recipe for pdflatex
  recipes/pdflatex/meta.yaml
Labels: review-requested, python

#24465 ADD: Add arm-test-data recipe
  recipes/arm-test-data/meta.yaml
Labels: review-requested, python

#24376 add napari-locan-0.1.0
  recipes/napari-locan/meta.yaml
  recipes/napari-locan/yum_requirements.txt
Labels: staged-recipes, review-requested

#24475 add rst2text
  recipes/rst2txt/meta.yaml
Labels: staged-recipes, review-requested, python

#24479 add meeko
  recipes/meeko/meta.yaml
Labels: review-requested, python

#24482 Add clusterX
  recipes/clusterx/meta.yaml
Labels: staged-recipes, review-requested

#24474 add zernike
  recipes/zernike/meta.yaml
Labels: review-requested, python

#24481 Add `ribasim-api` to conda-forge
  recipes/ribasim-api/meta.yaml
Labels: review-requested, python

#22016 Add pysirius client to conda-forge
  recipes/pysirius/Kaempferol.ms
  recipes/pysirius/LICENSE.txt
  recipes/pysirius/meta.yaml
  recipes/pysirius/test_script.bat
  recipes/pysirius/test_script.py
  recipes/pysirius/test_script.sh
Labels: staged-recipes, review-requested

#24432 add pydmd
  recipes/PyDMD/meta.yaml
Labels: staged-recipes, review-requested

#24413 Add recipie for package nrel.routee.compass
  recipes/nrel-routee-compass/LICENSE.txt
  recipes/nrel-routee-compass/meta.yaml
Labels: review-requested, python

#24486 Add aioresponses
  recipes/aioresponses/meta.yaml
Labels: review-requested, python

#24435 Add presto-server
  recipes/presto-server/meta.yaml
Labels: review-requested, java

#24492 add pytest-copie package
  recipes/pytest-copie/meta.yaml
Labels: review-requested, python

#24494 Add recipe for python-localvenv-kernel
  recipes/python-localvenv-kernel/meta.yaml
Labels: review-requested, python

#24491 Add pyGSTi recipe
  recipes/pygsti/meta.yaml
Labels: staged-recipes, review-requested, python

#24501 Adding pysnirf2
  recipes/snirf/meta.yaml
Labels: review-requested, python

#24503 Add channels_redis
  recipes/channels_redis/meta.yaml
Labels: review-requested, python

#24411 Adding actflow package
  recipes/actflow/LICENSE
  recipes/actflow/meta.yaml
  recipes/wbplot/LICENSE.txt
  recipes/wbplot/meta.yaml
Labels: staged-recipes, review-requested

#24507 Add rubin-scheduler
  recipes/rubin-scheduler/meta.yaml
Labels: review-requested, python

#24500 Add HoloNote recipe
  recipes/holonote/meta.yaml
Labels: review-requested, python

#24452 Add waterdynamics recipe
  recipes/waterdynamics/meta.yaml
Labels: review-requested, python

#24453 Add pathsimanalysis recipe
  recipes/pathsimanalysis/meta.yaml
Labels: review-requested, python

#24490 Add `flowermd`
  recipes/flowermd/meta.yaml
Labels: review-requested, python

#24510 Adding 'reconciliation'
  recipes/reconciliation/meta.yaml
Labels: review-requested, python

#24511 Adding edfio
  recipes/edfio/meta.yaml
Labels: review-requested, python

#24514 Add stk
  recipes/atomlite/meta.yaml
  recipes/mchammer/LICENSE
  recipes/mchammer/meta.yaml
  recipes/spindry/meta.yaml
  recipes/stk/meta.yaml
  recipes/vabene/license
  recipes/vabene/meta.yaml
Labels: staged-recipes, review-requested

#24518 Add pyformlang
  recipes/pyformlang/meta.yaml
Labels: review-requested, python

#24476 add `uuid-utils`
  recipes/uuid-utils/bld.bat
  recipes/uuid-utils/build.sh
  recipes/uuid-utils/meta.yaml
Labels: review-requested, python

#24525 Add matsubplots
  recipes/matsubplots/meta.yaml
Labels: review-requested, python

#24526 Add unpaddedbase64 recipe
  recipes/unpaddedbase64/meta.yaml
Labels: staged-recipes, review-requested

#24265 Add initial recipe for Hurl
  recipes/hurl/bld.bat
  recipes/hurl/build.sh
  recipes/hurl/meta.yaml
Labels: staged-recipes, review-requested

#23471 Add spatialdata recipe
  recipes/spatialdata/meta.yaml
Labels: staged-recipes, review-requested

#24377 Add napari-simpleannotate recipe
  recipes/napari-simpleannotate/meta.yaml
  recipes/napari-simpleannotate/yum_requirements.txt
Labels: staged-recipes, review-requested

#24495 Add nap-plot-tools recipe
  recipes/nap-plot-tools/meta.yaml
  recipes/nap-plot-tools/yum_requirements.txt
Labels: staged-recipes, review-requested

#24319 Add roocs-grids
  recipes/roocs-grids/meta.yaml
Labels: review-requested, python

#20849 Add napari-splinedist recipe
  recipes/napari-splinedist/meta.yaml
  recipes/napari-splinedist/yum_requirements.txt
Labels: staged-recipes, review-requested

#19756 Add napari-lf recipe
  recipes/napari-lf/meta.yaml
  recipes/napari-lf/yum_requirements.txt
Labels: staged-recipes, review-requested

#19677 Add napari-aideveloper recipe
  recipes/napari-aideveloper/meta.yaml
  recipes/napari-aideveloper/warnings.patch
  recipes/napari-aideveloper/yum_requirements.txt
Labels: staged-recipes, review-requested

#23744 Add large-image-viewer recipe
  recipes/large-image-viewer/meta.yaml
  recipes/large-image-viewer/yum_requirements.txt
Labels: staged-recipes, review-requested

#24127 Add napari-rembg recipe
  recipes/napari-rembg/meta.yaml
  recipes/napari-rembg/yum_requirements.txt
Labels: staged-recipes, review-requested

#24270 Add brainrender-napari recipe
  recipes/brainrender-napari/meta.yaml
  recipes/brainrender-napari/yum_requirements.txt
Labels: staged-recipes, review-requested

#24227 Add napari-microtubule-analyzer recipe
  recipes/napari-microtubule-analyzer/meta.yaml
  recipes/napari-microtubule-analyzer/yum_requirements.txt
Labels: staged-recipes, review-requested

#24436 Add set-calibration recipe
  recipes/set-calibration/meta.yaml
  recipes/set-calibration/yum_requirements.txt
Labels: staged-recipes, review-requested

#24403 Add napari-annotation-project recipe
  recipes/napari-annotation-project/meta.yaml
  recipes/napari-annotation-project/yum_requirements.txt
Labels: staged-recipes, review-requested

#24129 Add ufish recipe
  recipes/ufish/meta.yaml
  recipes/ufish/setup.patch
Labels: staged-recipes, review-requested

#24448 Add python-blosc2 recipe
  recipes/blosc2/0001-Add-imported-target-with-pkg-config-to-support-windo.patch
  recipes/blosc2/bld.bat
  recipes/blosc2/build.sh
  recipes/blosc2/meta.yaml
  recipes/blosc2/run_test.py
Labels: staged-recipes, review-requested

#24451 Add napari-guitils recipe
  recipes/napari-guitils/meta.yaml
Labels: staged-recipes, review-requested

#24434 Add napari-melt-pool-tracker recipe
  recipes/napari-melt-pool-tracker/meta.yaml
  recipes/napari-melt-pool-tracker/yum_requirements.txt
Labels: staged-recipes, review-requested

#17857 Add zarpaint recipe
  recipes/zarpaint/meta.yaml
  recipes/zarpaint/yum_requirements.txt
Labels: staged-recipes, review-requested

#21218 Add napari-bud-cell-segmenter recipe
  recipes/napari-bud-cell-segmenter/meta.yaml
  recipes/napari-bud-cell-segmenter/yum_requirements.txt
Labels: staged-recipes, review-requested

#23187 Add napari-labelprop recipe
  recipes/napari-labelprop/meta.yaml
  recipes/napari-labelprop/yum_requirements.txt
Labels: staged-recipes, review-requested

#24437 Add brainglobe-segmentation recipe
  recipes/brainglobe-segmentation/meta.yaml
  recipes/brainglobe-segmentation/yum_requirements.txt
Labels: staged-recipes, review-requested

#24472 Adding horovod
  recipes/horovod/build.sh
  recipes/horovod/conda_build_config.yaml
  recipes/horovod/meta.yaml
Labels: review-requested, python-c

#24538 Add recipe for `backports.strenum`
  recipes/backports.strenum/meta.yaml
Labels: review-requested, python

#24126 Add napari-ufish recipe
  recipes/napari-ufish/meta.yaml
  recipes/napari-ufish/yum_requirements.txt
Labels: staged-recipes, review-requested

#24527 Add aiohttp-socks recipe
  recipes/aiohttp-socks/meta.yaml
Labels: staged-recipes, review-requested

#24447 Add iohub recipe
  recipes/iohub/meta.yaml
Labels: staged-recipes, review-requested

#22333 initial commit of my hspf_utils for some analysis utilities for HSPF
  recipes/hspf_utils/meta.yaml
Labels: Awaiting author contribution, python

#23806 Add dydx-v3-python
  recipes/dydx-v3-python/meta.yaml
Labels: Awaiting author contribution, python

#22713 Add dynamo-release
  recipes/dynamo-release/meta.yaml
Labels: Awaiting author contribution, python

#24541 Add folium-pmtiles package
  recipes/folium-pmtiles/meta.yaml
Labels: review-requested, python

#24508 Adding cif2hkl
  recipes/cif2hkl/build.sh
  recipes/cif2hkl/meta.yaml
Labels: staged-recipes, review-requested

#24532 Add Broh5: browser-based GUI HDF Viewer in Python
  recipes/broh5/meta.yaml
Labels: review-requested, python

#24471 Add r-pim using the conda-forge-r-helper script
  recipes/r-pim/bld.bat
  recipes/r-pim/build.sh
  recipes/r-pim/meta.yaml
Labels: R, review-requested

#24547 Adding pyDOE3
  recipes/pydoe3/meta.yaml
Labels: review-requested, python

#24425 Add openawsem
  recipes/openawsem/meta.yaml
Labels: review-requested, python

#24546 Add sphinx-simplepdf
  recipes/sphinx-simplepdf/meta.yaml
Labels: review-requested, python

#24552 Add recipe for gurobi-logtools
  recipes/gurobi-logtools/meta.yaml
Labels: review-requested, python

#24554 Add vizent
  recipes/vizent/meta.yaml
Labels: review-requested, python

#22638 Add atomic-counter
  recipes/atomic-counter/meta.yaml
Labels: review-requested, python-c, rust

#24557 adding nbcx
  recipes/nbcx/meta.yaml
Labels: review-requested, python

#24563 Added locate as a package
  recipes/locate/meta.yaml
Labels: staged-recipes, review-requested

#24570 Add nomad-camels
  recipes/nomad-camels/meta.yaml
Labels: staged-recipes, review-requested

#24573 Add nomad-camels-driver
  recipes/nomad-camels-driver-cam-control-pylablib/meta.yaml
  recipes/nomad-camels-driver-keithley-2400/meta.yaml
  recipes/nomad-camels-driver-mechonics-cu30cl/meta.yaml
  recipes/nomad-camels-driver-swabianinstruments-timetagger/meta.yaml
  recipes/nomad-camels-driver-thorlabs-K10CR1/meta.yaml
  recipes/nomad-camels-driver-thorlabs-MFF/meta.yaml
  recipes/nomad-camels-driver-thorlabs-TLPM/meta.yaml
  recipes/nomad-camels-driver-trinamic-tmcm-1110/meta.yaml
Labels: staged-recipes, review-requested

#24577 add polaris
  recipes/polaris-lib/meta.yaml
Labels: review-requested, python

#24578 Add docstring_parser_fork
  recipes/docstring_parser_fork/meta.yaml
Labels: staged-recipes, review-requested

#22566 Adding cbcflow to conda-forge
  recipes/cbcflow/meta.yaml
Labels: review-requested, python

#24583 add linmarg package
  recipes/linmarg/meta.yaml
Labels: review-requested, python

#23931 Add feedstock for qdoas
  recipes/qdoas/bld.bat
  recipes/qdoas/build.sh
  recipes/qdoas/meta.yaml
  recipes/qdoas/yum_requirements.txt
Labels: staged-recipes, review-requested

#24587 add dace-query python package (PyPI)
  recipes/dace-query/LICENSE
  recipes/dace-query/meta.yaml
Labels: review-requested, python

#24580 Adding `climate4r.hub`
  recipes/r-climate4r.hub/bld.bat
  recipes/r-climate4r.hub/build.sh
  recipes/r-climate4r.hub/conda_build_config.yaml
  recipes/r-climate4r.hub/meta.yaml
Labels: R, review-requested

#24584 Adding medenv package published on pypi
  recipes/medenv/meta.yaml
Labels: review-requested, python

#24588 Add recipe for the stream-zip Python package from PyPI
  recipes/stream-zip/meta.yaml
Labels: review-requested, python

#24585 Add conway-polynomials
  recipes/conway-polynomials/meta.yaml
Labels: review-requested, python

#24592 Add dbbot-sqlalchemy recipe
  recipes/dbbot-sqlalchemy/LICENSE.txt
  recipes/dbbot-sqlalchemy/meta.yaml
Labels: review-requested, python

#24593 Add gravis recipe)
  recipes/gravis/meta.yaml
Labels: review-requested, python

#24497 Adding recipe for smqtk-core
  recipes/smqtk-core/meta.yaml
Labels: review-requested, python

#24591 Adding the vertica_highcharts project to conda-forge
  LICENSE
  recipes/vertica_highcharts/meta.yaml
Labels: review-requested, python

#23785 Adding filepattern
  recipes/filepattern/bld.bat
  recipes/filepattern/build.sh
  recipes/filepattern/meta.yaml
Labels: review-requested, c-cpp, python, python-c

#23376 Add pipefunc
  recipes/pipefunc/meta.yaml
Labels: review-requested, python

#24605 Adding 'lbcharmdb' package to conda-forge
  recipes/lbcharmdb/meta.yaml
Labels: staged-recipes, review-requested

#24187 Add mcstas
  recipes/mcstas/install-files-core.sh
  recipes/mcstas/install-files-data.bat
  recipes/mcstas/install-files-data.sh
  recipes/mcstas/meta.yaml
  recipes/mcstas/test_pkg.py
Labels: staged-recipes, review-requested

#24280 Add dynare preprocessor executable only.
  recipes/dynare_preprocessor/build.sh
  recipes/dynare_preprocessor/example1.mod
  recipes/dynare_preprocessor/meta.yaml
  recipes/dynare_preprocessor/run_test.sh
Labels: Awaiting author contribution, c-cpp

#24629 Add flake8-debugger
  recipes/flake8-debugger/LICENCE
  recipes/flake8-debugger/meta.yaml
Labels: staged-recipes, review-requested

#24628 Add Flake8-Executable
  recipes/flake8-executable/meta.yaml
Labels: staged-recipes, review-requested

#24598 Adding, again, `c4r-calibrator`
  recipes/r-c4r-calibrator/bld.bat
  recipes/r-c4r-calibrator/build.sh
  recipes/r-c4r-calibrator/conda_build_config.yaml
  recipes/r-c4r-calibrator/meta.yaml
Labels: R, review-requested
