Repository conda-forge/staged-recipes, pull requests merged in 2024-04, with the labels that each got.

#25927 Add phytreeviz
  recipes/phytreeviz/meta.yaml
Labels: review-requested, python

#25921 Adding antmocdata and baseopt
  recipes/antmocdata/meta.yaml
  recipes/baseopt/meta.yaml
Labels: staged-recipes, review-requested, python

#25924 Add repo-review
  recipes/repo-review/meta.yaml
Labels: review-requested, python

#25916 Opentelemetry exporter gcp trace
  recipes/opentelemetry-exporter-gcp-monitoring/meta.yaml
  recipes/opentelemetry-exporter-gcp-trace/meta.yaml
  recipes/opentelemetry-resourcedetector-gcp/meta.yaml
Labels: review-requested, python

#25532 Add CAD_to_OpenMC surface mesh creation package.
  recipes/cad-to-openmc/7pin.step
  recipes/cad-to-openmc/meta.yaml
  recipes/cad-to-openmc/yum_requirements.txt
Labels: review-requested, python

#24887 Adding hishel
  recipes/hishel/meta.yaml
Labels: review-requested, python

#25915 Add opentelemetry-propagator-gcp
  recipes/opentelemetry-propagator-gcp/meta.yaml
Labels: review-requested, python

#25709 Added getdaft as a package
  recipes/getdaft/conda_build_config.yaml
  recipes/getdaft/meta.yaml
Labels: R, review-requested, rust

#25883 Add Rollup
  recipes/rollup/build.sh
  recipes/rollup/conda_build_config.yaml
  recipes/rollup/meta.yaml
Labels: nodejs, R, review-requested, c-cpp, rust

#25890 add cargo-feature
  recipes/cargo-feature/bld.bat
  recipes/cargo-feature/build.sh
  recipes/cargo-feature/conda_build_config.yaml
  recipes/cargo-feature/meta.yaml
Labels: R, review-requested, rust

#24782 Adding mdsapt
  recipes/mdsapt/meta.yaml
Labels: staged-recipes, review-requested, python

#25891 add pyQParamWidget package
  recipes/pyQParamWidget/meta.yaml
  recipes/pyQParamWidget/yum_requirements.txt
Labels: review-requested, python

#25918 add gemviz package
  recipes/gemviz/meta.yaml
  recipes/gemviz/yum_requirements.txt
Labels: review-requested, python

#25930 Add django-structlog
  recipes/django-structlog/meta.yaml
Labels: review-requested, python

#25936 Add vastdb
  recipes/vastdb/meta.yaml
Labels: review-requested, python

#25937 Add sp repo review
  recipes/sp-repo-review/meta.yaml
Labels: review-requested, python

#25278 Add trame-jupyter-extension recipe
  recipes/trame-jupyter-extension/LICENSE
  recipes/trame-jupyter-extension/meta.yaml
Labels: staged-recipes, review-requested, python

#25945 Add django-health-check
  recipes/django-health-check/meta.yaml
Labels: review-requested, python

#25838 add langchain-experimental
  recipes/langchain-experimental/meta.yaml
Labels: review-requested, python

#25824 add-ipfsspec
  recipes/ipfsspec/meta.yaml
Labels: review-requested, python

#25942 Add mujs
  recipes/mujs/build.sh
  recipes/mujs/make.patch
  recipes/mujs/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#25940 Adding quasielasticbayes
  recipes/quasielasticbayes/conda_build_config.yaml
  recipes/quasielasticbayes/meta.yaml
Labels: review-requested, python

#25594 Adding eatpy
  recipes/eatpy/bld.bat
  recipes/eatpy/build.sh
  recipes/eatpy/conda_build_config.yaml
  recipes/eatpy/cross-linux.cmake
  recipes/eatpy/datetime.patch
  recipes/eatpy/ersem.patch
  recipes/eatpy/meta.yaml
Labels: review-requested, python

#25946 Add mlcroissant
  recipes/jsonpath-rw/LICENSE
  recipes/jsonpath-rw/meta.yaml
  recipes/mlcroissant/LICENSE.md
  recipes/mlcroissant/meta.yaml
Labels: staged-recipes, review-requested, python

#25933 Adding DDOutlier R package from CRAN
  recipes/r-ddoutlier/bld.bat
  recipes/r-ddoutlier/build.sh
  recipes/r-ddoutlier/meta.yaml
Labels: R, staged-recipes, review-requested

#25949 Add StructLog-GCP
  recipes/structlog-gcp/meta.yaml
Labels: review-requested, python

#25950 add fair package
  recipes/fair/meta.yaml
Labels: review-requested, python

#25963 Add e3x
  recipes/e3x/meta.yaml
Labels: staged-recipes, review-requested, python

#25959 Added pydumpling as a package
  recipes/pydumpling/meta.yaml
Labels: staged-recipes, review-requested, python

#25958 Added django-prose-editor as a package
  recipes/django-prose-editor/meta.yaml
Labels: staged-recipes, review-requested, python

#25957 Added mermaid-py as a package
  recipes/mermaid-py/meta.yaml
Labels: staged-recipes, review-requested, python

#25955 Add metis-python
  recipes/metis-python/LICENSE.txt
  recipes/metis-python/meta.yaml
Labels: review-requested, python

#25954 Added r-report as a package
  recipes/r-report/bld.bat
  recipes/r-report/build.sh
  recipes/r-report/meta.yaml
Labels: R, staged-recipes, review-requested

#25939 Add erlab recipe
  recipes/erlab/meta.yaml
  recipes/erlab/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#25975 Add llmtuner
  recipes/galore-torch/meta.yaml
  recipes/galore-torch/requirements.patch
  recipes/llmtuner/meta.yaml
  recipes/trl/meta.yaml
Labels: staged-recipes, review-requested, python

#25960 Added pyromark as a package
  recipes/pyromark/conda_build_config.yaml
  recipes/pyromark/meta.yaml
Labels: R, staged-recipes, review-requested, python, rust

#25873 Add recipe for Helios++
  recipes/helios/conda_build_config.yaml
  recipes/helios/meta.yaml
Labels: review-requested, python-c

#25727 Add `libdispatch` package
  recipes/libdispatch/0001-glibc-unistd-wrapper.patch
  recipes/libdispatch/bld.bat
  recipes/libdispatch/build.sh
  recipes/libdispatch/conda_build_config.yaml
  recipes/libdispatch/meta.yaml
Labels: review-requested, c-cpp

#25131 add litestar 2.8.0
  recipes/litestar/meta.yaml
Labels: staged-recipes, review-requested, python

#25038 Add vale-spelling-*-en-dict
  recipes/vale-spelling-aoo-mozilla-en-dict/meta.yaml
  recipes/vale-spelling-aoo-mozilla-en-dict/test_spelling.py
  recipes/vale-spelling-aoo-mozilla-en-dict/write_rule.py
Labels: staged-recipes, review-requested, go, python

#25017 Add vale-styles-*
  recipes/vale-styles-alex/.vale.ini
  recipes/vale-styles-alex/bld.bat
  recipes/vale-styles-alex/build.sh
  recipes/vale-styles-alex/meta.yaml
  recipes/vale-styles-alex/run_test.py
  recipes/vale-styles-google/.vale.ini
  recipes/vale-styles-google/bld.bat
  recipes/vale-styles-google/build.sh
  recipes/vale-styles-google/meta.yaml
  recipes/vale-styles-google/run_test.py
  recipes/vale-styles-joblint/.vale.ini
  recipes/vale-styles-joblint/bld.bat
  recipes/vale-styles-joblint/build.sh
  recipes/vale-styles-joblint/meta.yaml
  recipes/vale-styles-joblint/run_test.py
  recipes/vale-styles-microsoft/.vale.ini
  recipes/vale-styles-microsoft/bld.bat
  recipes/vale-styles-microsoft/build.sh
  recipes/vale-styles-microsoft/meta.yaml
  recipes/vale-styles-microsoft/run_test.py
  recipes/vale-styles-proselint/.vale.ini
  recipes/vale-styles-proselint/bld.bat
  recipes/vale-styles-proselint/build.sh
  recipes/vale-styles-proselint/meta.yaml
  recipes/vale-styles-proselint/run_test.py
  recipes/vale-styles-readability/.vale.ini
  recipes/vale-styles-readability/bld.bat
  recipes/vale-styles-readability/build.sh
  recipes/vale-styles-readability/meta.yaml
  recipes/vale-styles-readability/run_test.py
  recipes/vale-styles-write-good/.vale.ini
  recipes/vale-styles-write-good/bld.bat
  recipes/vale-styles-write-good/build.sh
  recipes/vale-styles-write-good/meta.yaml
  recipes/vale-styles-write-good/run_test.py
Labels: staged-recipes, review-requested, go, python

#25978 Adding recipe for coded-flows a package in dev for a no-code app
  recipes/coded-flows/LICENSE
  recipes/coded-flows/meta.yaml
Labels: staged-recipes, review-requested, python

#25979 add backports.tarfile recipe
  recipes/backports.tarfile/meta.yaml
Labels: staged-recipes, review-requested

#25982 Add frictionless-ckan-mapper
  recipes/frictionless-ckan-mapper/meta.yaml
Labels: review-requested, python

#25778 Adding ponio
  recipes/ponio/bld.bat
  recipes/ponio/build.sh
  recipes/ponio/conda_build_config.yaml
  recipes/ponio/meta.yaml
Labels: review-requested, c-cpp

#25964 Add cargo-make
  recipes/cargo-make/bld.bat
  recipes/cargo-make/build.sh
  recipes/cargo-make/conda_build_config.yaml
  recipes/cargo-make/meta.yaml
Labels: R, review-requested, rust

#25910 Add recipe for gz-sim-yarp-plugins package
  recipes/gz-sim-yarp-plugins/activate.msh
  recipes/gz-sim-yarp-plugins/bld_cxx.bat
  recipes/gz-sim-yarp-plugins/build_cxx.sh
  recipes/gz-sim-yarp-plugins/conda_build_config.yaml
  recipes/gz-sim-yarp-plugins/deactivate.msh
  recipes/gz-sim-yarp-plugins/meta.yaml
  recipes/gz-sim-yarp-plugins/yum_requirements.txt
Labels: staged-recipes, review-requested, c-cpp

#25502 Add Upkie
  recipes/upkie/meta.yaml
Labels: review-requested, python

#25855 Shadie conda-forge recipe
  recipes/shadie/meta.yaml
Labels: review-requested, python

#25988 Add qlient and qlient-core
  recipes/qlient-core/meta.yaml
  recipes/qlient/meta.yaml
Labels: staged-recipes, review-requested, python

#25907 Add llama-index-readers-file
  recipes/llama-index-readers-file/meta.yaml
Labels: staged-recipes, review-requested, python

#25941 Add pulumi
  recipes/pulumi-sdks/build_pulumi_core.sh
  recipes/pulumi-sdks/build_pulumi_go.sh
  recipes/pulumi-sdks/build_pulumi_nodejs.sh
  recipes/pulumi-sdks/build_pulumi_python.sh
  recipes/pulumi-sdks/meta.yaml
Labels: staged-recipes, review-requested

#25935 Add adani recipe
  recipes/adani/meta.yaml
Labels: staged-recipes, review-requested, python, python-c

#26002 Add llama-index-cli
  recipes/llama-index-cli/LICENSE
  recipes/llama-index-cli/meta.yaml
Labels: staged-recipes, review-requested, python

#26005 Add llama-index-indices-managed-llama-cloud
  recipes/llama-index-indices-managed-llama-cloud/LICENSE
  recipes/llama-index-indices-managed-llama-cloud/meta.yaml
Labels: staged-recipes, review-requested, python

#26003 Add llama-index-readers-llama-parse
  recipes/llama-index-readers-llama-parse/LICENSE
  recipes/llama-index-readers-llama-parse/meta.yaml
  recipes/llama-parse/meta.yaml
Labels: staged-recipes, review-requested, python

#25993 Add marimo-labs
  recipes/marimo-labs/meta.yaml
Labels: review-requested, python

#26007 Add asaplib
  recipes/asaplib/LICENSE
  recipes/asaplib/meta.yaml
Labels: staged-recipes, review-requested, python

#26011 Add gauche
  recipes/gauche/meta.yaml
Labels: staged-recipes, review-requested, python

#25934 Add tmuxp and libtmux (noarch python)
  recipes/libtmux/conda-forge.yml
  recipes/libtmux/meta.yaml
  recipes/tmuxp/conda-forge.yml
  recipes/tmuxp/meta.yaml
  recipes/tmuxp/session.yaml
Labels: review-requested, python

#25972 Add neighpy recipe
  recipes/neighpy/meta.yaml
Labels: review-requested, python

#26018 Add chemiscope
  recipes/chemiscope/meta.yaml
Labels: staged-recipes, review-requested, python

#26019 Add dsms-sdk
  recipes/dsms-sdk/meta.yaml
Labels: staged-recipes, review-requested, python

#25606 Add MAFFT package
  recipes/mafft/build.sh
  recipes/mafft/meta.yaml
Labels: review-requested, c-cpp

#26000 Add mljar-scikit-plot
  recipes/mljar-scikit-plot/meta.yaml
Labels: staged-recipes, review-requested

#26021 Add pydefect
  recipes/pydefect/LICENSE
  recipes/pydefect/meta.yaml
  recipes/pydefect/requirements.patch
  recipes/vise/LICENSE
  recipes/vise/meta.yaml
  recipes/vise/requirements.patch
Labels: staged-recipes, review-requested, python

#26022 Add MoleculeACE
  recipes/moleculeace/LICENCE
  recipes/moleculeace/meta.yaml
  recipes/moleculeace/rdkit.patch
Labels: staged-recipes, review-requested, python

#26024 Asyncmock
  recipes/asyncmock/LICENSE
  recipes/asyncmock/meta.yaml
Labels: review-requested, python

#26025 Add multifutures
  recipes/multifutures/meta.yaml
Labels: review-requested, python

#26017 Create jinja_partials recipe
  recipes/jinja_partials/meta.yaml
Labels: review-requested, python

#26014 add sciencebasepy
  recipes/sciencebasepy/meta.yaml
Labels: staged-recipes, review-requested

#26031 Added r-easystats as a package
  recipes/r-easystats/bld.bat
  recipes/r-easystats/build.sh
  recipes/r-easystats/meta.yaml
Labels: R, staged-recipes, review-requested

#26037 Add apache-airflow-providers-fab
  recipes/apache-airflow-providers-fab/meta.yaml
Labels: review-requested, python

#26035 Package declare
  recipes/declare/meta.yaml
Labels: review-requested, python

#26039 Add maplibre package
  recipes/maplibre/meta.yaml
Labels: review-requested, python

#26029 new conda forge package cp2kdata
  recipes/cp2kdata/meta.yaml
Labels: staged-recipes, review-requested, python

#26043 add mkdocs-glightbox
  recipes/mkdocs-lightbox/LICENSE
  recipes/mkdocs-lightbox/meta.yaml
Labels: staged-recipes, review-requested, python

#26041 add ioos_metrics
  recipes/ioos_metrics/meta.yaml
Labels: staged-recipes, review-requested

#24634 Add regional-mom6
  recipes/regional-mom6/meta.yaml
Labels: staged-recipes, review-requested, python

#26042 Add pychromatic
  recipes/pychromatic/meta.yaml
Labels: staged-recipes, review-requested, python

#26034 Package fps-notebook
  recipes/fps-notebook/meta.yaml
Labels: review-requested, python

#26032 Added narwhals as a package
  recipes/narwhals/meta.yaml
Labels: staged-recipes, review-requested, python

#25863 Add carlsim6
  recipes/carlsim6/LICENSE_CUDA_SAMPLES
  recipes/carlsim6/bld.bat
  recipes/carlsim6/build.sh
  recipes/carlsim6/cuda-samples/exception.h
  recipes/carlsim6/cuda-samples/helper_cuda.h
  recipes/carlsim6/cuda-samples/helper_string.h
  recipes/carlsim6/cuda-samples/helper_timer.h
  recipes/carlsim6/fix-build.patch
  recipes/carlsim6/fix-clang.patch
  recipes/carlsim6/meta.yaml
Labels: review-requested, python-c

#25986 Add recipe for metatensor
  recipes/metatensor/bld.bat
  recipes/metatensor/build.sh
  recipes/metatensor/conda_build_config.yaml
  recipes/metatensor/meta.yaml
  recipes/metatensor/mktemp-mkdir.patch
Labels: R, review-requested, c-cpp, rust

#26020 add plotille
  recipes/plotille/meta.yaml
Labels: review-requested, python

#26055 adding geo-parameters
  recipes/geo-parameters/meta.yaml
Labels: review-requested, python

#26057 Added tetra as a package
  recipes/tetra/meta.yaml
Labels: staged-recipes, review-requested, python

#26050 Add tad-mctc package
  recipes/tad-mctc/meta.yaml
Labels: staged-recipes, review-requested, python

#25714 Adding echoregions
  recipes/echoregions/meta.yaml
Labels: staged-recipes, review-requested, python

#23864 Adding microgen
  recipes/microgen/meta.yaml
  recipes/microgen/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#25823 Add mypy-boto3-ssm
  recipes/mypy-boto3-ssm/meta.yaml
Labels: review-requested, python

#25822 Add mypy-boto3-ses
  recipes/mypy-boto3-ses/meta.yaml
Labels: review-requested, python

#26056 Add virushostinteractionpredictor recipe
  recipes/virushostinteractionpredictor/meta.yaml
Labels: review-requested, python

#26058 add raydar
  recipes/raydar/meta.yaml
Labels: review-requested, python

#25677 Adding diive package meta.yaml
  recipes/diive/meta.yaml
Labels: review-requested, python

#25787 Add labbench (python lab automation module)
  recipes/labbench/bld.bat
  recipes/labbench/build.sh
  recipes/labbench/meta.yaml
Labels: review-requested, python

#25909 Add PyGM
  recipes/pygm/meta.yaml
Labels: review-requested, python-c

#25998 Add recipe for Paicos
  recipes/paicos/meta.yaml
Labels: staged-recipes, review-requested, python-c

#25943 Add molbloom package
  recipes/molbloom/meta.yaml
Labels: review-requested, python-c

#25999 Create recipe for metaflow-netflixtext
  recipes/metaflow-netflixext/meta.yaml
Labels: staged-recipes, review-requested, python

#26063 add daggre
  recipes/daggre/meta.yaml
Labels: review-requested, python

#25929 Adding semsimian package from github source
  recipes/semsimian/conda_build_config.yaml
  recipes/semsimian/meta.yaml
Labels: review-requested, python

#26065 add pubmed-parser
  recipes/pubmed-parser/meta.yaml
Labels: review-requested, python

#26066 add graphdatascience
  recipes/graphdatascience/meta.yaml
Labels: review-requested, python

#25881 added mudirac recipe
  recipes/mudirac/build.sh
  recipes/mudirac/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#26045 add asapdiscovery package
  recipes/asapdiscovery/build.sh
  recipes/asapdiscovery/meta.yaml
Labels: review-requested, python

#26074 adding `sim-tools`
  recipes/sim-tools/meta.yaml
Labels: review-requested, python

#26075 Adding agilent-format
  recipes/agilent-format/meta.yaml
Labels: review-requested, python

#26077 Add recipe for bmi_dbseabed
  recipes/bmi_dbseabed/meta.yaml
Labels: staged-recipes, review-requested, python

#26089 Add yandex-query-client
  recipes/yandex-query-client/0001-remove-typing.patch
  recipes/yandex-query-client/meta.yaml
Labels: review-requested, python

#26096 Add hypercoast package
  recipes/hypercoast/meta.yaml
Labels: review-requested, python

#26099 add streamlit-vis-timeline
  recipes/streamlit-vis-timeline/meta.yaml
Labels: review-requested, python

#26072 Adding recipe r-kdetrees
  recipes/r-kdetrees/bld.bat
  recipes/r-kdetrees/build.sh
  recipes/r-kdetrees/meta.yaml
Labels: R, review-requested

#26095 Added recipe for langchain-aws package
  recipes/langchain-aws/meta.yaml
Labels: review-requested, python

#26102 add ewmh
  recipes/ewmh/meta.yaml
Labels: review-requested, python

#26106 Add bert-extractive-summarizer
  recipes/bert-extractive-summarizer/meta.yaml
Labels: review-requested, python

#26105 add `instructor`
  recipes/instructor/meta.yaml
Labels: review-requested, python

#26054 adding smoothr
  recipes/r-smoothr/bld.bat
  recipes/r-smoothr/build.sh
  recipes/r-smoothr/meta.yaml
  recipes/r-smoothr/testthat.R
  recipes/r-smoothr/testthat/test_drop-crumbs.R
  recipes/r-smoothr/testthat/test_fill-holes.R
  recipes/r-smoothr/testthat/test_smooth-chaikin.R
  recipes/r-smoothr/testthat/test_smooth-densify.R
  recipes/r-smoothr/testthat/test_smooth-ksmooth.R
  recipes/r-smoothr/testthat/test_smooth-spline.R
  recipes/r-smoothr/testthat/test_smooth.r
Labels: R, review-requested

#26113 Add `mkdocs-get-deps`
  recipes/mkdocs-get-deps/meta.yaml
Labels: review-requested, python

#26115 Add ewmhlib
  recipes/ewmhlib/meta.yaml
  recipes/ewmhlib/yum_requirements.txt
Labels: review-requested, python

#26123 Add recipe for linkchecker
  recipes/linkcheckmd/meta.yaml
Labels: review-requested, python

#26103 add pypeec recipe
  recipes/pypeec/meta.yaml
  recipes/pypeec/yum_requirements.txt
Labels: review-requested, python

#26127 Create meta.yaml for wellapplication
  recipes/wellapplication/meta.yaml
Labels: review-requested, python

#26120 Adding sqlean.py
  recipes/sqlean.py/LICENSE
  recipes/sqlean.py/meta.yaml
  recipes/sqlean.py/run_test.py
Labels: review-requested, python

#24542 Adding RadGEEToolbox recipe
  recipes/radgeetoolbox/meta.yaml
Labels: staged-recipes, review-requested, python

#26128 recipes for zodiax and dlux
  recipes/dlux/meta.yaml
  recipes/zodiax/meta.yaml
Labels: review-requested, python

#26133 Added nodify python package
  recipes/nodify/meta.yaml
Labels: review-requested, python

#26135 initial version autocron
  recipes/autocron/meta.yaml
Labels: review-requested, python

#26087 [NOARCH] Add a recipe for helios-menuinst
  recipes/helios-menuinst/meta.yaml
  recipes/helios-menuinst/src/LICENSE.md
  recipes/helios-menuinst/src/menu.json
Labels: review-requested, python

#26137 Add data2rdf
  recipes/chowlk-unofficial-fork/meta.yaml
  recipes/data2rdf/meta.yaml
Labels: staged-recipes, review-requested, python

#26141 Adding QCManyBody
  recipes/qcmanybody/meta.yaml
Labels: review-requested, python

#26143 Added dliswriter package
  recipes/dliswriter/meta.yaml
Labels: staged-recipes, review-requested, python

#26138 Add orgparse.
  recipes/orgparse/meta.yaml
Labels: staged-recipes, review-requested, python

#26122 adding r-predicts to conda-forge
  recipes/r-predicts/bld.bat
  recipes/r-predicts/build.sh
  recipes/r-predicts/meta.yaml
Labels: R, review-requested

#26151 Added jinja2-humanize-extension
  recipes/jinja2-humanize-extension/meta.yaml
Labels: review-requested, python

#26150 Add tad-multicharge package
  recipes/tad-multicharge/meta.yaml
Labels: staged-recipes, review-requested, python

#26082 Add recipe for `atlasgo`
  recipes/atlasgo/bld.bat
  recipes/atlasgo/build.sh
  recipes/atlasgo/conda_build_config.yaml
  recipes/atlasgo/meta.yaml
Labels: staged-recipes, review-requested, go

#26080 Add recipe for `sqlx-cli`
  recipes/sqlx-cli/bld.bat
  recipes/sqlx-cli/build.sh
  recipes/sqlx-cli/conda_build_config.yaml
  recipes/sqlx-cli/meta.yaml
Labels: R, review-requested, rust

#26153 Add tad-dftd3 package
  recipes/tad-dftd3/meta.yaml
Labels: staged-recipes, review-requested, python

#26152 Add tad-dftd4 package
  recipes/tad-dftd4/meta.yaml
Labels: staged-recipes, review-requested, python

#26101 Add papi
  recipes/papi/build.sh
  recipes/papi/conda_build_config.yaml
  recipes/papi/meta.yaml
Labels: review-requested, c-cpp

#25567 Add label-studio-sdk
  recipes/label-studio-sdk/meta.yaml
  recipes/label-studio-sdk/setup-py.patch
Labels: review-requested, python

#26079 Add recipe for pymt_dbseabed
  recipes/pymt_dbseabed/meta.yaml
Labels: staged-recipes, review-requested, python

#26146 Add cpptrace
  recipes/cpptrace/build.sh
  recipes/cpptrace/meta.yaml
  recipes/cpptrace/patches/0001-libdwarf-patches.patch
  recipes/cpptrace/test/CMakeLists.txt
  recipes/cpptrace/test/main.cpp
Labels: review-requested, c-cpp

#26129 Add new recipe for pygsheets package - useful for interacting with Google sheets
  recipes/pygsheets/meta.yaml
Labels: review-requested, python

#26130 Add new recipe for python csaps package
  recipes/csaps/meta.yaml
Labels: review-requested, python

#26139 add cads-api-client
  recipes/cads-api-client/meta.yaml
Labels: review-requested, python

#26126 Adding recipe for jax-finufft
  recipes/jax-finufft/conda_build_config.yaml
  recipes/jax-finufft/meta.yaml
Labels: review-requested, python-c

#26088 Add recipe for egobox
  recipes/egobox/conda_build_config.yaml
  recipes/egobox/meta.yaml
Labels: R, review-requested, python, rust

#26160 Added packaging-legacy as a package
  recipes/packaging-legacy/meta.yaml
Labels: staged-recipes, review-requested, python
