Repository conda-forge/staged-recipes, pull requests merged in 2024-02, with the labels that each got.

#25189 Added loopdesigner
  recipes/loopdesigner/meta.yaml
  recipes/loopdesigner/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#25185 Added interactivefitting
  recipes/interactivefitting/meta.yaml
  recipes/interactivefitting/yum_requirements.txt
Labels: Awaiting author contribution, staged-recipes, python

#25163 Add ndx-pose
  recipes/ndx-pose/meta.yaml
Labels: review-requested, python

#25172 Add grape and dependencies
  recipes/ddd_subplots/meta.yaml
  recipes/ddd_subplots/yum_requirements.txt
  recipes/embiggen/meta.yaml
  recipes/grape/meta.yaml
  recipes/keras_mixed_sequence/LICENSE
  recipes/keras_mixed_sequence/meta.yaml
  recipes/sanitize_ml_labels/LICENSE
  recipes/sanitize_ml_labels/meta.yaml
Labels: review-requested, python

#25139 Add Recipe for TJPCov
  recipes/tjpcov/meta.yaml
Labels: staged-recipes, review-requested, python

#25206 Add dirtyjson
  recipes/dirtyjson/meta.yaml
Labels: staged-recipes, review-requested

#22495 Add seasocks
  recipes/seasocks/build.sh
  recipes/seasocks/meta.yaml
  recipes/seasocks/test/CMakeLists.txt
  recipes/seasocks/test/main.cpp
Labels: review-requested, c-cpp

#23896 Add logtalk-jupyter-kernel recipe
  recipes/logtalk-jupyter-kernel/meta.yaml
Labels: review-requested, python

#24068 Adding mwparserfromhell
  recipes/mwparserfromhell/meta.yaml
Labels: Awaiting author contribution, review-requested, python

#24324 Update README.md
  README.md
Labels: staged-recipes, review-requested

#25207 add recipe for r-getip, using cran_r_skeleton_helper
  recipes/r-getip/bld.bat
  recipes/r-getip/build.sh
  recipes/r-getip/meta.yaml
Labels: R, review-requested

#23861 Add Robot Raconteur packages
  recipes/robotraconteur/bld.bat
  recipes/robotraconteur/build.sh
  recipes/robotraconteur/meta.yaml
  recipes/robotraconteur_companion/bld.bat
  recipes/robotraconteur_companion/build.sh
  recipes/robotraconteur_companion/meta.yaml
Labels: Awaiting author contribution, c-cpp

#24630 Add recipe for `jaxsim`
  recipes/jaxsim/meta.yaml
Labels: staged-recipes, review-requested, python

#24999 Add recipe for ZOSPy
  recipes/zospy/conda-forge.yml
  recipes/zospy/meta.yaml
Labels: review-requested, python

#25217 Add a recipe of `capsula` package
  recipes/capsula/meta.yaml
Labels: review-requested, python

#25215 add dvg-ringbuffer
  recipes/dvg-ringbuffer/meta.yaml
Labels: review-requested, python

#24889 Add recipe for bloaty
  recipes/bloaty/0001-Add-missing-stdexcept-include.patch
  recipes/bloaty/0001-Don-t-force-C-11.patch
  recipes/bloaty/build.sh
  recipes/bloaty/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#25218 Adding single-sample-gsea
  recipes/single-sample-gsea/meta.yaml
Labels: review-requested, python

#25222 Add django-flags
  recipes/django-flags/meta.yaml
Labels: review-requested, python

#25223 Add django-events-timetable
  recipes/django-events-timetable/meta.yaml
Labels: review-requested, python

#25221 Add wagtail-generic-chooser
  recipes/wagtail-generic-chooser/meta.yaml
Labels: review-requested, python

#25225 Add django-solo
  recipes/django-solo/meta.yaml
Labels: review-requested, python

#25226 Add Django-todo
  recipes/django-todo/meta.yaml
Labels: review-requested, python

#25229 Add bynder-sdk
  recipes/bynder-sdk/meta.yaml
Labels: review-requested, python

#25233 Add webstories
  recipes/webstories/meta.yaml
Labels: review-requested, python

#25230 Add heroicons
  recipes/heroicons/meta.yaml
Labels: review-requested, python

#25234 Add wagtail-app-pages
  recipes/wagtail-app-pages/meta.yaml
Labels: review-requested, python

#25236 Add wagtail-modeladmin
  recipes/wagtail-modeladmin/meta.yaml
Labels: review-requested, python

#25210 Adding repro-tarfile
  recipes/repro-tarfile/meta.yaml
Labels: review-requested, python

#25245 Add wagtailnews
  recipes/wagtailnews/meta.yaml
Labels: review-requested, python

#25242 Add wagtail-taggable
  recipes/wagtail-taggable/meta.yaml
Labels: review-requested, python

#25244 Add wagtailtables
  recipes/wagtailtables/meta.yaml
Labels: review-requested, python

#25243 Add wagtailstreamforms
  recipes/wagtailstreamforms/meta.yaml
Labels: review-requested, python

#25246 Add wagtailgridder
  recipes/wagtailgridder/meta.yaml
Labels: review-requested, python

#25248 Add wagtailcharts
  recipes/wagtailcharts/meta.yaml
Labels: review-requested, python

#25247 Add wagtailmedia
  recipes/wagtailmedia/meta.yaml
Labels: review-requested, python

#25249 Add wagtail-treemodeladmin
  recipes/wagtail-treemodeladmin/meta.yaml
Labels: review-requested, python

#25252 Add wagtail-themes
  recipes/wagtail-themes/meta.yaml
Labels: review-requested, python

#25251 Add wagtail-transfer
  recipes/wagtail-transfer/meta.yaml
Labels: review-requested, python

#25250 Add wagtail-trash
  recipes/wagtail-trash/meta.yaml
Labels: review-requested, python

#25254 Add wagtail-surveyjs
  recipes/wagtail-surveyjs/meta.yaml
Labels: review-requested, python

#25255 Add wagtail-color-panel
  recipes/wagtail-color-panel/meta.yaml
Labels: review-requested, python

#25269 Add recipe for mypy-boto3-glue
  recipes/mypy-boto3-glue/meta.yaml
Labels: review-requested, python

#25267 Adding cobyqa
  recipes/cobyqa/meta.yaml
Labels: review-requested, python

#25262 Add wagtail-json-widget
  recipes/wagtail-json-widget/meta.yaml
Labels: review-requested, python

#25261 Add wagtail-knowledgebase
  recipes/wagtail-knowledgebase/meta.yaml
Labels: review-requested, python

#25259 Add wagtail-linkchecker
  recipes/wagtail-linkchecker/meta.yaml
Labels: review-requested, python

#24837 add pycmtensor receipe
  recipes/pycmtensor/meta.yaml
Labels: review-requested, python

#25275 Add Django breeze and dependencies
  recipes/django-breeze/meta.yaml
  recipes/django-vite-plugin/meta.yaml
  recipes/django-vite/meta.yaml
  recipes/inertia-django/meta.yaml
Labels: staged-recipes, review-requested, python

#25277 Add Passhash 1.0.1
  recipes/passhash/meta.yaml
Labels: review-requested, python

#25274 add meamfit
  recipes/meamfit/build.sh
  recipes/meamfit/conda_build_config.yaml
  recipes/meamfit/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#25281 Coderedcms and dependencies
  recipes/coderedcms/meta.yaml
  recipes/django-eventtools/meta.yaml
  recipes/wagtail-cache/meta.yaml
  recipes/wagtail-seo/meta.yaml
Labels: review-requested, python

#25284 Add `sqlmermaid`
  recipes/sqlmermaid/meta.yaml
Labels: review-requested, python

#25282 Add `hextools` package
  recipes/hextools/meta.yaml
Labels: staged-recipes, review-requested

#25093 Add pylance
  recipes/pylance/bld.bat
  recipes/pylance/build.sh
  recipes/pylance/conda_build_config.yaml
  recipes/pylance/meta.yaml
Labels: staged-recipes, review-requested

#22556 Adding gocommands package
  recipes/gocommands/bld.bat
  recipes/gocommands/build.sh
  recipes/gocommands/meta.yaml
Labels: Awaiting author contribution, staged-recipes, c-cpp, go

#25279 Add recipe for recurring-ical-events
  recipes/recurring-ical-events/meta.yaml
Labels: review-requested, python

#25285 Add compas_robots (robot fundamentals for COMPAS framework)
  recipes/compas_robots/meta.yaml
Labels: review-requested, python

#25293 Add recipe for python-caldav
  recipes/caldav/meta.yaml
Labels: review-requested, python

#25192 Added wassima as a package
  recipes/wassima/conda_build_config.yaml
  recipes/wassima/meta.yaml
Labels: staged-recipes, review-requested, python, rust

#25299 Added typed-configparser as a package
  recipes/typed-configparser/meta.yaml
Labels: staged-recipes, review-requested, python

#25303 Added tfcausalimpact as a package
  recipes/tfcausalimpact/meta.yaml
Labels: staged-recipes, review-requested, python

#25305 Added fastcrud as a pacakge
  recipes/fastcrud/meta.yaml
Labels: staged-recipes, review-requested, python

#25220 create geetools recipe
  recipes/geetools/meta.yaml
Labels: review-requested, python

#25263 Add llm - Python library for interacting with Large Language Models
  recipes/llm/conda-forge.yml
  recipes/llm/meta.yaml
  recipes/python-ulid/meta.yaml
  recipes/sqlite-migrate/meta.yaml
Labels: review-requested, python

#25288 Add recipe for ai2-olmo
  recipes/ai2-olmo/meta.yaml
Labels: review-requested, python

#25308 Add poe-api-wrapper package recipe to recipes directory
  recipes/poe-api-wrapper/meta.yaml
Labels: staged-recipes, review-requested

#25297 Adding SegAlign
  recipes/segalign/build.sh
  recipes/segalign/meta.yaml
  recipes/segalign/patches/CMakeLists.txt.patch
  recipes/segalign/patches/common__seed_pos_table.cu.patch
  recipes/segalign/patches/d1a73a0c9169d5517c9316d9bdc68fd52f63e885.patch
  recipes/segalign/patches/repeat_masker_src__seed_filter.cu.patch
  recipes/segalign/patches/src__seed_filter.cu.patch
Labels: staged-recipes, review-requested, c-cpp

#25322 Add fluidfft-builder package
  recipes/fluidfft-builder/LICENSE
  recipes/fluidfft-builder/meta.yaml
Labels: review-requested, python

#24708 Add recipes for dmri-amico and dmri-dicelib
  recipes/dmri-amico/bld.bat
  recipes/dmri-amico/build.sh
  recipes/dmri-amico/meta.yaml
  recipes/dmri-amico/setup.py.patch
  recipes/dmri-dicelib/meta.yaml
Labels: review-requested, python

#25323 Add laces - Django components that know how to render themselves.
  recipes/laces/meta.yaml
Labels: review-requested, python

#25292 Add `brainglobe-space`
  recipes/brainglobe-space/meta.yaml
Labels: review-requested, python

#25324 Add tico
  recipes/tico/meta.yaml
Labels: review-requested, python

#25325 Add pyberny recipe
  recipes/pyberny/meta.yaml
Labels: review-requested, python

#25067 Add Vulp
  recipes/vulp/meta.yaml
Labels: review-requested, python

#25213 Add pydlm
  recipes/pydlm/meta.yaml
Labels: review-requested, python

#25214 Add mdp-toolkit
  recipes/mdp/gh100.patch
  recipes/mdp/gh94.patch
  recipes/mdp/meta.yaml
Labels: review-requested, python

#25272 Add mqttlibrary to the conda-forge
  recipes/robotframework-mqttlibrary/meta.yaml
Labels: staged-recipes, review-requested, python

#25321 Adding birka
  recipes/birka/meta.yaml
  recipes/birka/yum_requirements.txt
Labels: review-requested, python

#25289 Add `httpx-ntlm`, `httpx-negotiate-sspi`
  recipes/httpx-negotiate-sspi/LICENSE
  recipes/httpx-negotiate-sspi/conda-forge.yml
  recipes/httpx-negotiate-sspi/meta.yaml
  recipes/httpx-ntlm/meta.yaml
Labels: review-requested, python

#25334 Add django-constance
  recipes/django-constance/meta.yaml
Labels: review-requested, python

#25331 Added django-cte as a pacakge
  recipes/django-cte/meta.yaml
Labels: staged-recipes, review-requested, python

#25330 Added granian as a package
  recipes/granian/conda_build_config.yaml
  recipes/granian/meta.yaml
Labels: R, staged-recipes, review-requested, python

#24843 Add `google-cloud-cpp-ai` feedstock
  recipes/google-cloud-cpp-ai/bld.bat
  recipes/google-cloud-cpp-ai/build.sh
  recipes/google-cloud-cpp-ai/conda_build_config.yaml
  recipes/google-cloud-cpp-ai/install-libgoogle-cloud.bat
  recipes/google-cloud-cpp-ai/install-libgoogle-cloud.sh
  recipes/google-cloud-cpp-ai/meta.yaml
  recipes/google-cloud-cpp-ai/run_test_feature.bat
  recipes/google-cloud-cpp-ai/run_test_feature.sh
Labels: review-requested, c-cpp

#25253 Wagtail tag manager
  recipes/wagtail-tag-manager/meta.yaml
Labels: review-requested, python

#25090 Add taipy-templates
  recipes/taipy-templates/meta.yaml
Labels: review-requested, python

#25089 Add KillThreads
  recipes/ kthread/meta.yaml
Labels: review-requested, python

#25228 Add django-plotly-dash
  recipes/django-plotly-dash/meta.yaml
Labels: review-requested, python

#25157 Add recipe for the vala compiler
  recipes/vala/build.sh
  recipes/vala/meta.yaml
  recipes/vala/test.vala
Labels: staged-recipes, review-requested, c-cpp

#25232 Add django-plotly-wagtail
  recipes/django-plotly-wagtail/LICENSE
  recipes/django-plotly-wagtail/meta.yaml
Labels: review-requested, python

#24603 OpenLLM
  recipes/openllm-client/meta.yaml
  recipes/openllm-core/meta.yaml
  recipes/openllm-playground/meta.yaml
  recipes/openllm/meta.yaml
Labels: staged-recipes, review-requested, python

#25342 Fix review label workflow wrongly applying r label on ruby and rust PRs
  .github/workflows/automate-review-labels.yml
Labels: staged-recipes, review-requested

#25341 Add `toolong`
  recipes/toolong/meta.yaml
Labels: review-requested, python

#25343 Add cfenv
  recipes/cfenv/LICENSE.txt
  recipes/cfenv/meta.yaml
Labels: staged-recipes, review-requested, python

#25345 Add phidata
  recipes/phidata/meta.yaml
Labels: staged-recipes, review-requested, python

#23758 Add validate-pyproject
  recipes/validate-pyproject/meta.yaml
Labels: review-requested, python

#25311 Adding ploomber-extension
  recipes/ploomber-extension/conda-forge.yml
  recipes/ploomber-extension/meta.yaml
Labels: staged-recipes, review-requested, python

#25335 Add `argbash`
  recipes/argbash/meta.yaml
Labels: staged-recipes, review-requested

#25367 Add wagtail-grapple
  recipes/wagtail-grapple/meta.yaml
  recipes/wagtail-headless-preview/meta.yaml
Labels: review-requested, python

#25365 Add wagtail-font-awesome-svg
  recipes/wagtail-font-awesome-svg/meta.yaml
Labels: review-requested, python

#25362 Add wagtail-accessibility
  recipes/wagtail-accessibility/meta.yaml
Labels: review-requested, python

#25361 Add django-wildewidgets
  recipes/django-wildewidgets/meta.yaml
Labels: review-requested, python

#25360 Add django-streamfield
  recipes/django-streamfield/meta.yaml
Labels: review-requested, python

#25359 Add django-data-browser
  recipes/django-data-browser/meta.yaml
Labels: review-requested, python

#25358 Add django-admin-rangefilter
  recipes/django-admin-rangefilter/meta.yaml
Labels: review-requested, python

#25149 Add harmony-py Python package
  recipes/harmony-py/76.diff
  recipes/harmony-py/meta.yaml
Labels: review-requested, python

#25376 Add wagtail-storages
  recipes/wagtail-storages/meta.yaml
Labels: review-requested, python

#25375 Add wagtail-sharing
  recipes/wagtail-sharing/meta.yaml
Labels: review-requested, python

#25374 Add wagtail-sb-admin-interface
  recipes/wagtail-sb-admin-interface/meta.yaml
Labels: review-requested, python

#25372 Add wagtail-nav-menus
  recipes/wagtail-nav-menus/meta.yaml
Labels: review-requested, python

#25364 Add wagtail-blocks
  recipes/wagtail-blocks/meta.yaml
Labels: review-requested, python

#25356 Add types-click-default-group stub
  recipes/types-click-default-group/LICENSE
  recipes/types-click-default-group/meta.yaml
Labels: review-requested, python

#25197 Add rotary-embedding-torch recipe
  recipes/rotary-embedding-torch/meta.yaml
Labels: staged-recipes, review-requested, python

#25340 Add kanidm-clients
  recipes/kanidm-clients/bld.bat
  recipes/kanidm-clients/build.sh
  recipes/kanidm-clients/conda_build_config.yaml
  recipes/kanidm-clients/meta.yaml
Labels: R, review-requested, rust

#25371 Adding R package r-iheatmapr
  recipes/r-iheatmapr/bld.bat
  recipes/r-iheatmapr/build.sh
  recipes/r-iheatmapr/meta.yaml
Labels: R, review-requested

#25328 Add universaltest package
  recipes/universaltest/bld.bat
  recipes/universaltest/build.sh
  recipes/universaltest/conda_build_config.yaml
  recipes/universaltest/meta.yaml
Labels: review-requested, c-cpp

#25383 Add wagtail-flags
  recipes/wagtail-flags/meta.yaml
Labels: review-requested, python

#24972 Added quasiqueue as a package
  recipes/quasiqueue/meta.yaml
Labels: staged-recipes, review-requested, python

#25377 Add wagtail-inventory
  recipes/wagtail-inventory/meta.yaml
Labels: review-requested, python

#25256 Add robotraconteur_companion_python package recipe
  recipes/robotraconteur_companion_python/meta.yaml
Labels: review-requested, python

#25339 New recipe for s1etad
  recipes/s1etad/meta.yaml
Labels: review-requested, python

#25388 Added django-webhook as a package
  recipes/django-webhook/meta.yaml
Labels: staged-recipes, review-requested, python

#25391 Adding PanelAero
  recipes/PanelAero/meta.yaml
Labels: staged-recipes, review-requested, python

#25404 add kinisi
  recipes/kinisi/meta.yaml
  recipes/uravu/meta.yaml
Labels: staged-recipes, review-requested, python

#25403 Add LoadsKernel
  recipes/LoadsKernel/meta.yaml
Labels: review-requested, python

#25076 Add cortecs package
  recipes/cortecs/meta.yaml
Labels: review-requested, python

#25408 Added fasthx as a package
  recipes/fasthx/meta.yaml
Labels: staged-recipes, review-requested, python

#25407 Add finagg as a package
  recipes/finagg/meta.yaml
Labels: staged-recipes, review-requested, python

#24163 Added recipe for sagemaker-code-editor
  recipes/sagemaker-code-editor/LICENSE
  recipes/sagemaker-code-editor/LICENSE-THIRD-PARTY
  recipes/sagemaker-code-editor/LICENSE.vscode.txt
  recipes/sagemaker-code-editor/ThirdPartyNotices.vscode.txt
  recipes/sagemaker-code-editor/build.sh
  recipes/sagemaker-code-editor/meta.yaml
Labels: staged-recipes, review-requested

#25416 adds `r-chatgpt`
  recipes/r-chatgpt/bld.bat
  recipes/r-chatgpt/build.sh
  recipes/r-chatgpt/meta.yaml
Labels: R, review-requested

#25394 Add coinbase-advanced-py
  recipes/coinbase-advanced-py/meta.yaml
Labels: review-requested, python

#25413 Add pyassimp via grayskull
  recipes/pyassimp/LICENSE
  recipes/pyassimp/meta.yaml
Labels: review-requested, python

#25396 Adding openinference-semantic-conventions
  recipes/openinference-semantic-conventions/meta.yaml
Labels: review-requested, python

#25387 Add recipe for fluidfft-fftw
  recipes/fluidfft-fftw/LICENSE
  recipes/fluidfft-fftw/meta.yaml
Labels: review-requested, python

#25411 add recipe for iosacal, a radiocarbon calibration program
  recipes/iosacal/meta.yaml
Labels: review-requested, python

#25400 Adding openinference-instrumentation-dspy
  recipes/openinference-instrumentation-dspy/meta.yaml
Labels: review-requested, python

#25397 Adding openinference-instrumentation-openai
  recipes/openinference-instrumentation-openai/meta.yaml
Labels: review-requested, python

#25384 Add bayesopt
  recipes/bayesopt/bld.bat
  recipes/bayesopt/build-py.bat
  recipes/bayesopt/build-py.sh
  recipes/bayesopt/build.sh
  recipes/bayesopt/meta.yaml
Labels: review-requested, c-cpp

#25196 Add ast-grep recipe.
  recipes/ast-grep/0001-Downgrade-tree-sitter-cpp-for-statis_assert-build-er.patch
  recipes/ast-grep/build.sh
  recipes/ast-grep/conda_build_config.yaml
  recipes/ast-grep/meta.yaml
Labels: R, review-requested

#25401 Adding openinference-instrumentation-bedrock
  recipes/openinference-instrumentation-bedrock/meta.yaml
Labels: review-requested, python

#25399 Adding openinference-instrumentation-langchain
  recipes/openinference-instrumentation-langchain/meta.yaml
Labels: review-requested, python

#23787 Add Bip32
  recipes/bip32/fix-coincurve-version.patch
  recipes/bip32/meta.yaml
Labels: Awaiting author contribution, python-c

#25426 Add runnerase
  recipes/runnerase/meta.yaml
Labels: staged-recipes, review-requested, python

#25398 Adding openinference-instrumentation-llama-index
  recipes/openinference-instrumentation-llama-index/meta.yaml
Labels: review-requested, python

#25266 add ctransformers
  recipes/ctransformers/conda_build_config.yaml
  recipes/ctransformers/meta.yaml
Labels: staged-recipes, review-requested, python-c

#25430 add multipart
  recipes/multipart/meta.yaml
Labels: staged-recipes, review-requested

#25433 Add llama-index subpackages
  recipes/llama-index-agent-openai/meta.yaml
  recipes/llama-index-core/meta.yaml
  recipes/llama-index-embeddings-openai/meta.yaml
  recipes/llama-index-legacy/meta.yaml
  recipes/llama-index-llms-openai/meta.yaml
  recipes/llama-index-multi-modal-llms-openai/meta.yaml
  recipes/llama-index-program-openai/meta.yaml
  recipes/llama-index-question-gen-openai/meta.yaml
Labels: staged-recipes, review-requested, python

#25418 Add spruce recipe
  recipes/spruce/meta.yaml
Labels: review-requested, go

#25437 Add vivid, a rust package for $LS_COLOR generation
  recipes/vivid/bld.bat
  recipes/vivid/build.sh
  recipes/vivid/conda_build_config.yaml
  recipes/vivid/meta.yaml
Labels: R, review-requested, rust

#25434 Add recipe for tf-keras
  recipes/tf-keras/meta.yaml
Labels: review-requested, python
