Repository conda-forge/staged-recipes, pull requests merged in 2024-09, with the labels that each got.

#27454 Added r-oyster as a package
  recipes/r-oyster/bld.bat
  recipes/r-oyster/build.sh
  recipes/r-oyster/meta.yaml
Labels: R, staged-recipes, review-requested

#27453 Added r-checkhelper as a package
  recipes/r-checkhelper/bld.bat
  recipes/r-checkhelper/build.sh
  recipes/r-checkhelper/meta.yaml
Labels: R, staged-recipes, review-requested

#27455 Added r-functiondepends as a package
  recipes/r-functiondepends/bld.bat
  recipes/r-functiondepends/build.sh
  recipes/r-functiondepends/meta.yaml
Labels: R, staged-recipes, review-requested

#27442 add r-rcompendium
  recipes/r-rcompendium/bld.bat
  recipes/r-rcompendium/build.sh
  recipes/r-rcompendium/meta.yaml
Labels: R, staged-recipes, review-requested

#27459 Add collectfasta
  recipes/collectfasta/meta.yaml
Labels: review-requested, python

#27464 Add pywbt
  recipes/pywbt/meta.yaml
Labels: review-requested, python

#27447 Add shot-scraper
  recipes/shot-scraper/meta.yaml
Labels: review-requested, python

#27449 add pypi package oxli
  recipes/oxli/meta.yaml
Labels: review-requested, python

#27452 Added picows as a package
  recipes/picows/meta.yaml
Labels: staged-recipes, review-requested, python

#27451 Added django-cotton as a package
  recipes/django-cotton/meta.yaml
Labels: staged-recipes, review-requested, python

#27450 Added csv_trimming as a package
  recipes/csv_trimming/meta.yaml
Labels: staged-recipes, review-requested, python

#27457 Added poltergeist as a package
  recipes/poltergeist/meta.yaml
Labels: staged-recipes, review-requested, python

#27466 Add unfoldNd via grayskull / conda-recipe-manager
  recipes/unfoldNd/recipe.yaml
Labels: review-requested, python

#27467 Add matcalc
  recipes/matcalc/meta.yaml
Labels: staged-recipes, review-requested, python

#27445 Add package textual-serve
  recipes/textual-serve/meta.yaml
Labels: review-requested, python

#27458 Add uvicorn-worker
  recipes/uvicorn-worker/meta.yaml
Labels: review-requested, python

#27400 Adding bibmon
  recipes/bibmon/meta.yaml
Labels: staged-recipes, review-requested, python

#27398 Add `marp-cli`
  recipes/marp-cli/bld.bat
  recipes/marp-cli/build.sh
  recipes/marp-cli/meta.yaml
Labels: nodejs, staged-recipes, review-requested

#27408 Adding cifkit to conda-forge (Python)
  recipes/cifkit/meta.yaml
Labels: review-requested, python

#27440 feat: add conda-forge-feedstock-ops
  recipes/conda-forge-feedstock-ops/meta.yaml
Labels: staged-recipes, review-requested, python

#27443 Add Vulkan Memory Allocator v3.1.0
  recipes/vulkan-memory-allocator/meta.yaml
Labels: review-requested, c-cpp

#27392 Add `keyrings.artifacts` recipe for Azure Artifacts keyring backend
  recipes/keyrings.artifacts/meta.yaml
Labels: staged-recipes, review-requested, python

#27432 Adding the Nested-Pandas and Nested-Dask Packages
  recipes/nested-dask/meta.yaml
  recipes/nested-pandas/meta.yaml
Labels: staged-recipes, review-requested, python

#27427 Add SageMaker Hyperpod package to conda-forge
  recipes/amazon-sagemaker-hyperpod/meta.yaml
Labels: review-requested, python

#27149 add kubeseal
  recipes/kubeseal/meta.yaml
Labels: review-requested, go

#27477 Add peccary
  recipes/peccary/meta.yaml
Labels: staged-recipes, review-requested, python

#27188 Add adacpp
  recipes/adacpp/LICENSE
  recipes/adacpp/bld.bat
  recipes/adacpp/build.sh
  recipes/adacpp/conda_build_config.yaml
  recipes/adacpp/meta.yaml
  recipes/adacpp/patches/remove_hardcoded_osx_sysroot_and_deployment_target.patch
  recipes/adacpp/yum_requirements.txt
Labels: review-requested, python-c

#27363 Add antio
  recipes/antio/meta.yaml
Labels: review-requested, python-c

#27357 Add AtomGPT
  recipes/atomgpt/meta.yaml
Labels: staged-recipes, review-requested, python

#27485 Add pytest-deadfixtures
  recipes/pytest-deadfixtures/meta.yaml
Labels: review-requested, python

#27468 Adding magic-cta-pipe
  recipes/magic-cta-pipe/meta.yaml
Labels: review-requested, python

#27359 adding openinference-instrumentation-anthropic
  recipes/openinference-instrumentation-anthropic/meta.yaml
Labels: review-requested, python

#27289 Adding `geoindex-rs` (A Python package)
  recipes/geoindex_rs/meta.yaml
Labels: R, review-requested, python, rust

#27409 Add recipe for cuda-api-wrappers
  recipes/cuda-api-wrappers/build.sh
  recipes/cuda-api-wrappers/meta.yaml
Labels: review-requested, c-cpp

#27471 Add beancount
  recipes/beancount/meta.yaml
Labels: staged-recipes, review-requested, python

#27259 Added bregman-learning and torch-simplify
  recipes/bregman-learning/meta.yaml
  recipes/torch-simplify/meta.yaml
Labels: review-requested, python

#27475 Added R-gsignal recipe
  recipes/r-gsignal/bld.bat
  recipes/r-gsignal/build.sh
  recipes/r-gsignal/meta.yaml
Labels: R, review-requested

#27206 Adding geopy-distrib packages
  recipes/curve-apps/meta.yaml
  recipes/geoapps-utils/meta.yaml
  recipes/mira-simpeg/meta.yaml
  recipes/octree-creation-app/meta.yaml
  recipes/param-sweeps/meta.yaml
  recipes/peak-finder-app/meta.yaml
Labels: review-requested, python

#27278 scriptconfig: add package
  recipes/scriptconfig/meta.yaml
Labels: review-requested, python

#27277 kwarray: add package
  recipes/kwarray/meta.yaml
Labels: review-requested, python

#27495 Add recipe for pyhyperscattering
  recipes/pyhyperscattering/meta.yaml
Labels: review-requested, python

#27505 add `jrnl`
  recipes/jrnl/meta.yaml
Labels: review-requested, python

#27494 Add `spikeinterface`
  recipes/spikeinterface/meta.yaml
Labels: review-requested, python

#27515 Add mambular
  recipes/mambular/meta.yaml
Labels: staged-recipes, review-requested, python

#27160 add `fiftyone`
  recipes/fiftyone-brain/meta.yaml
  recipes/fiftyone/0000-allow-newer-strawberry.patch
  recipes/fiftyone/0000-dropin-fiftyone-db.patch
  recipes/fiftyone/0000-relax-deps.patch
  recipes/fiftyone/meta.yaml
  recipes/fiftyone/yum_requirements.txt
  recipes/universal-analytics-python3/LICENSE
  recipes/universal-analytics-python3/meta.yaml
  recipes/voxel51-eta/meta.yaml
  recipes/voxel51-eta/yum_requirements.txt
Labels: review-requested, python

#27517 feat: pre-register feedstock outputs
  .github/workflows/scripts/create_feedstocks
  .github/workflows/scripts/create_feedstocks.py
Labels: maintenance

#27496 kwimage: add package
  recipes/kwimage/meta.yaml
Labels: review-requested, python

#27492 Added flory as a package
  recipes/flory/meta.yaml
Labels: review-requested, python

#27521 Add sam2 package
  recipes/sam2/meta.yaml
Labels: review-requested, python

#27523 add `jd`
  recipes/jd/bld.bat
  recipes/jd/build.sh
  recipes/jd/meta.yaml
Labels: review-requested, go

#27348 Add Spherely
  recipes/spherely/meta.yaml
Labels: review-requested, python-c

#27484 add code-minimap, dprint, tree-sitter-cli, ttags
  recipes/code-minimap/bld.bat
  recipes/code-minimap/build.sh
  recipes/code-minimap/meta.yaml
  recipes/dprint/bld.bat
  recipes/dprint/build.sh
  recipes/dprint/meta.yaml
  recipes/tree-sitter-cli/bld.bat
  recipes/tree-sitter-cli/build.sh
  recipes/tree-sitter-cli/meta.yaml
  recipes/ttags/bld.bat
  recipes/ttags/build.sh
  recipes/ttags/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27482 add elvish, murex, oh-my-posh
  recipes/elvish/bld.bat
  recipes/elvish/build.sh
  recipes/elvish/meta.yaml
  recipes/murex/build.sh
  recipes/murex/meta.yaml
  recipes/oh-my-posh/build.sh
  recipes/oh-my-posh/license-files/github.com/golang/freetype/raster/ftl.txt
  recipes/oh-my-posh/license-files/github.com/golang/freetype/raster/gpl.txt
  recipes/oh-my-posh/license-files/github.com/golang/freetype/truetype/ftl.txt
  recipes/oh-my-posh/license-files/github.com/golang/freetype/truetype/gpl.txt
  recipes/oh-my-posh/license-files/github.com/mattn/go-localereader/LICENSE
  recipes/oh-my-posh/meta.yaml
Labels: staged-recipes, review-requested, go

#27532 Add pyocse
  recipes/pyocse/meta.yaml
Labels: staged-recipes, review-requested, python

#27508 Adding radarx
  recipes/radarx/meta.yaml
Labels: review-requested, python

#27491 Adding ringtail package
  recipes/ringtail/meta.yaml
Labels: review-requested, python

#26580 Adding cublasMp recipes
  recipes/cublasmp/meta.yaml
  recipes/libcal/meta.yaml
  recipes/libcublasmp/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27499 Added algotree as a package
  recipes/algotree/meta.yaml
Labels: staged-recipes, review-requested, python

#27536 add pubtator_loader
  recipes/pubtator_loader/LICENSE
  recipes/pubtator_loader/meta.yaml
Labels: review-requested, python

#27547 NEW: Add default values for cuda_compiler on osx and windows
  .ci_support/osx64.yaml
  .ci_support/win64.yaml
  recipes/libcal/meta.yaml
  recipes/libcublasmp/meta.yaml
Labels: maintenance

#27559 Add fhaviary
  recipes/fhaviary/meta.yaml
Labels: staged-recipes, review-requested, python

#27564 Create xorg-libxxf86dga feedstock
  recipes/xorg-libxxf86dga/bld.bat
  recipes/xorg-libxxf86dga/build.sh
  recipes/xorg-libxxf86dga/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27556 Adding parallelbar
  recipes/parallelbar/meta.yaml
Labels: review-requested, python

#27565 Create xorg-libxv feedstock
  recipes/xorg-libxv/bld.bat
  recipes/xorg-libxv/build.sh
  recipes/xorg-libxv/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27560 Create xorg-libxshmfence feedstock
  recipes/xorg-libxshmfence/bld.bat
  recipes/xorg-libxshmfence/build.sh
  recipes/xorg-libxshmfence/meta.yaml
  recipes/xorg-libxshmfence/windows.patch
Labels: staged-recipes, review-requested, c-cpp

#27557 Adding filesendercli recipe
  recipes/filesendercli/meta.yaml
Labels: staged-recipes, review-requested, python

#27570 Add surface-water-network
  recipes/surface-water-network/meta.yaml
Labels: review-requested, python

#27558 Add tantivy
  recipes/tantivy/conda_build_config.yaml
  recipes/tantivy/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27579 feat: add quadax
  recipes/quadax/meta.yaml
Labels: review-requested, python

#27129 Add dydxprotocol v4 client py
  recipes/dydxprotocol-v4-client-py/install-py.bat
  recipes/dydxprotocol-v4-client-py/install-py.sh
  recipes/dydxprotocol-v4-client-py/meta.yaml
  recipes/dydxprotocol-v4-client-py/patches/0001-update-v4-proto-version.patch
  recipes/dydxprotocol-v4-client-py/patches/0002-use-pyext-over-_ubp.patch
Labels: review-requested, python

#27483 add curlie, lychee, orgalorg, pget, xh
  recipes/curlie/bld.bat
  recipes/curlie/build.sh
  recipes/curlie/meta.yaml
  recipes/lychee/build.sh
  recipes/lychee/meta.yaml
  recipes/orgalorg/bld.bat
  recipes/orgalorg/build.sh
  recipes/orgalorg/license-files/github.com/zazab/zhash/LICENSE
  recipes/orgalorg/meta.yaml
  recipes/pget/bld.bat
  recipes/pget/build.sh
  recipes/pget/meta.yaml
  recipes/xh/bld.bat
  recipes/xh/build.sh
  recipes/xh/meta.yaml
Labels: R, staged-recipes, review-requested, go, rust

#27534 add `fastmod`
  recipes/fastmod/build.sh
  recipes/fastmod/meta.yaml
Labels: R, review-requested, rust

#26705 recipe for tantivy-py
  recipes/tantivy/meta.yaml
Labels: review-requested, python

#27582 add popclass
  recipes/popclass/meta.yaml
Labels: review-requested, python

#27581 add tox-gh recipe
  recipes/tox-gh/meta.yaml
Labels: review-requested, python

#27524 Adding `ai4ts` from PyPI
  recipes/ai4ts/meta.yaml
Labels: review-requested, python

#27599 Add papis
  recipes/arxiv2bib/LICENSE
  recipes/arxiv2bib/meta.yaml
  recipes/papis/meta.yaml
  recipes/python-doi/meta.yaml
Labels: staged-recipes, review-requested, python

#27498 delayed_image: add package
  recipes/delayed_image/meta.yaml
Labels: review-requested, python

#27598 Add recipe for repype
  recipes/repype/meta.yaml
Labels: review-requested, python

#27474 Add pyeda
  recipes/pyeda/meta.yaml
Labels: review-requested, python-c

#27183 Adding screenFetch v3.9.1
  recipes/screenFetch/build.sh
  recipes/screenFetch/meta.yaml
Labels: staged-recipes, review-requested

#27530 Add pangolin
  recipes/pangolin/build.sh
  recipes/pangolin/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27486 Add build123d
  recipes/build123d/0001-Use-lib3mf-python.patch
  recipes/build123d/0002-Don-t-try-to-help-lib3mf-find-it-s-library.patch
  recipes/build123d/0003-Change-explicit-dependency-lock-version.patch
  recipes/build123d/0004-Fix-raw-regex.patch
  recipes/build123d/build.sh
  recipes/build123d/meta.yaml
Labels: review-requested, python

#27603 Attempt 1 at recipe for 'empix' package.
  recipes/empix/meta.yaml
Labels: review-requested, python

#27562 Adding cytosim to conda-forge
  recipes/cytosim/meta.yaml
Labels: staged-recipes, review-requested, python-c

#27590 feat: unify linting
  .github/workflows/correct_directory.yml
  .github/workflows/do_not_edit_example.yml
  .github/workflows/linter.yml
  .github/workflows/linter_make_comment.yml
  .github/workflows/only_edit_in_recipes.yaml
  .github/workflows/scripts/linter.py
  .github/workflows/scripts/linter_make_comment.py
Labels: maintenance, staged-recipes, review-requested

#27618 fix: ensure linter makes comments properly
  .github/workflows/linter_make_comment.yml
  .github/workflows/scripts/linter_make_comment.py
Labels: maintenance

#27601 Adding numbacs
  recipes/numbacs/meta.yaml
Labels: review-requested, python

#27210 kwcoco: add package
  recipes/kwcoco/meta.yaml
Labels: review-requested, python

#27619 fix: do not require the R team to comment for linter
  .github/workflows/scripts/linter.py
Labels: maintenance

#27622 fix: skip non-recipe files
  .github/workflows/scripts/linter.py
Labels: maintenance

#27621 Add dxtb package
  recipes/dxtb/meta.yaml
Labels: staged-recipes, review-requested, python

#27617 Add r-indicspecies package
  recipes/r-indicspecies/bld.bat
  recipes/r-indicspecies/build.sh
  recipes/r-indicspecies/meta.yaml
Labels: R, review-requested

#27633 fix: inspect it all
  .ci_support/requirements.txt
  .scripts/build_steps.sh
  .scripts/run_win_build.bat
Labels: maintenance

#27634 fix: `inspect_artifacts --all-packages` in osx too
  .scripts/build_steps.sh
  .scripts/run_osx_build.sh
  .scripts/run_win_build.bat
Labels: maintenance

#27368 Adding supertree
  recipes/supertree/meta.yaml
Labels: review-requested, python

#27189 Adding Lazydocker v0.23.3
  recipes/lazydocker/bld.bat
  recipes/lazydocker/build.sh
  recipes/lazydocker/meta.yaml
Labels: review-requested, go

#27540 Provide a first draft of the conda-forge triqs_ctseg package
  recipes/triqs_ctseg/build.sh
  recipes/triqs_ctseg/conda_build_config.yaml
  recipes/triqs_ctseg/meta.yaml
Labels: review-requested, python-c

#27506 Adding the Tracy C++ library (and its Python bindings)
  recipes/tracy/LICENSE.txt
  recipes/tracy/build_tracy_client.bat
  recipes/tracy/build_tracy_client.sh
  recipes/tracy/build_tracy_client_python.bat
  recipes/tracy/build_tracy_client_python.sh
  recipes/tracy/meta.yaml
  recipes/tracy/patches/0001-Install-bindings-on-Windows-and-allow-__init__.py-to.patch
  recipes/tracy/patches/0002-Don-t-link-against-Python-library-in-Python-module.patch
Labels: staged-recipes, review-requested, c-cpp

#27539 Adding grpcurl & tmsu
  recipes/grpcurl/meta.yaml
  recipes/tmsu/go.mod
  recipes/tmsu/go.sum
  recipes/tmsu/meta.yaml
Labels: staged-recipes, review-requested, go

#27516 Adding Kakoune
  recipes/kakoune/build.sh
  recipes/kakoune/meta.yaml
Labels: review-requested, c-cpp

#27628 Adding konnektor and scikit-mol
  recipes/konnektor/meta.yaml
  recipes/scikit-mol/meta.yaml
Labels: review-requested, python

#27636 Added r-overviewr as a package
  recipes/r-overviewr/bld.bat
  recipes/r-overviewr/build.sh
  recipes/r-overviewr/meta.yaml
Labels: R, staged-recipes, review-requested

#27600 Add recipe for numba-cuda
  recipes/numba-cuda/recipe.yaml
Labels: review-requested, python

#27637 Add ecmwflibs
  recipes/ecmwflibs/find_conda_libs.diff
  recipes/ecmwflibs/meta.yaml
Labels: review-requested, python

#27522 add ablang
  recipes/ablang2/meta.yaml
Labels: review-requested, python

#27535 Adding libpyvinyl and mcstasscript
  recipes/libpyvinyl/meta.yaml
  recipes/mcstasscript/meta.yaml
Labels: review-requested, python

#27235 Adding Peco v0.5.11
  recipes/peco/bld.bat
  recipes/peco/build.sh
  recipes/peco/meta.yaml
Labels: review-requested, go

#27580 Add vrs recipe
  recipes/vrs/bld.bat
  recipes/vrs/build.sh
  recipes/vrs/conda_build_config.yaml
  recipes/vrs/meta.yaml
Labels: review-requested, c-cpp

#27586 add fork-cleaner, git-town, gitql, treefmt
  recipes/fork-cleaner/bld.bat
  recipes/fork-cleaner/build.sh
  recipes/fork-cleaner/meta.yaml
  recipes/git-town/bld.bat
  recipes/git-town/build.sh
  recipes/git-town/meta.yaml
  recipes/gitql/bld.bat
  recipes/gitql/build.sh
  recipes/gitql/license-files/github.com/pjbgf/sha1cd/LICENSE
  recipes/gitql/meta.yaml
  recipes/treefmt/bld.bat
  recipes/treefmt/build.sh
  recipes/treefmt/meta.yaml
Labels: staged-recipes, review-requested, go

#27587 add flint, git-hound, lefthook
  recipes/flint-checker/bld.bat
  recipes/flint-checker/build.sh
  recipes/flint-checker/meta.yaml
  recipes/git-hound/bld.bat
  recipes/git-hound/build.sh
  recipes/git-hound/meta.yaml
  recipes/lefthook/bld.bat
  recipes/lefthook/build.sh
  recipes/lefthook/meta.yaml
Labels: staged-recipes, review-requested, go

#27356 Add cbflib and cqrlib
  recipes/cbflib/01-off-by-one.patch
  recipes/cbflib/02-overrun.patch
  recipes/cbflib/03-binary-size-third-dimension-2D.patch
  recipes/cbflib/04-fgetln.patch
  recipes/cbflib/05-mkstemplate.patch
  recipes/cbflib/06-realpath.patch
  recipes/cbflib/07-vla.patch
  recipes/cbflib/08-libtiff-public-api.patch
  recipes/cbflib/09-pycbf-dials.patch
  recipes/cbflib/10-cmake.patch
  recipes/cbflib/11-cmakelist.patch
  recipes/cbflib/12-msvc.patch
  recipes/cbflib/13-warnings.patch
  recipes/cbflib/bld.bat
  recipes/cbflib/build.sh
  recipes/cbflib/cbflib-data-input-0.9.7.patch
  recipes/cbflib/cbflib-data-output-0.9.7.patch
  recipes/cbflib/meta.yaml
  recipes/cqrlib/01-cmake.patch
  recipes/cqrlib/bld.bat
  recipes/cqrlib/build.sh
  recipes/cqrlib/meta.yaml
Labels: review-requested, c-cpp

#27330 Add 'dssp' package
  recipes/dssp/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27607 Add libabigail
  recipes/libabigail/build.sh
  recipes/libabigail/meta.yaml
Labels: review-requested, c-cpp

#27638 Add torch-harmonics
  recipes/torch-harmonics/fix_numpy.diff
  recipes/torch-harmonics/meta.yaml
Labels: review-requested, python

#26397 Adding qss
  recipes/qss/meta.yaml
Labels: review-requested, python

#27589 add dura, git-absorb, jj, prr
  recipes/dura/build.sh
  recipes/dura/meta.yaml
  recipes/git-absorb/bld.bat
  recipes/git-absorb/build.sh
  recipes/git-absorb/meta.yaml
  recipes/jj/bld.bat
  recipes/jj/build.sh
  recipes/jj/meta.yaml
  recipes/prr/build.sh
  recipes/prr/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27588 add fetch, karn, kickstart, stgit
  recipes/fetch/bld.bat
  recipes/fetch/build.sh
  recipes/fetch/meta.yaml
  recipes/karn/bld.bat
  recipes/karn/build.sh
  recipes/karn/meta.yaml
  recipes/kickstart/bld.bat
  recipes/kickstart/build.sh
  recipes/kickstart/meta.yaml
  recipes/stgit/bld.bat
  recipes/stgit/build.sh
  recipes/stgit/meta.yaml
Labels: R, staged-recipes, review-requested, go, rust

#27543 Adding Legendre-to-Chebyshev C/python package
  recipes/leg2cheb/meta.yaml
Labels: review-requested, python-c

#27652 Added overviewpy as a package
  recipes/overviewpy/meta.yaml
Labels: staged-recipes, review-requested, python

#27651 Added summarytools as a package
  recipes/summarytools/meta.yaml
Labels: staged-recipes, review-requested, python

#27655 Added r-dupree as a package
  recipes/r-dupree/bld.bat
  recipes/r-dupree/build.sh
  recipes/r-dupree/meta.yaml
Labels: R, staged-recipes, review-requested

#27656 Added r-rscc as a package
  recipes/r-rscc/bld.bat
  recipes/r-rscc/build.sh
  recipes/r-rscc/meta.yaml
Labels: R, staged-recipes, review-requested

#27657 Added r-jshintr as a package
  recipes/r-jshintr/bld.bat
  recipes/r-jshintr/build.sh
  recipes/r-jshintr/meta.yaml
Labels: R, staged-recipes, review-requested

#27654 Added peepdb as a package
  recipes/peepdb/meta.yaml
Labels: staged-recipes, review-requested, python

#27544 add hololinked
  recipes/hololinked/meta.yaml
Labels: review-requested, python

#27573 Add ollama Python package
  recipes/ollama-python/meta.yaml
Labels: review-requested, python

#27668 fix: example lint
  recipes/example-v1/recipe.yaml
  recipes/example/meta.yaml
Labels: maintenance

#26097 Add recipe for ZodiPy
  recipes/zodipy/meta.yaml
Labels: staged-recipes, review-requested, python

#27665 add cbfmt, typos-cli, typos-lsp
  recipes/cbfmt/bld.bat
  recipes/cbfmt/build.sh
  recipes/cbfmt/meta.yaml
  recipes/typos-cli/bld.bat
  recipes/typos-cli/build.sh
  recipes/typos-cli/meta.yaml
  recipes/typos-lsp/bld.bat
  recipes/typos-lsp/build.sh
  recipes/typos-lsp/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27541 feat: Add func-adl
  recipes/func-adl/meta.yaml
Labels: review-requested, python

#27673 Add pybliometrics
  recipes/pybliometrics/meta.yaml
Labels: staged-recipes, review-requested, python

#27674 Add knowledge-graph-maker
  recipes/knowledge-graph-maker/meta.yaml
Labels: staged-recipes, review-requested, python

#27677 Added streamlit-keyup as a package
  recipes/streamlit-keyup/meta.yaml
Labels: staged-recipes, review-requested, python

#27671 adds `r-unigd`
  recipes/r-unigd/bld.bat
  recipes/r-unigd/build.sh
  recipes/r-unigd/meta.yaml
Labels: R, review-requested

#26845 Add recipe for libzenohcxx package
  recipes/zenoh-cpp/136.patch
  recipes/zenoh-cpp/bld.bat
  recipes/zenoh-cpp/build.sh
  recipes/zenoh-cpp/disable_tests_examples_and_docs.patch
  recipes/zenoh-cpp/disable_zenoh_pico.patch
  recipes/zenoh-cpp/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27653 Add pc_rasterize
  recipes/pc_rasterize/meta.yaml
Labels: review-requested, python

#27675 Add recipe for icub-firmware-shared packages
  recipes/icub-firmware-shared/bld_cxx.bat
  recipes/icub-firmware-shared/build_cxx.sh
  recipes/icub-firmware-shared/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27691 Add recipe for ibmcloudant
  recipes/ibmcloudant/meta.yaml
Labels: review-requested, python

#27690 add recipe for array-api-extra
  recipes/array-api-extra/meta.yaml
Labels: review-requested, python

#27335 Adding fastnanquantile
  recipes/fastnanquantile/meta.yaml
Labels: review-requested, python

#27461 add mlwc package v.0.1.0
  recipes/MLWC/meta.yaml
Labels: staged-recipes, review-requested, python

#27501 Add `wrenfold` as a package
  recipes/wrenfold/bld.bat
  recipes/wrenfold/build.sh
  recipes/wrenfold/meta.yaml
Labels: review-requested, python

#26843 Adding pypolymlp as a package
  recipes/pypolymlp/meta.yaml
Labels: staged-recipes, review-requested, python-c

#27678 add `jfrog-cli`
  recipes/jfrog-cli/bld.bat
  recipes/jfrog-cli/build.sh
  recipes/jfrog-cli/meta.yaml
Labels: review-requested, go

#27367 Adding bbf package
  recipes/bbf/meta.yaml
Labels: review-requested, python-c

#27279 Adding pixell to conda-forge
  recipes/pixell/LICENSE
  recipes/pixell/meta.yaml
  recipes/pixell/qsort_const.patch
Labels: review-requested, python-c

#27545 Add turbo turtle
  recipes/turbo_turtle/bld.bat
  recipes/turbo_turtle/build.sh
  recipes/turbo_turtle/meta.yaml
  recipes/turbo_turtle/run_test.bat
  recipes/turbo_turtle/run_test.sh
Labels: review-requested, python

#27575 add recipe for bokeh-fastapi
  recipes/bokeh-fastapi/meta.yaml
Labels: review-requested, python

#27689 Add recipe for red
  recipes/red-molsim/meta.yaml
Labels: review-requested, python
