Repository conda-forge/staged-recipes, pull requests merged in 2024-10, with the labels that each got.

#27723 Add recipe for human-dynamics-estimation packages
  recipes/human-dynamics-estimation/activate.msh
  recipes/human-dynamics-estimation/bld_cxx.bat
  recipes/human-dynamics-estimation/bld_py.bat
  recipes/human-dynamics-estimation/build_cxx.sh
  recipes/human-dynamics-estimation/build_py.sh
  recipes/human-dynamics-estimation/deactivate.msh
  recipes/human-dynamics-estimation/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27254 Add wagtail-draftail-plugins
  recipes/wagtail-draftail-plugins/recipe.yaml
Labels: review-requested, python

#27704 Add swmmanywhere
  recipes/swmmanywhere/meta.yaml
Labels: review-requested, python

#27639 Add nvidia-dali-python
  recipes/nvidia-dali-python/build.sh
  recipes/nvidia-dali-python/fix_nvimgcodec.diff
  recipes/nvidia-dali-python/meta.yaml
  recipes/nvidia-dali-python/use_shared_deps.diff
Labels: review-requested, c-cpp, python

#27733 Add jxlpy
  recipes/jxlpy/meta.yaml
Labels: review-requested, python, python-c

#27747 Add CatSmoothing
  recipes/catsmoothing/meta.yaml
Labels: review-requested, python

#27729 Adding aioretry
  recipes/aioretry/meta.yaml
Labels: review-requested, python

#27765 MNT: Implement [ci skip] for Azure
  azure-pipelines.yml
Labels: maintenance

#27681 Added r-pkggraphr as a package
  recipes/r-pkggraphr/bld.bat
  recipes/r-pkggraphr/build.sh
  recipes/r-pkggraphr/meta.yaml
Labels: R, staged-recipes, review-requested

#27682 Added r-cleanr as a package
  recipes/r-cleanr/bld.bat
  recipes/r-cleanr/build.sh
  recipes/r-cleanr/meta.yaml
Labels: R, staged-recipes, review-requested

#27769 Added type-lens as a package
  recipes/type-lens/meta.yaml
Labels: staged-recipes, review-requested, python

#27766 Add pyiron_dataclasses
  recipes/pyiron_dataclasses/meta.yaml
Labels: staged-recipes, review-requested, python

#27760 Add optopHyre
  recipes/optopHyre/meta.yaml
Labels: review-requested, python

#27465 Add einconv and curvlinops
  recipes/curvlinops-for-pytorch/recipe.yaml
  recipes/einconv/recipe.yaml
Labels: review-requested, python

#27737 Add pelicanfs
  recipes/pelicanfs/meta.yaml
Labels: review-requested, python

#27752 Add rms-vax recipe
  recipes/rms-vax/meta.yaml
Labels: staged-recipes, review-requested, python

#27770 Bump `vmImage` to `macos-13`
  .azure-pipelines/azure-pipelines-osx.yml
Labels: maintenance

#27775 Add sopsy
  recipes/sopsy/meta.yaml
Labels: review-requested, python

#27712 Add mget3
  recipes/mget3/meta.yaml
Labels: review-requested, python

#27790 add ddh, diskonaut, diskus, fclones
  recipes/ddh/bld.bat
  recipes/ddh/build.sh
  recipes/ddh/meta.yaml
  recipes/diskonaut/bld.bat
  recipes/diskonaut/build.sh
  recipes/diskonaut/meta.yaml
  recipes/diskus/bld.bat
  recipes/diskus/build.sh
  recipes/diskus/meta.yaml
  recipes/fclones/bld.bat
  recipes/fclones/build.sh
  recipes/fclones/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27792 add tere, xplr, zet
  recipes/tere/bld.bat
  recipes/tere/build.sh
  recipes/tere/meta.yaml
  recipes/xplr/bld.bat
  recipes/xplr/build.sh
  recipes/xplr/meta.yaml
  recipes/zet/bld.bat
  recipes/zet/build.sh
  recipes/zet/conda_build_config.yaml
  recipes/zet/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27791 add felix, fselect, joshuto, kondo
  recipes/felix/bld.bat
  recipes/felix/build.sh
  recipes/felix/meta.yaml
  recipes/fselect/bld.bat
  recipes/fselect/build.sh
  recipes/fselect/meta.yaml
  recipes/joshuto/build.sh
  recipes/joshuto/conda_build_config.yaml
  recipes/joshuto/meta.yaml
  recipes/kondo/bld.bat
  recipes/kondo/build.sh
  recipes/kondo/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27794 Added spiderweb-framework as a package
  recipes/spiderweb-framework/meta.yaml
Labels: staged-recipes, review-requested, python

#27793 Added streamable as a package
  recipes/streamable/meta.yaml
Labels: staged-recipes, review-requested, python

#27787 Added django-q2 as a package
  recipes/django-q2/meta.yaml
Labels: staged-recipes, review-requested, python

#27785 Added djade as a package
  recipes/djade/meta.yaml
Labels: R, staged-recipes, review-requested, python, rust

#27784 Added wordllama as a package
  recipes/wordllama/meta.yaml
Labels: staged-recipes, review-requested, c-cpp, python, python-c

#27788 add duf, gdu, godu
  recipes/duf/bld.bat
  recipes/duf/build.sh
  recipes/duf/meta.yaml
  recipes/gdu/bld.bat
  recipes/gdu/build.sh
  recipes/gdu/meta.yaml
  recipes/godu/bld.bat
  recipes/godu/build.sh
  recipes/godu/meta.yaml
Labels: staged-recipes, review-requested, go

#27789 add lf, llama, periscope
  recipes/lf/bld.bat
  recipes/lf/build.sh
  recipes/lf/meta.yaml
  recipes/llama/bld.bat
  recipes/llama/build.sh
  recipes/llama/meta.yaml
  recipes/periscope/bld.bat
  recipes/periscope/build.sh
  recipes/periscope/meta.yaml
Labels: staged-recipes, review-requested, go

#27758 add scifem
  recipes/scifem/42.patch
  recipes/scifem/build.sh
  recipes/scifem/conda_build_config.yaml
  recipes/scifem/recipe.yaml
Labels: review-requested, python-c

#27742 Add inplace-abn
  recipes/inplace-abn/build.sh
  recipes/inplace-abn/meta.yaml
Labels: review-requested, python, python-c

#27796 Add jh2
  recipes/jh2/meta.yaml
Labels: review-requested, python

#27778 add durationpy
  recipes/durationpy/meta.yaml
Labels: review-requested, python

#27805 Add splinkclickhouse as a package
  recipes/splinkclickhouse/meta.yaml
Labels: review-requested, python

#27804 Add pycallgraph recipe
  recipes/pycallgraphix/meta.yaml
Labels: review-requested, python

#27803 rename example-new-recipe to example-v1
  .ci_support/build_all.py
Labels: maintenance

#27273 Add skyrim and dependencies
  recipes/earth2mip/meta.yaml
  recipes/nvidia-modulus/meta.yaml
  recipes/skyrim/meta.yaml
Labels: review-requested, python

#27797 Distoptica
  recipes/distoptica/meta.yaml
Labels: review-requested, python

#27763 Add boutiques
  recipes/boutiques/meta.yaml
Labels: review-requested, python

#27764 Add pvandyken-deprecated
  recipes/pvandyken-deprecated/meta.yaml
Labels: review-requested, python

#27748 Add ixwebsocket
  recipes/ixwebsocket/build.sh
  recipes/ixwebsocket/meta.yaml
Labels: review-requested, c-cpp

#27799 Add urllib3-future
  recipes/urllib3-future/meta.yaml
Labels: review-requested, python

#27777 Adding diffpy.srmise
  recipes/diffpy.srmise/conda_build_config.yaml
  recipes/diffpy.srmise/meta.yaml
Labels: review-requested, python

#27786 Adding diffpy.fourigui
  recipes/diffpy.fourigui/conda_build_config.yaml
  recipes/diffpy.fourigui/meta.yaml
  recipes/diffpy.fourigui/run_test.bat
  recipes/diffpy.fourigui/run_test.sh
  recipes/diffpy.fourigui/yum_requirements.txt
Labels: review-requested, python

#27783 Add package mcplot
  recipes/mcplot/meta.yaml
Labels: review-requested, python

#27402 Adding snowflake.core
  recipes/snowflake.core/meta.yaml
Labels: review-requested, python

#27768 Add recipe for inference-server
  recipes/inference-server/meta.yaml
Labels: staged-recipes, review-requested, python

#27810 add amp, ark, bacon, bacon-ls, bartib
  recipes/amp/build.sh
  recipes/amp/meta.yaml
  recipes/ark/bld.bat
  recipes/ark/build.sh
  recipes/ark/meta.yaml
  recipes/bacon-ls/bld.bat
  recipes/bacon-ls/build.sh
  recipes/bacon-ls/meta.yaml
  recipes/bacon/bld.bat
  recipes/bacon/build.sh
  recipes/bacon/meta.yaml
  recipes/bartib/bld.bat
  recipes/bartib/build.sh
  recipes/bartib/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27811 add bkt, bottom, chars, choose-rust, csview
  recipes/bkt/bld.bat
  recipes/bkt/build.sh
  recipes/bkt/meta.yaml
  recipes/bottom/bld.bat
  recipes/bottom/build.sh
  recipes/bottom/meta.yaml
  recipes/chars/bld.bat
  recipes/chars/build.sh
  recipes/chars/meta.yaml
  recipes/choose-rust/bld.bat
  recipes/choose-rust/build.sh
  recipes/choose-rust/meta.yaml
  recipes/csview/bld.bat
  recipes/csview/build.sh
  recipes/csview/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27821 Add check-jsonschema
  recipes/check-jsonschema/meta.yaml
  recipes/regress/meta.yaml
Labels: review-requested, python

#27759 Adding `virtualship`
  recipes/virtualship/meta.yaml
Labels: staged-recipes, review-requested

#27718 mvapich
  recipes/mvapich2/build.sh
  recipes/mvapich2/meta.yaml
Labels: staged-recipes, review-requested

#27829 add pyrasa
  recipes/pyrasa/meta.yaml
Labels: staged-recipes, review-requested, python

#27823 Add propcache
  recipes/propcache/meta.yaml
Labels: review-requested, python

#27808 Add inplace-abn
  recipes/inplace-abn/build.sh
  recipes/inplace-abn/meta.yaml
Labels: review-requested, python

#27650 NEW: Add recipe for NVIDIA Performance Libraries (NVPL)
  recipes/libnvpl-blas/conda-forge.yml
  recipes/libnvpl-blas/conda_build_config.yaml
  recipes/libnvpl-blas/meta.yaml
  recipes/libnvpl-blas/test/CMakeLists.txt
  recipes/libnvpl-blas/test/all_headers.c
  recipes/libnvpl-blas/test/all_headers.cxx
  recipes/libnvpl-common/meta.yaml
  recipes/libnvpl-fft/conda-forge.yml
  recipes/libnvpl-fft/conda_build_config.yaml
  recipes/libnvpl-fft/meta.yaml
  recipes/libnvpl-fft/test/CMakeLists.txt
  recipes/libnvpl-fft/test/all_headers.c
  recipes/libnvpl-fft/test/all_headers.cxx
  recipes/libnvpl-lapack/conda-forge.yml
  recipes/libnvpl-lapack/conda_build_config.yaml
  recipes/libnvpl-lapack/meta.yaml
  recipes/libnvpl-lapack/test/CMakeLists.txt
  recipes/libnvpl-lapack/test/all_headers.c
  recipes/libnvpl-lapack/test/all_headers.cxx
  recipes/libnvpl-rand/conda-forge.yml
  recipes/libnvpl-rand/conda_build_config.yaml
  recipes/libnvpl-rand/meta.yaml
  recipes/libnvpl-rand/test/CMakeLists.txt
  recipes/libnvpl-rand/test/all_headers.c
  recipes/libnvpl-rand/test/all_headers.cxx
  recipes/libnvpl-scalapack/conda-forge.yml
  recipes/libnvpl-scalapack/conda_build_config.yaml
  recipes/libnvpl-scalapack/meta.yaml
  recipes/libnvpl-scalapack/test/CMakeLists.txt
  recipes/libnvpl-scalapack/test/all_headers.c
  recipes/libnvpl-scalapack/test/all_headers.cxx
  recipes/libnvpl-sparse/conda-forge.yml
  recipes/libnvpl-sparse/conda_build_config.yaml
  recipes/libnvpl-sparse/meta.yaml
  recipes/libnvpl-sparse/test/CMakeLists.txt
  recipes/libnvpl-sparse/test/all_headers.c
  recipes/libnvpl-sparse/test/all_headers.cxx
  recipes/libnvpl-tensor/conda-forge.yml
  recipes/libnvpl-tensor/conda_build_config.yaml
  recipes/libnvpl-tensor/meta.yaml
  recipes/libnvpl-tensor/test/CMakeLists.txt
  recipes/libnvpl-tensor/test/all_headers.c
  recipes/libnvpl-tensor/test/all_headers.cxx
  recipes/libnvpl/meta.yaml
Labels: review-requested, c-cpp, core

#27819 Add cbonsai, scdoc
  recipes/cbonsai/meta.yaml
  recipes/scdoc/meta.yaml
Labels: review-requested, c-cpp

#27410 Add recipe for MELODIES MONET
  recipes/melodies-monet/meta.yaml
Labels: review-requested, python

#27734 Add `jupyterlab-quickopen`
  recipes/jupyterlab-quickopen/meta.yaml
Labels: review-requested, python

#27813 add croc, cue, dependabot-cli
  recipes/croc/bld.bat
  recipes/croc/build.sh
  recipes/croc/meta.yaml
  recipes/cue/bld.bat
  recipes/cue/build.sh
  recipes/cue/meta.yaml
  recipes/dependabot-cli/bld.bat
  recipes/dependabot-cli/build.sh
  recipes/dependabot-cli/meta.yaml
Labels: staged-recipes, review-requested, go

#27812 add airy, akamai, ccat, checkmate
  recipes/airy/bld.bat
  recipes/airy/build.sh
  recipes/airy/meta.yaml
  recipes/akamai/bld.bat
  recipes/akamai/build.sh
  recipes/akamai/meta.yaml
  recipes/ccat/bld.bat
  recipes/ccat/build.sh
  recipes/ccat/meta.yaml
  recipes/checkmate/build.sh
  recipes/checkmate/license-files/github.com/golang/freetype/raster/ftl.txt
  recipes/checkmate/license-files/github.com/golang/freetype/raster/gpl.txt
  recipes/checkmate/license-files/github.com/golang/freetype/truetype/ftl.txt
  recipes/checkmate/license-files/github.com/golang/freetype/truetype/gpl.txt
  recipes/checkmate/meta.yaml
Labels: staged-recipes, review-requested, go

#27798 Add EnTT
  recipes/entt/bld.bat
  recipes/entt/build.sh
  recipes/entt/meta.yaml
Labels: review-requested, c-cpp

#27773 add ez-zarr recipe for conda-forge
  recipes/ez-zarr/meta.yaml
Labels: review-requested, python

#27771 Add aicspylibczi package
  recipes/aicspylibczi/bld.bat
  recipes/aicspylibczi/build.sh
  recipes/aicspylibczi/meta.yaml
Labels: review-requested, python

#27827 Adding tag-mne
  recipes/tag-mne/meta.yaml
Labels: staged-recipes, review-requested, python

#27577 recipe for trivy
  recipes/trivy/meta.yaml
Labels: review-requested, go

#27661 Added rocksdict as a package
  recipes/rocksdict/meta.yaml
Labels: R, staged-recipes, review-requested, python, python-c, rust

#27504 Adding ODL (Operator Discretization Library).
  recipes/odl/meta.yaml
Labels: review-requested, python

#27834 Add recipe for dive
  recipes/dive/bld.bat
  recipes/dive/build.sh
  recipes/dive/meta.yaml
Labels: staged-recipes, review-requested

#27735 Add swmm-toolkit
  recipes/swmm-toolkit/meta.yaml
Labels: review-requested, python-c

#27800 Add recipe for opensubdiv
  recipes/opensubdiv/bld.bat
  recipes/opensubdiv/build.sh
  recipes/opensubdiv/disable_install_of_static_libraries.patch
  recipes/opensubdiv/enable_shared_library_on_windows.patch
  recipes/opensubdiv/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27840 add fblog, fcp-rust, fend
  recipes/fblog/bld.bat
  recipes/fblog/build.sh
  recipes/fblog/meta.yaml
  recipes/fcp-rust/build.sh
  recipes/fcp-rust/conda_build_config.yaml
  recipes/fcp-rust/meta.yaml
  recipes/fend/build.sh
  recipes/fend/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27846 Add libmaxxminddb
  recipes/libmaxminddb/meta.yaml
Labels: review-requested, c-cpp

#27837 add efm-langserver, f2, fq, fx, gaze
  recipes/efm-langserver/bld.bat
  recipes/efm-langserver/build.sh
  recipes/efm-langserver/meta.yaml
  recipes/f2/bld.bat
  recipes/f2/build.sh
  recipes/f2/meta.yaml
  recipes/fq/bld.bat
  recipes/fq/build.sh
  recipes/fq/meta.yaml
  recipes/fx/bld.bat
  recipes/fx/build.sh
  recipes/fx/license-files/github.com/mattn/go-localereader/LICENSE
  recipes/fx/meta.yaml
  recipes/gaze/bld.bat
  recipes/gaze/build.sh
  recipes/gaze/meta.yaml
Labels: staged-recipes, review-requested, go

#27851 Added pephubclient
  recipes/pephubclient/meta.yaml
Labels: review-requested, python

#27839 add diffsitter, dioxus, dua-cli, earthlyls, eva
  recipes/diffsitter/bld.bat
  recipes/diffsitter/build.sh
  recipes/diffsitter/meta.yaml
  recipes/dioxus/bld.bat
  recipes/dioxus/build.sh
  recipes/dioxus/conda_build_config.yaml
  recipes/dioxus/meta.yaml
  recipes/dua-cli/bld.bat
  recipes/dua-cli/build.sh
  recipes/dua-cli/meta.yaml
  recipes/earthlyls/bld.bat
  recipes/earthlyls/build.sh
  recipes/earthlyls/meta.yaml
  recipes/eva/bld.bat
  recipes/eva/build.sh
  recipes/eva/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27852 add stdlib to example recipe
  recipes/example/meta.yaml
Labels: maintenance

#27825 Add rush
  recipes/rush/bld.bat
  recipes/rush/build.sh
  recipes/rush/meta.yaml
Labels: review-requested, go

#27856 Added tree-sitter-python as a package
  recipes/tree-sitter-python/meta.yaml
Labels: staged-recipes, review-requested, python-c

#27847 Add goaccess
  recipes/goaccess/0001-Patch-libncursesw-naming-on-darwin.patch
  recipes/goaccess/meta.yaml
Labels: review-requested, c-cpp

#27859 Adding mlrose-ky recipe
  recipes/mlrose-ky/meta.yaml
Labels: staged-recipes, review-requested, python

#27740 Add multiwebcam
  recipes/multiwebcam/meta.yaml
Labels: review-requested, python

#27860 Add flake8-deprecated recipe
  recipes/flake8-deprecated/meta.yaml
Labels: staged-recipes, review-requested, python

#27094 Add openqdc
  recipes/openqdc/meta.yaml
Labels: review-requested, python

#27824 Add Numbat
  recipes/numbat/bld.bat
  recipes/numbat/build.sh
  recipes/numbat/meta.yaml
Labels: R, review-requested, rust

#27776 Adding diffpy.labpdfproc
  recipes/diffpy.labpdfproc/meta.yaml
Labels: review-requested, python

#27715 add torchaudio
  recipes/torchaudio/build.sh
  recipes/torchaudio/patches/0001-point-to-correct-prefix.patch
  recipes/torchaudio/patches/0002-use-conda-cuda.patch
  recipes/torchaudio/patches/0003-Apply-CMAKE_ARGS-if-set.patch
  recipes/torchaudio/patches/0004-add-missing-ffmpeg-skip.patch
  recipes/torchaudio/recipe.yaml
  recipes/torchaudio/run_tests.sh
Labels: review-requested, c-cpp

#27868 Add recipe for mdformat-ruff generated with grayskull
  recipes/mdformat-ruff/meta.yaml
Labels: review-requested, python

#27866 add flux-lsp, gitoxide, gleam, gpg-tui, grex
  recipes/flux-lsp/build.sh
  recipes/flux-lsp/meta.yaml
  recipes/gitoxide/bld.bat
  recipes/gitoxide/build.sh
  recipes/gitoxide/meta.yaml
  recipes/gleam/bld.bat
  recipes/gleam/build.sh
  recipes/gleam/meta.yaml
  recipes/gpg-tui/build.sh
  recipes/gpg-tui/meta.yaml
  recipes/grex/bld.bat
  recipes/grex/build.sh
  recipes/grex/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27871 Add foamlib
  recipes/foamlib/meta.yaml
Labels: review-requested, python

#27869 Adding `cz-changeup`
  recipes/cz-changeup/meta.yaml
Labels: review-requested, python

#27858 Add fontawesome font
  recipes/font-otf-fontawesome/build.sh
  recipes/font-otf-fontawesome/meta.yaml
Labels: staged-recipes, review-requested

#27705 Add qcs-api-client-common (needed by qcs-sdk-python, which needed by pyquil)
  recipes/qcs-api-client-common/bld.bat
  recipes/qcs-api-client-common/build.sh
  recipes/qcs-api-client-common/install.bat
  recipes/qcs-api-client-common/install.sh
  recipes/qcs-api-client-common/meta.yaml
Labels: R, review-requested, python, rust

#27476 Add `libblst`
  recipes/libblst/bld.bat
  recipes/libblst/build.sh
  recipes/libblst/helpers/update_win_cflags.ps1
  recipes/libblst/meta.yaml
  recipes/libblst/patches/0001-win-simplify-build.sh.patch
Labels: review-requested, c-cpp

#27710 Adding cb-clipboard
  recipes/cb-clipboard/bld.bat
  recipes/cb-clipboard/build.sh
  recipes/cb-clipboard/conda_build_config.yaml
  recipes/cb-clipboard/meta.yaml
Labels: review-requested, c-cpp

#27058 added kvrocks recipe
  recipes/kvrocks/build.sh
  recipes/kvrocks/meta.yaml
Labels: staged-recipes, review-requested

#27874 fix: lint for teams in cf; allow cuda to go ahead
  .github/workflows/scripts/linter.py
Labels: maintenance

#27658 Quixstreams
  recipes/quixstreams/meta.yaml
Labels: staged-recipes, review-requested, python

#27883 Add langgraph-sdk
  recipes/langgraph-sdk/meta.yaml
Labels: staged-recipes, review-requested, python

#27879 Add super-collections
  recipes/super-collections/meta.yaml
Labels: review-requested, python

#27849 Added new package -- altair-aitools-devkit
  recipes/altair-aitools-devkit/conda_build_config.yaml
  recipes/altair-aitools-devkit/meta.yaml
Labels: review-requested, python

#27875 Added recipe for caf.base
  recipes/caf.base/meta.yaml
Labels: review-requested, python

#27887 recipe for slurmgen
  recipes/slurmgen/meta.yaml
Labels: staged-recipes, review-requested, python

#27854 add recipe for r-autometric from conda_r_skeleton_helper
  recipes/r-autometric/bld.bat
  recipes/r-autometric/build.sh
  recipes/r-autometric/meta.yaml
Labels: R, review-requested

#27767 MNT: Use `D:` drive in Windows
  .azure-pipelines/azure-pipelines-win.yml
Labels: maintenance

#27835 Add binsider
  recipes/binsider/bld.bat
  recipes/binsider/build.sh
  recipes/binsider/meta.yaml
Labels: R, review-requested, rust

#27889 recipe for scisave
  recipes/scisave/meta.yaml
Labels: review-requested, python

#27890 Add pettingzoo python recipe
  recipes/pettingzoo/meta.yaml
Labels: review-requested, python

#27896 add languagetool-rust, lelwel, lsd-rust, macchina, mako-rust
  recipes/languagetool-rust/bld.bat
  recipes/languagetool-rust/build.sh
  recipes/languagetool-rust/meta.yaml
  recipes/lelwel/bld.bat
  recipes/lelwel/build.sh
  recipes/lelwel/meta.yaml
  recipes/lsd-rust/bld.bat
  recipes/lsd-rust/build.sh
  recipes/lsd-rust/meta.yaml
  recipes/macchina/bld.bat
  recipes/macchina/build.sh
  recipes/macchina/meta.yaml
  recipes/mako-rust/build.sh
  recipes/mako-rust/conda_build_config.yaml
  recipes/mako-rust/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27753 MNT: Use micromamba to provision base environment on macOS and Windows
  .azure-pipelines/azure-pipelines-osx.yml
  .azure-pipelines/azure-pipelines-win.yml
  .scripts/run_osx_build.sh
  .scripts/run_win_build.bat
Labels: maintenance

#27902 Add recipe for mdformat-footnote
  recipes/mdformat-footnote/meta.yaml
Labels: review-requested, python

#27899 Add torch-dftd
  recipes/torch-dftd/meta.yaml
Labels: staged-recipes, review-requested, python

#27911 Add legacy-cgi
  recipes/legacy-cgi/meta.yaml
Labels: review-requested, python

#27905 Add bioat 0.12.15
  recipes/bioat/meta.yaml
Labels: review-requested, python

#27884 Adding gpyconform recipe
  recipes/gpyconform/meta.yaml
Labels: staged-recipes, review-requested, python

#27907 Add lightrag-hku and nano-vectordb
  recipes/lightrag-hku/meta.yaml
  recipes/lightrag-hku/requirements.patch
  recipes/lightrag-hku/setup.patch
  recipes/nano-vectordb/LICENSE
  recipes/nano-vectordb/meta.yaml
  recipes/nano-vectordb/requirements.patch
Labels: staged-recipes, review-requested, python

#27920 Add timefiller recipe
  recipes/timefiller/meta.yaml
Labels: review-requested, python

#27914 Add recipes for "hats" and "hats-import"
  recipes/hats-import/meta.yaml
  recipes/hats/meta.yaml
Labels: review-requested, python

#27922 Add playwright-stealth
  recipes/playwright-stealth/meta.yaml
Labels: staged-recipes, review-requested, python

#27924 Add apyxl recipe
  recipes/apyxl/meta.yaml
Labels: review-requested, python

#27928 Add pyironflow
  recipes/pyironflow/meta.yaml
Labels: nodejs, staged-recipes, review-requested, python

#27935 Add quantile-forest
  recipes/quantile-forest/meta.yaml
Labels: review-requested, python

#27927 Add pytest-playwright
  recipes/ pytest-playwright/meta.yaml
Labels: review-requested, python

#27931 Add Bspline
  recipes/bspline/meta.yaml
Labels: staged-recipes, review-requested, python

#27943 Add griffe-pydantic
  recipes/griffe-pydantic/meta.yaml
Labels: review-requested, python

#27942 Add recipe for httpx-gssapi.
  recipes/httpx-gssapi/meta.yaml
Labels: staged-recipes, review-requested, python

#27944 Adding firewxpy recipe
  recipes/firewxpy/meta.yaml
Labels: review-requested, python

#27941 Add twemoji font
  recipes/font-ttf-twemoji/recipe.yaml
Labels: staged-recipes, review-requested

#27940 Add rubik font
  recipes/font-ttf-rubik/recipe.yaml
Labels: staged-recipes, review-requested

#27947 Add jumanji
  recipes/jumanji/recipe.yaml
  recipes/jumanji/relax-matplotlib-pin.patch
Labels: review-requested, python

#27948 Add nebula3-python
  recipes/nebula3-python/LICENSE
  recipes/nebula3-python/meta.yaml
Labels: staged-recipes, review-requested, python

#27956 Add package gaiaxpy
  recipes/gaiaxpy/LICENCE
  recipes/gaiaxpy/meta.yaml
Labels: review-requested, python

#26704 add package ogs
  recipes/ogs/build.sh
  recipes/ogs/meta.yaml
Labels: Awaiting author contribution, c-cpp

#27904 Add git-privacy
  recipes/git-privacy/recipe.yaml
Labels: review-requested, python

#27953 Add recipe for pyarrow-stubs
  recipes/pyarrow-stubs/meta.yaml
Labels: review-requested, python

#27952 add rancher-cli 2.9.2
  recipes/rancher-cli/bld.bat
  recipes/rancher-cli/build.sh
  recipes/rancher-cli/meta.yaml
Labels: review-requested, go

#27957 Add `nomino`
  recipes/nomino/bld.bat
  recipes/nomino/build.sh
  recipes/nomino/meta.yaml
Labels: R, review-requested, rust

#27933 Add mira-omf, las-geoh5, lasio and simpeg-drivers
  recipes/las-geoh5/meta.yaml
  recipes/lasio/meta.yaml
  recipes/mira-omf/meta.yaml
  recipes/simpeg-drivers/meta.yaml
Labels: review-requested, python

#27963 Add sevenn
  recipes/sevenn/meta.yaml
Labels: staged-recipes, review-requested, python

#27965 Add b2 and dependencies
  recipes/b2/meta.yaml
  recipes/b2sdk/meta.yaml
  recipes/logfury/meta.yaml
  recipes/phx-class-registry/meta.yaml
  recipes/rst2ansi/LICENSE
  recipes/rst2ansi/meta.yaml
Labels: review-requested, python

#27971 Add matchpoint
  recipes/matchpoint/meta.yaml
Labels: review-requested, python

#27962 Adding initial recipe for pyspatialstats
  recipes/pyspatialstats/meta.yaml
Labels: review-requested, python

#27848 Adding phasefieldx package
  recipes/phasefieldx/meta.yaml
Labels: staged-recipes, review-requested, python

#27968 add openonload
  .azure-pipelines/azure-pipelines-linux.yml
  .ci_support/linux64.yaml
  recipes/openonload/build.sh
  recipes/openonload/conda_build_config.yaml
  recipes/openonload/meta.yaml
Labels: staged-recipes, review-requested

#27850 Add ofxhome 0.3.3 via Grayskull
  recipes/ofxhome/LICENSE
  recipes/ofxhome/meta.yaml
Labels: staged-recipes, review-requested

#27976 Add tcpdirect
  recipes/tcpdirect/build.sh
  recipes/tcpdirect/conda_build_config.yaml
  recipes/tcpdirect/install.diff
  recipes/tcpdirect/meta.yaml
Labels: review-requested, c-cpp

#27977 Revert "temporarily update the docker image name"
  .azure-pipelines/azure-pipelines-linux.yml
  .ci_support/linux64.yaml
Labels: maintenance

#27985 Add recipe for pysmiles
  recipes/pysmiles/meta.yaml
Labels: review-requested, python

#27989 feat: Add ccorp-yaml-include-relative-path
  recipes/ccorp-yaml-include-relative-path/meta.yaml
Labels: review-requested, python

#27981 Adding defectpl recipe
  recipes/defectpl/LICENSE
  recipes/defectpl/meta.yaml
Labels: review-requested, python
