Repository conda-forge/staged-recipes, pull requests merged in 2024-06, with the labels that each got.

#26528 Add pynucastro
  recipes/pynucastro/meta.yaml
Labels: review-requested, python

#26522 Adding snompy package
  recipes/snompy/meta.yaml
Labels: staged-recipes, review-requested, python

#26333 Add C package xsel recipe
  recipes/xsel/build.sh
  recipes/xsel/conda-forge.yml
  recipes/xsel/meta.yaml
Labels: review-requested, c-cpp

#26531 Add dash-pydantic-form recipe
  recipes/dash-pydantic-form/meta.yaml
Labels: review-requested, python

#26165 Add C package xclip recipe
  recipes/xclip/build.sh
  recipes/xclip/conda-forge.yml
  recipes/xclip/meta.yaml
Labels: review-requested, c-cpp, python-c

#26254 Add C package xdotool recipe
  recipes/xdotool/build.sh
  recipes/xdotool/conda-forge.yml
  recipes/xdotool/meta.yaml
Labels: review-requested, c-cpp

#26256 Add C package wmctrl-cli recipe
  recipes/wmctrl-cli/build.sh
  recipes/wmctrl-cli/conda-forge.yml
  recipes/wmctrl-cli/meta.yaml
  recipes/wmctrl-cli/wmctrl.patch
Labels: review-requested, c-cpp

#26242 Add X11 package xorg-libxcvt recipe
  recipes/xorg-libxcvt/bld.bat
  recipes/xorg-libxcvt/build.sh
  recipes/xorg-libxcvt/conda-forge.yml
  recipes/xorg-libxcvt/meta.yaml
Labels: review-requested, c-cpp

#26538 Add windows-default-manifest
  recipes/windows-default-manifest/conda-forge.yml
  recipes/windows-default-manifest/conda_build_config.yaml
  recipes/windows-default-manifest/install.sh
  recipes/windows-default-manifest/meta.yaml
Labels: review-requested, c-cpp

#26533 Add backends
  recipes/backends/meta.yaml
Labels: review-requested, python

#26534 Add fdm
  recipes/fdm/meta.yaml
Labels: review-requested, python

#26542 feat: add ansys-api-platform-instancemanagement
  recipes/ansys-api-platform-instancemanagement/meta.yaml
Labels: review-requested, python

#26530 add quill recipe
  recipes/quill/bld.bat
  recipes/quill/build.sh
  recipes/quill/meta.yaml
  recipes/quill/patches/fix.patch
Labels: staged-recipes, review-requested, c-cpp

#26540 Add pygsl
  recipes/pygsl/meta.yaml
Labels: review-requested, python

#26545 Add types-influxdb-client
  recipes/types-influxdb-client/meta.yaml
Labels: review-requested, python

#26442 Add m2w64-sysroot
  recipes/m2w64-sysroot/0001-Allow-to-use-bessel-and-complex-functions-without-un.patch
  recipes/m2w64-sysroot/0002-heades-add-full-name-winrt.patch
  recipes/m2w64-sysroot/build.sh
  recipes/m2w64-sysroot/conda-forge.yml
  recipes/m2w64-sysroot/conda_build_config.yaml
  recipes/m2w64-sysroot/copy.sh
  recipes/m2w64-sysroot/install.sh
  recipes/m2w64-sysroot/meta.yaml
  recipes/m2w64-sysroot/yum_requirements.txt
Labels: review-requested, c-cpp

#26546 feat: add ansys-tools-visualization-interface
  recipes/ansys-tools-visualization-interface/meta.yaml
  recipes/ansys-tools-visualization-interface/yum_requirements.txt
Labels: review-requested, python

#26554 add `gliner`
  recipes/gliner/meta.yaml
Labels: review-requested, python

#26553 add smbfs
  recipes/fs.smbfs/meta.yaml
Labels: review-requested, python

#26557 Add grep-ast
  recipes/grep-ast/meta.yaml
Labels: staged-recipes, review-requested, python

#26560 Add pyairports
  recipes/pyairports/meta.yaml
Labels: review-requested, python

#26552 Add ersilia recipe
  recipes/ersilia/meta.yaml
Labels: review-requested, python

#25204 Added GeoFabrics package - created with GraySkull
  recipes/geofabrics/meta.yaml
Labels: review-requested, python

#26565 add dialectid
  recipes/dialectid/meta.yaml
Labels: review-requested, python

#26567 adding `sourmash_plugin_directsketch` (python/rust)
  recipes/sourmash_plugin_directsketch/build.sh
  recipes/sourmash_plugin_directsketch/meta.yaml
Labels: review-requested, python

#26548 Add Fortran program 'dimad'
  recipes/dimad/bld.bat
  recipes/dimad/build.sh
  recipes/dimad/meta.yaml
Labels: staged-recipes, review-requested

#26576 Add symfc recipe
  recipes/symfc/meta.yaml
Labels: review-requested, python

#26575 Add package conda-protect to conda-forge
  recipes/conda-protect/meta.yaml
Labels: review-requested, python

#26574 Add tecio
  recipes/tecio/meta.yaml
Labels: staged-recipes, review-requested, python

#26569 Add gendef
  recipes/gendef/build.sh
  recipes/gendef/conda-forge.yml
  recipes/gendef/meta.yaml
Labels: review-requested, c-cpp

#26578 Set c_stdlib_version for macos
  .ci_support/osx64.yaml
Labels: staged-recipes, review-requested

#26579 Add tbparse
  recipes/tbparse/meta.yaml
Labels: review-requested, python

#26260 Add spacy-universal-sentence-encoder
  recipes/spacy-universal-sentence-encoder/meta.yaml
Labels: review-requested, python

#26591 Adding pyhepmc 2.13.4
  recipes/pyhepmc/meta.yaml
Labels: review-requested, python

#26612 Add r-box.linters
  recipes/r-box.linters/bld.bat
  recipes/r-box.linters/build.sh
  recipes/r-box.linters/meta.yaml
Labels: R, review-requested

#26586 Add async-property
  recipes/async-property/meta.yaml
Labels: staged-recipes, review-requested, python

#26582 Add ncompare noarch Python package
  recipes/ncompare/meta.yaml
Labels: review-requested, python

#26597 Add playwright and playwright-python - unix only
  recipes/playwright-python/auditwheel.patch
  recipes/playwright-python/driver.patch
  recipes/playwright-python/meta.yaml
  recipes/playwright-python/setup.patch
  recipes/playwright/build.sh
  recipes/playwright/meta.yaml
Labels: nodejs, staged-recipes, review-requested, python

#26581 add taskgroup 0.0.0a4
  recipes/taskgroup/meta.yaml
Labels: review-requested, python

#26615 Add django-csvimport
  recipes/django-csvimport/meta.yaml
Labels: review-requested, python

#26585 feat: add ansys-geometry-core
  recipes/ansys-geometry-core/meta.yaml
Labels: staged-recipes, review-requested, python

#26616 Add setuptools-git-version
  recipes/setuptools-git-version/LICENSE
  recipes/setuptools-git-version/meta.yaml
Labels: review-requested, python

#26618 Add django-excel-tools
  recipes/django-excel-tools/meta.yaml
Labels: review-requested, python

#26619 Add pinyin
  recipes/pinyin/meta.yaml
Labels: review-requested, python

#26609 Add langgraph
  recipes/langgraph/meta.yaml
Labels: staged-recipes, review-requested, python

#26608 Add jaraco.test
  recipes/jaraco.test/meta.yaml
Labels: staged-recipes, review-requested, python

#26605 Add upsonic
  recipes/mgzip/LICENSE
  recipes/mgzip/meta.yaml
  recipes/upsonic/meta.yaml
Labels: staged-recipes, review-requested, python

#26556 Add burstH2MM
  recipes/bursth2mm/meta.yaml
Labels: review-requested, python

#26562 Add ivmodels to conda-forge
  recipes/ivmodels/meta.yaml
Labels: review-requested, python

#26620 Add meshcat-shapes
  recipes/meshcat-shapes/meta.yaml
Labels: review-requested, python

#26607 Add pysoundcard
  recipes/pysoundcard/conda-forge.yml
  recipes/pysoundcard/meta.yaml
Labels: staged-recipes, review-requested, python

#26593 Add vhs
  recipes/vhs/meta.yaml
Labels: review-requested, go

#26610 Add typstyle
  recipes/typstyle/bld.bat
  recipes/typstyle/build.sh
  recipes/typstyle/meta.yaml
Labels: review-requested, rust

#26537 added aws-s3-cli
  recipes/aws-s3-cli/meta.yaml
  recipes/text-encrypt-decrypt/meta.yaml
Labels: review-requested, go, python

#26626 Add ftpretty
  recipes/ftpretty/meta.yaml
Labels: review-requested, python

#26631 Add flexcache
  recipes/flexcache/meta.yaml
Labels: staged-recipes, review-requested, python

#26632 Add flexparser
  recipes/flexparser/meta.yaml
Labels: staged-recipes, review-requested, python

#26604 Add aider
  recipes/aider/LICENSE.txt
  recipes/aider/meta.yaml
Labels: staged-recipes, review-requested, python

#26555 Adding crane
  recipes/crane/conda_build_config.yaml
  recipes/crane/meta.yaml
Labels: review-requested, go

#26635 Adding sseclient-py recipe
  recipes/sseclient-py/meta.yaml
Labels: review-requested, python

#26642 add fast-barnes-py
  recipes/fast-barnes-py/meta.yaml
  recipes/fast-barnes-py/missing_long_description.patch
Labels: review-requested, python

#26630 Adding resolvo-cpp
  recipes/resolvo-cpp/bld.bat
  recipes/resolvo-cpp/build.sh
  recipes/resolvo-cpp/meta.yaml
Labels: review-requested, c-cpp

#26568 add actionlint 1.7.1
  recipes/actionlint/bld.bat
  recipes/actionlint/build.sh
  recipes/actionlint/build_win.sh
  recipes/actionlint/conda_build_config.yaml
  recipes/actionlint/meta.yaml
Labels: staged-recipes, review-requested, go

#26614 Add deptry
  recipes/deptry/meta.yaml
Labels: review-requested, python-c

#26563 Add @conda-forge/help-go to pull_request_template.md
  .github/pull_request_template.md
Labels: staged-recipes, review-requested

#26598 add kornia-rs recipe
  recipes/kornia-rs/bld.bat
  recipes/kornia-rs/build.sh
  recipes/kornia-rs/meta.yaml
Labels: R, review-requested, python, rust

#26561 Add act recipe
  recipes/act/build.sh
  recipes/act/meta.yaml
Labels: review-requested, go

#26118 Add Leiningen
  recipes/leiningen/COPYING
  recipes/leiningen/bld.bat
  recipes/leiningen/build.sh
  recipes/leiningen/meta.yaml
  recipes/leiningen/scripts/activate.bat
  recipes/leiningen/scripts/lein.bat
Labels: review-requested, java

#24496 add surelog
  recipes/surelog/build.sh
  recipes/surelog/meta.yaml
Labels: review-requested, c-cpp

#26590 Add typst-lsp
  recipes/typst-lsp/bld.bat
  recipes/typst-lsp/build.sh
  recipes/typst-lsp/meta.yaml
Labels: review-requested, rust

#26641 Adding alpaca-py recipe
  recipes/alpaca-py/meta.yaml
Labels: review-requested, python

#26644 Add ghtoken
  recipes/ghtoken/meta.yaml
Labels: review-requested, python

#26650 Add recipe for `conda-pypi`
  recipes/conda-pypi/meta.yaml
Labels: staged-recipes, review-requested, python

#26648 add sphericaltexture
  recipes/SphericalTexture/LICENSE
  recipes/SphericalTexture/meta.yaml
Labels: review-requested, python

#26654 added recipe for compas_model
  recipes/compas_model/meta.yaml
Labels: review-requested, python

#26636 Add amazon-sagemaker-jupyter-ai-q-developer recipe
  recipes/amazon-sagemaker-jupyter-ai-q-developer/meta.yaml
Labels: review-requested, python

#26649 Add amazon-q-developer-jupyterlab-ext recipe
  recipes/amazon-q-developer-jupyterlab-ext/meta.yaml
Labels: review-requested, python

#26655 Added radicli as a package
  recipes/radicli/meta.yaml
Labels: staged-recipes, review-requested, python

#26480 Add Kustomize
  recipes/kustomize/build.sh
  recipes/kustomize/meta.yaml
Labels: staged-recipes, review-requested, go

#26343 add libtinyspline
  recipes/libtinyspline/meta.yaml
Labels: review-requested, c-cpp

#25590 add `silicon`
  recipes/silicon/build.sh
  recipes/silicon/meta.yaml
Labels: R, review-requested, rust

#26658 Add py2cfg
  recipes/py2cfg/meta.yaml
  recipes/py2cfg/pyproject.patch
  recipes/websocket-server/meta.yaml
Labels: staged-recipes, review-requested, python

#26662 Add gspread-dataframe
  recipes/gspread-dataframe/meta.yaml
Labels: review-requested, python

#25216 ENH: Add asv_bench_memray
  recipes/asv_bench_memray/LICENSE
  recipes/asv_bench_memray/meta.yaml
Labels: review-requested, python

#26447 Add charidotella + deps
  recipes/charidotella/LICENSE
  recipes/charidotella/meta.yaml
  recipes/charidotella/unvendor_command_line_tools.patch
  recipes/colourtime/LICENSE
  recipes/colourtime/meta.yaml
  recipes/command_line_tools/CMakeLists.txt
  recipes/command_line_tools/build.sh
  recipes/command_line_tools/meta.yaml
  recipes/event-stream/LICENSE
  recipes/event-stream/meta.yaml
Labels: review-requested, python-c

#26435 adding r-equalityml via github source tarball
  recipes/r-equalityml/bld.bat
  recipes/r-equalityml/build.sh
  recipes/r-equalityml/meta.yaml
Labels: R, review-requested

#26652 Adding ib_async recipe
  recipes/ib_async/meta.yaml
Labels: review-requested, python

#26474 Add grayskull-generated recipe for gym-pusht
  recipes/gym-pusht/meta.yaml
Labels: staged-recipes, review-requested, python

#23378 Adding mariadb
  recipes/mariadb/bld.bat
  recipes/mariadb/build.sh
  recipes/mariadb/meta.yaml
Labels: review-requested, python

#26656 add jschon
  recipes/jschon/meta.yaml
Labels: review-requested, python

#26592 Add mpackview
  recipes/mpackview/LICENSE
  recipes/mpackview/meta.yaml
  recipes/mpackview/yum_requirements.txt
Labels: review-requested, python

#26529 add iotop
  recipes/iotop/meta.yaml
Labels: review-requested, c-cpp

#26673 Adding `textgrad` from PyPI
  recipes/textgrad/meta.yaml
Labels: review-requested, python

#26665 Add minimal_molview
  recipes/minimal_molview/meta.yaml
Labels: review-requested, python

#26517 contribute hklpy2 package
  recipes/hklpy2/meta.yaml
Labels: staged-recipes, review-requested, python

#26621 add gridemissions 0.1.3 from PyPI
  recipes/gridemissions/meta.yaml
Labels: review-requested, python

#26676 Add pyserini
  recipes/pyserini/meta.yaml
  recipes/pyserini/setup.patch
Labels: staged-recipes, review-requested, java, python

#26677 Add metalearners.
  recipes/metalearners/meta.yaml
Labels: review-requested, python

#26689 Add forallpeople to conda-forge
  recipes/forallpeople/meta.yaml
Labels: staged-recipes, review-requested, python

#26668 Adding rq_scheduler recipe
  recipes/rq_scheduler/meta.yaml
Labels: review-requested, python

#26671 Add ipecharts
  recipes/ipecharts/meta.yaml
Labels: review-requested, python

#26674 Add choppa package
  recipes/choppa/meta.yaml
Labels: review-requested, python

#26696 Add ocifs
  recipes/ocifs/meta.yaml
Labels: staged-recipes, review-requested, python

#26702 Add azure-search-documents
  recipes/azure-search-documents/meta.yaml
Labels: staged-recipes, review-requested, python

#26700 Add httpx-sse
  recipes/httpx-sse/meta.yaml
Labels: staged-recipes, review-requested, python

#26691 Add upstash-redis and upstash-ratelimit
  recipes/upstash-ratelimit/meta.yaml
  recipes/upstash-redis/meta.yaml
Labels: staged-recipes, review-requested, python

#26690 Add azure-ai-documentintelligence
  recipes/azure-ai-documentintelligence/meta.yaml
Labels: staged-recipes, review-requested, python

#26693 Add premai
  recipes/premai/LICENSE
  recipes/premai/meta.yaml
Labels: staged-recipes, review-requested, python

#26697 Add oracle-ads
  recipes/oracle-ads/meta.yaml
  recipes/python_jsonschema_objects/meta.yaml
Labels: staged-recipes, review-requested, python

#26699 Add friendli-client
  recipes/friendli-client/meta.yaml
Labels: staged-recipes, review-requested, python

#26698 Add gradientai
  recipes/gradientai/LICENSE
  recipes/gradientai/meta.yaml
Labels: staged-recipes, review-requested, python

#26701 Add fireworks-ai
  recipes/fireworks-ai/meta.yaml
Labels: staged-recipes, review-requested, python

#26703 add ariadne-codegen
  recipes/ariadne-codegen/meta.yaml
Labels: review-requested, python

#26679 add xarray-selafin
  recipes/xarray-selafin/meta.yaml
Labels: review-requested, python

#26695 Add vdms
  recipes/vdms/LICENSE
  recipes/vdms/meta.yaml
Labels: staged-recipes, review-requested, python

#26489 Add "pdgstaging"
  recipes/pdgstaging/meta.yaml
Labels: review-requested, python

#26686 Add sagemaker-mlflow recipe
  recipes/sagemaker-mlflow/meta.yaml
Labels: staged-recipes, review-requested, python

#26709 Add langchain-fireworks
  recipes/langchain-fireworks/meta.yaml
Labels: staged-recipes, review-requested, python

#26714 Add langchain-azure-dynamic-sessions
  recipes/langchain-azure-dynamic-sessions/meta.yaml
Labels: staged-recipes, review-requested, python

#26713 Add langchain-chroma
  recipes/langchain-chroma/meta.yaml
Labels: staged-recipes, review-requested, python

#26716 Add langchain-together
  recipes/langchain-together/meta.yaml
Labels: staged-recipes, review-requested, python

#26715 Add langchain-voyageai and voyageai
  recipes/langchain-voyageai/meta.yaml
  recipes/voyageai/meta.yaml
Labels: staged-recipes, review-requested, python

#26717 Add langchain-prompty
  recipes/langchain-prompty/meta.yaml
Labels: staged-recipes, review-requested, python

#26721 Add langchain-mongodb
  recipes/langchain-mongodb/meta.yaml
Labels: staged-recipes, review-requested, python

#26719 Add langchain-qdrant
  recipes/langchain-qdrant/meta.yaml
Labels: staged-recipes, review-requested, python

#26718 Add langchain-robocorp
  recipes/langchain-robocorp/meta.yaml
Labels: staged-recipes, review-requested, python

#26720 Add langchain-nomic and nomic
  recipes/langchain-nomic/meta.yaml
  recipes/nomic/LICENSE
  recipes/nomic/meta.yaml
Labels: staged-recipes, review-requested, python

#26722 Add langchain-mistralai
  recipes/langchain-mistralai/meta.yaml
Labels: staged-recipes, review-requested, python

#26707 Adding `BenchPOTS` from PyPI
  recipes/benchpots/meta.yaml
Labels: review-requested, python

#26599 Add IJava recipe
  recipes/ijava/bld.bat
  recipes/ijava/build.sh
  recipes/ijava/meta.yaml
  recipes/ijava/run_test.py
Labels: review-requested, java

#26726 Add fx-gltf
  recipes/fx-gltf/bld.bat
  recipes/fx-gltf/build.sh
  recipes/fx-gltf/exclude-apple-from-stdc++fs-linking.patch
  recipes/fx-gltf/meta.yaml
Labels: review-requested, c-cpp

#26729 Add Dispenso
  recipes/dispenso/bld.bat
  recipes/dispenso/build.sh
  recipes/dispenso/disable-install-gtest.patch
  recipes/dispenso/meta.yaml
Labels: review-requested, c-cpp

#26734 Add drjit-cpp
  recipes/drjit-cpp/bld.bat
  recipes/drjit-cpp/build.sh
  recipes/drjit-cpp/disable-broken-tests.patch
  recipes/drjit-cpp/disable-trig-test-on-apple.patch
  recipes/drjit-cpp/include-tuple.patch
  recipes/drjit-cpp/meta.yaml
  recipes/drjit-cpp/test-avx512-support.patch
  recipes/drjit-cpp/use-system-robin-map.patch
Labels: review-requested, c-cpp

#26733 Add albucore
  recipes/albucore/meta.yaml
  recipes/albucore/yum_requirements.txt
Labels: review-requested, python

#26737 Add llama-cloud
  recipes/llama-cloud/meta.yaml
Labels: staged-recipes, review-requested, python

#26524 Adding nessai-bilby
  recipes/nessai-bilby/meta.yaml
Labels: review-requested, python

#26744 add tminterface and bytefield
  recipes/bytefield/meta.yaml
  recipes/tminterface/meta.yaml
Labels: staged-recipes, review-requested, python

#26747 Add readwritememory
  recipes/readwritememory/meta.yaml
Labels: staged-recipes, review-requested, python

#26745 Add pydirectinput
  recipes/pydirectinput/LICENSE.txt
  recipes/pydirectinput/conda-forge.yml
  recipes/pydirectinput/meta.yaml
Labels: staged-recipes, review-requested, python

#26746 Add dxcam
  recipes/dxcam/conda-forge.yml
  recipes/dxcam/meta.yaml
Labels: staged-recipes, review-requested, python

#26742 Add pyorerun
  recipes/pyorerun/LICENSE.md
  recipes/pyorerun/meta.yaml
Labels: review-requested, python

#26751 Add pygbx
  recipes/pygbx/LICENSE
  recipes/pygbx/meta.yaml
Labels: staged-recipes, review-requested, python

#26657 Adding ptflops
  recipes/ptflops/meta.yaml
Labels: review-requested, python

#26008 Add rocFFT
  recipes/rocfft/0001-Add-find_package-hip.patch
  recipes/rocfft/0001-Disable-ahead-of-time-kernel-compilation.patch
  recipes/rocfft/0001-Fix-mman-include-for-MADV_HUGEPAGE.patch
  recipes/rocfft/0001-Make-rocm-cmake-mandatory.patch
  recipes/rocfft/build.sh
  recipes/rocfft/meta.yaml
Labels: review-requested, c-cpp

#26735 Add Python package bmadx (Bmad-X)
  recipes/bmadx/meta.yaml
Labels: review-requested, python

#26753 add polgrain
  recipes/poligrain/meta.yaml
Labels: staged-recipes, review-requested, python

#26685 Add pyjsg recipe
  recipes/pyjsg/meta.yaml
Labels: review-requested, python

#26754 added pokemonpy recipe
  recipes/pokemonpy/meta.yaml
Labels: review-requested, python

#26623 Add Python package `ndbc-api` from PyPi
  recipes/ndbc-api/meta.yaml
Labels: staged-recipes, review-requested, python

#26708 Add dagster cloud
  recipes/dagster-cloud-cli/LICENSE
  recipes/dagster-cloud-cli/meta.yaml
  recipes/dagster-cloud/LICENSE
  recipes/dagster-cloud/meta.yaml
  recipes/pex/LICENSE
  recipes/pex/conda-forge.yml
  recipes/pex/meta.yaml
Labels: staged-recipes, review-requested
