Repository conda-forge/staged-recipes, pull requests merged in 2024-03, with the labels that each got.

#25601 Add koolstof
  recipes/koolstof/meta.yaml
Labels: review-requested, python

#25596 Add Rdatasets
  recipes/rdatasets/meta.yaml
Labels: review-requested, python

#25580 Add hydra-zen
  recipes/hydra-zen/meta.yaml
Labels: staged-recipes, review-requested, python

#25577 Add pyrovelocity (xfail [win])
  recipes/pyrovelocity/conda_build_config.yaml
  recipes/pyrovelocity/meta.yaml
Labels: staged-recipes, review-requested, python

#17837 Add open3d recipe
  recipes/Open3D/LICENSE_TBB
  recipes/Open3D/build.sh
  recipes/Open3D/conda_build_config.yaml
  recipes/Open3D/fix-curl.patch
  recipes/Open3D/fix-error.patch
  recipes/Open3D/fix-find-imgui.patch
  recipes/Open3D/fix-tbb.patch
  recipes/Open3D/fix-unzip.patch
  recipes/Open3D/meta.yaml
  recipes/Open3D/yum_requirements.txt
  recipes/imgui/CMakeLists.txt
  recipes/imgui/build.sh
  recipes/imgui/imgui-config.cmake.in
  recipes/imgui/meta.yaml
  recipes/imgui/run_test.sh
  recipes/imgui/test/CMakeLists.txt
  recipes/imgui/test/test.cpp
  recipes/liblzf/0001-Make-sure-that-the-library-is-linked-with-C-symbols.patch
  recipes/liblzf/CMakeLists.txt
  recipes/liblzf/build.sh
  recipes/liblzf/liblzf-config.cmake.in
  recipes/liblzf/liblzf.pc.in
  recipes/liblzf/meta.yaml
Labels: review-requested, c-cpp, python-c

#25611 add ecape
  recipes/ecape/meta.yaml
Labels: review-requested, python

#25615 Add langchain-text-splitters
  recipes/langchain-text-splitters/LICENSE
  recipes/langchain-text-splitters/meta.yaml
Labels: review-requested, python

#25616 add ecape-parcel
  recipes/ecape-parcel/meta.yaml
Labels: review-requested, python

#25612 Adding HofstadterTools
  recipes/HofstadterTools/meta.yaml
Labels: staged-recipes, review-requested, python

#25564 Add solders & jsonalias - WIP: Awaiting `pybip39` merge
  recipes/jsonalias/LICENSE
  recipes/jsonalias/meta.yaml
  recipes/solders/conda_build_config.yaml
  recipes/solders/meta.yaml
Labels: R, review-requested, rust

#25480 Add recipe for `rl-games`
  recipes/rl-games/01-exclude_package_data.patch
  recipes/rl-games/02-remove_watchdog_upper_bound.patch
  recipes/rl-games/meta.yaml
Labels: staged-recipes, review-requested, python

#25617 add sounderpy
  recipes/sounderpy/meta.yaml
Labels: review-requested, python

#25609 Added functime as a package
  recipes/functime/conda_build_config.yaml
  recipes/functime/meta.yaml
Labels: R, staged-recipes, review-requested, python, rust

#25618 Added sqlglotrs as a package
  recipes/sqlglotrs/LICENSE
  recipes/sqlglotrs/conda_build_config.yaml
  recipes/sqlglotrs/meta.yaml
Labels: R, staged-recipes, review-requested, python, rust

#25493 add django-pint recipe
  recipes/django-pint/meta.yaml
  recipes/django-pint/run_test.py
Labels: review-requested, python

#25336 add clearml-agent
  recipes/clearml-agent/meta.yaml
Labels: review-requested, python

#25369 Add hypothesis-rdkit
  recipes/hypothesis-rdkit/meta.yaml
Labels: review-requested, python

#25337 Add recipe for PyClean (generated by grayskull)
  recipes/pyclean/meta.yaml
Labels: review-requested, python

#25045 Adding pdbstore package
  recipes/pdbstore/meta.yaml
Labels: review-requested, python

#25614 Add recipe for agox
  recipes/agox/meta.yaml
Labels: review-requested, python

#25049 Adding harissa
  recipes/harissa/meta.yaml
Labels: review-requested, python

#25150 Adding pyfilemanager v1.0.0 from pypi
  recipes/pyfilemanager/meta.yaml
Labels: staged-recipes, review-requested, python

#25597 Package liburing
  recipes/liburing/build.sh
  recipes/liburing/meta.yaml
Labels: review-requested, c-cpp

#24499 added hillmaker recipe
  recipes/hillmaker/meta.yaml
Labels: review-requested, python

#24386 Add recipe for biolmai
  recipes/biolmai/meta.yaml
Labels: review-requested, python

#25622 Add litdata
  recipes/litdata/meta.yaml
Labels: review-requested, python

#25626 Add pycolorbar package
  recipes/pycolorbar/meta.yaml
Labels: review-requested, python

#25633 Adding tmm
  recipes/tmm/LICENSE.txt
  recipes/tmm/meta.yaml
Labels: review-requested, python

#25130 Add jscatter
  recipes/jscatter/meta.yaml
  recipes/jscatter/patches/0001-Add-PyMODINIT_FUNC.patch
Labels: review-requested, python

#25625 Add cptec-subsaz
  recipes/cptec-subsaz/meta.yaml
Labels: staged-recipes, review-requested

#25640 add alpha-shapes
  recipes/alpha-shapes/meta.yaml
Labels: staged-recipes, review-requested

#25641 Add cryptlib
  recipes/cryptlib/0001-Add-missing-include.patch
  recipes/cryptlib/0002-Use-cf-compiler.patch
  recipes/cryptlib/build.sh
  recipes/cryptlib/conda-forge.yml
  recipes/cryptlib/meta.yaml
Labels: staged-recipes, review-requested

#25647 add bindensity python package (PyPI)
  recipes/bindensity/meta.yaml
Labels: review-requested, python-c

#25649 Add pyeee
  recipes/pyeee/meta.yaml
Labels: review-requested, python

#25664 Add jax-tqdm+spyx via GraySkull
  recipes/jax-tqdm/LICENSE
  recipes/jax-tqdm/meta.yaml
  recipes/spyx/meta.yaml
Labels: review-requested, python

#25679 Add recipe for types-editdistance
  recipes/types-editdistance/LICENSE
  recipes/types-editdistance/meta.yaml
Labels: staged-recipes, review-requested

#25681 Add recipe for types-hdbcli
  recipes/types-hdbcli/LICENSE
  recipes/types-hdbcli/meta.yaml
Labels: staged-recipes, review-requested

#25682 Added uniplot as a package
  recipes/uniplot/meta.yaml
Labels: staged-recipes, review-requested, python

#25685 Add pytorch-minimize
  recipes/pytorch-minimize/meta.yaml
Labels: staged-recipes, review-requested, python

#25684 Add joserfc
  recipes/joserfc/meta.yaml
Labels: staged-recipes, review-requested, python

#25673 Add eza
  recipes/eza/bld.bat
  recipes/eza/build.sh
  recipes/eza/conda_build_config.yaml
  recipes/eza/meta.yaml
Labels: R, review-requested, rust

#25689 Adding `eval_type_backport` recipe
  recipes/eval-type-backport/meta.yaml
Labels: review-requested, python

#25488 Added r-rolocisccnbs as a package
  recipes/r-rolocisccnbs/bld.bat
  recipes/r-rolocisccnbs/build.sh
  recipes/r-rolocisccnbs/meta.yaml
Labels: R, staged-recipes, review-requested

#25693 Package pwdlib
  recipes/pwdlib/meta.yaml
Labels: review-requested, python

#25690 Added `segy` package recipe
  recipes/segy/meta.yaml
Labels: review-requested, python

#25694 Add pydpc
  recipes/pydpc/meta.yaml
Labels: staged-recipes, review-requested, python-c

#25696 Add pysisso
  recipes/pysisso/meta.yaml
Labels: staged-recipes, review-requested, python

#25692 Add copernicusmarine
  recipes/copernicusmarine/meta.yaml
Labels: staged-recipes, review-requested, python

#25705 Add apache-airflow-providers-smtp
  recipes/apache-airflow-providers-smtp/meta.yaml
Labels: review-requested, python

#25023 add adapy
  recipes/adapy/meta.yaml
  recipes/adapy/yum_requirements.txt
Labels: review-requested, python

#25700 Add pysmartdl2
  recipes/pysmartdl2/meta.yaml
Labels: staged-recipes, review-requested, python

#25699 Add lz, memoir, son and paradigm
  recipes/lz/meta.yaml
  recipes/memoir/LICENSE
  recipes/memoir/meta.yaml
  recipes/paradigm/meta.yaml
  recipes/son/meta.yaml
Labels: staged-recipes, review-requested, python

#25707 Add katex
  recipes/katex/meta.yaml
Labels: staged-recipes, review-requested

#25702 feat: Add madminer recipe
  recipes/madminer/meta.yaml
Labels: review-requested, python

#25656 Add unidock recipe
  recipes/unidock/meta.yaml
Labels: review-requested, c-cpp

#25704 Add pixi-pycharm
  recipes/pixi-pycharm/meta.yaml
Labels: staged-recipes, review-requested

#25703 add Python yamlable package
  recipes/yamlable/meta.yaml
Labels: review-requested, python

#25715 add r-sdmpredictors
  recipes/r-sdmpredicors/bld.bat
  recipes/r-sdmpredicors/build.sh
  recipes/r-sdmpredicors/meta.yaml
Labels: R, review-requested

#25711 Add django-star-ratings
  recipes/django-star-ratings/meta.yaml
Labels: review-requested, python

#25712 Django hitcount
  recipes/django-etc/meta.yaml
  recipes/django-hitcount/meta.yaml
Labels: review-requested, python

#25713 Add streamlit-reveal-slides
  recipes/streamlit-reveal-slides/meta.yaml
Labels: review-requested, python

#25721 add jarvis-leaderboard
  recipes/jarvis-leaderboard/meta.yaml
Labels: staged-recipes, review-requested, python

#25710 Adding kineticpredictormodel and obcanonicalradicals
  recipes/kineticpredictormodel/meta.yaml
  recipes/obcanonicalradicals/meta.yaml
Labels: staged-recipes, review-requested, python

#25719 add dataflows-tabulator
  recipes/dataflows-tabulator/meta.yaml
Labels: staged-recipes, review-requested

#24720 recipe for autoawq
  recipes/autoawq/meta.yaml
Labels: review-requested, python

#25270 Add graspologic-native
  recipes/graspologic-native/LICENSE.txt
  recipes/graspologic-native/conda_build_config.yaml
  recipes/graspologic-native/meta.yaml
Labels: review-requested, python

#25432 Add recipe for fluidfft-mpi_with_fftw
  recipes/fluidfft-mpi_with_fftw/LICENSE
  recipes/fluidfft-mpi_with_fftw/conda_build_config.yaml
  recipes/fluidfft-mpi_with_fftw/meta.yaml
Labels: review-requested, python, python-c

#25533 Add brainglobe-atlasapi and pymcubes dependency
  recipes/brainglobe-atlasapi/meta.yaml
  recipes/pymcubes/meta.yaml
Labels: review-requested, python

#25629 Add dust
  recipes/dust/conda_build_config.yaml
  recipes/dust/meta.yaml
Labels: R, review-requested, rust

#25733 Add python-sscha
  recipes/cellconstructor/meta.yaml
  recipes/python-sscha/meta.yaml
Labels: staged-recipes, review-requested, python-c

#25741 Add tdscha
  recipes/pypar/meta.yaml
  recipes/tdscha/LICENSE.txt
  recipes/tdscha/meta.yaml
Labels: staged-recipes, review-requested, python-c

#25735 add prisms-jobs
  recipes/prisms-jobs/meta.yaml
Labels: staged-recipes, review-requested, python

#24535 Adding testgres
  LICENSE
  recipes/testgres/meta.yaml
Labels: staged-recipes, review-requested

#24378 Adding Medcoupling
  recipes/medcoupling/bld.bat
  recipes/medcoupling/build.sh
  recipes/medcoupling/conda_build_config.yaml
  recipes/medcoupling/meta.yaml
Labels: Awaiting author contribution, python-c

#25737 Adding darkgraylib
  recipes/darkgraylib/meta.yaml
Labels: review-requested, python

#25728 Add graspologic package
  recipes/graspologic/LICENSE.txt
  recipes/graspologic/meta.yaml
Labels: review-requested, python

#25744 Add elphmod
  recipes/elphmod/meta.yaml
Labels: staged-recipes, review-requested, python

#25750 Add alt-profanity-check
  recipes/alt-profanity-check/meta.yaml
Labels: review-requested, python

#25753 Adding ria
  recipes/ria/meta.yaml
Labels: review-requested, python

#24741 Acachecontrol
  recipes/acachecontrol/LICENSE
  recipes/acachecontrol/meta.yaml
Labels: review-requested, python

#25732 Add aws_secretsmanager_caching recipe
  recipes/aws_secretsmanager_caching/meta.yaml
Labels: review-requested, python

#25716 Add cosmopharm recipe
  recipes/cosmopharm/meta.yaml
Labels: review-requested, python

#25755 Add bython
  recipes/bython/LICENSE
  recipes/bython/meta.yaml
Labels: review-requested, python

#25752 Add hipcc
  recipes/hipcc/build.sh
  recipes/hipcc/meta.yaml
Labels: review-requested, c-cpp

#25759 Add makemake90
  recipes/makemake90/meta.yaml
Labels: review-requested, python

#25758 Add frettipy
  recipes/frettipy/meta.yaml
Labels: review-requested, python

#25757 Add StoryLines
  recipes/storylines/meta.yaml
Labels: review-requested, python

#23091 Add polybeat
  recipes/polybeat/LICENSE
  recipes/polybeat/meta.yaml
Labels: review-requested, python

#25240 Adding ttp package
  recipes/ttp/meta.yaml
Labels: review-requested, python

#25756 Add django-utils-six
  recipes/django-utils-six/meta.yaml
Labels: review-requested, python

#25754 Add okta-jwt-verifier
  recipes/okta-jwt-verifier/LONG_DESCRIPTION.md
  recipes/okta-jwt-verifier/meta.yaml
Labels: review-requested, python

#25064 Added salabim and salabim-animation.
  recipes/salabim/license.txt
  recipes/salabim/meta.yaml
Labels: review-requested, python

#25743 Add activemq-cpp
  recipes/activemq-cpp/build.sh
  recipes/activemq-cpp/meta.yaml
  recipes/activemq-cpp/testing.diff
Labels: review-requested, c-cpp

#25760 Adding altair_tiles
  recipes/altair_tiles/meta.yaml
Labels: review-requested, python

#25765 Adding optimask recipe
  recipes/optimask/meta.yaml
Labels: review-requested, python

#25389 Adding datashuttle.
  recipes/datashuttle/meta.yaml
Labels: review-requested, python

#25770 add xarg-python
  recipes/xarg-python/meta.yaml
Labels: staged-recipes, review-requested, python

#25775 add cppimport
  recipes/cppimport/meta.yaml
Labels: review-requested, python

#25769 add posebusters
  recipes/posebusters/meta.yaml
Labels: staged-recipes, review-requested, python

#25718 Add pyshqg
  recipes/pyshqg/meta.yaml
Labels: review-requested, python

#25419 Add eis_toolkit
  recipes/eis_toolkit/meta.yaml
Labels: review-requested, python

#25747 Add recipe for unfold
  recipes/unfold/meta.yaml
Labels: review-requested, python

#25785 ENH add jupyterlab-gist-it
  .ci_support/build_all.py
  .ci_support/compute_build_graph.py
  .ci_support/requirements.txt
  recipes/jupyterlab-gist-it/meta.yaml
Labels: staged-recipes, review-requested

#25768 Add rxnmapper
  recipes/rxn-chem-utils/meta.yaml
  recipes/rxn-utils/meta.yaml
  recipes/rxnmapper/meta.yaml
Labels: staged-recipes, review-requested, python

#25631 create recipes/rtopy/
  LICENSE
  LICENSE.txt
  recipes/rtopy/meta.yaml
Labels: review-requested, python

#25793 Adding deepcs python package recipe
  recipes/deepcs/meta.yaml
Labels: review-requested, python

#25672 build: Add caustics conda recipe
  recipes/caustics/meta.yaml
Labels: review-requested, python

#25789 feat: Add hepconvert
  recipes/hepconvert/meta.yaml
Labels: review-requested, python

#25805 Adding zabbix_utils
  recipes/zabbix_utils/meta.yaml
Labels: review-requested, python

#25809 Add recipe for lintsampler
  recipes/lintsampler/meta.yaml
Labels: staged-recipes, review-requested, python

#25821 Adding amep
  recipes/amep/meta.yaml
Labels: staged-recipes, review-requested, python

#25819 recipe for thresholdclustering
  recipes/thresholdclustering/LICENSE
  recipes/thresholdclustering/meta.yaml
Labels: review-requested, python

#25818 recipe for angelcommunity
  recipes/angelcommunity/meta.yaml
Labels: review-requested, python

#25817 recipe for bimlpa
  recipes/bimlpa/LICENSE
  recipes/bimlpa/meta.yaml
Labels: review-requested, python

#25816 recipe for demon
  recipes/demon/meta.yaml
Labels: review-requested, python

#25812 recipe for nf1
  recipes/nf1/meta.yaml
Labels: review-requested, python

#25813 recipe for markov-clustering
  recipes/markov-clustering/meta.yaml
Labels: review-requested, python

#25815 recipe for dynetx
  recipes/dynetx/meta.yaml
Labels: review-requested, python

#25811 recipe for rinohtype
  recipes/rinohtype/meta.yaml
Labels: review-requested, python

#25804 Add fides
  recipes/fides/LICENSE.md
  recipes/fides/meta.yaml
Labels: review-requested, python

#25795 Add pytest-aio
  recipes/pytest-aio/LICENSE
  recipes/pytest-aio/meta.yaml
Labels: review-requested, python

#25794 Add nox-poetry
  recipes/nox-poetry/meta.yaml
Labels: review-requested, python

#25820 recipe for cdlib
  recipes/cdlib/meta.yaml
Labels: review-requested, python

#25810 Add recipe for r-idefix.
  recipes/r-idefix/bld.bat
  recipes/r-idefix/build.sh
  recipes/r-idefix/meta.yaml
Labels: R, review-requested

#25833 Add r-logitr.
  recipes/r-logitr/bld.bat
  recipes/r-logitr/build.sh
  recipes/r-logitr/meta.yaml
Labels: R, review-requested

#25803 Create recipe for seapipy
  recipes/seapipy/meta.yaml
Labels: review-requested, python

#25826 Add rustimport as a package
  recipes/rustimport/meta.yaml
Labels: staged-recipes, review-requested, python

#25659 add csp
  recipes/csp/conda_build_config.yaml
  recipes/csp/meta.yaml
Labels: review-requested, python, python-c

#25393 Adding DAML
  recipes/daml/meta.yaml
Labels: review-requested, python

#25037 add apriltag library
  recipes/apriltag/CMakeLists.txt
  recipes/apriltag/bld.bat
  recipes/apriltag/build.sh
  recipes/apriltag/meta.yaml
  recipes/apriltag/test.c
Labels: review-requested, c-cpp

#25834 Add r-conf.design.
  recipes/r-conf.design/bld.bat
  recipes/r-conf.design/build.sh
  recipes/r-conf.design/meta.yaml
Labels: R, review-requested

#25843 Add django-dcat
  recipes/django-dcat/meta.yaml
Labels: review-requested, python

#25841 Git Add django-db-logger
  recipes/django-db-logger/meta.yaml
Labels: review-requested, python

#25839 Add django-log-viewer
  recipes/django-log-viewer/meta.yaml
Labels: review-requested, python

#25837 Add igor2
  recipes/igor2/meta.yaml
Labels: review-requested, python

#25828 Adding Serialite
  recipes/serialite/meta.yaml
Labels: review-requested, python

#25832 Add r-doe.base.
  recipes/r-doe.base/bld.bat
  recipes/r-doe.base/build.sh
  recipes/r-doe.base/meta.yaml
Labels: R, review-requested

#25808 Adding recordclass
  recipes/recordclass/meta.yaml
Labels: review-requested, python

#25825 Adding CountEst
  recipes/CountEst/meta.yaml
Labels: review-requested, python

#25849 Add unstructured
  recipes/jsonpath-python/meta.yaml
  recipes/python-iso639/meta.yaml
  recipes/unstructured-client/dataclassesjson.patch
  recipes/unstructured-client/meta.yaml
  recipes/unstructured/meta.yaml
  recipes/unstructured/setup.patch
Labels: staged-recipes, review-requested, python

#24569 Add recipe for pytest-codspeed
  recipes/pytest-codspeed/meta.yaml
Labels: staged-recipes, review-requested

#25842 Add llmlingua
  recipes/llmlingua/meta.yaml
Labels: staged-recipes, review-requested, python

#25774 Add aestream
  recipes/aestream/build.sh
  recipes/aestream/conda_build_config.yaml
  recipes/aestream/meta.yaml
  recipes/aestream/unvendor.patch
Labels: review-requested, python-c

#25852 Add litellm
  recipes/litellm/meta.yaml
Labels: staged-recipes, review-requested, python

#25851 Add tokentrim
  recipes/tokentrim/meta.yaml
Labels: staged-recipes, review-requested, python

#25850 Add html2image
  recipes/html2image/meta.yaml
Labels: staged-recipes, review-requested, python

#25683 Added polars-ds as a package
  recipes/polars-ds/conda_build_config.yaml
  recipes/polars-ds/meta.yaml
Labels: R, review-requested, python, rust

#25654 add genomekit
  recipes/genomekit/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#25830 Add pathlib-abc
  recipes/pathlib-abc/LICENSE
  recipes/pathlib-abc/meta.yaml
Labels: staged-recipes, review-requested, python

#25782 adding cad-to-dagmc
  recipes/cad_to_dagmc/meta.yaml
  recipes/cad_to_dagmc/yum_requirements.txt
Labels: review-requested, python
