Repository conda-forge/staged-recipes, pull requests merged in 2024-11, with the labels that each got.

#28067 add streamlit-searchbox
  recipes/streamlit-searchbox/0001-remove-tests-from-distribution.patch
  recipes/streamlit-searchbox/meta.yaml
Labels: review-requested, python

#28073 Add recipes for microsoft-kiota-serialization-*
  recipes/microsoft-kiota-serialization-form/meta.yaml
  recipes/microsoft-kiota-serialization-json/meta.yaml
  recipes/microsoft-kiota-serialization-multipart/meta.yaml
  recipes/microsoft-kiota-serialization-text/meta.yaml
Labels: review-requested, python

#28072 Django django-survey-and-report plus dependencies
  recipes/confusable-homoglyphs/meta.yaml
  recipes/customersatisfactionmetrics/meta.yaml
  recipes/django-bootstrap-form/LICENSE
  recipes/django-bootstrap-form/meta.yaml
  recipes/django-registration/meta.yaml
  recipes/django-survey-and-report/meta.yaml
  recipes/django-tastypie/meta.yaml
Labels: review-requested, python

#28071 Add recipe for sphinxcontrib-googleanalytics
  recipes/sphinxcontrib-googleanalytics/LICENSE.txt
  recipes/sphinxcontrib-googleanalytics/meta.yaml
Labels: staged-recipes, review-requested, python

#28000 Add inifix recipe
  recipes/inifix/meta.yaml
Labels: review-requested, python

#28074 Add packages editor, runs and xmod
  recipes/editor/meta.yaml
  recipes/runs/meta.yaml
  recipes/xmod/meta.yaml
Labels: review-requested, python

#27631 CRbeam program
  recipes/crbeam/build.sh
  recipes/crbeam/meta.yaml
Labels: review-requested, c-cpp

#28023 Added timbertrek as a package
  recipes/timbertrek/LICENSE
  recipes/timbertrek/meta.yaml
Labels: staged-recipes, review-requested, python

#28082 Added perpetual as a package
  recipes/perpetual/conda_build_config.yaml
  recipes/perpetual/meta.yaml
Labels: R, staged-recipes, review-requested, python, rust

#28083 Added wimsey as a package
  recipes/wimsey/meta.yaml
Labels: staged-recipes, review-requested, python

#28087 Add Pytzer
  recipes/pytzer/meta.yaml
Labels: review-requested, python

#28088 Adding echopop
  recipes/echopop/meta.yaml
Labels: review-requested, python

#27950 New package: cuda-histogram
  recipes/cuda-histogram/cupy.patch
  recipes/cuda-histogram/meta.yaml
Labels: review-requested, python

#28090 add `meteor-maps`
  recipes/meteor-maps/meta.yaml
Labels: staged-recipes, review-requested, python

#28104 Added path-imports as a package
  recipes/path-imports/meta.yaml
Labels: staged-recipes, review-requested, python

#28066 Adding symbolfit
  recipes/symbolfit/meta.yaml
Labels: review-requested, python

#28108 Add aiida-shell
  recipes/aiida-shell/meta.yaml
Labels: staged-recipes, review-requested, python

#28080 Add solar-data-tools recipe
  recipes/solar-data-tools/meta.yaml
Labels: review-requested, python

#28110 Add sober
  recipes/sober/meta.yaml
Labels: review-requested, python

#28114 Add factur-x
  recipes/factur-x/LICENSE
  recipes/factur-x/meta.yaml
Labels: staged-recipes, review-requested, python

#28092 add loguru-cpp
  recipes/loguru-cpp/recipe.yaml
Labels: staged-recipes, review-requested, c-cpp, python-c

#28119 infra: improve macOS local build experience
  .gitignore
  .scripts/run_docker_build.sh
  build-locally.py
  setup.cfg
Labels: maintenance

#28112 add django-currentuser recipe
  recipes/django-currentuser/meta.yaml
Labels: review-requested, python

#27756 Adding new software to conda-forge: BELT (BEam Longitudinal Tracking)
  recipes/belt/meta.yaml
Labels: staged-recipes, review-requested

#28084 feat: Add Sherpa
  recipes/sherpa/0001-convert-print-statements-using-2to3.patch
  recipes/sherpa/0002-remove-null-characters-for-prefix-replacement.patch
  recipes/sherpa/build.sh
  recipes/sherpa/meta.yaml
Labels: review-requested, c-cpp

#28129 Adding DASPy-toolbox
  recipes/DASPy-toolbox/meta.yaml
Labels: staged-recipes, review-requested, python

#28123 Add libipld
  recipes/libipld/meta.yaml
Labels: review-requested, python

#28130 Add COLLIER
  recipes/collier/meta.yaml
Labels: staged-recipes, review-requested

#28061 Add `rustic`
  recipes/rustic/bld.bat
  recipes/rustic/build.sh
  recipes/rustic/meta.yaml
Labels: R, review-requested, rust

#28120 Update README badge
  README.md
Labels: maintenance

#28063 Add `xcp`
  recipes/xcp/bld.bat
  recipes/xcp/build.sh
  recipes/xcp/meta.yaml
Labels: R, review-requested, rust

#28121 Add recipe for ai2-olmo-eval
  recipes/ai2-olmo-eval/meta.yaml
Labels: review-requested, python

#28131 Add atproto
  recipes/atproto/meta.yaml
Labels: review-requested, python

#28106 add ccflow
  recipes/ccflow/meta.yaml
Labels: review-requested, python

#28144 feat: enable unique token per provider
  .github/workflows/scripts/create_feedstocks.py
Labels: maintenance

#28150 Add PyCifStar to conda-forge
  recipes/pycifstar/recipe.yaml
Labels: review-requested, python

#27894 add protolint, pug-lsp, regal, regols, rospo
  recipes/protolint/bld.bat
  recipes/protolint/build.sh
  recipes/protolint/meta.yaml
  recipes/pug-lsp/LICENSE
  recipes/pug-lsp/build.sh
  recipes/pug-lsp/conda_build_config.yaml
  recipes/pug-lsp/meta.yaml
  recipes/regal/bld.bat
  recipes/regal/build.sh
  recipes/regal/meta.yaml
  recipes/regols/bld.bat
  recipes/regols/build.sh
  recipes/regols/meta.yaml
  recipes/rospo/bld.bat
  recipes/rospo/build.sh
  recipes/rospo/meta.yaml
Labels: staged-recipes, review-requested, go

#27893 add moar, opa, pdfcpu, please
  recipes/moar/bld.bat
  recipes/moar/build.sh
  recipes/moar/meta.yaml
  recipes/opa/bld.bat
  recipes/opa/build.sh
  recipes/opa/meta.yaml
  recipes/pdfcpu/bld.bat
  recipes/pdfcpu/build.sh
  recipes/pdfcpu/meta.yaml
  recipes/please/build.sh
  recipes/please/meta.yaml
Labels: staged-recipes, review-requested, go

#27831 Add the xhydro recipe
  recipes/xhydro/meta.yaml
Labels: review-requested, python

#28154 Add cryspy to conda-forge
  recipes/cryspy/recipe.yaml
Labels: review-requested, python

#28139 Adding streamlit-flow-component
  recipes/streamlit-flow-component/LICENSE
  recipes/streamlit-flow-component/meta.yaml
Labels: review-requested, python

#28156 Adding pytomoatt
  recipes/pytomoatt/meta.yaml
Labels: review-requested, python

#28159 Add sharedlibpp C++ library
  recipes/sharedlibpp/bld.bat
  recipes/sharedlibpp/build.sh
  recipes/sharedlibpp/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#28163 add mprocs, navi, nickel
  recipes/mprocs/build.sh
  recipes/mprocs/meta.yaml
  recipes/navi/bld.bat
  recipes/navi/build.sh
  recipes/navi/meta.yaml
  recipes/nickel/bld.bat
  recipes/nickel/build.sh
  recipes/nickel/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#28091 add deepsearch-toolkit docling-ibm-models docling-parse docling-core mean-average-precision
  recipes/deepsearch-toolkit/recipe.yaml
  recipes/docling-core/recipe.yaml
  recipes/docling-ibm-models/recipe.yaml
  recipes/docling-parse/fix-utfcpp.patch
  recipes/docling-parse/recipe.yaml
  recipes/mean-average-precision/recipe.yaml
Labels: review-requested, python, python-c

#28164 Add piq
  recipes/piq/meta.yaml
Labels: review-requested, python

#28157 Add pytango-db recipe
  recipes/pytango-db/meta.yaml
Labels: review-requested, python

#28165 adding petsird python package
  recipes/petsird-python/meta.yaml
Labels: review-requested, python

#27984 added check-internet-speed v0.0.3
  recipes/check-internet-speed/meta.yaml
Labels: review-requested, python

#28118 Add mistral-inference
  recipes/mistral-common/meta.yaml
  recipes/mistral-inference/meta.yaml
Labels: review-requested, python

#28189 add types-cffi
  recipes/types-cffi/meta.yaml
Labels: review-requested, python

#28116 Add helanal
  recipes/helanal/meta.yaml
Labels: review-requested, python

#28043 Add ucimlrepo
  recipes/ucimlrepo/meta.yaml
Labels: review-requested, python

#28042 Imagededup
  recipes/imagededup/recipe.yaml
Labels: review-requested, python

#27961 Recipe for pytrms (pypi).
  recipes/pytrms/meta.yaml
Labels: review-requested, python

#27955 Add mkdocs-marimo
  recipes/mkdocs-marimo/recipe.yaml
Labels: review-requested, python

#27925 adding dyson-equalizer
  recipes/dyson-equalizer/meta.yaml
Labels: review-requested, python

#28076 add r-pastclim from CRAN via conda_r_skeleton_helper
  recipes/r-pastclim/LICENSE.md
  recipes/r-pastclim/bld.bat
  recipes/r-pastclim/build.sh
  recipes/r-pastclim/meta.yaml
Labels: R, review-requested

#28170 Add recipe for CADET-Python
  recipes/CADET-Python/meta.yaml
Labels: review-requested, python

#28095 Add recipe for ozzy-pic
  recipes/ozzy-pic/meta.yaml
Labels: staged-recipes, review-requested, python

#28169 Add QCDLoop
  recipes/qcdloop/0001-fix-Use-grep-E-over-egrep.patch
  recipes/qcdloop/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#28201 add urljsf 0.1.0
  recipes/urljsf/meta.yaml
Labels: review-requested, python

#28199 Add chessnut python package
  recipes/chessnut/meta.yaml
Labels: review-requested, python

#28208 Adding datapi
  recipes/datapi/meta.yaml
Labels: staged-recipes, review-requested, python

#27754 Add Pixi support for local debugging (including Windows)
  .azure-pipelines/azure-pipelines-osx.yml
  .ci_support/build_all.py
  .ci_support/requirements.txt
  .gitattributes
  .github/workflows/linter.yml
  .github/workflows/scripts/linter.py
  .gitignore
  .scripts/build_steps.sh
  .scripts/run_osx_build.sh
  .scripts/run_win_build.bat
  README.md
  build-locally.py
  environment.yaml
  pixi.toml
Labels: maintenance

#28206 Add requests-scitokens
  recipes/requests-scitokens/meta.yaml
Labels: review-requested, python

#28223 Add clean-notebook
  recipes/clean-notebook/meta.yaml
Labels: review-requested, python

#28213 Adding asesurfacefinder
  recipes/asesurfacefinder/meta.yaml
Labels: staged-recipes, review-requested

#27684 adding efmtool_link, optlang_enumerator
  recipes/efmtool_link/meta.yaml
  recipes/optlang_enumerator/meta.yaml
Labels: review-requested, python

#28179 Add pytdigest
  recipes/pytdigest/meta.yaml
Labels: review-requested, python-c

#28160 add rsc-2fa, sift, snyk-ls, solt
  recipes/rsc-2fa/bld.bat
  recipes/rsc-2fa/build.sh
  recipes/rsc-2fa/meta.yaml
  recipes/sift/bld.bat
  recipes/sift/build.sh
  recipes/sift/meta.yaml
  recipes/snyk-ls/bld.bat
  recipes/snyk-ls/build.sh
  recipes/snyk-ls/meta.yaml
  recipes/solt/bld.bat
  recipes/solt/build.sh
  recipes/solt/meta.yaml
Labels: staged-recipes, review-requested, go

#27988 Add libfabric recipe
  recipes/libfabric/build.sh
  recipes/libfabric/meta.yaml
Labels: review-requested, c-cpp

#26068 Add recipe for ckzg
  recipes/ckzg/conda_build_config.yaml
  recipes/ckzg/meta.yaml
  recipes/ckzg/setup.py.patch
Labels: review-requested, python

#28158 add less (closes #22777)
  recipes/less/recipe.yaml
Labels: review-requested, c-cpp

#28245 Do not error with undefined `${CI}` on Linux
  .scripts/build_steps.sh
Labels: maintenance

#28240 sprocket: init at 0.8.0
  recipes/sprocket/recipe.yaml
Labels: R, review-requested, rust

#28231 Collate sqllineage
  recipes/collate-sqllineage/LICENSE
  recipes/collate-sqllineage/meta.yaml
Labels: review-requested, python

#28227 Added django-phonenumber-field as a package
  recipes/django-phonenumber-field/meta.yaml
Labels: staged-recipes, review-requested, python

#28256 Add atomai
  recipes/atomai/meta.yaml
Labels: staged-recipes, review-requested, python

#28236 Add linux-aarch64 and osx-arm64 configs for local debugging
  .ci_support/linux_aarch64.yaml
  .ci_support/osx_arm64.yaml
Labels: maintenance

#28257 add glidertest recipe
  recipes/glidertest/meta.yaml
Labels: review-requested, python

#28260 Run conda-index on `$CONDA_BLD_PATH` (osx, win)
  .ci_support/build_all.py
  .scripts/run_osx_build.sh
  .scripts/run_win_build.bat
Labels: maintenance

#28191 Adding CRAN package 'semaphore'
  recipes/r-semaphore/bld.bat
  recipes/r-semaphore/build.sh
  recipes/r-semaphore/meta.yaml
Labels: R, review-requested

#24753 Add napari-nyxus recipe
  recipes/napari-nyxus/meta.yaml
  recipes/napari-nyxus/yum_requirements.txt
Labels: Awaiting author contribution

#28239 Use RATTLER_CACHE_DIR instead of XDG_CACHE_HOME
  build-locally.py
Labels: maintenance

#28271 Remove duplicate conda-index call on Windows
  .scripts/run_win_build.bat
Labels: maintenance

#28041 add reptyr
  recipes/reptyr/recipe.yaml
Labels: review-requested, c-cpp

#28259 adds `r-genio`
  recipes/r-genio/bld.bat
  recipes/r-genio/build.sh
  recipes/r-genio/meta.yaml
Labels: R, review-requested

#25307 adds `r-bedmatrix` and `r-crochet`
  recipes/r-bedmatrix/bld.bat
  recipes/r-bedmatrix/build.sh
  recipes/r-bedmatrix/meta.yaml
  recipes/r-crochet/bld.bat
  recipes/r-crochet/build.sh
  recipes/r-crochet/meta.yaml
Labels: R, review-requested

#28155 Adding CyRK Python Package (v0.11.0)
  recipes/CyRK/meta.yaml
Labels: staged-recipes, review-requested, python-c

#28200 Add torchkbnufft recipe
  recipes/torchkbnufft/meta.yaml
  recipes/torchkbnufft/patches/0001-conftest-np-2-0.patch
Labels: review-requested, python

#28224 Add OneLOop
  recipes/oneloop/meta.yaml
Labels: staged-recipes, review-requested

#28235 add pomsky, procs, protols, pueue
  recipes/pomsky/bld.bat
  recipes/pomsky/build.sh
  recipes/pomsky/meta.yaml
  recipes/procs/bld.bat
  recipes/procs/build.sh
  recipes/procs/meta.yaml
  recipes/protols/bld.bat
  recipes/protols/build.sh
  recipes/protols/meta.yaml
  recipes/pueue/bld.bat
  recipes/pueue/build.sh
  recipes/pueue/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#28234 add oxlint, page, pbls, pest-language-server, pipe-rename
  recipes/oxlint/bld.bat
  recipes/oxlint/build.sh
  recipes/oxlint/meta.yaml
  recipes/page/bld.bat
  recipes/page/build.sh
  recipes/page/meta.yaml
  recipes/pbls/bld.bat
  recipes/pbls/build.sh
  recipes/pbls/meta.yaml
  recipes/pest-language-server/bld.bat
  recipes/pest-language-server/build.sh
  recipes/pest-language-server/meta.yaml
  recipes/pipe-rename/LICENSE
  recipes/pipe-rename/bld.bat
  recipes/pipe-rename/build.sh
  recipes/pipe-rename/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#28288 Replace gitter with zulip
  .github/ISSUE_TEMPLATE/bugs_template.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.yml
  .github/pull_request_template.md
  README.md
Labels: maintenance

#28268 feat: add atlas-schema into conda-forge
  recipes/atlas-schema/meta.yaml
Labels: review-requested, python

#28185 Add deffcode
  recipes/deffcode/meta.yaml
Labels: review-requested, python

#25670 Add idtrackerai
  recipes/idtrackerai/meta.yaml
Labels: review-requested, python

#28248 Add xlens recipe
  recipes/xlens/meta.yaml
Labels: review-requested, python

#28040 Added django-appointment as a package
  recipes/django-appointment/meta.yaml
Labels: staged-recipes, review-requested, python

#28238 Added finstruments as a package
  recipes/finstruments/meta.yaml
Labels: staged-recipes, review-requested, python

#28017 Added kalmangrad as a package
  recipes/kalmangrad/licence.txt
  recipes/kalmangrad/meta.yaml
Labels: staged-recipes, review-requested, python

#28014 Added cubedpandas as a package
  recipes/cubedpandas/0001-get-version.patch
  recipes/cubedpandas/meta.yaml
Labels: staged-recipes, review-requested, python

#26894 Add con-duct
  recipes/con-duct/meta.yaml
Labels: staged-recipes, review-requested, python

#27841 Add csvtk
  recipes/csvtk/bld.bat
  recipes/csvtk/build.sh
  recipes/csvtk/meta.yaml
Labels: review-requested, go

#28299 Added augurs as a package
  recipes/augurs/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27726 Adding Raysect
  recipes/raysect/recipe.yaml
Labels: staged-recipes, review-requested, python-c

#28215 Add evcxr
  recipes/evcxr/recipe.yaml
Labels: R, review-requested, rust

#28105 Add scikit-sundae
  recipes/scikit-sundae/integrate.py
  recipes/scikit-sundae/meta.yaml
Labels: review-requested, python-c

#28301 Adding safehttpx
  recipes/safehttpx/conda_build_config.yaml
  recipes/safehttpx/meta.yaml
Labels: review-requested, python

#28210 Adding Yazi
  recipes/yazi/bld.bat
  recipes/yazi/build.sh
  recipes/yazi/meta.yaml
Labels: R, review-requested, rust

#27970 Add `brename`
  recipes/brename/bld.bat
  recipes/brename/build.sh
  recipes/brename/meta.yaml
Labels: review-requested, go

#27755 Add vulkan-validation-layers
  recipes/vulkan-validation-layers/bld.bat
  recipes/vulkan-validation-layers/build.sh
  recipes/vulkan-validation-layers/conda_build_config.yaml
  recipes/vulkan-validation-layers/meta.yaml
Labels: review-requested, c-cpp

#28146 Adding `neo4j-rust-ext` recipe
  recipes/neo4j-python-driver-rust-ext/conda_build_config.yaml
  recipes/neo4j-python-driver-rust-ext/meta.yaml
Labels: R, review-requested, rust

#28221 Add recipe for idaes-pse
  recipes/idaes-pse/meta.yaml
Labels: staged-recipes, review-requested, python

#28143 Add datacube-compute
  recipes/datacube-compute/recipe.yaml
Labels: R, review-requested, python, rust

#28178 Add recipe for qpsolvers-eigen
  recipes/qpsolvers-eigen/bld_core.bat
  recipes/qpsolvers-eigen/bld_osqp.bat
  recipes/qpsolvers-eigen/bld_proxqp.bat
  recipes/qpsolvers-eigen/build_core.sh
  recipes/qpsolvers-eigen/build_osqp.sh
  recipes/qpsolvers-eigen/build_proxqp.sh
  recipes/qpsolvers-eigen/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#28198 Add package for ampl-asl C library
  recipes/ampl-asl/22.patch
  recipes/ampl-asl/bld.bat
  recipes/ampl-asl/build.sh
  recipes/ampl-asl/install_library_in_default_location.patch
  recipes/ampl-asl/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#28275 adds `r-dalextra`
  recipes/r-dalextra/bld.bat
  recipes/r-dalextra/build.sh
  recipes/r-dalextra/meta.yaml
Labels: R, review-requested

#28274 adds `r-spatialsample`
  recipes/r-spatialsample/bld.bat
  recipes/r-spatialsample/build.sh
  recipes/r-spatialsample/meta.yaml
Labels: R, review-requested

#28263 Add potpourri3d and dependencies
  recipes/geometry-central/LICENSE_nanoflann
  recipes/geometry-central/LICENSE_nanort
  recipes/geometry-central/build.sh
  recipes/geometry-central/meta.yaml
  recipes/happly/bld.bat
  recipes/happly/build.sh
  recipes/happly/meta.yaml
  recipes/potpourri3d/CMakeLists.txt
  recipes/potpourri3d/build.sh
  recipes/potpourri3d/meta.yaml
Labels: review-requested, c-cpp, python-c

#27605 Adding coal
  recipes/coal/build_coal_python.bat
  recipes/coal/build_coal_python.sh
  recipes/coal/build_cppcoal.bat
  recipes/coal/build_cppcoal.sh
  recipes/coal/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#27909 Add butane
  recipes/butane/meta.yaml
Labels: review-requested, go

#28303 Added recipe for `lion-pytorch`
  recipes/lion-pytorch/meta.yaml
Labels: review-requested, python

#28305 Added pipe-operator as a package
  recipes/pipe-operator/meta.yaml
Labels: staged-recipes, review-requested, python

#28296 Add CosmoPower
  recipes/cosmopower/meta.yaml
Labels: staged-recipes, review-requested, python

#28290 add pyeddytracker
  recipes/pyeddytracker/meta.yaml
Labels: review-requested, python

#28308 Added deply as a package
  recipes/deply/0001-use-environment-for-version.patch
  recipes/deply/meta.yaml
Labels: staged-recipes, review-requested, python

#28311 Add pixi-inject
  recipes/pixi-inject/build.bat
  recipes/pixi-inject/build.sh
  recipes/pixi-inject/recipe.yaml
Labels: R, review-requested, rust

#28309 Added recipe for `pytorch_toolbelt`
  recipes/pytorch_toolbelt/meta.yaml
Labels: review-requested, python

#28313 feat: add interpax
  recipes/interpax/meta.yaml
Labels: review-requested, python

#28312 Added lightapi as a package
  recipes/lightapi/LICENSE
  recipes/lightapi/meta.yaml
Labels: review-requested, python

#28318 Added tkinter_form as a package
  recipes/tkinter_form/meta.yaml
  recipes/tkinter_form/yum_requirements.txt
Labels: review-requested, python

#28317 Added tkinter-tooltip as a package
  recipes/tkinter-tooltip/meta.yaml
  recipes/tkinter-tooltip/yum_requirements.txt
Labels: review-requested, python

#28316 Added autocombobox as a package
  recipes/autocombobox/meta.yaml
  recipes/autocombobox/yum_requirements.txt
Labels: review-requested, python

#28314 Added rerankers as a package
  recipes/rerankers/meta.yaml
Labels: review-requested, python

#28310 Added iommi as a package
  recipes/iommi/meta.yaml
Labels: review-requested, python

#28326 update images to use alma9
  .azure-pipelines/azure-pipelines-linux.yml
  .ci_support/linux64.yaml
  .ci_support/linux64_cuda118.yaml
  .ci_support/linux64_cuda120.yaml
  .ci_support/linux_aarch64.yaml
  .scripts/build_steps.sh
Labels: maintenance

#28173 Add beangulp 0.1.1 via grayskull, plus corrections
  recipes/beangulp/bld.bat
  recipes/beangulp/build.sh
  recipes/beangulp/meta.yaml
Labels: review-requested, python

#28297 first recipe gatiab
  recipes/gatiab/meta.yaml
Labels: review-requested, python

#28302 seareport-data feedstock
  recipes/seareport-data/meta.yaml
Labels: review-requested, python

#28307 Added r-tidyplots as a package
  recipes/r-tidyplots/bld.bat
  recipes/r-tidyplots/build.sh
  recipes/r-tidyplots/meta.yaml
Labels: R, review-requested

#28292 Add LoopTools
  recipes/looptools/examples/example01.cpp
  recipes/looptools/meta.yaml
Labels: staged-recipes, review-requested

#28320 Added dante-db as a package
  recipes/dante-db/LICENSE
  recipes/dante-db/meta.yaml
Labels: review-requested, python

#28327 add skim, sleek, swc, t-rec, tagref
  recipes/skim/build.sh
  recipes/skim/meta.yaml
  recipes/sleek/bld.bat
  recipes/sleek/build.sh
  recipes/sleek/meta.yaml
  recipes/swc/build.sh
  recipes/swc/meta.yaml
  recipes/t-rec/build.sh
  recipes/t-rec/meta.yaml
  recipes/tagref/bld.bat
  recipes/tagref/build.sh
  recipes/tagref/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#28325 add safe-rm, shadowenv, sheldon, shellharden
  recipes/safe-rm/build.sh
  recipes/safe-rm/meta.yaml
  recipes/shadowenv/build.sh
  recipes/shadowenv/meta.yaml
  recipes/sheldon/build.sh
  recipes/sheldon/meta.yaml
  recipes/shellharden/bld.bat
  recipes/shellharden/build.sh
  recipes/shellharden/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#28324 add rnr, rune, rustywind, rusync, sad
  recipes/rnr/bld.bat
  recipes/rnr/build.sh
  recipes/rnr/meta.yaml
  recipes/rune/bld.bat
  recipes/rune/build.sh
  recipes/rune/meta.yaml
  recipes/rustywind/bld.bat
  recipes/rustywind/build.sh
  recipes/rustywind/meta.yaml
  recipes/rusync/bld.bat
  recipes/rusync/build.sh
  recipes/rusync/meta.yaml
  recipes/sad/bld.bat
  recipes/sad/build.sh
  recipes/sad/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#28323 add rargs, relay, rm-improved
  recipes/rargs/bld.bat
  recipes/rargs/build.sh
  recipes/rargs/meta.yaml
  recipes/relay/bld.bat
  recipes/relay/build.sh
  recipes/relay/meta.yaml
  recipes/rm-improved/build.sh
  recipes/rm-improved/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#28220 Adding pysciencemode
  recipes/pyScienceMode/meta.yaml
Labels: review-requested, python

#28202 Add stellarmesh
  recipes/stellarmesh/meta.yaml
Labels: review-requested, python
