Repository conda-forge/staged-recipes, pull requests merged in 2024-01, with the labels that each got.

#24874 Djangocms frontend & plugins for Django CMS 4.1
  recipes/django-entangled/meta.yaml
  recipes/djangocms-attributes-field/meta.yaml
  recipes/djangocms-frontend/meta.yaml
  recipes/djangocms-icon/meta.yaml
  recipes/djangocms-picture/meta.yaml
  recipes/djangocms-style/meta.yaml
Labels: staged-recipes, review-requested

#24864 Added audio-separator recipe
  recipes/audio-separator/LICENSE
  recipes/audio-separator/conda-forge.yml
  recipes/audio-separator/meta.yaml
Labels: review-requested, python

#24866 Add h5io_browser
  recipes/h5io_browser/meta.yaml
Labels: staged-recipes, review-requested, python

#22803 Add lpynn package
  recipes/lpynn/meta.yaml
Labels: stale, review-requested, python

#22973 Add PowerGenome recipe
  recipes/powergenome/meta.yaml
Labels: stale, review-requested, python

#22705 Adding xsocs Python application
  recipes/xsocs/meta.yaml
Labels: stale, review-requested, python

#23016 Adding aggregate recipe.
  recipes/aggregate/meta.yaml
Labels: stale, review-requested, python

#23019 Adding pyibs package
  recipes/pyibs/meta.yaml
Labels: stale, review-requested, python

#23048 add dmff
  recipes/dmff/meta.yaml
Labels: review-requested, python

#22991 Adding PlanetMapper
  recipes/planetmapper/meta.yaml
  recipes/planetmapper/yum_requirements.txt
Labels: review-requested, python

#24682 Add ensmallen dependencies
  recipes/bioregistry/meta.yaml
  recipes/cache_decorator/meta.yaml
  recipes/compress_json/meta.yaml
  recipes/curies/meta.yaml
  recipes/deflate_dict/LICENSE
  recipes/deflate_dict/meta.yaml
  recipes/dict_hash/meta.yaml
  recipes/downloaders/LICENSE
  recipes/downloaders/meta.yaml
  recipes/environments_utils/meta.yaml
  recipes/jaro-winkler/meta.yaml
  recipes/more-click/meta.yaml
  recipes/support_developer/LICENSE
  recipes/support_developer/meta.yaml
  recipes/userinput/meta.yaml
  recipes/validate_version_code/LICENSE
  recipes/validate_version_code/meta.yaml
Labels: review-requested, python

#23217 Added inform and nestedtext packages.
  recipes/inform/LICENSE
  recipes/inform/meta.yaml
  recipes/nestedtext/LICENSE
  recipes/nestedtext/meta.yaml
Labels: stale, review-requested, python

#24877 add r-smd package
  recipes/r-smd/bld.bat
  recipes/r-smd/build.sh
  recipes/r-smd/meta.yaml
Labels: R, staged-recipes, review-requested

#24880 add r-sensemakr and r-srvyr packages
  recipes/r-sensemakr/bld.bat
  recipes/r-sensemakr/build.sh
  recipes/r-sensemakr/meta.yaml
  recipes/r-srvyr/bld.bat
  recipes/r-srvyr/build.sh
  recipes/r-srvyr/meta.yaml
Labels: R, review-requested

#24908 add r-medflex package
  recipes/r-medflex/bld.bat
  recipes/r-medflex/build.sh
  recipes/r-medflex/meta.yaml
Labels: R, staged-recipes, review-requested

#24909 add pyopenbt
  recipes/pyopenbt/meta.yaml
Labels: review-requested, python

#24886 Add internetarchive
  recipes/internetarchive/meta.yaml
Labels: staged-recipes, review-requested

#24916 Added exonote as a package
  recipes/exonote/meta.yaml
  recipes/exonote/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#24919 Add pygridmet
  recipes/pygridmet/meta.yaml
Labels: review-requested, python

#24917 Added hooking as a package
  recipes/hooking/meta.yaml
Labels: staged-recipes, review-requested, python

#24888 Add sphinxcontrib-towncrier
  recipes/sphinxcontrib-towncrier/meta.yaml
Labels: review-requested, python

#24929 Adding pem package
  recipes/pem/meta.yaml
Labels: review-requested, python

#24928 added recipe for `concurrentbuffer`
  recipes/concurrentbuffer/meta.yaml
Labels: review-requested, python

#24927 added recipe for `creationism`
  recipes/creationism/meta.yaml
Labels: review-requested, python

#24790 ENH add new stackvana build up to meas_algorithms
  .ci_support/build_all.py
  recipes/stackvana-meas_algorithms/COPYRIGHT
  recipes/stackvana-meas_algorithms/LICENSE
  recipes/stackvana-meas_algorithms/conda-forge.yml
  recipes/stackvana-meas_algorithms/meta.yaml
Labels: staged-recipes, review-requested

#24884 Add poincare recipe
  recipes/poincare/meta.yaml
Labels: review-requested, python

#24907 Add python-twitter-v2 (pytwitter)
  recipes/python-twitter-v2/meta.yaml
Labels: review-requested, python

#24895 Added braq as a package
  recipes/braq/meta.yaml
Labels: staged-recipes, review-requested, python

#24918 Added viewstack as a package
  recipes/viewstack/meta.yaml
  recipes/viewstack/yum_requirements.txt
Labels: staged-recipes, review-requested

#24890 Add trx-python.
  recipes/trx-python/meta.yaml
Labels: review-requested, python

#24906 Add boxsdk
  recipes/boxsdk/meta.yaml
Labels: review-requested, python

#24905 New recipe for 'ncdata'
  recipes/ncdata/meta.yaml
Labels: review-requested, python

#24664 Add ximage recipe
  recipes/ximage/meta.yaml
Labels: review-requested, python

#24931 added recipe for `wholeslidedata`
  recipes/wholeslidedata/meta.yaml
  recipes/wholeslidedata/yum_requirements.txt
Labels: review-requested, python

#24944 Add CyFi
  recipes/cyfi/meta.yaml
  recipes/cyfi/yum_requirements.txt
Labels: review-requested, python

#24867 Add mtenn package
  recipes/mtenn/meta.yaml
Labels: review-requested, python

#24932 Additional CUDA 11.2 cleanup
  .ci_support/linux64.yaml
  .ci_support/linux64_cuda112.yaml
Labels: maintenance

#24945 Add recipe for jhub-apps
  recipes/jhub-apps/meta.yaml
Labels: review-requested, python

#24959 Added r-funspotr as a package
  recipes/r-funspotr/bld.bat
  recipes/r-funspotr/build.sh
  recipes/r-funspotr/meta.yaml
Labels: R, staged-recipes, review-requested

#24933 Add recipe for membrane-curvature
  recipes/membrane-curvature/meta.yaml
Labels: staged-recipes, review-requested, python

#24893 Added paradict as a package
  recipes/paradict/meta.yaml
Labels: staged-recipes, review-requested, python

#24946 Add Django-Apporval
  recipes/django-approval/meta.yaml
Labels: staged-recipes, review-requested

#24898 Add fixit
  recipes/fixit/meta.yaml
Labels: review-requested, python

#24947 Add Django-Moderation
  recipes/django-moderation/meta.yaml
Labels: staged-recipes, review-requested

#24949 Added gaspium as a package
  recipes/gaspium/meta.yaml
  recipes/gaspium/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#24951 Added cappa as a package
  recipes/cappa/meta.yaml
Labels: staged-recipes, review-requested, python

#24952 Added honcho as a package
  recipes/honcho/meta.yaml
Labels: staged-recipes, review-requested, python

#24953 Added paracelsus as a package
  recipes/paracelsus/meta.yaml
Labels: staged-recipes, review-requested, python

#24954 Added microdot as a package
  recipes/microdot/meta.yaml
Labels: staged-recipes, review-requested, python

#24956 Added marcel as a package
  recipes/marcel/meta.yaml
Labels: staged-recipes, review-requested, python

#24957 Added giturlparse as a package
  recipes/giturlparse/meta.yaml
Labels: staged-recipes, review-requested, python

#24958 Added win-precise-time as a package
  recipes/win-precise-time/meta.yaml
Labels: staged-recipes, review-requested, python, python-c

#24960 Added tldraw as a package
  recipes/tldraw/meta.yaml
Labels: staged-recipes, review-requested, python

#24891 Adding mlgb
  recipes/mlgb/meta.yaml
Labels: review-requested, python

#24966 Pyecharts
  recipes/pyecharts/LICENSE
  recipes/pyecharts/meta.yaml
Labels: review-requested, python

#24961 Add tastymap
  recipes/tastymap/meta.yaml
Labels: review-requested, python

#24967 add skfolio
  recipes/skfolio/meta.yaml
Labels: review-requested, python

#24968 add nbprint
  recipes/nbprint/meta.yaml
Labels: review-requested, python

#24939 Add recipe for lupa
  recipes/lupa/meta.yaml
Labels: review-requested, python, python-c

#24974 add kagglehub
  recipes/kagglehub/meta.yaml
Labels: review-requested, python

#24875 Add more trame components
  recipes/trame-code/meta.yaml
  recipes/trame-formkit/meta.yaml
  recipes/trame-grid-layout/meta.yaml
  recipes/trame-iframe/meta.yaml
  recipes/trame-leaflet/meta.yaml
  recipes/trame-pvui/meta.yaml
  recipes/trame-quasar/meta.yaml
  recipes/trame-tauri/meta.yaml
  recipes/trame-xterm/meta.yaml
Labels: review-requested, python

#24955 Added movis as a package
  recipes/movis/meta.yaml
  recipes/movis/yum_requirements.txt
Labels: review-requested, python, python-c

#24971 adding r-tolerance
  recipes/r-tolerance/bld.bat
  recipes/r-tolerance/build.sh
  recipes/r-tolerance/meta.yaml
  recipes/r-tolerance/yum_requirements.txt
Labels: R, review-requested

#24986 Added flask-muck as a package
  recipes/flask-muck/meta.yaml
Labels: staged-recipes, review-requested, python

#24989 Add binlets recipe
  recipes/binlets/meta.yaml
Labels: review-requested, python

#24663 Add disdrodb
  recipes/disdrodb/meta.yaml
Labels: review-requested, python

#24977 Add numthreads Python package recipe
  recipes/numthreads/meta.yaml
Labels: review-requested, python

#24979 Added homeharvest as a package
  recipes/homeharvest/meta.yaml
Labels: staged-recipes, review-requested, python

#24982 Added pygraft as a package
  recipes/pygraft/meta.yaml
Labels: staged-recipes, review-requested, python

#24981 Adding datamapplot
  recipes/datamapplot/meta.yaml
Labels: review-requested, python

#24980 add pytest-twisted
  recipes/pytest-twisted/meta.yaml
Labels: review-requested, python

#24922 Added hubstore as a package
  recipes/hubstore/meta.yaml
  recipes/hubstore/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#24921 Added jupitest as a package
  recipes/jupitest/meta.yaml
  recipes/jupitest/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#24920 Added rustiql as a package
  recipes/rustiql/meta.yaml
  recipes/rustiql/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#24821 Added filequery as a package
  recipes/filequery/meta.yaml
Labels: staged-recipes, review-requested, python

#24985 Added reader as a package
  recipes/reader/meta.yaml
Labels: staged-recipes, review-requested, python

#24993 Add recipe for psycopg-pool
  recipes/psycopg-pool/meta.yaml
Labels: review-requested, python

#24978 add pywwa
  recipes/pywwa/meta.yaml
Labels: review-requested, python

#24996 add gis-utils from PyPI
  recipes/gis-utils/meta.yaml
Labels: review-requested, python

#24995 Added great_tables as a package
  recipes/great_tables/meta.yaml
Labels: staged-recipes, review-requested, python

#24997 Add pawflim recipe
  recipes/pawflim/meta.yaml
Labels: review-requested, python

#21337 Add Robotframework serialLibrary package
  recipes/robotframework-seriallibrary/0000-fix-install-requires-install-requires.patch
  recipes/robotframework-seriallibrary/meta.yaml
Labels: staged-recipes, review-requested

#24994 add r-fdasrvf
  recipes/r-fdasrvf/bld.bat
  recipes/r-fdasrvf/build.sh
  recipes/r-fdasrvf/conda_build_config.yaml
  recipes/r-fdasrvf/meta.yaml
Labels: R, review-requested

#24976 add r-stpphawkes
  recipes/r-stpphawkes/bld.bat
  recipes/r-stpphawkes/build.sh
  recipes/r-stpphawkes/conda_build_config.yaml
  recipes/r-stpphawkes/meta.yaml
Labels: R, review-requested

#23886 Added recipe for pycompilation.
  recipes/pycompilation/importlib.patch
  recipes/pycompilation/meta.yaml
  recipes/pycompilation/on_the_fly_main.py
Labels: Awaiting author contribution, python

#24719 recipe for attributedict
  recipes/attributedict/meta.yaml
Labels: review-requested, python

#25003 Recipe for Aioprometheus
  recipes/aioprometheus/meta.yaml
Labels: review-requested, python

#25000 add vale-ls 0.3.7
  recipes/vale-ls/bld.bat
  recipes/vale-ls/build.sh
  recipes/vale-ls/meta.yaml
Labels: R, staged-recipes, review-requested

#24897 add serapis package
  recipes/serapis/meta.yaml
Labels: review-requested, python

#25015 Add recipe for dashing
  recipes/dashing/meta.yaml
Labels: review-requested, python

#23741 Add libsecp256k1 & libsecp256k1-py-bindings & coincurve
  .appveyor.yml.notused
  .ci_support/requirements.txt
  .github/workflows/scripts/create_feedstocks
  recipes/coincurve/meta.yaml
  recipes/libsecp256k1-py-bindings/meta.yaml
  recipes/libsecp256k1/0001_conda_relocatable.patch
  recipes/libsecp256k1/bld.bat
  recipes/libsecp256k1/build.sh
  recipes/libsecp256k1/meta.yaml
  recipes/libsecp256k1/shared_standalone_tests/src/CMakeLists.txt
  recipes/libsecp256k1/shared_standalone_tests/src/cmake/TryAppendCFlags.cmake
Labels: Awaiting author contribution, python-c

#24930 Add recipes for `lsst-sphgeom` and `lsst-versions`
  recipes/lsst-sphgeom/meta.yaml
  recipes/lsst-versions/meta.yaml
Labels: review-requested, python-c

#25020 Add tilupy python package
  recipes/tilupy/meta.yaml
Labels: review-requested, python

#24910 add radtraq
  recipes/radtraq/meta.yaml
Labels: review-requested, python

#25022 Add recipe for asitop
  recipes/asitop/meta.yaml
Labels: review-requested, python

#25026 Add CUDA 11.8
  .azure-pipelines/azure-pipelines-linux.yml
  .ci_support/linux64_cuda118.yaml
Labels: maintenance

#25002 Add can-isotp package
  recipes/can-isotp/meta.yaml
Labels: staged-recipes, review-requested, python

#25029 Use `conda-index`'s `update_index`
  .ci_support/build_all.py
  .ci_support/requirements.txt
Labels: maintenance

#24408 Add simple-build-system pkg
  recipes/simple-build-system/meta.yaml
  recipes/simple-build-system/run_test.sh
Labels: review-requested, python

#24926 Added recipe for nrtk
  recipes/nrtk/meta.yaml
  recipes/nrtk/yum_requirements.txt
Labels: review-requested, python

#25031 Adding `trustllm` from PyPI
  recipes/trustllm/LICENSE
  recipes/trustllm/meta.yaml
Labels: staged-recipes, review-requested, python

#24885 Add qt6-graphs
  recipes/qt-graphs/bld.bat
  recipes/qt-graphs/build.sh
  recipes/qt-graphs/meta.yaml
  recipes/qt-graphs/yum_requirements.txt
Labels: review-requested, c-cpp

#25025 Add `redis-dict` package
  recipes/redis-dict/meta.yaml
Labels: staged-recipes, review-requested, python

#24726 Adding the USNISTGOV SCTK (word error rate scoring toolkit) as a conda package
  recipes/sctk/0001-fix-compiler-for-rfilter1.patch
  recipes/sctk/LICENSE.txt
  recipes/sctk/build.sh
  recipes/sctk/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#24787 Adding sasktran2
  recipes/sasktran2/meta.yaml
Labels: review-requested, python-c

#25024 Add recipe for mlx-lm
  recipes/mlx-lm/meta.yaml
Labels: review-requested, python

#25001 Adding qpbenchmark
  recipes/qpbenchmark/meta.yaml
Labels: review-requested, python

#25011 Added autometrics as a package
  recipes/autometrics/meta.yaml
Labels: staged-recipes, review-requested, python

#22839 Add mpv
  recipes/mpv/build.sh
  recipes/mpv/conda_build_config.yaml
  recipes/mpv/meta.yaml
Labels: review-requested, c-cpp

#24039 Adding SpiceQL
  recipes/spiceql/bld.bat
  recipes/spiceql/build.sh
  recipes/spiceql/meta.yaml
Labels: staged-recipes, review-requested

#24948 add xmpppy
  recipes/xmpppy/meta.yaml
Labels: review-requested, python

#25041 feat: add `pypi` package `vector-vis-graph`
  recipes/vector-vis-graph/meta.yaml
Labels: review-requested, python

#25043 Add recipe for launchdarkly-eventsource
  recipes/launchdarkly-eventsource/meta.yaml
Labels: review-requested, python

#24003 add xgboost-ray / lightgbm-ray
  recipes/lightgbm_ray/meta.yaml
  recipes/xgboost_ray/meta.yaml
Labels: review-requested, python

#25052 Add mkdocstrings-python-xref feedstock
  recipes/mkdocstrings-python-xref/LICENSE.md
  recipes/mkdocstrings-python-xref/meta.yaml
Labels: review-requested, python

#25054 Add optparse-pretty
  recipes/optparse-pretty/LICENSE
  recipes/optparse-pretty/meta.yaml
Labels: review-requested, python

#25053 Add modflow-setup package
  recipes/modflow-setup/meta.yaml
Labels: review-requested, python

#25057 Add gwcosmo
  recipes/gwcosmo/conda_build_config.yaml
  recipes/gwcosmo/meta.yaml
Labels: staged-recipes, review-requested, python

#23944 Add r-quickjsr.
  recipes/r-quickjsr/LICENSE-quickjs
  recipes/r-quickjsr/bld.bat
  recipes/r-quickjsr/build.sh
  recipes/r-quickjsr/conda_build_config.yaml
  recipes/r-quickjsr/meta.yaml
Labels: R, review-requested, c-cpp

#23778 Add bech32 package
  recipes/bech32/LICENSE.txt
  recipes/bech32/meta.yaml
Labels: review-requested, python

#23775 Add aioprocessing
  recipes/aioprocessing/meta.yaml
Labels: review-requested, python

#25006 Add recipes for harlequin-extensions
  recipes/harlequin-bigquery/meta.yaml
  recipes/harlequin-odbc/meta.yaml
  recipes/harlequin-postgres/meta.yaml
  recipes/harlequin-trino/meta.yaml
Labels: review-requested, python

#25035 adds `r-usemodels`
  recipes/r-usemodels/bld.bat
  recipes/r-usemodels/build.sh
  recipes/r-usemodels/meta.yaml
Labels: R, review-requested

#25016 Add recipe for rice
  recipes/rice/bld.bat
  recipes/rice/build.sh
  recipes/rice/meta.yaml
Labels: R, review-requested, ruby

#25059 add pandas-bokeh
  recipes/pandas-bokeh/meta.yaml
Labels: staged-recipes, review-requested

#25070 Add recipe for openactive
  recipes/openactive/meta.yaml
Labels: staged-recipes, review-requested, python

#25072 Add snaphu
  recipes/snaphu/meta.yaml
Labels: review-requested, python-c

#25080 Adding hydrosar python package
  recipes/hydrosar/meta.yaml
Labels: review-requested, python

#25068 Add haystack-ai
  recipes/haystack-ai/conda_build_config.yaml
  recipes/haystack-ai/meta.yaml
Labels: review-requested, python

#25084 Add safety-schemas 0.0.1
  recipes/safety-schemas/meta.yaml
Labels: staged-recipes, review-requested, python

#25083 Add ssh-utilities
  recipes/ssh-utilities/meta.yaml
Labels: staged-recipes, review-requested, python

#25074 Added pascal-voc-writer
  recipes/pascal-voc-writer/meta.yaml
Labels: review-requested, python

#25086 Add conda_subprocess
  recipes/conda_subprocess/meta.yaml
Labels: staged-recipes, review-requested, python

#25095 Add a recipe for apache-airflow-providers-common-io
  recipes/apache-airflow-providers-common-io/meta.yaml
Labels: review-requested, python

#25099 Introduce @conda-forge/help-rust
  .github/pull_request_template.md
  .github/workflows/automate-review-labels.yml
Labels: staged-recipes, review-requested

#25060 Add files via upload
  recipes/cptec-model/meta.yaml
Labels: staged-recipes, review-requested, python

#25078 add perl-compress-bgzf
  recipes/perl-compress-bgzf/meta.yaml
Labels: review-requested, perl

#25105 add `r-interleave`
  recipes/r-interleave/bld.bat
  recipes/r-interleave/build.sh
  recipes/r-interleave/meta.yaml
Labels: R, review-requested

#25104 Add recipe for sphinx-wagtail-theme
  recipes/sphinx-wagtail-theme/meta.yaml
Labels: review-requested, python

#25063 Added OSM python tools recipe
  recipes/OSMPythonTools/meta.yaml
Labels: review-requested, python

#25114 Add xcube-smos recipe
  recipes/xcube-smos/meta.yaml
Labels: review-requested, python

#24938 Add BeAMF package
  recipes/BeAMF/meta.yaml
Labels: staged-recipes, review-requested, python

#25126 Add Recipe for `s1_frame_enumerator`
  recipes/s1_frame_enumerator/meta.yaml
Labels: review-requested, python

#25113 add pydantic-partial 0.5.4
  recipes/pydantic-partial/meta.yaml
Labels: staged-recipes, review-requested, python

#25112 Add pygmtools
  recipes/pygmtools/meta.yaml
Labels: staged-recipes, review-requested, python

#25111 Added inputimeout
  recipes/inputimeout/meta.yaml
Labels: review-requested, python

#25107 Add Python Package `tile_mate`
  recipes/tile_mate/meta.yaml
Labels: review-requested, python

#25091 Add taipy-config
  recipes/taipy-config/meta.yaml
Labels: staged-recipes, review-requested, python

#23240 Add GHEtool
  recipes/GHEtool/meta.yaml
Labels: review-requested, python

#25143 Add simple_template recipe
  recipes/simple_template/meta.yaml
Labels: staged-recipes, review-requested, python
