Repository conda-forge/staged-recipes, pull requests merged in 2024-05, with the labels that each got.

#26196 Add recipe for mlx-vlm
  recipes/mlx-vlm/meta.yaml
Labels: review-requested, python

#26182 add python-systemd
  recipes/python-systemd/conda_build_config.yaml
  recipes/python-systemd/meta.yaml
Labels: review-requested, python

#26200 add google-geo-type package
  recipes/google-geo-type/meta.yaml
Labels: review-requested, python

#26191 Add pylabeladjust to conda-forge
  recipes/pylabeladjust/meta.yaml
Labels: review-requested, python

#26206 Add `c_stdlib_version` to Linux variants
  .ci_support/linux64.yaml
  .ci_support/linux64_cuda112.yaml
  .ci_support/linux64_cuda118.yaml
  .ci_support/linux64_cuda120.yaml
Labels: maintenance

#26204 Drop CUDA 11.2
  .azure-pipelines/azure-pipelines-linux.yml
  .ci_support/linux64_cuda112.yaml
  .ci_support/linux64_cuda118.yaml
  .ci_support/linux64_cuda120.yaml
Labels: maintenance

#26171 Add qcs-sdk-python
  recipes/qcs-sdk-python/bld.bat
  recipes/qcs-sdk-python/build.sh
  recipes/qcs-sdk-python/conda_build_config.yaml
  recipes/qcs-sdk-python/install.bat
  recipes/qcs-sdk-python/install.sh
  recipes/qcs-sdk-python/install_grpc.bat
  recipes/qcs-sdk-python/install_grpc.sh
  recipes/qcs-sdk-python/meta.yaml
  recipes/qcs-sdk-python/pyproject.toml
Labels: R, review-requested, rust

#26194 Adding `auto-ts` from PyPI
  recipes/auto-ts/LICENSE
  recipes/auto-ts/meta.yaml
Labels: review-requested, python

#26085 Add gwtc tools package
  recipes/gwtc-tools/meta.yaml
Labels: staged-recipes, review-requested, python

#26209 Add pandas-indexing python package
  recipes/pandas-indexing/meta.yaml
Labels: review-requested, python

#26208 Add recipe for mlx-ctc
  recipes/mlx-ctc/conda_build_config.yaml
  recipes/mlx-ctc/meta.yaml
Labels: review-requested, python

#26211 ENH add pizza-patches code
  recipes/des-pizza-patches/meta.yaml
Labels: review-requested, python

#26210 Added prefect-docker
  recipes/prefect-docker/meta.yaml
Labels: review-requested, python

#26199 add google-maps-routing package
  recipes/google-maps-routing/meta.yaml
Labels: review-requested, python

#26214 ENH add des-pizza-cutter-masking
  recipes/pcm/meta.yaml
Labels: review-requested, python

#25886 Conda-forge feedstock for libucc.
  recipes/ucc/0001-EC-CUDA-fix-build-with-12.2-and-older-arch-847.patch
  recipes/ucc/build.sh
  recipes/ucc/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#26215 Add tt-sketch
  recipes/tt-sketch/LICENSE
  recipes/tt-sketch/meta.yaml
Labels: staged-recipes, review-requested, python-c

#26219 Add equalityml from pypi
  recipes/equalityml/meta.yaml
Labels: review-requested, python

#26190 Add r-chnosz
  recipes/r-chnosz/bld.bat
  recipes/r-chnosz/build.sh
  recipes/r-chnosz/meta.yaml
Labels: R, review-requested

#26197 Add meta.yaml for nbappinator from PyPI
  recipes/nbappinator/meta.yaml
Labels: staged-recipes, review-requested, python

#26223 Add recipe for mlx-image
  recipes/mlx-image/meta.yaml
Labels: review-requested, python

#26225 Add recipe for samplex
  recipes/samplex/meta.yaml
Labels: staged-recipes, review-requested

#26224 Add recipe for amara3.iri
  recipes/amara3.iri/0001-Remove-pytest-from-requirements.patch
  recipes/amara3.iri/LICENSE
  recipes/amara3.iri/meta.yaml
Labels: review-requested, python

#26216 Adding plasticparcels
  recipes/plasticparcels/meta.yaml
Labels: review-requested, python

#26226 Add modelmimic recipe
  recipes/modelmimic/meta.yaml
Labels: review-requested, python

#23821 Adding julearn
  recipes/julearn/meta.yaml
Labels: staged-recipes, review-requested, python

#26195 Add `ampform-dpd` from PyPI
  recipes/ampform-dpd/meta.yaml
Labels: review-requested, python

#25857 Add package scikit-fdiff
  recipes/scikit-fdiff/LICENSE
  recipes/scikit-fdiff/meta.yaml
Labels: review-requested, python

#25062 Add package Elegant, including MPI-accelerated Pelegant (Parallel Elegant)
  recipes/elegant/build.sh
  recipes/elegant/fdlibm_license.txt
  recipes/elegant/meschach_license.txt
  recipes/elegant/meta.yaml
  recipes/elegant/pgapack_license.txt
  recipes/elegant/xlslib_license.txt
Labels: review-requested, c-cpp

#25901 Add libcuba
  recipes/libcuba/0001-Add-CMake-script.patch
  recipes/libcuba/0002-Fix-build-on-MinGW.patch
  recipes/libcuba/0003-Fix-build-on-MSVC.patch
  recipes/libcuba/0005-Hardlink-KorobovCoeff.c.patch
  recipes/libcuba/bld.bat
  recipes/libcuba/build.sh
  recipes/libcuba/meta.yaml
Labels: review-requested, c-cpp

#26231 Add fastapi-cli
  recipes/fastapi-cli/meta.yaml
Labels: review-requested, python

#25056 Add tsplib95 and python-tsp.
  recipes/python-tsp/example.py
  recipes/python-tsp/meta.yaml
  recipes/tsplib95/meta.yaml
Labels: review-requested, python

#26232 Added r-erify as a package
  recipes/r-erify/bld.bat
  recipes/r-erify/build.sh
  recipes/r-erify/meta.yaml
Labels: R, staged-recipes, review-requested

#26227 Added r-thankr as a package
  recipes/r-thankr/bld.bat
  recipes/r-thankr/build.sh
  recipes/r-thankr/meta.yaml
Labels: R, staged-recipes, review-requested

#26230 Added r-citation as a package
  recipes/r-citation/bld.bat
  recipes/r-citation/build.sh
  recipes/r-citation/meta.yaml
Labels: R, staged-recipes, review-requested

#26221 Added r-allcontributors as a package
  recipes/r-allcontributors/bld.bat
  recipes/r-allcontributors/build.sh
  recipes/r-allcontributors/meta.yaml
Labels: R, staged-recipes, review-requested

#26238 BUG: Add missing channel pinnings
  .ci_support/linux64.yaml
  .ci_support/linux64_cuda118.yaml
  .ci_support/linux64_cuda120.yaml
  .ci_support/osx64.yaml
  .ci_support/win64.yaml
Labels: maintenance

#26237 Add daemontools-encore
  recipes/daemontools-encore/build.sh
  recipes/daemontools-encore/cflags.patch
  recipes/daemontools-encore/ldflags.patch
  recipes/daemontools-encore/meta.yaml
Labels: staged-recipes, review-requested

#26244 Add executorlib-core
  recipes/executorlib-core/meta.yaml
Labels: staged-recipes, review-requested, python

#24520 Add recipe for crystal-toolkit and dependencies
  recipes/crystal-toolkit/meta.yaml
  recipes/crystaltoolkit-extension/meta.yaml
  recipes/dash-mp-components/meta.yaml
Labels: review-requested, python

#26228 Add libzio
  recipes/libzio/build.sh
  recipes/libzio/fix-makefile.diff
  recipes/libzio/meta.yaml
Labels: review-requested, c-cpp

#26258 Add verticalize
  recipes/verticalize/build.sh
  recipes/verticalize/meta.yaml
Labels: staged-recipes, review-requested

#26262 Add recipe for robomimic
  recipes/robomimic/meta.yaml
Labels: staged-recipes, review-requested, python, python-c

#26261 Add relentless
  recipes/relentless/meta.yaml
Labels: review-requested, python

#26218 Adding recipe for FINUFFT
  recipes/finufft/0001-python-extension.patch
  recipes/finufft/0002-cufinufft-no-static.patch
  recipes/finufft/0003-cufinufft-python-extension.patch
  recipes/finufft/build_finufft.bat
  recipes/finufft/build_finufft.sh
  recipes/finufft/conda_build_config.yaml
  recipes/finufft/meta.yaml
Labels: review-requested, c-cpp, python

#26201 Add sunkit-magex
  recipes/sunkit-magex/meta.yaml
Labels: review-requested, python

#26268 Add menpowidgets v0.4.3
  recipes/menpowidgets/meta.yaml
Labels: review-requested, python

#26275 Add physicsml and molflux
  recipes/molflux/meta.yaml
  recipes/physicsml/meta.yaml
Labels: staged-recipes, review-requested, python

#26278 Added finvader as a package
  recipes/finvader/meta.yaml
Labels: staged-recipes, review-requested

#26281 Adding auroris
  recipes/auroris/meta.yaml
Labels: review-requested, python

#26277 Add aixd_ara: grasshopper plugin for the aixd toolkit
  recipes/aixd_ara/meta.yaml
Labels: review-requested, python

#26284 Add ragas
  recipes/ragas/meta.yaml
Labels: staged-recipes, review-requested, python

#26279 feat: Add hepdata-validator
  recipes/hepdata-validator/meta.yaml
Labels: review-requested, python

#26287 Add langchainhub
  recipes/langchainhub/meta.yaml
Labels: staged-recipes, review-requested, python

#26250 Add recipe for libmetatensor
  recipes/libmetatensor/bld.bat
  recipes/libmetatensor/build.sh
  recipes/libmetatensor/conda_build_config.yaml
  recipes/libmetatensor/meta.yaml
Labels: R, review-requested, c-cpp, rust

#26272 Add fa2_modified
  recipes/fa2_modified/meta.yaml
Labels: review-requested, python-c

#26119 add dspy-ai
  recipes/dspy-ai/meta.yaml
Labels: review-requested, python

#26295 Add langchain-groq
  recipes/groq/meta.yaml
  recipes/langchain-groq/meta.yaml
Labels: staged-recipes, review-requested

#26290 Add json-flattener recipe
  recipes/json-flattener/LICENSE
  recipes/json-flattener/meta.yaml
Labels: review-requested, python

#26291 Add prefixmaps recipe
  recipes/prefixmaps/meta.yaml
Labels: review-requested, python

#26294 Add langchain-anthropic
  recipes/langchain-anthropic/meta.yaml
Labels: staged-recipes, review-requested, python

#26298 Add recipe for dbt-athena-community
  recipes/dbt-athena-community/meta.yaml
Labels: staged-recipes, review-requested, python

#26301 add recipe for preliz
  recipes/preliz/meta.yaml
Labels: review-requested, python

#26288 Add receipe for sysloss
  recipes/sysloss/meta.yaml
Labels: review-requested, python

#26257 Add aiolimiter
  recipes/aiolimiter/meta.yaml
Labels: review-requested, python

#26266 Adding python-cmethods
  recipes/python-cmethods/meta.yaml
Labels: review-requested, python

#26317 Add packaged and yen
  recipes/packaged/meta.yaml
  recipes/yen/meta.yaml
Labels: review-requested, python

#26309 add yahoo-search-py
  recipes/yahoo-search-py/meta.yaml
Labels: staged-recipes, review-requested, python

#26307 Add langchain-google-genai
  recipes/google-ai-generativelanguage/meta.yaml
  recipes/google-generativeai/meta.yaml
  recipes/langchain-google-genai/meta.yaml
Labels: staged-recipes, review-requested, python

#26292 Add chiLife recipe
  recipes/chilife/meta.yaml
Labels: review-requested, python

#26306 Add Daff
  recipes/daff/LICENSE.md
  recipes/daff/meta.yaml
Labels: review-requested, python

#26320 Add `aioca` package
  recipes/aioca/LICENSE
  recipes/aioca/meta.yaml
Labels: staged-recipes, review-requested, python

#26303 Add maite recipe
  recipes/maite/meta.yaml
Labels: review-requested, python

#26322 Add dbt-common
  recipes/dbt-common/meta.yaml
Labels: review-requested, python

#26192 Add gnucobol
  recipes/gnucobol/build.sh
  recipes/gnucobol/meta.yaml
  recipes/gnucobol/test.sh
Labels: review-requested, c-cpp

#26293 feat: Add hepdata-lib
  recipes/hepdata-lib/meta.yaml
Labels: review-requested, python

#26300 added pdemtools recipe
  recipes/pdemtools/meta.yaml
  recipes/pdemtools/yum_requirements.txt
Labels: review-requested, python

#26093 add litescope
  recipes/litescope/meta.yaml
Labels: review-requested, python

#26324 Added lxml-html-clean as a package
  recipes/lxml-html-clean/meta.yaml
Labels: staged-recipes, review-requested, python

#26325 Added mf2py as a package
  recipes/mf2py/meta.yaml
Labels: staged-recipes, review-requested, python

#25766 Adding fluoriclogppka package
  recipes/fluoriclogppka/meta.yaml
Labels: review-requested, python

#25777 adding myjive package
  recipes/myjive/meta.yaml
Labels: review-requested, python

#26094 adding litesata
  recipes/litesata/meta.yaml
Labels: Awaiting author contribution, python

#26308 add minify-html
  recipes/minify-html/conda_build_config.yaml
  recipes/minify-html/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#26326 Added pyrdfa3 as a package
  recipes/pyrdfa3/meta.yaml
Labels: staged-recipes, review-requested, python

#24559 Add package: hyfetch
  recipes/hyfetch/meta.yaml
Labels: Awaiting author contribution, python

#26327 Add dbt-adapters
  recipes/dbt-adapters/meta.yaml
Labels: review-requested, python

#24711 recipe for auto_gqtq
  recipes/auto_gptq/meta.yaml
  recipes/auto_gptq/patches/setup.patch
Labels: review-requested, python-c

#26334 Add recipe for gen_domain tools from CIME
  recipes/gen_domain/CMakeLists.txt
  recipes/gen_domain/build.sh
  recipes/gen_domain/cmake/FindNETCDF.cmake
  recipes/gen_domain/cmake_macros/gnu.cmake
  recipes/gen_domain/meta.yaml
Labels: staged-recipes, review-requested

#26337 Adding pytest-flakefinder
  recipes/pytest-flakefinder/meta.yaml
Labels: review-requested, python

#26336 Adding pytest-shard
  recipes/pytest-shard/LICENSE.txt
  recipes/pytest-shard/meta.yaml
Labels: review-requested, python

#26328 add: testcontainers-python
  recipes/testcontainers/meta.yaml
Labels: review-requested, python

#26340 Add dbt-postgres
  recipes/dbt-postgres/meta.yaml
Labels: review-requested, python

#26329 Add pyproject-fmt-rust 1.0.4
  recipes/pyproject-fmt-rust/conda_build_config.yaml
  recipes/pyproject-fmt-rust/meta.yaml
Labels: R, review-requested, python, python-c, rust

#26338 Add age
  recipes/age/meta.yaml
Labels: review-requested, go

#26335 Add recipe for squadgen
  recipes/squadgen/0001-remove-png-h.patch
  recipes/squadgen/CMakeLists.txt
  recipes/squadgen/build.sh
  recipes/squadgen/cmake/FindNETCDF.cmake
  recipes/squadgen/cmake_macros/gnu.cmake
  recipes/squadgen/meta.yaml
  recipes/squadgen/test/grid.png
Labels: review-requested, c-cpp

#26052 Adding pyleco recipe (python package)
  recipes/pyleco/meta.yaml
Labels: review-requested, python

#26323 Added html-text as a package
  recipes/html-text/meta.yaml
Labels: staged-recipes, review-requested, python

#26222 Adding r-bwstools
  recipes/r-bwstools/bld.bat
  recipes/r-bwstools/build.sh
  recipes/r-bwstools/meta.yaml
Labels: R, review-requested

#26351 add faststream and fast-depends pacakges
  recipes/fast-depends/meta.yaml
  recipes/faststream/meta.yaml
Labels: staged-recipes, review-requested

#26352 add posix_ipc
  recipes/posix_ipc/meta.yaml
Labels: review-requested, python

#26348 add pyncview and dependencies
  recipes/pyncview/meta.yaml
  recipes/xmlplot/meta.yaml
  recipes/xmlstore/meta.yaml
Labels: review-requested, python

#26067 Adding superblockify recipy
  recipes/superblockify/conda_build_config.yaml
  recipes/superblockify/meta.yaml
Labels: Awaiting author contribution, python

#21900 Add tinycbor c++ library package
  recipes/tinycbor/0001-Add-CMake-support.patch
  recipes/tinycbor/0002-Fix-static_assert-compiler-support.patch
  recipes/tinycbor/bld.bat
  recipes/tinycbor/build.sh
  recipes/tinycbor/meta.yaml
Labels: review-requested, c-cpp

#26353 Added vet as a package
  recipes/vet/meta.yaml
Labels: staged-recipes, review-requested, python

#26356 Added pacemaker-lite as a package
  recipes/pacemaker-lite/meta.yaml
Labels: staged-recipes, review-requested, python

#26358 Added arabica as a package
  recipes/arabica/meta.yaml
Labels: staged-recipes, review-requested, python

#26345 add quickseries package
  recipes/quickseries/meta.yaml
Labels: review-requested, python

#26363 Added simple_spaced_repetition as a package
  recipes/simple_spaced_repetition/meta.yaml
Labels: staged-recipes, review-requested, python

#26362 add nats-py package
  recipes/nats-py/meta.yaml
Labels: staged-recipes, review-requested

#26364 Added wireviz as a package
  recipes/wireviz/meta.yaml
Labels: staged-recipes, review-requested, python

#26359 Add langchain-huggingface
  recipes/langchain-huggingface/meta.yaml
  recipes/text-generation/LICENSE
  recipes/text-generation/meta.yaml
Labels: staged-recipes, review-requested, python

#26321 Added extruct as a package
  recipes/extruct/meta.yaml
Labels: staged-recipes, review-requested, python

#26365 Added escaping as a package
  recipes/escaping/meta.yaml
Labels: staged-recipes, review-requested, python

#26366 Added django-simple-menu as a package
  recipes/django-simple-menu/meta.yaml
Labels: staged-recipes, review-requested, python

#26369 add exactextract
  recipes/exactextract/conda_build_config.yaml
  recipes/exactextract/meta.yaml
Labels: review-requested, python

#26376 Add Orthority v0.4.0
  recipes/orthority/meta.yaml
Labels: review-requested, python

#26357 Add recipe for `mrmr-selection`
  recipes/mrmr_selection/LICENSE
  recipes/mrmr_selection/meta.yaml
Labels: review-requested, python

#26274 Creating recipe for CosolvKit package
  recipes/cosolvkit/meta.yaml
  recipes/cosolvkit/yum_requirements.txt
Labels: review-requested, python

#26388 Added loguru-mypy as a package
  recipes/loguru-mypy/meta.yaml
Labels: staged-recipes, review-requested, python

#26382 Add Valmix
  recipes/valmix/meta.yaml
Labels: review-requested, python

#26316 Add recipe for libmetatensor-torch
  recipes/libmetatensor-torch/conda_build_config.yaml
  recipes/libmetatensor-torch/meta.yaml
  recipes/libmetatensor-torch/test-project/CMakeLists.txt
  recipes/libmetatensor-torch/test-project/main.cpp
Labels: Awaiting author contribution, c-cpp

#26361 Add biome
  recipes/biome/conda_build_config.yaml
  recipes/biome/meta.yaml
Labels: R, review-requested, rust

#26385 Adding geouned
  recipes/geouned/meta.yaml
Labels: review-requested, python

#26400 Added itrm as a package
  recipes/itrm/meta.yaml
Labels: staged-recipes, review-requested, python

#26398 Add qonnx
  recipes/qonnx/meta.yaml
Labels: review-requested, python

#26399 Add uxsim as a package
  recipes/uxsim/meta.yaml
Labels: staged-recipes, review-requested, python

#26401 Add bokeh-django
  recipes/bokeh-django/meta.yaml
Labels: review-requested, python

#26386 Adding r-fairmodels from CRAN, recipe gen via conda_r_skeleton_helper
  recipes/r-fairmodels/bld.bat
  recipes/r-fairmodels/build.sh
  recipes/r-fairmodels/meta.yaml
Labels: R, review-requested

#26381 Adding Higra python package
  recipes/higra/conda_build_config.yaml
  recipes/higra/meta.yaml
Labels: review-requested, python-c

#26393 Add recipe for pyampute
  recipes/pyampute/meta.yaml
Labels: review-requested, python

#26395 add lkml 1.3.4
  recipes/lkml/meta.yaml
Labels: review-requested, python

#26404 added pygmc
  recipes/pygmc/meta.yaml
Labels: review-requested, python

#26405 Add pygenomeviz
  recipes/pygenomeviz/meta.yaml
Labels: review-requested, python

#26271 Added r-makefiler as a package
  recipes/r-makefiler/bld.bat
  recipes/r-makefiler/build.sh
  recipes/r-makefiler/meta.yaml
Labels: R, staged-recipes, review-requested

#26263 Added r-debugr as a package
  recipes/r-debugr/bld.bat
  recipes/r-debugr/build.sh
  recipes/r-debugr/meta.yaml
Labels: R, staged-recipes, review-requested

#26234 Added r-flow as a package
  recipes/r-flow/bld.bat
  recipes/r-flow/build.sh
  recipes/r-flow/meta.yaml
Labels: R, staged-recipes, review-requested

#26406 Add StringZilla - SIMD-accelerated string search
  recipes/stringzilla/conda_build_config.yaml
  recipes/stringzilla/meta.yaml
Labels: review-requested, python, python-c

#26184 nrtk-explorer: Added Pypi nrtk-explorer package
  recipes/nrtk-explorer/LICENSE
  recipes/nrtk-explorer/meta.yaml
  recipes/nrtk-explorer/yum_requirements.txt
Labels: Awaiting author contribution, python

#26384 Adding recipe for the Python package "passwordless"
  recipes/passwordless/meta.yaml
Labels: review-requested, python

#26415 Add HySetter
  conda_build_config.yaml
  recipes/hysetter/meta.yaml
Labels: review-requested, python

#26407 v0.2.0 of sphinxcontrib-video initial conda-forge package added
  recipes/sphinxcontrib-video/meta.yaml
Labels: review-requested, python

#26413 Add msgraph-core and its missing dependencies
  recipes/microsoft-kiota-abstractions/meta.yaml
  recipes/microsoft-kiota-authentication-azure/meta.yaml
  recipes/microsoft-kiota-http/meta.yaml
  recipes/msgraph-core/meta.yaml
  recipes/std-uritemplate/LICENSE
  recipes/std-uritemplate/meta.yaml
Labels: review-requested, python

#26420 Add bokeh_sampledata
  recipes/bokeh_sampledata/meta.yaml
Labels: review-requested, python

#26180 Add r-rcdd to conda-forge
  recipes/r-rcdd/bld.bat
  recipes/r-rcdd/build.sh
  recipes/r-rcdd/meta.yaml
Labels: R, review-requested

#26416 Add html5-parser 0.4.12
  recipes/html5-parser/0000-no-build-test.diff
  recipes/html5-parser/bld.bat
  recipes/html5-parser/build.sh
  recipes/html5-parser/meta.yaml
  recipes/html5-parser/run_test.py
Labels: review-requested, python, python-c

#26428 Add jiter
  recipes/jiter/conda_build_config.yaml
  recipes/jiter/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#26423 Adding recipe for streamlit_passwordless Python package.
  recipes/streamlit_passwordless/meta.yaml
Labels: review-requested, python

#26419 Add Carma (fast conversion between Armadillo and Numpy matrices)
  recipes/carma/bld.bat
  recipes/carma/build.sh
  recipes/carma/meta.yaml
Labels: review-requested, c-cpp, python, python-c

#26431 add pygbif
  recipes/pygbif/meta.yaml
Labels: staged-recipes, review-requested
