Repository conda-forge/staged-recipes, pull requests merged in 2024-07, with the labels that each got.

#26793 Added reladiff as a package
  recipes/reladiff/meta.yaml
Labels: staged-recipes, review-requested, python

#26795 adding spectra-cpp
  recipes/spectra-cpp/bld.bat
  recipes/spectra-cpp/build.sh
  recipes/spectra-cpp/meta.yaml
Labels: review-requested, c-cpp

#26749 Add TBLIS
  recipes/tblis/build.sh
  recipes/tblis/meta.yaml
Labels: review-requested, c-cpp

#26661 add medatetime
  recipes/medatetime/LICENSE
  recipes/medatetime/meta.yaml
Labels: review-requested, python-c

#26813 Add new package: pydron-dataflow
  recipes/pydron-dataflow/meta.yaml
Labels: review-requested, python

#26768 Added nx-parallel
  recipes/nx-parallel/meta.yaml
Labels: review-requested, python

#26775 Adding dmgbuild
  recipes/dmgbuild/conda-forge.yaml
  recipes/dmgbuild/meta.yaml
Labels: review-requested, python

#26757 Add cfgraph recipe
  recipes/cfgraph/LICENSE.txt
  recipes/cfgraph/meta.yaml
Labels: review-requested, python

#26815 Add rdflib-shim recipe
  recipes/rdflib-shim/meta.yaml
Labels: review-requested, python

#26816 Add shexjsg recipe
  recipes/shexjsg/meta.yaml
Labels: review-requested, python

#26792 Add pydantic-mongo
  recipes/pydantic-mongo/meta.yaml
Labels: review-requested, python

#26806 add csp-adapter-symphony
  recipes/csp-adapter-symphony/meta.yaml
Labels: review-requested, python

#25193 Added qh3 as a package
  recipes/qh3/conda_build_config.yaml
  recipes/qh3/meta.yaml
Labels: Awaiting author contribution, c-cpp

#26526 Adding bfiocpp recipe
  conda_build_config.yaml
  recipes/bfiocpp/bld.bat
  recipes/bfiocpp/build.sh
  recipes/bfiocpp/cmake_osx_png.patch
  recipes/bfiocpp/conda_build_config.yaml
  recipes/bfiocpp/meta.yaml
  recipes/bfiocpp/windows_build.patch
Labels: review-requested, c-cpp

#26818 Added harfile as a package
  recipes/harfile/meta.yaml
Labels: staged-recipes, review-requested, python

#26738 Add OpenFBX
  recipes/OpenFBX/bld.bat
  recipes/OpenFBX/build.sh
  recipes/OpenFBX/meta.yaml
Labels: review-requested, c-cpp

#26821 Added cookiecutter-data-science as a package
  recipes/cookiecutter-data-science/meta.yaml
Labels: staged-recipes, review-requested, python

#26822 Added terminaltexteffects as a package
  recipes/terminaltexteffects/meta.yaml
Labels: staged-recipes, review-requested

#26826 Add PyShExC recipe
  recipes/PyShExC/meta.yaml
Labels: review-requested, python

#26824 Added antitesting as a package
  recipes/antitesting/meta.yaml
Labels: staged-recipes, review-requested, python

#26827 Add termdbms
  recipes/termdbms/meta.yaml
Labels: review-requested, go

#26588 Conda forge package kmc_smudge_pairs
  recipes/kmc-smudge-pairs/build.sh
  recipes/kmc-smudge-pairs/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#26835 Added crawlerdetect as a package
  recipes/crawlerdetect/meta.yaml
Labels: staged-recipes, review-requested, python

#26834 Added copykitten as a package
  recipes/copykitten/meta.yaml
Labels: R, staged-recipes, review-requested, python, rust

#26846 Adding foxes-opt
  recipes/foxes-opt/meta.yaml
Labels: review-requested, python

#26847 Add pyometiff
  recipes/pyometiff/meta.yaml
  recipes/pyometiff/require.patch
Labels: staged-recipes, review-requested, python

#26839 Added timer-dict as a package
  recipes/timer-dict/meta.yaml
Labels: staged-recipes, review-requested, python

#26849 Added pkg-about as a package
  recipes/pkg-about/meta.yaml
Labels: staged-recipes, review-requested, python

#26841 Added uniserde as a package
  recipes/uniserde/meta.yaml
Labels: staged-recipes, review-requested, python

#26842 Added renumerate as a package
  recipes/renumerate/meta.yaml
Labels: staged-recipes, review-requested, python

#26840 Added unicall as a package
  recipes/unicall/meta.yaml
Labels: staged-recipes, review-requested, python

#26837 Added introspection as a package
  recipes/introspection/meta.yaml
Labels: staged-recipes, review-requested, python

#26836 Added imy as a package
  recipes/imy/meta.yaml
Labels: staged-recipes, review-requested, python

#26858 Add barfi
  recipes/barfi/meta.yaml
Labels: staged-recipes, review-requested, python

#26859 Add pyflyde
  recipes/pyflyde/meta.yaml
Labels: staged-recipes, review-requested, python

#26731 Added astrolink recipe
  recipes/astrolink/meta.yaml
Labels: staged-recipes, review-requested, python

#26573 adding "featuremap-learn" package
  recipes/featuremap-learn/meta.yaml
Labels: review-requested, go, python

#26550 Adding foundry-platform-sdk
  recipes/foundry-platform-sdk/meta.yaml
Labels: review-requested, python, python-c

#26828 feat: Add `staged-script` recipe
  recipes/staged-script/meta.yaml
Labels: review-requested, python

#26756 Add pycontrails
  recipes/pycontrails/meta.yaml
Labels: review-requested, python-c

#26774 Add r-opera
  recipes/r-opera/build.sh
  recipes/r-opera/meta.yaml
Labels: R, review-requested

#26862 Created recipe for czekitout library.
  recipes/czekitout/meta.yaml
Labels: staged-recipes, review-requested, python

#26874 Add molpipeline
  recipes/molpipeline/meta.yaml
Labels: staged-recipes, review-requested, python

#26875 Add bofire
  recipes/bofire/meta.yaml
Labels: staged-recipes, review-requested, python

#26861 Adding crunchflow
  recipes/crunchflow/meta.yaml
Labels: review-requested, python

#26777 Adds `poli`, a library of discrete black box objectives
  recipes/poli/meta.yaml
Labels: review-requested, python

#26741 Add momentum
  recipes/Momentum/bld.bat
  recipes/Momentum/build.sh
  recipes/Momentum/conda_build_config.yaml
  recipes/Momentum/meta.yaml
Labels: review-requested, c-cpp

#26675 Add pylibacl
  recipes/pylibacl/meta.yaml
Labels: review-requested, python-c

#26868 Add gs-quant
  recipes/gs-quant/LICENSE
  recipes/gs-quant/meta.yaml
Labels: review-requested, python

#26819 add fabmos and dependencies
  recipes/awex/bld.bat
  recipes/awex/build.sh
  recipes/awex/conda_build_config.yaml
  recipes/awex/cross-linux.cmake
  recipes/awex/meta.yaml
  recipes/fabmos/bld.bat
  recipes/fabmos/build.sh
  recipes/fabmos/conda_build_config.yaml
  recipes/fabmos/meta.yaml
  recipes/pygetm/bld.bat
  recipes/pygetm/build.sh
  recipes/pygetm/conda_build_config.yaml
  recipes/pygetm/cross-linux.cmake
  recipes/pygetm/meta.yaml
  recipes/pygotm/bld.bat
  recipes/pygotm/build.sh
  recipes/pygotm/conda_build_config.yaml
  recipes/pygotm/cross-linux.cmake
  recipes/pygotm/meta.yaml
Labels: review-requested, python

#26853 Added fazy as a package
  recipes/fazy/meta.yaml
Labels: staged-recipes, review-requested, python

#26825 Add Jupyter Idle server extensions recipes
  recipes/jupyter-idle/meta.yaml
Labels: review-requested, python

#26856 Add siphash24
  recipes/siphash24/meta.yaml
Labels: review-requested, python

#26814 pygamma
  recipes/pygamma/meta.yaml
Labels: review-requested, python

#26860 add erddaplogs
  recipes/erddaplogs/meta.yaml
Labels: review-requested, python

#26799 Adding r-fedmatch as a package
  recipes/r-fedmatch/bld.bat
  recipes/r-fedmatch/build.sh
  recipes/r-fedmatch/meta.yaml
Labels: R, staged-recipes, review-requested

#26885 Add pyshex
  recipes/pyshex/meta.yaml
Labels: review-requested, python

#26892 add asyncpg-stubs 0.29.1
  recipes/asyncpg-stubs/meta.yaml
Labels: review-requested, python

#26549 add msbox
  recipes/r-msbox/meta.yaml
Labels: R, staged-recipes, review-requested

#26897 add r-modeva
  recipes/r-modeva/bld.bat
  recipes/r-modeva/build.sh
  recipes/r-modeva/meta.yaml
Labels: R, review-requested

#26848 Add rocrate-inveniordm recipe
  recipes/rocrate-inveniordm/meta.yaml
Labels: review-requested, python

#26786 Submits PyGSP2 Package to conda-forge
  recipes/pygsp2/meta.yaml
Labels: staged-recipes, review-requested, python

#26888 add textidote
  recipes/textidote/build.sh
  recipes/textidote/licenses/bullwinkle/LICENSE-2.0.txt
  recipes/textidote/licenses/json-lif/LICENSE
  recipes/textidote/licenses/languagetool-bundle/LICENSE
  recipes/textidote/meta.yaml
Labels: staged-recipes, review-requested

#26889 add nuget-license
  recipes/nuget-license/build.sh
  recipes/nuget-license/meta.yaml
Labels: staged-recipes, review-requested

#26890 add lima
  recipes/lima-vm/bld.bat
  recipes/lima-vm/build.sh
  recipes/lima-vm/conda_build_config.yaml
  recipes/lima-vm/meta.yaml
Labels: staged-recipes, review-requested

#26886 Add aiocsv
  recipes/aiocsv/meta.yaml
Labels: review-requested, python-c

#26916 Add tensorpotental
  recipes/tensorpotential/meta.yaml
Labels: staged-recipes, review-requested, python

#26910 add r-statcanr
  recipes/r-statcanr/bld.bat
  recipes/r-statcanr/build.sh
  recipes/r-statcanr/meta.yaml
Labels: R, staged-recipes, review-requested

#26887 add ltex-ls
  recipes/ltex-ls/build.sh
  recipes/ltex-ls/meta.yaml
Labels: staged-recipes, review-requested

#26913 Adding jsonsubschema
  recipes/jsonsubschema/LICENSE.txt
  recipes/jsonsubschema/meta.yaml
Labels: review-requested, python

#26904 Add `orjsonl`, a pip package, recipe generated with grayskull
  recipes/orjsonl/meta.yaml
Labels: review-requested, python

#26920 Adding s2downloader
  recipes/s2downloader/meta.yaml
Labels: staged-recipes, review-requested, python

#26917 Add mdanse
  recipes/mdanse/meta.yaml
Labels: staged-recipes, review-requested

#26918 add polars hash
  recipes/polars-hash/bld.bat
  recipes/polars-hash/build.sh
  recipes/polars-hash/meta.yaml
Labels: review-requested, python

#26852 add `polars-distance`
  recipes/polars-distance/bld.bat
  recipes/polars-distance/build.sh
  recipes/polars-distance/meta.yaml
Labels: review-requested, python

#26921 Add ctypesgen-pypdfium2-team
  recipes/ctypesgen-pypdfium2-team/gcc.patch
  recipes/ctypesgen-pypdfium2-team/meta.yaml
Labels: staged-recipes, review-requested, python-c

#26907 Adding pyDGSA
  recipes/pyDGSA/meta.yaml
Labels: review-requested, python

#26870 Package txl-cell
  recipes/txl-cell/meta.yaml
Labels: review-requested, python

#26893 add recipe for clusterCleaver
  recipes/clusterCleaver/meta.yaml
Labels: review-requested, python

#26871 Package txl-console
  recipes/txl-console/meta.yaml
Labels: review-requested, python

#26873 Package txl-file-browser
  recipes/txl-file-browser/meta.yaml
Labels: review-requested, python

#26934 Adding wpextract
  recipes/wpextract/meta.yaml
Labels: review-requested, python

#26855 Adding hpfrec
  recipes/hpfrec/build.sh
  recipes/hpfrec/meta.yaml
Labels: review-requested, python-c

#26879 Add bip3x
  recipes/libbip3x/bld.bat
  recipes/libbip3x/bld.ps1
  recipes/libbip3x/build.sh
  recipes/libbip3x/meta.yaml
  recipes/libbip3x/patches/0001-add-so-version.patch
  recipes/libbip3x/patches/0002-add-so-version-c.patch
  recipes/libbip3x/patches/0003-add-so-version-jni.patch
Labels: review-requested, c-cpp

#26935 Added printo as a package
  recipes/printo/meta.yaml
Labels: staged-recipes, review-requested, python

#26937 Add pyxenon
  recipes/noodles/meta.yaml
  recipes/pyxenon/LICENSE
  recipes/pyxenon/meta.yaml
  recipes/pyxenon/setupunix.patch
  recipes/pyxenon/setupwin.patch
  recipes/qmflows/meta.yaml
Labels: staged-recipes, review-requested, python

#26936 Add pypdfium2
  recipes/pypdfium2/LICENSE
  recipes/pypdfium2/meta.yaml
Labels: staged-recipes, review-requested, python-c

#26950 Add texify
  recipes/texify/meta.yaml
Labels: staged-recipes, review-requested, python

#26949 Add pdftext
  recipes/pdftext/meta.yaml
Labels: staged-recipes, review-requested, python

#26951 Add surya-ocr
  recipes/surya-ocr/meta.yaml
  recipes/surya-ocr/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#26944 Package txl-markdown-viewer
  recipes/txl-markdown-viewer/meta.yaml
Labels: review-requested, python

#26939 Add package txl-kernel
  recipes/txl-kernel/meta.yaml
Labels: review-requested, python

#26940 Add package txl-launcher
  recipes/txl-launcher/meta.yaml
Labels: review-requested, python

#26945 add schedulefree
  recipes/schedulefree/meta.yaml
Labels: review-requested, python

#26943 Add package txl-notebook-editor
  recipes/txl-notebook-editor/meta.yaml
Labels: review-requested, python

#26942 Add package txl-terminal
  recipes/txl-terminal/meta.yaml
Labels: review-requested, python

#26941 Add package txl-text-editor
  recipes/txl-text-editor/meta.yaml
Labels: review-requested, python

#26948 Add cucopy recipe
  recipes/cucopy/meta.yaml
Labels: review-requested, python

#26954 Add pysages
  recipes/pysages/meta.yaml
Labels: staged-recipes, review-requested, python

#26958 Add package txl-local-kernels
  recipes/txl-local-kernels/meta.yaml
Labels: review-requested, python

#26961 Add package txl-jpterm
  recipes/txl-jpterm/meta.yaml
Labels: review-requested, python

#26967 add aioopenssl
  recipes/aioopenssl/meta.yaml
Labels: review-requested, python

#26966 add aiosasl
  recipes/aiosasl/meta.yaml
Labels: review-requested, python

#26947 Attempt 1 at recipe for 'fancytypes' package.
  recipes/fancytypes/meta.yaml
Labels: review-requested, python

#26955 Add conquest
  recipes/conquest/build.sh
  recipes/conquest/conda_build_config.yaml
  recipes/conquest/meta.yaml
  recipes/conquest/system.patch
Labels: staged-recipes, review-requested

#26971 add rabbitpy
  recipes/rabbitpy/meta.yaml
Labels: review-requested, python

#26932 Adding QLayers
  recipes/qlayers/meta.yaml
Labels: review-requested, python

#26687 Add libpdal package
  recipes/libpdal/bld.bat
  recipes/libpdal/build.sh
  recipes/libpdal/conda-forge.yml
  recipes/libpdal/conda_build_config.yaml
  recipes/libpdal/cpd-find.patch
  recipes/libpdal/install_pdal_plugin.bat
  recipes/libpdal/install_pdal_plugin.sh
  recipes/libpdal/meta.yaml
  recipes/libpdal/no-arrow-gdal-link.patch
  recipes/libpdal/pdal-e57-link.diff
  recipes/libpdal/scripts/activate.bat
  recipes/libpdal/scripts/activate.ps1
  recipes/libpdal/scripts/activate.sh
  recipes/libpdal/scripts/deactivate.bat
  recipes/libpdal/scripts/deactivate.ps1
  recipes/libpdal/scripts/deactivate.sh
Labels: staged-recipes, review-requested

#26959 Add package txl-local-terminals
  recipes/txl-local-terminals/conda-forge.yml
  recipes/txl-local-terminals/meta.yaml
Labels: review-requested, python

#26905 Added xaitk-jatic package
  recipes/xaitk-jatic/meta.yaml
Labels: review-requested, python

#26851 Added recipe for nrtk-jatic package
  recipes/nrtk-jatic/meta.yaml
Labels: review-requested, python

#26957 Add package txl-local-contents
  recipes/txl-local-contents/meta.yaml
Labels: review-requested, python

#26970 add aioxmpp
  recipes/aioxmpp/meta.yaml
Labels: review-requested, python

#26438 Adding pyvpt2 feedstock
  recipes/pyvpt2/meta.yaml
Labels: review-requested, python

#26960 Add package jpterm
  recipes/jpterm/meta.yaml
Labels: review-requested, python

#26880 Adding the accelerator-toolbox package
  recipes/accelerator-toolbox/meta.yaml
Labels: staged-recipes, review-requested, python-c

#26876 Add fastexcel
  recipes/fastexcel/meta.yaml
Labels: R, staged-recipes, review-requested, python, rust

#26931 Adding gammasimtools package
  recipes/gammasimtools/LICENSE
  recipes/gammasimtools/meta.yaml
Labels: review-requested, python

#26927 add r-cchsflow package
  recipes/r-cchsflow/bld.bat
  recipes/r-cchsflow/build.sh
  recipes/r-cchsflow/meta.yaml
Labels: R, staged-recipes, review-requested

#26928 add r-cansim
  recipes/r-cansim/bld.bat
  recipes/r-cansim/build.sh
  recipes/r-cansim/meta.yaml
Labels: R, staged-recipes, review-requested

#26929 add r-cancensus
  recipes/r-cancensus/bld.bat
  recipes/r-cancensus/build.sh
  recipes/r-cancensus/meta.yaml
Labels: R, staged-recipes, review-requested

#26831 Adding r-fredr as a package
  recipes/r-fredr/bld.bat
  recipes/r-fredr/build.sh
  recipes/r-fredr/meta.yaml
Labels: R, review-requested

#26973 Add a recipe for mosaic
  recipes/mosaic/meta.yaml
Labels: review-requested, python

#26938 Add jwskate python package
  recipes/jwskate/meta.yaml
Labels: review-requested, python

#26977 Add executorlib
  recipes/executorlib/meta.yaml
Labels: staged-recipes, review-requested, python

#26865 Add graphrag
  recipes/datashaper/LICENSE
  recipes/datashaper/meta.yaml
  recipes/graphrag/meta.yaml
Labels: staged-recipes, review-requested, python

#26750 adding r-phyloregion to conda forge
  recipes/r-phyloregion/bld.bat
  recipes/r-phyloregion/build.sh
  recipes/r-phyloregion/meta.yaml
  recipes/r-phyloregion/tinytest.R
Labels: R, review-requested

#26830 Adding r-specr as a package
  recipes/r-specr/bld.bat
  recipes/r-specr/build.sh
  recipes/r-specr/meta.yaml
Labels: R, review-requested

#26969 Add xdatasets
  recipes/xdatasets/meta.yaml
Labels: review-requested, python

#26992 adds `r-iterpc`
  recipes/r-iterpc/bld.bat
  recipes/r-iterpc/build.sh
  recipes/r-iterpc/meta.yaml
Labels: R, review-requested

#26993 adds `r-ieugwasr`
  recipes/r-ieugwasr/bld.bat
  recipes/r-ieugwasr/build.sh
  recipes/r-ieugwasr/meta.yaml
Labels: R, review-requested

#26646 Adding pyem to conda-forge
  recipes/pyem/meta.yaml
Labels: staged-recipes, review-requested, python

#26512 Adding r-bootsvd recipe from conda_r_skeleton_helper
  recipes/r-bootsvd/bld.bat
  recipes/r-bootsvd/build.sh
  recipes/r-bootsvd/meta.yaml
Labels: R, review-requested

#26812 Fix UX papercuts while debugging locally
  .scripts/build_steps.sh
Labels: maintenance

#27000 Adds EEGrasp package to conda-forge
  recipes/eegrasp/meta.yaml
Labels: staged-recipes, review-requested, python

#26922 Add recipe for compas_viewer
  recipes/compas_viewer/meta.yaml
  recipes/compas_viewer/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#26178 feat: Add qastle
  recipes/qastle/meta.yaml
Labels: review-requested, python

#27003 add Java tools - jdtls, pmd, google-java-format, checkstyle
  recipes/checkstyle/build.sh
  recipes/checkstyle/meta.yaml
  recipes/google-java-format/build.sh
  recipes/google-java-format/meta.yaml
  recipes/jdtls/build.sh
  recipes/jdtls/meta.yaml
  recipes/pmd/build.sh
  recipes/pmd/meta.yaml
Labels: staged-recipes, review-requested, c-cpp, java

#26791 Add inetutils
  recipes/inetutils/meta.yaml
Labels: review-requested, c-cpp

#27001 add docker-cli, docker-buildx and colima
  recipes/colima/bld.bat
  recipes/colima/build.sh
  recipes/colima/meta.yaml
  recipes/docker-buildx/bld.bat
  recipes/docker-buildx/build.sh
  recipes/docker-buildx/meta.yaml
  recipes/docker-cli/bld.bat
  recipes/docker-cli/build.sh
  recipes/docker-cli/meta.yaml
Labels: staged-recipes, review-requested, go

#27005 add scala3, ammonite-repl, mill, scalariform and ivy
  recipes/ammonite-repl/build.sh
  recipes/ammonite-repl/meta.yaml
  recipes/ivy/build.sh
  recipes/ivy/meta.yaml
  recipes/mill/build.sh
  recipes/mill/meta.yaml
  recipes/scala3/build.sh
  recipes/scala3/meta.yaml
  recipes/scalariform/build.sh
  recipes/scalariform/meta.yaml
Labels: staged-recipes, review-requested, java

#26770 Add Travo and Travo-Jupyter recipes
  recipes/travo/build_travo-jupyter.bat
  recipes/travo/build_travo-jupyter.sh
  recipes/travo/build_travo.bat
  recipes/travo/build_travo.sh
  recipes/travo/meta.yaml
Labels: review-requested, python

#27026 Add ccx2paraview
  recipes/ccx2paraview/meta.yaml
Labels: staged-recipes, review-requested, python

#27025 feat: adding ``ansys-api-mechanical`` package
  recipes/ansys-api-mechanical/meta.yaml
Labels: staged-recipes, review-requested, python

#26999 Add package txl-remote-terminals
  recipes/txl-remote-terminals/meta.yaml
Labels: review-requested, python

#27018 Add cpprb (Python Replay Buffers Library)
  recipes/cpprb/meta.yaml
Labels: review-requested, python

#26972 add spatialdata-plot recipe
  recipes/spatialdata-plot/meta.yaml
Labels: review-requested, python

#27030 Adding openinference-instrumentation-vertexai
  recipes/openinference-instrumentation-vertexai/meta.yaml
Labels: review-requested, python

#27034 Add .NET tools - dotnet-diagnostics, dotnet-script, msbuild-project-tools-server, opendebugad7
  recipes/dotnet-diagnostics/build.sh
  recipes/dotnet-diagnostics/meta.yaml
  recipes/dotnet-script/build.sh
  recipes/dotnet-script/meta.yaml
  recipes/msbuild-project-tools-server/build.sh
  recipes/msbuild-project-tools-server/meta.yaml
  recipes/opendebugad7/build.sh
  recipes/opendebugad7/meta.yaml
Labels: staged-recipes, review-requested

#27032 Add C# tools - omnisharp-roslyn, csharpier, cake, nuke
  recipes/cake/build.sh
  recipes/cake/meta.yaml
  recipes/csharpier/build.sh
  recipes/csharpier/meta.yaml
  recipes/nuke/build.sh
  recipes/nuke/meta.yaml
  recipes/omnisharp-roslyn/build.sh
  recipes/omnisharp-roslyn/meta.yaml
Labels: staged-recipes, review-requested
