Repository conda-forge/staged-recipes, pull requests merged in 2024-12, with the labels that each got.

#28414 add litestar-htmx
  recipes/litestar-htmx/meta.yaml
Labels: review-requested, python

#28379 Add remotebmi
  recipes/remotebmi/LICENSE
  recipes/remotebmi/meta.yaml
Labels: review-requested, python

#28422 Added kvf as a package
  recipes/kvf/meta.yaml
Labels: review-requested, python

#28423 Add POPS-Regression
  recipes/popsregression/meta.yaml
Labels: staged-recipes, review-requested, python

#28425 Add aiida-pythonjob
  recipes/aiida-pythonjob/meta.yaml
Labels: staged-recipes, review-requested, python

#28427 Add `mdtop`
  recipes/mdtop/meta.yaml
Labels: review-requested, python

#28332 add python-uv
  recipes/python-uv/0000-no-rust.patch
  recipes/python-uv/0001-use-conda-forge-bin.patch
  recipes/python-uv/meta.yaml
Labels: review-requested, python

#28441 add asm-lsp, rbspy, selene, stylua
  recipes/asm-lsp/build.bat
  recipes/asm-lsp/build.sh
  recipes/asm-lsp/recipe.yaml
  recipes/rbspy/build.bat
  recipes/rbspy/build.sh
  recipes/rbspy/recipe.yaml
  recipes/selene/build.bat
  recipes/selene/build.sh
  recipes/selene/recipe.yaml
  recipes/stylua/build.bat
  recipes/stylua/build.sh
  recipes/stylua/recipe.yaml
Labels: R, staged-recipes, review-requested, rust

#28424 Add recipe for randonneur_data
  recipes/randonneur_data/meta.yaml
Labels: staged-recipes, review-requested

#28446 Add devtools
  recipes/devtools/meta.yaml
Labels: review-requested, python

#28443 Add transformcl
  recipes/transformcl/meta.yaml
Labels: review-requested, python

#28435 Add CTAO cosmic-ray-spectra package
  recipes/ctao-dpps-cosmic-ray-spectra/LICENSE
  recipes/ctao-dpps-cosmic-ray-spectra/meta.yaml
Labels: staged-recipes, review-requested

#28450 Add recipe for randonneur
  recipes/randonneur/meta.yaml
Labels: staged-recipes, review-requested

#28438 Add seastats package
  recipes/seastats/meta.yaml
Labels: review-requested, python

#28455 recipe for bursty-dynamics
  recipes/bursty-dynamics/meta.yaml
Labels: review-requested, python

#28452 Adding neatnet
  recipes/neatnet/meta.yaml
Labels: review-requested, python

#28447 Add gaussiancl
  recipes/gaussianlcl/meta.yaml
Labels: review-requested, python

#28417 Adding CAREamics-portfolio
  recipes/careamics-portfolio/meta.yaml
Labels: staged-recipes, review-requested, python

#28416 Adding CAREamics
  recipes/careamics/meta.yaml
Labels: staged-recipes, review-requested, python

#28448 Add BPX
  recipes/bpx/LICENSE.md
  recipes/bpx/meta.yaml
Labels: review-requested, python

#28454 recipe for networkx-temporal
  recipes/networkx-temporal/meta.yaml
Labels: review-requested, python

#28419 Add CAREamics-napari
  recipes/careamics-napari/meta.yaml
Labels: staged-recipes, review-requested, python

#28456 Adding xrf (ExPLAINABLE rANDOM fORESTs)
  recipes/xrf/meta.yaml
Labels: review-requested, python

#28439 add eclint, ejson-kms, go-spr, spicetify-cli
  recipes/eclint/build.sh
  recipes/eclint/meta.yaml
  recipes/ejson-kms/bld.bat
  recipes/ejson-kms/build.sh
  recipes/ejson-kms/meta.yaml
  recipes/go-spr/bld.bat
  recipes/go-spr/build.sh
  recipes/go-spr/meta.yaml
  recipes/spicetify-cli/build.sh
  recipes/spicetify-cli/meta.yaml
Labels: staged-recipes, review-requested, go

#28440 add deadnix, spr-rust, statix
  recipes/deadnix/build.bat
  recipes/deadnix/build.sh
  recipes/deadnix/recipe.yaml
  recipes/spr/build.bat
  recipes/spr/build.sh
  recipes/spr/recipe.yaml
  recipes/spr/variants.yaml
  recipes/statix/build.bat
  recipes/statix/build.sh
  recipes/statix/recipe.yaml
Labels: R, staged-recipes, review-requested, rust

#27833 ✨ Add Saxon-HE
  recipes/saxon-he/LICENSE.txt
  recipes/saxon-he/build.bat
  recipes/saxon-he/build.sh
  recipes/saxon-he/recipe.yaml
  recipes/saxon-he/scripts/activate.bat
  recipes/saxon-he/scripts/activate.sh
  recipes/saxon-he/scripts/deactivate.bat
  recipes/saxon-he/scripts/deactivate.sh
Labels: staged-recipes, review-requested, java

#28141 Add eMELA
  recipes/emela/0001-support-range-of-cmakes.patch
  recipes/emela/meta.yaml
Labels: review-requested, c-cpp

#28415 Add MPFUN90
  recipes/mpfun90/meta.yaml
Labels: staged-recipes, review-requested

#28460 Add node-graph-widget
  recipes/node-graph-widget/meta.yaml
Labels: staged-recipes, review-requested, python

#28436 adds `r-webmockr`
  recipes/r-webmockr/bld.bat
  recipes/r-webmockr/build.sh
  recipes/r-webmockr/meta.yaml
Labels: R, review-requested

#28469 Add batchgeneratorsv2
  recipes/batchgeneratorsv2/meta.yaml
Labels: staged-recipes, review-requested, python

#28385 Adding h3ronpy
  recipes/h3ronpy/LICENSE.txt
  recipes/h3ronpy/meta.yaml
Labels: R, review-requested, rust

#28358 Add recipe for keyrings.codeartifacts
  recipes/keyrings.codeartifacts/meta.yaml
Labels: staged-recipes, review-requested

#28463 NEW: Add recipe for talisman
  recipes/talisman/meta.yaml
Labels: review-requested, go

#28464 add cspell, remark-cli, remark-language-server, textlint, write-good
  recipes/cspell/build.sh
  recipes/cspell/recipe.yaml
  recipes/remark-cli/build.sh
  recipes/remark-cli/recipe.yaml
  recipes/remark-language-server/build.sh
  recipes/remark-language-server/recipe.yaml
  recipes/textlint/build.sh
  recipes/textlint/recipe.yaml
  recipes/write-good/build.sh
  recipes/write-good/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28465 add bibtex-tidy, fixjson, jsonlint, markdown-toc, sql-formatter
  recipes/bibtex-tidy/build.sh
  recipes/bibtex-tidy/recipe.yaml
  recipes/fixjson/build.sh
  recipes/fixjson/recipe.yaml
  recipes/jsonlint/build.sh
  recipes/jsonlint/recipe.yaml
  recipes/markdown-toc/build.sh
  recipes/markdown-toc/recipe.yaml
  recipes/sql-formatter/build.sh
  recipes/sql-formatter/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28466 add commitlint, napi-rs, npm-groovy-lint, spectral-cli
  recipes/commitlint/build.sh
  recipes/commitlint/recipe.yaml
  recipes/napi-rs/build.sh
  recipes/napi-rs/recipe.yaml
  recipes/npm-groovy-lint/build.sh
  recipes/npm-groovy-lint/recipe.yaml
  recipes/prettierd/build.sh
  recipes/prettierd/recipe.yaml
  recipes/spectral-cli/build.sh
  recipes/spectral-cli/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28467 add create-rslib, diagnostic-languageserver, rslib, vscode-langserver-extracted, yaml-language-server
  recipes/create-rslib/build.sh
  recipes/create-rslib/recipe.yaml
  recipes/diagnostic-languageserver/build.sh
  recipes/diagnostic-languageserver/recipe.yaml
  recipes/rslib/build.sh
  recipes/rslib/recipe.yaml
  recipes/vscode-langservers-extended/build.sh
  recipes/vscode-langservers-extended/recipe.yaml
  recipes/yaml-language-server/build.sh
  recipes/yaml-language-server/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28459 Adding tomoatt
  recipes/tomoatt/build.sh
  recipes/tomoatt/meta.yaml
Labels: review-requested, c-cpp

#28193 Add recipe for apache-solr
  recipes/apache-solr/build.sh
  recipes/apache-solr/meta.yaml
  recipes/apache-solr/yum_requirements.txt
Labels: staged-recipes, review-requested, java

#28434 adds `r-vcr`
  recipes/r-vcr/bld.bat
  recipes/r-vcr/build.sh
  recipes/r-vcr/meta.yaml
Labels: R, review-requested

#27274 ffbidx package for the fast feedback indexer library
  recipes/ffbidx/build.sh
  recipes/ffbidx/meta.yaml
Labels: review-requested, c-cpp, python-c

#28487 Add opennb recipe
  recipes/opennb/meta.yaml
Labels: review-requested, python

#28485 add eeg_positions
  recipes/eeg_positions/meta.yaml
Labels: review-requested, python

#28486 Add dooit
  recipes/dooit/recipe.yaml
Labels: review-requested, python

#28451 Add rich-toolkit
  recipes/rich-toolkit/recipe.yaml
Labels: review-requested, python

#28457 recipe for teneto
  recipes/teneto/meta.yaml
Labels: review-requested, python

#28489 Add scipy-events from pypi
  recipes/scipy-events/LICENSE
  recipes/scipy-events/meta.yaml
Labels: review-requested, python

#28479 add azure-pipelines-language-server, bash-language-server, create-jest, dot-language-server, vim-language-server
  recipes/azure-pipelines-language-server/build.sh
  recipes/azure-pipelines-language-server/recipe.yaml
  recipes/bash-language-server/LICENSE
  recipes/bash-language-server/build.sh
  recipes/bash-language-server/recipe.yaml
  recipes/create-jest/build.sh
  recipes/create-jest/recipe.yaml
  recipes/dot-language-server/build.sh
  recipes/dot-language-server/recipe.yaml
  recipes/vim-language-server/LICENSE
  recipes/vim-language-server/build.sh
  recipes/vim-language-server/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28480 add compose-language-service, dockerfile-language-server-nodejs, perlnavigator-server
  recipes/compose-language-service/build.sh
  recipes/compose-language-service/recipe.yaml
  recipes/dockerfile-language-server-nodejs/build.sh
  recipes/dockerfile-language-server-nodejs/recipe.yaml
  recipes/perlnavigator-server/LICENSE
  recipes/perlnavigator-server/build.sh
  recipes/perlnavigator-server/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28481 add auto-changelog, commit-tag-and-version, husky, inject-markdown, release-please
  recipes/auto-changelog/build.sh
  recipes/auto-changelog/recipe.yaml
  recipes/commit-tag-and-version/build.sh
  recipes/commit-tag-and-version/recipe.yaml
  recipes/husky/build.sh
  recipes/husky/recipe.yaml
  recipes/inject-markdown/build.sh
  recipes/inject-markdown/recipe.yaml
  recipes/release-please/build.sh
  recipes/release-please/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28482 add gts, lint-staged, stylelint
  recipes/gts/build.sh
  recipes/gts/recipe.yaml
  recipes/lint-staged/build.sh
  recipes/lint-staged/recipe.yaml
  recipes/stylelint/build.sh
  recipes/stylelint/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28497 Added snowplow-tracker as a package
  recipes/snowplow-tracker/meta.yaml
Labels: review-requested, python

#28491 Add arrakis-python
  recipes/arrakis-python/meta.yaml
Labels: review-requested, python

#28502 recipe for settings-doc
  recipes/settings-doc/meta.yaml
Labels: review-requested, python

#28505 Add `xdggs`
  recipes/xdggs/meta.yaml
Labels: review-requested, python

#28507 Add pygt
  recipes/pygt/meta.yaml
Labels: staged-recipes, review-requested, python

#28506 Add pafi
  recipes/pafi/meta.yaml
Labels: staged-recipes, review-requested, python

#26651 PyGnome initial recipe.
  recipes/pygnome/conda_build_config.yaml
  recipes/pygnome/meta.yaml
Labels: review-requested, python-c

#28514 add ava, c8, nyc, tape
  recipes/ava/build.sh
  recipes/ava/recipe.yaml
  recipes/c8/build.sh
  recipes/c8/recipe.yaml
  recipes/nyc/build.sh
  recipes/nyc/recipe.yaml
  recipes/tape/build.sh
  recipes/tape/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28513 add del-cli, globcat, selenium-standalone, shx
  recipes/del-cli/build.sh
  recipes/del-cli/recipe.yaml
  recipes/globcat/build.sh
  recipes/globcat/recipe.yaml
  recipes/selenium-standalone/build.sh
  recipes/selenium-standalone/recipe.yaml
  recipes/shx/build.sh
  recipes/shx/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28512 add concurrently, elf-cli, hereby, manypkg, webpack-cli
  recipes/concurrently/build.sh
  recipes/concurrently/recipe.yaml
  recipes/elf-cli/LICENSE.md
  recipes/elf-cli/build.sh
  recipes/elf-cli/recipe.yaml
  recipes/hereby/build.sh
  recipes/hereby/recipe.yaml
  recipes/manypkg/LICENSE
  recipes/manypkg/build.sh
  recipes/manypkg/recipe.yaml
  recipes/webpack-cli/build.sh
  recipes/webpack-cli/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28511 add babel-cli, jiti, ts-node, tshy, typedoc
  recipes/babel-cli/build.sh
  recipes/babel-cli/recipe.yaml
  recipes/jiti/build.sh
  recipes/jiti/recipe.yaml
  recipes/ts-node/build.sh
  recipes/ts-node/recipe.yaml
  recipes/tshy/build.sh
  recipes/tshy/recipe.yaml
  recipes/typedoc/build.sh
  recipes/typedoc/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28495 add r-quickmatch and r-scclust from CRAN
  recipes/r-quickmatch/bld.bat
  recipes/r-quickmatch/build.sh
  recipes/r-quickmatch/meta.yaml
  recipes/r-scclust/bld.bat
  recipes/r-scclust/build.sh
  recipes/r-scclust/meta.yaml
Labels: R, review-requested

#28496 Add r-dlnm and r-tsmodel from CRAN
  recipes/r-dlnm/bld.bat
  recipes/r-dlnm/build.sh
  recipes/r-dlnm/meta.yaml
  recipes/r-tsmodel/bld.bat
  recipes/r-tsmodel/build.sh
  recipes/r-tsmodel/meta.yaml
Labels: R, review-requested

#28516 Add recipe for changelog-chug
  recipes/changelog-chug/meta.yaml
Labels: review-requested, python

#28475 Add geant4-data-channeling pkg needed by Geant4 11.3.0
  recipes/geant4-data-channeling/CREDIT
  recipes/geant4-data-channeling/create_activation_scripts.sh
  recipes/geant4-data-channeling/meta.yaml
Labels: staged-recipes, review-requested

#28522 add angular-cli, architect-cli, astro-ls
  recipes/angular-cli/build.sh
  recipes/angular-cli/recipe.yaml
  recipes/architect-cli/build.sh
  recipes/architect-cli/recipe.yaml
  recipes/astro-ls/build.sh
  recipes/astro-ls/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28520 add adonisjs, docusaurus, eleventy, hexo, remix
  recipes/adonisjs/build.sh
  recipes/adonisjs/recipe.yaml
  recipes/docusaurus/build.sh
  recipes/docusaurus/recipe.yaml
  recipes/eleventy/build.sh
  recipes/eleventy/recipe.yaml
  recipes/hexo/build.sh
  recipes/hexo/recipe.yaml
  recipes/remix/build.sh
  recipes/remix/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28209 Adding skore
  recipes/skore/LICENSE
  recipes/skore/meta.yaml
Labels: review-requested, python

#28499 Add jupyter-kernel-client
  recipes/jupyter-kernel-client/meta.yaml
Labels: review-requested, python

#28500 Add jupyter-nbmodel-client
  recipes/jupyter-nbmodel-client/meta.yaml
Labels: review-requested, python

#28204 Adding my_hwm_package
  recipes/hwm/meta.yaml
Labels: review-requested, python

#28536 Adding sklearn-compat
  recipes/sklearn-compat/meta.yaml
Labels: review-requested, python

#28225 Add openpmix, prrte
  recipes/openpmix/build.sh
  recipes/openpmix/meta.yaml
  recipes/prrte/build.sh
  recipes/prrte/meta.yaml
Labels: review-requested, c-cpp

#28472 Add protobuf_to_pydantic from pypi
  recipes/protobuf_to_pydantic/meta.yaml
Labels: review-requested, python

#27549 NEW: Add libcudss recipe
  recipes/libcudss/build.sh
  recipes/libcudss/common/detect-glibc
  recipes/libcudss/conda-forge.yml
  recipes/libcudss/meta.yaml
  recipes/libcudss/test/CMakeLists.txt
  recipes/libcudss/test/all_headers.c
  recipes/libcudss/test/all_headers.cxx
Labels: review-requested, c-cpp

#28521 add dotenvx, jest, mocha, release-it, tapjs
  recipes/dotenvx/build.sh
  recipes/dotenvx/recipe.yaml
  recipes/jest/build.sh
  recipes/jest/recipe.yaml
  recipes/mocha/build.sh
  recipes/mocha/recipe.yaml
  recipes/release-it/build.sh
  recipes/release-it/recipe.yaml
  recipes/tapjs/build.sh
  recipes/tapjs/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28508 Add presidio-analyzer and presidio-anonymizer packages
  recipes/presidio-analyzer/meta.yaml
  recipes/presidio-anonymizer/meta.yaml
Labels: staged-recipes, review-requested

#28526 Add recipe for graph-pes
  recipes/data2objects/meta.yaml
  recipes/graph-pes/meta.yaml
  recipes/load-atoms/meta.yaml
  recipes/locache/meta.yaml
Labels: review-requested, python

#28488 Add torch-pme recipe
  recipes/torch-pme/meta.yaml
Labels: review-requested, python

#28099 Add FANS to conda-forge
  recipes/fans/fix_gitignore_ms.patch
  recipes/fans/recipe.yaml
Labels: review-requested, c-cpp

#28490 Add recipe for python-vesin
  recipes/vesin/LICENSE
  recipes/vesin/meta.yaml
Labels: review-requested, python-c

#28542 Add recipe for yarp-device-realsense2 package
  recipes/yarp-device-realsense2/build.sh
  recipes/yarp-device-realsense2/meta.yaml
Labels: review-requested, c-cpp

#28537 Adding 'cinemagoerng' and 'typedload'
  recipes/cinemagoerng/conda_build_config.yaml
  recipes/cinemagoerng/meta.yaml
  recipes/typedload/meta.yaml
Labels: review-requested, python

#28548 Adding trame-annotation package from PyPI
  recipes/trame-annotations/meta.yaml
Labels: review-requested, python

#28504 add stock-pandas
  recipes/stock-pandas/meta.yaml
Labels: review-requested, python

#28552 add js-beautify, jshint, lean-language-server, mardupling, mdx-language-server
  recipes/js-beautify/build.sh
  recipes/js-beautify/recipe.yaml
  recipes/jshint/build.sh
  recipes/jshint/recipe.yaml
  recipes/lean-language-server/build.sh
  recipes/lean-language-server/recipe.yaml
  recipes/markuplint/build.sh
  recipes/markuplint/recipe.yaml
  recipes/mdx-language-server/build.sh
  recipes/mdx-language-server/recipe.yaml
Labels: staged-recipes, review-requested

#28551 add emmet-language-server, emmet-ls, eslint_d, glint, graphql-language-service-cli
  recipes/emmet-language-server/build.sh
  recipes/emmet-language-server/recipe.yaml
  recipes/emmet-ls/build.sh
  recipes/emmet-ls/recipe.yaml
  recipes/eslint_d/build.sh
  recipes/eslint_d/recipe.yaml
  recipes/glint/LICENSE
  recipes/glint/build.sh
  recipes/glint/recipe.yaml
  recipes/graphql-language-service-cli/build.sh
  recipes/graphql-language-service-cli/recipe.yaml
Labels: staged-recipes, review-requested

#28550 add css-variables-language-server, cssmodules-language-server, custom-elements-languageserver, cypher-language-server, ember-language-server
  recipes/css-variables-language-server/LICENSE
  recipes/css-variables-language-server/build.sh
  recipes/css-variables-language-server/recipe.yaml
  recipes/cssmodulues-language-server/build.sh
  recipes/cssmodulues-language-server/recipe.yaml
  recipes/custom-elements-languageserver/LICENSE
  recipes/custom-elements-languageserver/build.sh
  recipes/custom-elements-languageserver/recipe.yaml
  recipes/cypher-language-server/build.sh
  recipes/cypher-language-server/recipe.yaml
  recipes/ember-language-server/build.sh
  recipes/ember-language-server/recipe.yaml
Labels: staged-recipes, review-requested

#28547 Live tests for https://github.com/conda-forge/conda-smithy/pull/2120
  .github/workflows/scripts/create_feedstocks
Labels: maintenance

#26706 Adding jupyterlab_gather
  recipes/jupyterlab-gather/meta.yaml
Labels: review-requested, python

#28549 add babylon, bower, cmake-js, coffeesense-language-server, commit-tag-and-version
  recipes/babylon/build.sh
  recipes/babylon/recipe.yaml
  recipes/bower/build.sh
  recipes/bower/recipe.yaml
  recipes/cmake-js/build.sh
  recipes/cmake-js/recipe.yaml
  recipes/coffeesense-language-server/LICENSE
  recipes/coffeesense-language-server/build.sh
  recipes/coffeesense-language-server/recipe.yaml
Labels: staged-recipes, review-requested

#28559 Revert "Live tests for https://github.com/conda-forge/conda-smithy/pull/2120"
  .github/workflows/scripts/create_feedstocks
Labels: maintenance

#28545 Add teos10
  recipes/teos10/meta.yaml
Labels: review-requested, python

#28557 Add fastjet-contrib
  recipes/fastjet-contrib/meta.yaml
  recipes/fastjet-contrib/run_test_shared.sh
  recipes/fastjet-contrib/run_test_static.sh
Labels: review-requested, c-cpp

#28560 add ncc, prisma-language-server, prisma-lint, xojs
  recipes/ncc/build.sh
  recipes/ncc/recipe.yaml
  recipes/prisma-language-server/build.sh
  recipes/prisma-language-server/recipe.yaml
  recipes/prisma-lint/build.sh
  recipes/prisma-lint/recipe.yaml
  recipes/xojs/build.sh
  recipes/xojs/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28561 add schematics-cli, semistandard, shopify-cli, some-sass-language-server
  recipes/schematics-cli/build.sh
  recipes/schematics-cli/recipe.yaml
  recipes/semistandard/build.sh
  recipes/semistandard/recipe.yaml
  recipes/shopify-cli/LICENSE
  recipes/shopify-cli/build.sh
  recipes/shopify-cli/recipe.yaml
  recipes/some-sass-language-server/build.sh
  recipes/some-sass-language-server/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28562 add shachl-language-server, sms-language-server, sparql-language-server, srs-language-server, stargdog-graphql-language-server
  recipes/shacl-language-server/LICENSE
  recipes/shacl-language-server/build.sh
  recipes/shacl-language-server/recipe.yaml
  recipes/sms-language-server/LICENSE
  recipes/sms-language-server/build.sh
  recipes/sms-language-server/recipe.yaml
  recipes/sparql-language-server/LICENSE
  recipes/sparql-language-server/build.sh
  recipes/sparql-language-server/recipe.yaml
  recipes/srs-language-server/LICENSE
  recipes/srs-language-server/build.sh
  recipes/srs-language-server/recipe.yaml
  recipes/stardog-graphql-language-server/LICENSE
  recipes/stardog-graphql-language-server/build.sh
  recipes/stardog-graphql-language-server/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28563 add stimulus-language-server, stylelint-lsp, stylint, stylus
  recipes/stimulus-language-server/LICENSE.txt
  recipes/stimulus-language-server/build.sh
  recipes/stimulus-language-server/recipe.yaml
  recipes/stylelint-lsp/build.sh
  recipes/stylelint-lsp/recipe.yaml
  recipes/stylint/build.sh
  recipes/stylint/recipe.yaml
  recipes/stylus/build.sh
  recipes/stylus/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28567 add svelte-language-server, tailwindcss-language-server, trig-language-server, ts-standard
  recipes/svelte-language-server/build.sh
  recipes/svelte-language-server/recipe.yaml
  recipes/tailwindcss-language-server/build.sh
  recipes/tailwindcss-language-server/recipe.yaml
  recipes/trig-language-server/LICENSE
  recipes/trig-language-server/build.sh
  recipes/trig-language-server/recipe.yaml
  recipes/ts-standard/build.sh
  recipes/ts-standard/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28568 add turbo-language-server, turtle-language-server, twiggy-language-server, typescript-language-server, typespec
  recipes/turbo-language-server/LICENSE.txt
  recipes/turbo-language-server/build.sh
  recipes/turbo-language-server/recipe.yaml
  recipes/turtle-language-server/LICENSE
  recipes/turtle-language-server/build.sh
  recipes/turtle-language-server/recipe.yaml
  recipes/twiggy-language-server/build.sh
  recipes/twiggy-language-server/recipe.yaml
  recipes/typescript-language-server/build.sh
  recipes/typescript-language-server/recipe.yaml
  recipes/typespec/build.sh
  recipes/typespec/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28571 Add pymc-extras
  recipes/pymc-extras/meta.yaml
Labels: review-requested, python

#28570 add browserify, docco, doxdox, open-cli
  recipes/browserify/build.sh
  recipes/browserify/recipe.yaml
  recipes/docco/build.sh
  recipes/docco/recipe.yaml
  recipes/doxdox/build.sh
  recipes/doxdox/recipe.yaml
  recipes/open-cli/build.sh
  recipes/open-cli/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28576 add analogjs-language-server, arethetypeswrong-cli, bundt, create-qwik, microbundle
  recipes/analogjs-language-server/LICENSE
  recipes/analogjs-language-server/build.sh
  recipes/analogjs-language-server/recipe.yaml
  recipes/arethetypeswrong-cli/build.sh
  recipes/arethetypeswrong-cli/recipe.yaml
  recipes/bundt/build.sh
  recipes/bundt/recipe.yaml
  recipes/create-qwik/build.sh
  recipes/create-qwik/recipe.yaml
  recipes/microbundle/build.sh
  recipes/microbundle/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28575 add grunt, jasmine-npm, lit-cli, metro, quasar-cli
  recipes/jasmine-npm/build.sh
  recipes/jasmine-npm/recipe.yaml
  recipes/lit-cli/LICENSE
  recipes/lit-cli/build.sh
  recipes/lit-cli/recipe.yaml
  recipes/metro/LICENSE
  recipes/metro/build.sh
  recipes/metro/recipe.yaml
  recipes/quasar-cli/build.sh
  recipes/quasar-cli/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28574 add cypress, karma, makes, pta, qunit
  recipes/cypress/LICENSE
  recipes/cypress/build.sh
  recipes/cypress/recipe.yaml
  recipes/karma/build.sh
  recipes/karma/recipe.yaml
  recipes/makes/build.sh
  recipes/makes/recipe.yaml
  recipes/pta/LICENSE
  recipes/pta/build.sh
  recipes/pta/recipe.yaml
  recipes/qunit/build.sh
  recipes/qunit/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28573 add cucumber-js, genversion, lockfile-lint, ls-engines, safe-publish-latest
  recipes/cucumber-js/build.sh
  recipes/cucumber-js/recipe.yaml
  recipes/genversion/build.sh
  recipes/genversion/recipe.yaml
  recipes/lockfile-lint/build.sh
  recipes/lockfile-lint/recipe.yaml
  recipes/ls-engines/build.sh
  recipes/ls-engines/recipe.yaml
  recipes/safe-publish-latest/build.sh
  recipes/safe-publish-latest/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28580 add blitz, storybook, unocss-language-server, unocss, vercel-cli
  recipes/blitz/build.sh
  recipes/blitz/recipe.yaml
  recipes/storybook/LICENSE
  recipes/storybook/build.sh
  recipes/storybook/recipe.yaml
  recipes/unocss-language-server/build.sh
  recipes/unocss-language-server/recipe.yaml
  recipes/unocss/build.sh
  recipes/unocss/recipe.yaml
  recipes/vercel-cli/build.sh
  recipes/vercel-cli/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28578 add cordova-js, stencil-core, ui5-webcomponents-react-cli
  recipes/cordova-js/build.sh
  recipes/cordova-js/recipe.yaml
  recipes/stencil-core/build.sh
  recipes/stencil-core/recipe.yaml
  recipes/ui5-webcomponents-react-cli/build.sh
  recipes/ui5-webcomponents-react-cli/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28579 add depcheck, fastify-cli, ionic-cli, sails, titanium
  recipes/depcheck/build.sh
  recipes/depcheck/recipe.yaml
  recipes/fastify-cli/build.sh
  recipes/fastify-cli/recipe.yaml
  recipes/ionic-cli/LICENSE
  recipes/ionic-cli/build.sh
  recipes/ionic-cli/recipe.yaml
  recipes/sails/build.sh
  recipes/sails/recipe.yaml
  recipes/titanium/build.sh
  recipes/titanium/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28577 add amplication-cli, nestjs-cli, publint, refinedev-cli, uvu
  recipes/amplication-cli/LICENSE
  recipes/amplication-cli/build.sh
  recipes/amplication-cli/recipe.yaml
  recipes/nestjs-cli/build.sh
  recipes/nestjs-cli/recipe.yaml
  recipes/publint/build.sh
  recipes/publint/recipe.yaml
  recipes/refinedev-cli/build.sh
  recipes/refinedev-cli/recipe.yaml
  recipes/uvu/build.sh
  recipes/uvu/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#28584 added recipe for `pdfminer-six`
  recipes/pdfminer-six/meta.yaml
Labels: review-requested, python

#28581 added recipe for `cobble`
  recipes/cobble/LICENSE
  recipes/cobble/meta.yaml
Labels: review-requested, python

#28330 Added venvstacks as a package
  recipes/venvstacks/meta.yaml
Labels: staged-recipes, review-requested, python

#28449 Add recipe for qnmfits
  recipes/qnmfits/meta.yaml
Labels: review-requested, python

#28591 recipe for FF-PIV library
  recipes/ffpiv/meta.yaml
Labels: review-requested, python

#28592 Add recipes for mammoth & markitdown
  recipes/mammoth/meta.yaml
  recipes/markitdown/conda_build_config.yaml
  recipes/markitdown/meta.yaml
Labels: review-requested, python

#28412 Adding inaSpeechSegmenter
  recipes/inaSpeechSegmenter/meta.yaml
Labels: review-requested, python

#28554 Adding imdclient package of IMDv3
  recipes/imdclient/meta.yaml
Labels: review-requested, python

#28601 Add recipe for fastapi-third-party-auth.
  recipes/fastapi-third-party-auth/meta.yaml
Labels: staged-recipes, review-requested, python

#28616 recipe for cbor
  recipes/cbor/LICENSE
  recipes/cbor/meta.yaml
Labels: review-requested, python

#28615 Base58check
  recipes/base58check/meta.yaml
Labels: review-requested, python

#28614 Blake256
  recipes/blake256/LICENSE
  recipes/blake256/meta.yaml
Labels: review-requested, python

#28605 Add msmtp and msmtp-sendmail
  recipes/msmtp/recipe.yaml
Labels: review-requested, c-cpp

#28611 Add mediainfo
  recipes/mediainfo/recipe.yaml
Labels: review-requested, c-cpp

#28564 Add ParaStation MPI - Ready for review
  recipes/parastation/LICENSE
  recipes/parastation/build.sh
  recipes/parastation/hello_world_mpi.f90
  recipes/parastation/meta.yaml
Labels: staged-recipes, review-requested

#28621 Adding hg-setup
  recipes/hg-setup/LICENSE
  recipes/hg-setup/meta.yaml
Labels: review-requested, python

#28624 add scipy-doctest recipe
  recipes/scipy-doctest/meta.yaml
Labels: review-requested, python

#28582 Add ipsurv
  recipes/ipsurv/meta.yaml
Labels: review-requested, python

#28589 add local-lua-debugger-vscode, perl-debug-adapter, vscode-go-debug-adapter
  recipes/local-lua-debugger-vscode/build.sh
  recipes/local-lua-debugger-vscode/meta.yaml
  recipes/perl-debug-adapter/build.sh
  recipes/perl-debug-adapter/meta.yaml
  recipes/tabby-agent/build.sh
  recipes/tabby-agent/meta.yaml
  recipes/vscode-go-debug-adapter/build.sh
  recipes/vscode-go-debug-adapter/meta.yaml
Labels: nodejs, staged-recipes, review-requested

#28636 Add UMNN
  recipes/umnn/meta.yaml
Labels: review-requested, python

#28635 Add pycsvy package
  recipes/pycsvy/meta.yaml
Labels: staged-recipes, review-requested, python

#28629 add datatrove
  recipes/datatrove/cli.patch
  recipes/datatrove/recipe.yaml
Labels: review-requested, python

#28600 Add pygyat
  recipes/pygyat/recipe.yaml
Labels: review-requested, python

#28594 Added DockQ
  recipes/DockQ/recipe.yaml
Labels: review-requested, python, python-c

#28631 add faust-cchardet
  recipes/faust-cchardet/recipe.yaml
Labels: review-requested, python-c

#28498 Create recipe for hpv-meta in version 1.0 for conda-forge.
  recipes/hpv-kite/build.sh
  recipes/hpv-kite/meta.yaml
Labels: staged-recipes, review-requested, java

#28630 add warcio
  recipes/warcio/recipe.yaml
Labels: review-requested, python

#28638 Add r-canyonb recipe
  recipes/r-canyonb/build.bat
  recipes/r-canyonb/build.sh
  recipes/r-canyonb/meta.yaml
Labels: R, staged-recipes, review-requested

#28622 Adding gempy_engine
  recipes/gempy_engine/meta.yaml
Labels: review-requested, python

#28641 Add nflows
  recipes/nflows/LICENSE.md
  recipes/nflows/meta.yaml
Labels: review-requested, python

#28645 Add nicelib recipe
  recipes/nicelib/meta.yaml
Labels: review-requested, python

#28643 Add fastapi-cache recipe
  recipes/fastapi-cache2/meta.yaml
Labels: review-requested, python

#28518 Add semantikon to conda
  recipes/semantikon/meta.yaml
Labels: review-requested, python

#28651 Add pyknos
  recipes/pyknos/meta.yaml
Labels: review-requested, python

#28653 Added ridgeplot as a package
  recipes/ridgeplot/meta.yaml
Labels: review-requested, python

#28654 Added django-removals as a package
  recipes/django-removals/meta.yaml
Labels: review-requested, python

#28655 Added pattern-utils as a package
  recipes/pattern-utils/meta.yaml
Labels: review-requested, python

#28658 Added leopards as a package
  recipes/leopards/meta.yaml
Labels: review-requested, python
