Repository conda-forge/staged-recipes, pull requests merged in 2024-08, with the labels that each got.

#27151 Replace HashableDict with frozendict.deepfreeze
  .ci_support/compute_build_graph.py
Labels: staged-recipes, review-requested

#27155 add cryptocode
  recipes/cryptocode/LICENSE
  recipes/cryptocode/meta.yaml
Labels: review-requested, python

#27152 add pypcd4 and python-lzf
  recipes/pypcd4/meta.yaml
  recipes/python-lzf/meta.yaml
  recipes/python-lzf/tests.py
Labels: staged-recipes, review-requested, python-c

#27156 Added f3dasm as a package
  recipes/f3dasm/meta.yaml
Labels: review-requested, python

#27153 Added tea-tasting as a package
  recipes/tea-tasting/meta.yaml
Labels: staged-recipes, review-requested, python

#27128 Adding feflow package
  recipes/feflow/meta.yaml
Labels: staged-recipes, review-requested, python

#27144 New recipe for climlab-sbm-convection
  recipes/climlab-sbm-convection/meta.yaml
Labels: review-requested, python

#26833 Added rio-ui as a package
  recipes/rio-ui/meta.yaml
Labels: staged-recipes, review-requested, python

#27159 Added case-conversion as a package
  recipes/case-conversion/LICENSE.md
  recipes/case-conversion/meta.yaml
Labels: staged-recipes, review-requested, python

#26273 Added r-gpg as a package
  recipes/r-gpg/bld.bat
  recipes/r-gpg/build.sh
  recipes/r-gpg/meta.yaml
Labels: R, review-requested

#25724 Add atool2
  recipes/atool2/meta.yaml
Labels: staged-recipes, review-requested, perl

#27157 Add cythonbiogeme.
  recipes/cythonbiogeme/meta.yaml
Labels: review-requested, python-c

#27108 Add `conda-which`
  recipes/conda-which/meta.yaml
Labels: staged-recipes, review-requested

#27161 Added lckr_jupyterlab_variableinspector as a package
  recipes/lckr_jupyterlab_variableinspector/meta.yaml
Labels: staged-recipes, review-requested, python

#27162 add airflow-priority
  recipes/airflow-priority/meta.yaml
Labels: review-requested, python

#27140 Please add "scores" to conda-forge
  recipes/scores/meta.yaml
Labels: review-requested, python

#27165 Add django-comments-xtd
  recipes/django-comments-xtd/meta.yaml
Labels: review-requested, python

#27146 Add lens-vpr feedstock
  recipes/lens-vpr/meta.yaml
Labels: review-requested, python

#27173 Added py-build-cmake 0.1.8
  recipes/py-build-cmake/meta.yaml
Labels: review-requested, python

#27175 Add highspy package
  recipes/highspy/meta.yaml
  recipes/highspy/patches/0001-Got-error-about-missing-std-tolower-on-MSVC.patch
Labels: review-requested, python

#27133 add aiohappyeyeballs
  recipes/aiohappyeyeballs/meta.yaml
Labels: review-requested, python

#27138 Add recipe supabase pydantic
  recipes/supabase-pydantic/meta.yaml
Labels: review-requested, python

#27091 Add recipe for `aeon-neuro`
  recipes/aeon-neuro/meta.yaml
Labels: review-requested, python

#27182 Add json-repair
  recipes/json-repair/meta.yaml
Labels: staged-recipes, review-requested, python

#27169 Add descwl-shear-sims package
  recipes/descwl-shear-sims/meta.yaml
Labels: review-requested, python

#26331 Adding notolog (Python Markdown Editor) as a package
  recipes/notolog/meta.yaml
Labels: Awaiting author contribution, python

#27180 Add recipe for `dataeval`
  recipes/dataeval/meta.yaml
Labels: review-requested, python

#27176 Adding hydrampp
  recipes/hydrampp/meta.yaml
Labels: staged-recipes, review-requested

#27178 add paradoc
  recipes/paradoc/conda-forge.yml
  recipes/paradoc/meta.yaml
Labels: review-requested, python

#27184 Add jupyter-sshd-proxy
  recipes/jupyter-sshd-proxy/meta.yaml
Labels: review-requested, python

#27190 Adding airflow-config
  recipes/airflow-config/meta.yaml
Labels: review-requested, python

#27187 add pytexit
  recipes/pytexit/meta.yaml
Labels: review-requested, python

#27194 Add a recipe for apache-airflow-providers-common-compat
  recipes/apache-airflow-providers-common-compat/meta.yaml
Labels: review-requested, python

#27192 Add langgraph-checkpoint
  recipes/langgraph-checkpoint/meta.yaml
Labels: staged-recipes, review-requested, python

#27195 Add opentelemetry-propagator-aws-xray and opentelemetry-sdk-extension-aws
  recipes/opentelemetry-propagator-aws-xray/meta.yaml
  recipes/opentelemetry-sdk-extension-aws/meta.yaml
Labels: staged-recipes, review-requested, python

#27191 Add baybe
  recipes/baybe/meta.yaml
  recipes/baybe/pyproject.patch
Labels: staged-recipes, review-requested, python

#27197 Add matplotlive
  recipes/matplotlive/meta.yaml
Labels: review-requested, python

#27196 Adding jrsync package
  recipes/jrsync/meta.yaml
Labels: review-requested, python

#23938 Add ElementEmbeddings package
  recipes/ElementEmbeddings/meta.yaml
Labels: review-requested, python

#27198 feat: add smokescreen
  recipes/smokescreen/meta.yaml
Labels: staged-recipes, review-requested, python

#27127 add r-fpp3
  recipes/r-fpp3/bld.bat
  recipes/r-fpp3/build.sh
  recipes/r-fpp3/meta.yaml
Labels: R, review-requested

#25806 Add jnv
  recipes/jnv/bld.bat
  recipes/jnv/build.sh
  recipes/jnv/meta.yaml
Labels: R, review-requested, rust

#27208 add stripe 10.6.0
  recipes/stripe/meta.yaml
Labels: review-requested, python

#27212 feat: add bot code base (!!!)
  recipes/conda-forge-tick/meta.yaml
Labels: staged-recipes, review-requested, python

#27216 added pz-rail-base
  recipes/pz-rail-base/meta.yaml
Labels: review-requested, python

#27200 Adding s1_orbits
  recipes/s1_orbits/meta.yaml
Labels: review-requested, python

#27102 Add scikits_odes_sundials
  recipes/scikits_odes_sundials/integrate.py
  recipes/scikits_odes_sundials/meta.yaml
Labels: staged-recipes, review-requested, python

#27218 added recipe for sqlalchemy-searchable
  recipes/sqlalchemy-searchable/meta.yaml
Labels: review-requested, python

#27221 Added saa as a package
  recipes/saa/meta.yaml
Labels: staged-recipes, review-requested, python

#27223 Added pz-rail-sklearn
  recipes/pz-rail-sklearn/meta.yaml
Labels: review-requested, python

#27202 Add MariaDB-Context-Manager recipe
  recipes/MariaDB-Context-Manager/meta.yaml
Labels: review-requested, python

#27164 Added r-dtrackr as a package
  recipes/r-dtrackr/bld.bat
  recipes/r-dtrackr/build.sh
  recipes/r-dtrackr/meta.yaml
Labels: R, staged-recipes, review-requested

#27231 Added locklib as a package
  recipes/locklib/meta.yaml
Labels: staged-recipes, review-requested, python

#27213 Add faim-ipa meta.yaml
  recipes/faim-ipa/meta.yaml
Labels: review-requested, python

#27229 Added persist_ext as a package
  recipes/persist_ext/meta.yaml
Labels: staged-recipes, review-requested, python

#27225 Added ipyflow as a package
  recipes/ipyflow/meta.yaml
Labels: staged-recipes, review-requested, python

#27227 Added wat-inspector as a pacakge
  recipes/wat-inspector/meta.yaml
Labels: staged-recipes, review-requested, python

#27228 Added aurora-ssg as a package
  recipes/aurora-ssg/meta.yaml
Labels: staged-recipes, review-requested, python

#27247 Adding recipe for pyclarify
  recipes/pyclarify/meta.yaml
Labels: staged-recipes, review-requested, python

#27174 Add recipe for bootstrap-flask
  recipes/bootstrap-flask/meta.yaml
Labels: staged-recipes, review-requested, python

#27107 Add libglvnd recipe
  recipes/libglvnd/build.sh
  recipes/libglvnd/libglvnd_look_for_egl_icd_in_system_location.patch
  recipes/libglvnd/meta.yaml
Labels: staged-recipes, review-requested

#27239 Added r-attachment as a package
  recipes/r-attachment/bld.bat
  recipes/r-attachment/build.sh
  recipes/r-attachment/meta.yaml
Labels: R, staged-recipes, review-requested

#27243 Adds rattler-build recipe compatibility (and adds jolt-physics)
  .ci_support/build_all.py
  .ci_support/requirements.txt
  .github/workflows/correct_directory.yml
  .github/workflows/scripts/create_feedstocks
  .github/workflows/scripts/create_feedstocks.py
  README.md
  recipes/example-new-recipe/recipe.yaml
  recipes/jolt-physics/recipe.yaml
Labels: maintenance

#26681 Adding ansys-pythonnet recipe
  recipes/ansys-pythonnet/conda_build_config.yaml
  recipes/ansys-pythonnet/meta.yaml
Labels: review-requested, python

#27135 Added types-aiobotocore
  recipes/types-aiobotocore/meta.yaml
Labels: staged-recipes, review-requested, python

#27253 Add recipe for fatrop
  recipes/fatrop/18.patch
  recipes/fatrop/build.sh
  recipes/fatrop/do_not_hardcode_blasfeo_path.patch
  recipes/fatrop/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#26772 Add openmm-hip
  recipes/openmm-hip/build.sh
  recipes/openmm-hip/meta.yaml
Labels: review-requested, c-cpp

#27251 Added r-lightparser as a package
  recipes/r-lightparser/bld.bat
  recipes/r-lightparser/build.sh
  recipes/r-lightparser/meta.yaml
Labels: R, staged-recipes, review-requested

#27204 Add RAthena recipe
  recipes/r-rathena/bld.bat
  recipes/r-rathena/build.sh
  recipes/r-rathena/meta.yaml
Labels: R, staged-recipes, review-requested

#27266 Adding rapidminer recipe
  recipes/rapidminer/LICENSE
  recipes/rapidminer/meta.yaml
Labels: staged-recipes, review-requested, python

#27268 arcx v0.2.1
  recipes/arcx/meta.yaml
Labels: review-requested, python

#27267 Add qpmpc
  recipes/qpmpc/meta.yaml
Labels: review-requested, python

#27257 add mdonatello
  recipes/mdonatello/meta.yaml
Labels: review-requested, python

#26617 add aioquic 1.2.0
  recipes/aioquic/meta.yaml
Labels: review-requested, python

#27272 Add socketify
  recipes/socketify/build.sh
  recipes/socketify/conda_build_config.yaml
  recipes/socketify/fix_native_makefile.diff
  recipes/socketify/meta.yaml
Labels: review-requested, python

#27275 Add fastcan
  recipes/fastcan/meta.yaml
Labels: staged-recipes, review-requested, python-c

#27282 Add mpdecimal
  recipes/libmpdec/build.sh
  recipes/libmpdec/conda-forge.yml
  recipes/libmpdec/meta.yaml
Labels: review-requested, python

#27287 new PvMail package
  recipes/pvMail/meta.yaml
Labels: review-requested, python

#27295 Added deltadb as a package
  recipes/deltadb/meta.yaml
Labels: staged-recipes, review-requested, python

#27301 Attempt 1 at recipe for 'h5pywrappers' package.
  recipes/h5pywrappers/meta.yaml
Labels: review-requested, python

#27300 Add vasprun-xml
  recipes/vasprun-xml/LICENSE
  recipes/vasprun-xml/meta.yaml
Labels: staged-recipes, review-requested, python

#27294 Added emval as a package
  recipes/emval/meta.yaml
Labels: R, staged-recipes, review-requested, python, rust

#27219 Adding moonrepo-moon 1.27.6
  recipes/moonrepo-moon/bld.bat
  recipes/moonrepo-moon/build.sh
  recipes/moonrepo-moon/meta.yaml
Labels: staged-recipes, review-requested, rust

#27280 add jupyter-templates
  recipes/jupyter-templates/meta.yaml
Labels: review-requested, python

#27209 Add `arro3`
  recipes/arro3/LICENSE_MIT
  recipes/arro3/conda_build_config.yaml
  recipes/arro3/meta.yaml
Labels: review-requested, python

#27064 add qsv
  recipes/qsv/build.sh
  recipes/qsv/conda_build_config.yaml
  recipes/qsv/meta.yaml
Labels: staged-recipes, review-requested

#26976 Add libtoolbox
  recipes/libtoolbox/bld.bat
  recipes/libtoolbox/bld.ps1
  recipes/libtoolbox/build.sh
  recipes/libtoolbox/meta.yaml
  recipes/libtoolbox/patches/0001-add-so-version.patch
  recipes/libtoolbox/tests/CMakeLists.txt
Labels: review-requested, c-cpp

#27067 Add go tools - impl, gofumpt, gomodifytags, goimports-reviser
  recipes/gofumpt/bld.bat
  recipes/gofumpt/build.sh
  recipes/gofumpt/meta.yaml
  recipes/goimports-reviser/bld.bat
  recipes/goimports-reviser/build.sh
  recipes/goimports-reviser/meta.yaml
  recipes/gomodifytags/bld.bat
  recipes/gomodifytags/build.sh
  recipes/gomodifytags/meta.yaml
  recipes/impl/bld.bat
  recipes/impl/build.sh
  recipes/impl/meta.yaml
Labels: staged-recipes, review-requested

#27065 Add Go tools golangci-lint, golangci-lint-langserver, gopls, delve
  recipes/delve/bld.bat
  recipes/delve/build.sh
  recipes/delve/meta.yaml
  recipes/golangci-lint-langserver/bld.bat
  recipes/golangci-lint-langserver/build.sh
  recipes/golangci-lint-langserver/meta.yaml
  recipes/golangci-lint/bld.bat
  recipes/golangci-lint/build.sh
  recipes/golangci-lint/meta.yaml
  recipes/gopls/bld.bat
  recipes/gopls/build.sh
  recipes/gopls/meta.yaml
Labels: staged-recipes, review-requested

#27066 Add Go tools - staticcheck, revive, golines, godoctor
  recipes/godoctor/bld.bat
  recipes/godoctor/build.sh
  recipes/godoctor/meta.yaml
  recipes/golines/bld.bat
  recipes/golines/build.sh
  recipes/golines/meta.yaml
  recipes/revive/bld.bat
  recipes/revive/build.sh
  recipes/revive/meta.yaml
  recipes/staticcheck/bld.bat
  recipes/staticcheck/build.sh
  recipes/staticcheck/meta.yaml
Labels: staged-recipes, review-requested

#27087 Add openmmdl
  recipes/openmmdl/meta.yaml
Labels: review-requested, python

#27215 Add poselib
  recipes/poselib/fix_compile_options.patch
  recipes/poselib/fix_windows.patch
  recipes/poselib/meta.yaml
  recipes/poselib/unvendor_pybind11.patch
Labels: review-requested, python-c

#26857 Add OpenPisco
  recipes/OpenPisco/meta.yaml
Labels: review-requested, python

#27181 Add FCGI2
  recipes/fcgi2/bld.bat
  recipes/fcgi2/build.sh
  recipes/fcgi2/meta.yaml
  recipes/fcgi2/patches/0001-support-x64-and-uwp-build.patch
  recipes/fcgi2/patches/0002-get-2.4.2-compiling-on-windows.patch
Labels: review-requested, c-cpp

#27245 Adding pygubu recipe.
  recipes/pygubu/meta.yaml
Labels: review-requested, python

#27303 Adding myst-sphinx-gallery recipe
  recipes/myst-sphinx-gallery/meta.yaml
Labels: review-requested, python

#27302 add docopt-ng
  recipes/docopt-ng/meta.yaml
Labels: review-requested, python

#27291 Adding gps-timemachine
  recipes/gps-timemachine/meta.yaml
Labels: staged-recipes, review-requested, python

#27230 Added metronomes as a package
  recipes/metronomes/meta.yaml
Labels: staged-recipes, review-requested, python

#27326 Adding nsidc-iceflow
  recipes/nsidc-iceflow/meta.yaml
Labels: review-requested, python

#27323 Add notebook-as-pdf
  recipes/notebook-as-pdf/meta.yaml
Labels: staged-recipes, review-requested, python

#27290 Adding Marsilea and legendkit
  recipes/legendkit/meta.yaml
  recipes/marsilea/meta.yaml
Labels: review-requested, python

#27329 Add recipe for `qpax`
  recipes/qpax/meta.yaml
Labels: staged-recipes, review-requested, python

#24071 Adding the ocean_wave_tracing project
  recipes/ocean_wave_tracing/meta.yaml
Labels: staged-recipes, review-requested, python

#27328 created meta.yml for pypi qubovert=1.2.5
  recipes/qubovert/meta.yaml
Labels: staged-recipes, review-requested

#27315 add prosemd-lsp, glow-md, mdcat, mdsf, mdslw
  recipes/glow-md/bld.bat
  recipes/glow-md/build.sh
  recipes/glow-md/meta.yaml
  recipes/mdcat/bld.bat
  recipes/mdcat/build.sh
  recipes/mdcat/meta.yaml
  recipes/mdsf/bld.bat
  recipes/mdsf/build.sh
  recipes/mdsf/meta.yaml
  recipes/mdslw/bld.bat
  recipes/mdslw/build.sh
  recipes/mdslw/meta.yaml
  recipes/prosemd-lsp/build.sh
  recipes/prosemd-lsp/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27316 add zellij
  recipes/zellij/build.sh
  recipes/zellij/meta.yaml
Labels: R, staged-recipes, review-requested, rust

#27314 add chezmoi
  recipes/chezmoi/bld.bat
  recipes/chezmoi/build.sh
  recipes/chezmoi/meta.yaml
Labels: staged-recipes, review-requested, go

#27313 add csvq, gojq, jaq, jql, prql-compiler
  recipes/csvq/bld.bat
  recipes/csvq/build.sh
  recipes/csvq/meta.yaml
  recipes/gojq/bld.bat
  recipes/gojq/build.sh
  recipes/gojq/meta.yaml
  recipes/jaq/bld.bat
  recipes/jaq/build.sh
  recipes/jaq/meta.yaml
  recipes/jql/bld.bat
  recipes/jql/build.sh
  recipes/jql/meta.yaml
  recipes/prql-compiler/bld.bat
  recipes/prql-compiler/build.sh
  recipes/prql-compiler/meta.yaml
Labels: R, staged-recipes, review-requested, go, rust

#27312 Add package for 'biotraj'
  recipes/biotraj/meta.yaml
Labels: staged-recipes, review-requested, python-c

#27186 Adding `plotpy` package, the Curve and Image Plot Toolkit for Python-Qt Applications
  recipes/plotpy/meta.yaml
Labels: staged-recipes, review-requested, python-c

#27341 Add pmtiles package
  recipes/pmtiles/LICENSE
  recipes/pmtiles/meta.yaml
Labels: review-requested, python

#27350 add litserve
  recipes/litserve/meta.yaml
Labels: review-requested, python

#27349 Add DataLab recipe
  recipes/datalab/meta.yaml
Labels: review-requested, python

#27339 Cptec sazonal
  recipes/cptec-sazonal/LICENSE.txt
  recipes/cptec-sazonal/meta.yaml
Labels: staged-recipes, review-requested

#27353 Add optimagic recipe
  recipes/optimagic/meta.yaml
Labels: review-requested, python

#27250 Add recipe for 'foundry-dev-tools-transforms'
  recipes/foundry-dev-tools-transforms/LICENSE
  recipes/foundry-dev-tools-transforms/meta.yaml
Labels: review-requested, python

#27351 Add DataLabSimpleClient recipe
  recipes/datalabsimpleclient/meta.yaml
Labels: review-requested, python

#27271 Move example to `example-v1`
  .github/workflows/do_not_edit_example.yml
  .github/workflows/only_edit_in_recipes.yaml
  recipes/example-v1/recipe.yaml
Labels: maintenance

#27362 adds `r-truncexpfam`
  recipes/r-truncexpfam/bld.bat
  recipes/r-truncexpfam/build.sh
  recipes/r-truncexpfam/meta.yaml
Labels: R, review-requested

#27340 Add mednet python package
  recipes/mednet/meta.yaml
Labels: review-requested, python

#27372 fix: dont create feedstock for example recipe.
  .github/workflows/scripts/create_feedstocks.py
Labels: maintenance

#27373 adds `r-shinycyjs`
  recipes/r-shinycyjs/bld.bat
  recipes/r-shinycyjs/build.sh
  recipes/r-shinycyjs/meta.yaml
Labels: R, review-requested

#27374 adds `r-dashboardthemes`
  recipes/r-dashboardthemes/bld.bat
  recipes/r-dashboardthemes/build.sh
  recipes/r-dashboardthemes/meta.yaml
Labels: R, review-requested

#27377 adds `r-rbeta2009`
  recipes/r-rbeta2009/bld.bat
  recipes/r-rbeta2009/build.sh
  recipes/r-rbeta2009/meta.yaml
Labels: R, review-requested

#27379 adds `r-mwcsr`
  recipes/r-mwcsr/bld.bat
  recipes/r-mwcsr/build.sh
  recipes/r-mwcsr/meta.yaml
Labels: R, review-requested

#27385 Add r-gggenomes
  recipes/r-gggenomes/bld.bat
  recipes/r-gggenomes/build.sh
  recipes/r-gggenomes/meta.yaml
Labels: R, staged-recipes, review-requested

#27376 adds `r-microbiomestat`
  recipes/r-microbiomestat/bld.bat
  recipes/r-microbiomestat/build.sh
  recipes/r-microbiomestat/meta.yaml
Labels: R, review-requested

#27375 adds `r-tidydr`
  recipes/r-tidydr/bld.bat
  recipes/r-tidydr/build.sh
  recipes/r-tidydr/meta.yaml
Labels: R, review-requested

#27381 adds `r-tca`
  recipes/r-tca/bld.bat
  recipes/r-tca/build.sh
  recipes/r-tca/meta.yaml
Labels: R, review-requested

#27347 Add chooch and pychooch recipes
  recipes/chooch/CMakeLists.txt
  recipes/chooch/LICENSE.txt
  recipes/chooch/build.sh
  recipes/chooch/meta.yaml
  recipes/pychooch/meta.yaml
Labels: review-requested, c-cpp

#27390 Adding `numpydantic`
  recipes/numpydantic/meta.yaml
Labels: review-requested, python

#27360 add openinference-instrumentation-haystack
  recipes/openinference-instrumentation-haystack/meta.yaml
Labels: review-requested, python

#27389 Adding `pydantic-numpy`
  recipes/pydantic-numpy/meta.yaml
Labels: review-requested, python

#27396 Add gridit
  recipes/gridit/meta.yaml
Labels: review-requested, python

#27404 Add package for microsoft-aurora
  recipes/microsoft-aurora/meta.yaml
Labels: review-requested, python

#27407 Adding evermore
  recipes/evermore/meta.yaml
Labels: review-requested, python

#27394 Add airflow-ha
  recipes/airflow-ha/meta.yaml
Labels: review-requested, python

#27370 Adding nabs
  recipes/nabs/meta.yaml
Labels: review-requested, python

#27413 Add orderly-set
  recipes/orderly-set/MIT-LICENSE
  recipes/orderly-set/meta.yaml
Labels: review-requested, python

#27417 Add `hatch-deps-selector`
  recipes/hatch-deps-selector/meta.yaml
Labels: review-requested, python

#27411 Added displayhooks as a package
  recipes/displayhooks/meta.yaml
Labels: staged-recipes, review-requested, python

#27283 CRYSTALpytools initial release on conda-forge
  recipes/CRYSTALpytools/meta.yaml
Labels: staged-recipes, review-requested

#27416 Adding jsonyx
  recipes/jsonyx/meta.yaml
Labels: staged-recipes, review-requested, python-c

#27414 feat: Add plothist
  recipes/plothist/meta.yaml
Labels: review-requested, python

#27425 Add recipe for e3sm-tools
  recipes/e3sm-tools/0001-fix-boz-erros-in-interpinic-build.patch
  recipes/e3sm-tools/0002-fix-iargc-issue-in-interpinic-build.patch
  recipes/e3sm-tools/0003-fix-boz-erros-in-mksurfdata_map-build.patch
  recipes/e3sm-tools/CMakeLists.txt
  recipes/e3sm-tools/build.sh
  recipes/e3sm-tools/cmake/FindNETCDF.cmake
  recipes/e3sm-tools/cmake_macros/gnu.cmake
  recipes/e3sm-tools/meta.yaml
  recipes/e3sm-tools/tools/cube_to_target/CMakeLists.txt
  recipes/e3sm-tools/tools/interpinic/CMakeLists.txt
  recipes/e3sm-tools/tools/mksurfdata_map/CMakeLists.txt
Labels: staged-recipes, review-requested

#27342 add crowdin-cli, jacoco, junit5
  recipes/crowdin-cli/build.sh
  recipes/crowdin-cli/meta.yaml
  recipes/jacoco/build.sh
  recipes/jacoco/meta.yaml
  recipes/junit5/build.sh
  recipes/junit5/meta.yaml
Labels: staged-recipes, review-requested

#27345 add gospel, harper
  recipes/gospel/build.sh
  recipes/gospel/conda_build_config.yaml
  recipes/gospel/meta.yaml
  recipes/harper/bld.bat
  recipes/harper/build.sh
  recipes/harper/meta.yaml
Labels: review-requested, go

#27100 Add dydxprotocol-v4-proto-py
  recipes/dydxprotocol-v4-proto-py/bld.bat
  recipes/dydxprotocol-v4-proto-py/build.sh
  recipes/dydxprotocol-v4-proto-py/install-py.bat
  recipes/dydxprotocol-v4-proto-py/install-py.sh
  recipes/dydxprotocol-v4-proto-py/meta.yaml
  recipes/dydxprotocol-v4-proto-py/patches/0001-win-docker-experimental.patch
Labels: review-requested, python

#26925 Adding AstroGlue recipe
  recipes/AstroGlue/meta.yaml
  recipes/AstroGlue/yum_requirements.txt
Labels: staged-recipes, review-requested, python
