Repository conda-forge/staged-recipes, pull requests merged in 2025-09, with the labels that each got.

#30861 add mamba-ssm
  recipes/mamba-ssm/meta.yaml
Labels: staged-recipes, review-requested

#30919 Adding async-interrupt package
  recipes/async-interrupt/recipe.yaml
Labels: review-requested, python

#30925 add `icmplib`
  recipes/icmplib/recipe.yaml
Labels: review-requested, python

#30924 add chacha20poly1305-reuseable
  recipes/chacha20poly1305-reuseable/recipe.yaml
Labels: review-requested, python

#30931 Add `imas-data-dictionaries`
  recipes/imas-data-dictionaries/conda-forge.yml
  recipes/imas-data-dictionaries/recipe.yaml
  recipes/imas-data-dictionaries/remove-setuptools-scm.patch
Labels: review-requested, python

#30935 Adding 'hatch-mkdocs'
  recipes/hatch-mkdocs/meta.yaml
Labels: review-requested, python

#30933 adding langchain-tavily
  recipes/langchain-tavily/meta.yaml
Labels: review-requested, python

#30855 Add pyLabDD recipe
  recipes/pylabdd/meta.yaml
Labels: staged-recipes, review-requested, python

#30952 Add dccp
  recipes/dccp/recipe.yaml
Labels: review-requested, python

#30929 Add r-tailor
  recipes/r-tailor/bld.bat
  recipes/r-tailor/build.sh
  recipes/r-tailor/meta.yaml
Labels: R

#30959 Add dns-lexicon and python-digitalocean
  recipes/dns-lexicon/recipe.yaml
  recipes/python-digitalocean/recipe.yaml
Labels: review-requested, python

#30960 Add mohtml and moterm
  recipes/mohtml/recipe.yaml
  recipes/moterm/recipe.yaml
Labels: review-requested, python

#30973 Added aLang - A programming language specializing in cross-compiling
  recipes/alang/meta.yaml
Labels: review-requested, python

#30968 Add aioresult and anysqlite
  recipes/aioresult/meta.yaml
  recipes/anysqlite/meta.yaml
Labels: review-requested, python

#30961 Add GPJax recipe
  recipes/gpjax/meta.yaml
Labels: review-requested, python

#30979 Add ReactPy - It's React, but in Python
  recipes/reactpy/recipe.yaml
Labels: review-requested, python

#30971 Add recipe for rocm-core
  recipes/rocm-core/build.sh
  recipes/rocm-core/recipe.yaml
Labels: staged-recipes, review-requested, c-cpp

#30975 Add pyjelly
  recipes/pyjelly/recipe.yaml
Labels: review-requested, python

#30991 Add moutils
  recipes/moutils/recipe.yaml
Labels: review-requested, python

#30995 add legend-pygeom-optics
  recipes/legend-pygeom-optics/meta.yaml
Labels: review-requested, python

#31001 Add bioio-lif
  recipes/bioio-lif/recipe.yaml
Labels: review-requested, python

#31005 Add bioio-ome-zarr
  recipes/bioio-ome-zarr/recipe.yaml
Labels: review-requested, python

#30992 First attempt at publishing 'emicroml' on conda-forge.
  recipes/emicroml/meta.yaml
Labels: review-requested, python

#30964 Add recipe for easchersim
  recipes/easchersim/meta.yaml
Labels: staged-recipes, review-requested, python

#31006 Add prek
  recipes/prek/recipe.yaml
Labels: review-requested, rust

#30999 add legend-pygeom-l1000
  recipes/legend-pygeom-l1000/meta.yaml
Labels: review-requested, python

#30815 add elecsolver no arch recipe for 1.0.4 - Ready for review
  recipes/elecsolver/meta.yaml
Labels: staged-recipes, review-requested, python

#30802 add grpcui recipe
  recipes/grpcui/recipe.yaml
Labels: review-requested, go

#31032 add `gepa`
  recipes/gepa/recipe.yaml
Labels: review-requested, python

#31029 Add django-online-issues
  recipes/django-online-issues/recipe.yaml
Labels: review-requested, python

#31051 fix: update linter workflow to include issue_comment event for PRs
  .github/workflows/linter.yml
Labels: maintenance

#31045 Add lightcurvelynx, replacement of tdastro
  recipes/lightcurvelynx/meta.yaml
Labels: review-requested, python

#30848 Add drugforge
  recipes/drugforge/recipe.yaml
Labels: review-requested, python

#31061 Add `python-datauri` recipe (initialized from Grayskull)
  recipes/python-datauri/recipe.yaml
Labels: review-requested, python

#31059 Add `cohere` recipe (initialized with Grayskull)
  recipes/cohere/recipe.yaml
Labels: review-requested, python

#31044 added py-cid py-multibase py-multicodec pymultihash for version bump of multiaddr
  recipes/py-cid/meta.yaml
  recipes/py-multibase/meta.yaml
  recipes/py-multicodec/meta.yaml
  recipes/pymultihash/meta.yaml
Labels: review-requested, python

#31072 Add jupyterlab-slideshow
  recipes/jupyterlab-slideshow/recipe.yaml
Labels: review-requested, python

#30958 Add certbot-dns plugins
  recipes/certbot-dns-cloudflare/recipe.yaml
  recipes/certbot-dns-digitalocean/recipe.yaml
  recipes/certbot-dns-dnsimple/recipe.yaml
  recipes/certbot-dns-dnsmadeeasy/recipe.yaml
  recipes/certbot-dns-gehirn/recipe.yaml
  recipes/certbot-dns-google/recipe.yaml
  recipes/certbot-dns-linode/recipe.yaml
  recipes/certbot-dns-luadns/recipe.yaml
  recipes/certbot-dns-nsone/recipe.yaml
  recipes/certbot-dns-ovh/recipe.yaml
  recipes/certbot-dns-rfc2136/recipe.yaml
  recipes/certbot-dns-route53/recipe.yaml
  recipes/certbot-dns-sakuracloud/recipe.yaml
Labels: review-requested, python

#31050 Adding `upstage-des` library.
  recipes/upstage-des/meta.yaml
Labels: staged-recipes, review-requested, python

#31089 Find conda_build_config.yaml and variants.yaml inside the new recipe v1 folder
  .ci_support/build_all.py
Labels: maintenance

#31116 Add httpx-aiohttp
  recipes/httpx-aiohttp/meta.yaml
Labels: staged-recipes, review-requested, python

#31058 Add feedstock for geoarrow-rust-python
  recipes/geoarrow-rust-python/build-pkg-core.bat
  recipes/geoarrow-rust-python/build-pkg-core.sh
  recipes/geoarrow-rust-python/build-pkg-io.bat
  recipes/geoarrow-rust-python/build-pkg-io.sh
  recipes/geoarrow-rust-python/meta.yaml
Labels: review-requested, python

#31114 Add sasdata recipe
  recipes/sasdata/meta.yaml
Labels: review-requested, python

#30955 Add aiortc, pylibsrtp, and libsrtp2
  recipes/aiortc/loosen_av_pin.patch
  recipes/aiortc/meta.yaml
  recipes/libsrtp2/bld.bat
  recipes/libsrtp2/build.sh
  recipes/libsrtp2/fix_dll_installation.patch
  recipes/libsrtp2/meta.yaml
  recipes/pylibsrtp/meta.yaml
Labels: review-requested, python

#31123 Add pymatgen-io-validation
  recipes/pymatgen-io-validation/meta.yaml
Labels: staged-recipes, review-requested, python
