Repository conda-forge/staged-recipes, pull requests merged in 2025-06, with the labels that each got.

#29763 Add recipe for arrakis-schema-python
  recipes/python-arrakis-schema/meta.yaml
Labels: review-requested, python

#29990 Add `libvalkey`
  recipes/libvalkey/patches/0000-tls.patch
  recipes/libvalkey/recipe.yaml
Labels: review-requested, c-cpp

#30017 Add recipe for test-drive
  recipes/test-drive/bld.bat
  recipes/test-drive/build.sh
  recipes/test-drive/meta.yaml
Labels: review-requested, c-cpp

#30047 Add kube-no-trouble package
  recipes/kube-no-trouble/bld.bat
  recipes/kube-no-trouble/build.sh
  recipes/kube-no-trouble/meta.yaml
Labels: review-requested, go

#30198 Add cpio, global, hello, indent
  recipes/cpio/build.sh
  recipes/cpio/recipe.yaml
  recipes/global/build.sh
  recipes/global/recipe.yaml
  recipes/hello/build.sh
  recipes/hello/recipe.yaml
  recipes/indent/build.sh
  recipes/indent/recipe.yaml
Labels: review-requested, c-cpp

#30224 Add niworkflows
  recipes/niworkflows/meta.yaml
Labels: review-requested, python

#30238 feat: add simple-settings
  recipes/simple-settings/recipe.yaml
Labels: review-requested, python

#30253 Add mopad
  recipes/mopad/recipe.yaml
Labels: review-requested, python

#30007 Add Zasper webapp package
  recipes/zasper/LICENSE
  recipes/zasper/meta.yaml
Labels: review-requested, go

#30252 Add rundec
  recipes/rundec/add-pyproject-toml-for-build-system.patch
  recipes/rundec/recipe.yaml
Labels: review-requested, python, python-c

#30239 Add pylha
  recipes/pylha/LICENSE
  recipes/pylha/recipe.yaml
Labels: review-requested, python

#30236 feat: add itkdb
  recipes/itkdb/patches/0001-drop-pylibmagic-dependency-for-pip-check.patch
  recipes/itkdb/recipe.yaml
Labels: review-requested, python

#30220 Add libmd, libsixel, libsmf, libsvg-cairo
  recipes/libmd/build.sh
  recipes/libmd/recipe.yaml
  recipes/libsixel/build.sh
  recipes/libsixel/recipe.yaml
  recipes/libsmf/build.sh
  recipes/libsmf/recipe.yaml
  recipes/libsvg/0001-use-newer-autotools.patch
  recipes/libsvg/0002-Fix-undefined-symbol-png_set_gray_1_2_4_to_8.patch
  recipes/libsvg/build.sh
  recipes/libsvg/recipe.yaml
Labels: review-requested, c-cpp

#30232 feat: add module-qc-database-tools
  recipes/module-qc-database-tools/recipe.yaml
Labels: review-requested, python

#30235 Add steppyngstounes recipe
  recipes/steppyngstounes/meta.yaml
Labels: review-requested, python

#30233 feat: add module-qc-tools
  recipes/module-qc-tools/recipe.yaml
Labels: review-requested, python

#30230 add encexp
  recipes/encexp/meta.yaml
Labels: review-requested, python

#30258 Add dbt-protos
  recipes/dbt-protos/recipe.yaml
Labels: review-requested, python

#30261 Add dtscalibration
  recipes/dtscalibration/meta.yaml
Labels: staged-recipes, review-requested, python

#30263 Re-add pyspainmobility 1.0.2 recipe
  recipes/pyspainmobility/meta.yaml
Labels: review-requested, python

#30254 Adding `skore-local-project` and `skore-hub-project`
  recipes/skore-hub-project/meta.yaml
  recipes/skore-local-project/meta.yaml
Labels: review-requested, python

#30219 Add xauth
  recipes/xauth/build.sh
  recipes/xauth/recipe.yaml
Labels: review-requested, c-cpp

#30039 Added r-packcircles as a package
  recipes/r-packcircles/bld.bat
  recipes/r-packcircles/build.sh
  recipes/r-packcircles/meta.yaml
Labels: R, staged-recipes, review-requested, c-cpp

#30274 Add Cherry-Picker package
  recipes/cherry-picker/meta.yaml
Labels: review-requested, python

#30262 Add fenicsx-pulse
  recipes/fenicsx-pulse/meta.yaml
Labels: review-requested, python

#30281 Add pydiverse-colspec
  recipes/pydiverse-colspec/recipe.yaml
Labels: review-requested, python

#30266 Add puncc recipe
  recipes/puncc/MIT-Clause.txt
  recipes/puncc/meta.yaml
Labels: review-requested, python

#30290 Add func_adl_servicex_xaodr25
  recipes/func_adl_servicex_xaodr25/LICENSE
  recipes/func_adl_servicex_xaodr25/recipe.yaml
Labels: review-requested, python

#30204 add package python-kasa
  recipes/python-kasa/conda-forge.yml
  recipes/python-kasa/meta.yaml
Labels: review-requested, python

#29962 fix: update deprecated PyGitHub method calls
  .github/workflows/scripts/linter.py
Labels: maintenance, staged-recipes, review-requested, python

#30297 Package pycrdt-store
  recipes/pycrdt-store/meta.yaml
Labels: review-requested, python

#30296 Add micro-liquid package
  recipes/micro-liquid/meta.yaml
Labels: review-requested, python

#30307 Add specta recipe
  recipes/specta/meta.yaml
Labels: review-requested, python

#30312 Add scikit-uplift
  recipes/scikit-uplift/recipe.yaml
Labels: review-requested, python

#30323 Add types-docker recipe
  recipes/types-docker/recipe.yaml
Labels: review-requested, python

#23686 added recipe for `antspyx`
  recipes/antspyx/itk_patch.diff
  recipes/antspyx/meta.yaml
Labels: review-requested, python-c

#30326 Add recipe for `databackend`
  recipes/databackend/meta.yaml
Labels: review-requested, python

#30321 Added sql-tstring as a package
  recipes/sql-tstring/LICENSE
  recipes/sql-tstring/recipe.yaml
Labels: review-requested, python

#30318 Added strif as a package
  recipes/strif/recipe.yaml
Labels: review-requested, python

#30325 Add djc-core-html-parser
  recipes/djc-core-html-parser/recipe.yaml
Labels: R, review-requested, rust

#30308 Add recipe for elegansbot
  recipes/elegansbot/meta.yaml
Labels: review-requested, python

#30313 Add trunk recipe
  recipes/trunk/recipe.yaml
Labels: R, review-requested, rust

#30333 Adding igorwriter recipe
  recipes/igorwriter/meta.yaml
Labels: staged-recipes, review-requested, python

#30306 Add fill-voids
  recipes/fill-voids/LICENSE-libdivide
  recipes/fill-voids/meta.yaml
Labels: review-requested, python

#29576 Add nerfstudio
  recipes/nerfstudio/meta.yaml
  recipes/nerfstudio/patches/0001-Adjust-dependencies.patch
Labels: review-requested, python

#28315 Added mininterface as a package
  recipes/mininterface/recipe.yaml
Labels: review-requested, python

#30038 Added r-vayr as a package
  recipes/r-vayr/bld.bat
  recipes/r-vayr/build.sh
  recipes/r-vayr/meta.yaml
Labels: R, review-requested

#30346 add saml-auth-proxy
  recipes/saml-auth-proxy/recipe.yaml
Labels: review-requested, go

#30338 add dm filler package
  recipes/packaging-dmfiller/build.bat
  recipes/packaging-dmfiller/build.sh
  recipes/packaging-dmfiller/meta.yaml
Labels: R, staged-recipes, review-requested

#30298 Add azure-monitor-opentelemetry, New Dependencies for azure-ai-ml-feedstock
  recipes/azure-core-tracing-opentelemetry/meta.yaml
  recipes/azure-monitor-opentelemetry-exporter/meta.yaml
  recipes/azure-monitor-opentelemetry/meta.yaml
  recipes/fixedint/meta.yaml
  recipes/opentelemetry-resource-detector-azure/meta.yaml
Labels: review-requested, python

#30350 Add ontolutils
  recipes/ontolutils/meta.yaml
Labels: staged-recipes, review-requested, python

#30362 Adding `brev`
  recipes/brev/recipe.yaml
Labels: staged-recipes, review-requested

#30371 Add mcrnmf 0.1.0 recipe
  recipes/mcrnmf/meta.yaml
Labels: review-requested, python

#30372 added recipe for `highdicom`
  recipes/highdicom/meta.yaml
Labels: review-requested, python

#30381 Add recipe for globalign.
  recipes/globalign/meta.yaml
Labels: staged-recipes, review-requested, python

#30375 Add fastmcp
  recipes/fastmcp/recipe.yaml
Labels: review-requested, python

#30374 Add markdown-to-confluence
  recipes/markdown-to-confluence/recipe.yaml
Labels: review-requested, python

#30383 Add pyodps
  recipes/pyodps/License
  recipes/pyodps/meta.yaml
Labels: review-requested, python

#30337 Adding QuackOSM
  recipes/quackosm/meta.yaml
  recipes/rq_geo_toolkit/meta.yaml
Labels: staged-recipes, review-requested, python

#30389 add sphinx-last-updated-by-git
  recipes/sphinx-last-updated-by-git/recipe.yaml
Labels: review-requested, python

#30365 Add zenoh-pico
  recipes/zenoh-pico/conda_build_config.yaml
  recipes/zenoh-pico/meta.yaml
  recipes/zenoh-pico/recipe.bak.yaml
Labels: staged-recipes, review-requested, c-cpp

#30391 New recipe for xarray-subset-grid
  recipes/xarray-subset-grid/meta.yaml
Labels: review-requested, python

#30396 Add pytest-docker-tools
  recipes/pytest-docker-tools/recipe.yaml
Labels: review-requested, python

#29662 add r-deconvolver, r-enshuman
  recipes/r-deconvolver/bld.bat
  recipes/r-deconvolver/build.sh
  recipes/r-deconvolver/meta.yaml
  recipes/r-enshuman/bld.bat
  recipes/r-enshuman/build.sh
  recipes/r-enshuman/meta.yaml
Labels: R, staged-recipes, review-requested

#30214 Add Bodo Recipe
  recipes/bodo/bld.bat
  recipes/bodo/build.sh
  recipes/bodo/conda_build_config.yaml
  recipes/bodo/meta.yaml
  recipes/bodo/patches/0001-fix-boost-cmake.patch
  recipes/bodo/run_test.bat
  recipes/bodo/run_test.sh
Labels: review-requested, python-c

#30401 Adding assyst pypi package
  recipes/assyst/meta.yaml
Labels: review-requested, python

#30382 drop CUDA 11.8
  .azure-pipelines/azure-pipelines-linux.yml
  .ci_support/linux64_cuda118.yaml
Labels: maintenance

#30360 Recipe for PyOpenGL-Accelerate
  recipes/pyopengl-accelerate/license.txt
  recipes/pyopengl-accelerate/long_type.patch
  recipes/pyopengl-accelerate/meta.yaml
Labels: review-requested, python-c

#30414 Add bagofholding
  recipes/bagofholding/meta.yaml
Labels: review-requested, python

#30419 Add TOML11
  recipes/toml11/build.bat
  recipes/toml11/build.sh
  recipes/toml11/recipe.yaml
Labels: review-requested, c-cpp

#30421 Adding scikit-bio-binaries
  recipes/scikit-bio-binaries/build.sh
  recipes/scikit-bio-binaries/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#30424 add pytest-lsp
  recipes/pytest-lsp/recipe.yaml
Labels: review-requested, python

#29919 Add stopt to conda-forge
  recipes/stopt/bld.bat
  recipes/stopt/build.sh
  recipes/stopt/meta.yaml
Labels: review-requested, c-cpp

#30417 add mds-toolbox recipe
  recipes/mds-toolbox/conda-forge.yml
  recipes/mds-toolbox/meta.yaml
Labels: review-requested, python

#29486 Adding optunahub
  recipes/optunahub/meta.yaml
Labels: review-requested, python

#30434 Add TinyHtml5
  recipes/tinyhtml5/recipe.yaml
Labels: review-requested, python

#30395 Add llmcompressor
  recipes/llmcompressor/meta.yaml
Labels: review-requested, python

#30436 Adding vitabel
  recipes/vitabel/meta.yaml
Labels: review-requested, python
