Repository conda-forge/staged-recipes, pull requests merged in 2025-10, with the labels that each got.

#31141 add `dbos`
  recipes/dbos/recipe.yaml
Labels: review-requested, python

#31146 add seabirdfilehandler
  recipes/seabirdfilehandler/meta.yaml
Labels: review-requested, python

#31144 add linear-inverse-model
  recipes/linear-inverse-model/meta.yaml
Labels: review-requested, python

#31143 add eo-tides
  recipes/eo-tides/meta.yaml
Labels: review-requested, python

#31160 Add elements
  recipes/elements/recipe.yaml
Labels: review-requested, python

#31154 Add portal
  recipes/portal/recipe.yaml
Labels: review-requested, python

#31151 adding boring-semantic-layer
  recipes/boring-semantic-layer/meta.yaml
Labels: review-requested, python

#30694 Add smblmath recipe
  recipes/sbmlmath/meta.yaml
Labels: staged-recipes, review-requested, python

#31171 Add multiclean package
  recipes/multiclean/meta.yaml
Labels: review-requested, python

#31161 Add granular
  recipes/granular/recipe.yaml
Labels: review-requested, python

#31162 Add ninjax
  recipes/ninjax/recipe.yaml
Labels: review-requested, python

#31165 Adding nwb2bids
  recipes/nwb2bids/meta.yaml
Labels: review-requested, python

#31112 Add recipe for font-ttf-roboto
  recipes/font-ttf-roboto/recipe.yaml
Labels: staged-recipes, review-requested

#31173 Add recipe for grapes
  recipes/grapes/meta.yaml
Labels: staged-recipes, review-requested, python

#31178 Add InSARScript
  recipes/insarscript/meta.yaml
Labels: review-requested, python

#30974 Adding PyBispectra
  recipes/pybispectra/meta.yaml
Labels: staged-recipes, review-requested, python

#30579 Add pyLabFEA recipe
  recipes/pylabfea/meta.yaml
Labels: staged-recipes, review-requested, python

#31076 Add pyiron_workflow_atomistics
  recipes/pyiron-workflow-atomistics/meta.yaml
Labels: staged-recipes, review-requested, python
