Repository conda-forge/staged-recipes, pull requests merged in 2025-04, with the labels that each got.

#29585 add anakin-language-server, dead, reorder_python_imports, uncalled
  recipes/anakin-language-server/meta.yaml
  recipes/dead/meta.yaml
  recipes/reorder_python_imports/meta.yaml
  recipes/uncalled/meta.yaml
Labels: staged-recipes, review-requested, python

#29586 Add nuscenes-devkit
  recipes/nuscenes-devkit/meta.yaml
  recipes/nuscenes-devkit/patches/0001-Use-os-specific-path-seperator.patch
Labels: review-requested, python

#29597 Add comet-ml
  recipes/viser/meta.yaml
Labels: review-requested, python

#29414 add r-mlr3extralearners from github source
  recipes/r-mlr3extralearners/bld.bat
  recipes/r-mlr3extralearners/build.sh
  recipes/r-mlr3extralearners/meta.yaml
Labels: R, review-requested

#29592 Add recipe for xcengine
  recipes/xcengine/meta.yaml
Labels: review-requested, python

#29594 Adding arcosparse
  recipes/arcosparse/meta.yaml
Labels: staged-recipes, review-requested, python

#29603 add pypfb
  recipes/pypfb/meta.yaml
Labels: staged-recipes, review-requested, python

#29604 Add omp4py
  recipes/omp4py/meta.yaml
Labels: staged-recipes, review-requested, python

#29602 add fsharplint
  recipes/fsharplint/build.sh
  recipes/fsharplint/recipe.yaml
Labels: staged-recipes, review-requested

#29601 add convco, millet, uutils-findutils
  recipes/convco/build.bat
  recipes/convco/build.sh
  recipes/convco/recipe.yaml
  recipes/millet/build.bat
  recipes/millet/build.sh
  recipes/millet/recipe.yaml
  recipes/uutils-findutils/build.sh
  recipes/uutils-findutils/recipe.yaml
Labels: R, staged-recipes, review-requested, rust

#29503 Adding Iris-Codec Recipe
  recipes/iris-codec/bld.bat
  recipes/iris-codec/build.sh
  recipes/iris-codec/conda_build_config.yaml
  recipes/iris-codec/meta.yaml
  recipes/iris-codec/run_test.py
Labels: review-requested, c-cpp, python

#29619 Add fpsample
  recipes/fpsample/meta.yaml
Labels: review-requested, python, python-c

#29287 Add scippnexus to conda-forge
  recipes/scippnexus/recipe.yaml
Labels: review-requested, python

#29622 Add igwn-robot-auth
  recipes/igwn-robot-auth/meta.yaml
Labels: review-requested, python

#29358 Add quickbayes recipe
  recipes/quickbayes/meta.yaml
Labels: staged-recipes, review-requested, python

#29567 Add pre-commit config
  .ci_support/build_all.py
  .ci_support/compute_build_graph.py
  .github/ISSUE_TEMPLATE/bugs_template.yml
  .github/ISSUE_TEMPLATE/issue_template.yml
  .github/ISSUE_TEMPLATE/package-request.yml
  .github/stale.yml
  .github/workflows/scripts/create_feedstocks.py
  .github/workflows/scripts/linter.py
  .github/workflows/scripts/linter_make_comment.py
  .github/workflows/scripts/print_tokens.py
  .pre-commit-config.yaml
  .scripts/build_steps.sh
  LICENSE.txt
  build-locally.py
  environment.yaml
Labels: maintenance

#29632 Add videoio
  recipes/videoio/meta.yaml
Labels: review-requested, python

#29612 Add constantdict
  recipes/constantdict/meta.yaml
Labels: staged-recipes, review-requested, python

#29600 add gargs, github-release, go-tools
  recipes/gargs/bld.bat
  recipes/gargs/build.sh
  recipes/gargs/meta.yaml
  recipes/github-release/bld.bat
  recipes/github-release/build.sh
  recipes/github-release/meta.yaml
  recipes/go-tools/bld.bat
  recipes/go-tools/build.sh
  recipes/go-tools/meta.yaml
Labels: staged-recipes, review-requested, go

#29645 add mdformat-shfmt recipe
  recipes/mdformat-shfmt/meta.yaml
Labels: review-requested, python

#29646 add mpcontribs-client recipe
  recipes/mpcontribs-client/meta.yaml
Labels: review-requested, python

#29651 Add csp-bot
  recipes/csp-bot/recipe.yaml
Labels: review-requested, python

#29635 Add sqlframe to conda-forge
  recipes/sqlframe/recipe.yaml
Labels: review-requested, python

#29656 Add ete4
  recipes/ete4/meta.yaml
Labels: review-requested, python

#29633 Adding pyTCR package
  recipes/pyTCR/meta.yaml
Labels: review-requested, python

#28687 Add gsplat
  recipes/gsplat/build.sh
  recipes/gsplat/meta.yaml
  recipes/gsplat/patches/0001-Remove-ninja-from-install-requirements.patch
Labels: review-requested, python-c

#29629 add tex-fmt (take 2)
  recipes/tex-fmt/recipe.yaml
Labels: R, review-requested, rust

#29611 Add openfpgaloader
  recipes/openfpgaloader/build.sh
  recipes/openfpgaloader/meta.yaml
Labels: review-requested, c-cpp

#27757 Add tiny-cuda-nn
  recipes/tiny-cuda-nn/build.sh
  recipes/tiny-cuda-nn/meta.yaml
Labels: review-requested, python-c

#29657 Add huracanpy
  recipes/huracanpy/meta.yaml
Labels: review-requested, python

#29666 Add slurm-sweeps
  recipes/slurm-sweeps/meta.yaml
Labels: staged-recipes, review-requested, python

#29667 Add xarray-regrid
  recipes/xarray-regrid/meta.yaml
Labels: staged-recipes, review-requested, python

#29668 add `shiny_validate`
  recipes/shiny_validate/meta.yaml
Labels: review-requested, python

#29620 add recipe for stanhf
  recipes/stanhf/meta.yaml
Labels: staged-recipes, review-requested, python

#29637 Adding job-pool Python package
  recipes/job-pool/meta.yaml
Labels: review-requested, python

#29672 add slem-learn via pypi - edited grayskull recipe
  recipes/slem-learn/meta.yaml
Labels: review-requested, python

#29675 Add pengwann recipe
  recipes/pengwann/meta.yaml
Labels: R, review-requested, python, rust

#29664 Add EvArgs.
  recipes/evargs/meta.yaml
Labels: review-requested, python

#29677 Add recipe for buildingregulariser
  recipes/buildingregulariser/meta.yaml
Labels: review-requested, python

#28771 Add TidalPy
  recipes/TidalPy/meta.yaml
Labels: review-requested, python-c

#29682 added recipe for `ndlinear`
  recipes/ndlinear/meta.yaml
Labels: review-requested, python

#29683 Add SMEFiT
  recipes/smefit/recipe.yaml
Labels: review-requested, python

#29685 Add servicex-analysis-utils
  recipes/servicex-analysis-utils/recipe.yaml
Labels: review-requested, python

#29624 Adding geoh5-interop meta package
  recipes/geoh5-interop/recipe.yaml
Labels: review-requested, python

#29424 Added kissbt recipe
  recipes/kissbt/meta.yaml
Labels: review-requested, python

#29658 Add rjieba recipe
  recipes/rjieba/meta.yaml
Labels: review-requested, python

#29399 Adding emi package
  recipes/emi/meta.yaml
Labels: staged-recipes, review-requested

#29693 Add google-adk
  recipes/google-adk/meta.yaml
Labels: staged-recipes, review-requested, python

#29696 Added django-typer as a package
  recipes/django-typer/recipe.yaml
Labels: review-requested, python

#29697 Added coredumpy as a package
  recipes/coredumpy/recipe.yaml
Labels: review-requested, python

#29698 Added clypi as a package
  recipes/clypi/recipe.yaml
Labels: review-requested, python

#29708 Add datastar-py
  recipes/datastar-py/LICENSE
  recipes/datastar-py/meta.yaml
Labels: review-requested, python

#29702 Added textcase as a package
  recipes/textcase/recipe.yaml
Labels: review-requested, python

#29703 Added pysqlscribe as a package
  recipes/pysqlscribe/recipe.yaml
Labels: review-requested, python

#28628 Add pds.api-client
  recipes/pds.api-client/meta.yaml
Labels: staged-recipes, review-requested, python

#29575 Add `xan`
  recipes/xan/recipe.yaml
Labels: R, review-requested, rust

#29556 add deepmd-gnn
  recipes/deepmd-gnn/activate.sh
  recipes/deepmd-gnn/build.sh
  recipes/deepmd-gnn/deactivate.sh
  recipes/deepmd-gnn/in.lammps
  recipes/deepmd-gnn/meta.yaml
  recipes/deepmd-gnn/train.json
  recipes/deepmd-gnn/water.lmp
Labels: review-requested, python-c

#29606 Add nanoeigenpy
  recipes/nanoeigenpy/build.bat
  recipes/nanoeigenpy/build.sh
  recipes/nanoeigenpy/conda_build_config.yaml
  recipes/nanoeigenpy/recipe.yaml
Labels: staged-recipes, review-requested, c-cpp

#29709 Add rdkit2ase
  recipes/rdkit2ase/meta.yaml
Labels: staged-recipes, review-requested, python

#29617 Add nerfacc
  recipes/nerfacc/build.sh
  recipes/nerfacc/meta.yaml
Labels: review-requested, python-c

#29337 Add Python bindings for metatensor-torch
  recipes/metatensor-torch/meta.yaml
Labels: review-requested, python, python-c

#29365 Add stanalyzer package
  recipes/stanalyzer/meta.yaml
Labels: staged-recipes, review-requested, python

#29690 Add r-catr
  recipes/r-catr/bld.bat
  recipes/r-catr/build.sh
  recipes/r-catr/meta.yaml
Labels: R, review-requested

#29590 Add recipe for r-bdrc
  recipes/r-bdrc/bld.bat
  recipes/r-bdrc/build.sh
  recipes/r-bdrc/meta.yaml
Labels: R, staged-recipes, review-requested

#29660 add r-gmcm, r-onlinepca, r-pdsce, r-pgenlibr, r-pqlseq
  recipes/r-gmcm/bld.bat
  recipes/r-gmcm/build.sh
  recipes/r-gmcm/meta.yaml
  recipes/r-onlinepca/bld.bat
  recipes/r-onlinepca/build.sh
  recipes/r-onlinepca/meta.yaml
  recipes/r-pdsce/bld.bat
  recipes/r-pdsce/build.sh
  recipes/r-pdsce/meta.yaml
  recipes/r-pgenlibr/bld.bat
  recipes/r-pgenlibr/build.sh
  recipes/r-pgenlibr/meta.yaml
  recipes/r-pqlseq/bld.bat
  recipes/r-pqlseq/build.sh
  recipes/r-pqlseq/meta.yaml
Labels: R, staged-recipes, review-requested

#29704 Added variable_inspector as a package
  recipes/variable_inspector/recipe.yaml
Labels: review-requested, python

#29695 Add sortedcontainers-stubs
  recipes/sortedcontainers-stubs/meta.yaml
Labels: staged-recipes, review-requested, python

#29712 Add google-cloud-ndb
  recipes/google-cloud-ndb/meta.yaml
Labels: review-requested, python

#29715 Adding pyplaces
  recipes/pyplaces/meta.yaml
Labels: staged-recipes, review-requested, python

#29636 Adding rb-bigdecimal.
  recipes/rb-bigdecimal/LICENSE
  recipes/rb-bigdecimal/conda_build_config.yaml
  recipes/rb-bigdecimal/meta.yaml
Labels: R, review-requested, ruby

#29718 Add recipe for ctapipe_io_zfits
  recipes/ctapipe_io_zfits/meta.yaml
Labels: review-requested, python

#29733 add `langfuse-python`
  recipes/langfuse-python/recipe.yaml
Labels: review-requested, python

#29731 Add pretab
  recipes/pretab/meta.yaml
Labels: staged-recipes, review-requested, python

#29528 Add maoto_agent
  recipes/maoto_agent/meta.yaml
Labels: review-requested, python

#29720 Add recipe for xarray-enmap
  recipes/xarray-enmap/meta.yaml
Labels: review-requested, python

#29729 Add verilator-python
  recipes/verilator-python/recipe.yaml
Labels: review-requested, python

#29737 Add abqpy
  recipes/abqpy/meta.yaml
Labels: review-requested, python

#29738 Add python package flickrhistory
  recipes/flickrhistory/meta.yaml
Labels: review-requested, python

#27546 NEW: Add recipe for libnvimgcodec
  recipes/libnvimgcodec/bld.bat
  recipes/libnvimgcodec/build.sh
  recipes/libnvimgcodec/meta.yaml
  recipes/libnvimgcodec/patches/0001-BLD-Use-only-dynamic-shared-library-links-to-CUDA-ta.patch
  recipes/libnvimgcodec/patches/0002-BLD-Move-CMake-config-install-directory.patch
  recipes/libnvimgcodec/test/CMakeLists.txt
  recipes/libnvimgcodec/test/all_headers.c
  recipes/libnvimgcodec/test/all_headers.cxx
  recipes/nvimgcodec/bld.bat
  recipes/nvimgcodec/build.sh
  recipes/nvimgcodec/meta.yaml
  recipes/nvimgcodec/patches/0001-BLD-Use-only-dynamic-shared-library-links-to-CUDA-ta.patch
  recipes/nvimgcodec/patches/0002-BLD-Move-CMake-config-install-directory.patch
Labels: review-requested, c-cpp

#29741 Add ilpy
  recipes/ilpy/meta.yaml
Labels: review-requested, python

#29740 feat: add diffstarpop
  recipes/diffstarpop/recipe.yaml
Labels: review-requested, python

#29744 Add `casacpp`: C++ libraries for CASA
  recipes/casacpp/build.sh
  recipes/casacpp/meta.yaml
  recipes/casacpp/versioning.patch
Labels: staged-recipes, review-requested, c-cpp

#29743 added recipe for `panoptica`
  recipes/panoptica/meta.yaml
Labels: review-requested, python

#29758 fix: remove lint for maintainer teams
  .github/workflows/scripts/linter.py
Labels: maintenance, staged-recipes, review-requested

#29678 Add rbloom
  recipes/rbloom/meta.yaml
Labels: review-requested, python-c

#29755 Add infomeasure recipe
  recipes/infomeasure/meta.yaml
Labels: review-requested, python

#29746 add Motile
  recipes/motile/meta.yaml
Labels: review-requested, python

#29641 Add roboverse-py with rootutils
  recipes/roboverse-py/meta.yaml
  recipes/rootutils/meta.yaml
Labels: review-requested, python

#29753 Add recipe for `smallestai`
  recipes/smallestai/meta.yaml
Labels: staged-recipes, review-requested, python

#29725 Add pds.peppi
  recipes/pds.peppi/meta.yaml
Labels: review-requested, python

#29248 Adding OpenFOAM
  recipes/openfoam/build.sh
  recipes/openfoam/meta.yaml
  recipes/openfoam/openfoam_activate.sh
  recipes/openfoam/openfoam_deactivate.sh
Labels: review-requested, c-cpp

#29616 Add xatlas-python
  recipes/xatlas-python/meta.yaml
Labels: review-requested, python-c

#29587 Add rawpy
  recipes/rawpy/bld.bat
  recipes/rawpy/build.sh
  recipes/rawpy/meta.yaml
  recipes/rawpy/patches/0001-Fix-include-path.patch
Labels: review-requested, python-c

#29752 add codex
  recipes/codex/build.sh
  recipes/codex/recipe.yaml
Labels: nodejs, review-requested

#29627 Add the recipe for the robotic vizualizer Candlewick
  recipes/candlewick/bld.bat
  recipes/candlewick/build.sh
  recipes/candlewick/meta.yaml
Labels: review-requested, c-cpp

#29750 Add casaconfig, a support package for the CASA analysis suite
  recipes/casaconfig/build.sh
  recipes/casaconfig/datadirs.patch
  recipes/casaconfig/meta.yaml
  recipes/casaconfig/run_test.py
Labels: review-requested, python-c

#29513 add OpenOrbitalOptimizer
  recipes/intxx/0001-windows-adaptations.patch
  recipes/intxx/bld.bat
  recipes/intxx/build.sh
  recipes/intxx/conda_build_config.yaml
  recipes/intxx/meta.yaml
  recipes/ooo/bld-cxx.bat
  recipes/ooo/build-cxx.sh
  recipes/ooo/conda_build_config.yaml
  recipes/ooo/meta.yaml
  recipes/ooo/tests/CMakeLists.txt
Labels: review-requested, c-cpp

#29680 Add xtcocotools
  recipes/xtcocotools/meta.yaml
Labels: review-requested, python-c

#29757 fix: move staged-recipes creation scripts to admin-requests
  .github/workflows/create_feedstocks.yml
  .github/workflows/scripts/create_feedstocks
  .github/workflows/scripts/create_feedstocks.py
Labels: maintenance

#29739 Adding superpunto
  recipes/superpunto/meta.yaml
Labels: review-requested, c-cpp

#29723 Add Tree sitter yaml
  recipes/tree-sitter-yaml/recipe.yaml
Labels: review-requested, python-c

#29721 Add Tree sitter c sharp
  recipes/tree-sitter-c-sharp/recipe.yaml
Labels: review-requested, python-c

#29722 Add Tree sitter embedded template
  recipes/tree-sitter-embedded-template/recipe.yaml
Labels: review-requested, python-c

#29768 add uv-build
  recipes/uv-build/bld.bat
  recipes/uv-build/build.sh
  recipes/uv-build/conda-forge.yml
  recipes/uv-build/meta.yaml
Labels: review-requested, python

#28817 Add winloop package
  recipes/winloop/meta.yaml
Labels: review-requested, python-c

#28774 add pbcuda
  recipes/pbcuda/meta.yaml
Labels: review-requested, python-c

#29774 Add func-adl-xAOD
  recipes/func-adl-xAOD/LICENSE
  recipes/func-adl-xAOD/recipe.yaml
Labels: review-requested, python

#29783 Add jsonformatter
  recipes/jsonformatter/recipe.yaml
  recipes/jsonformatter/testing/logger_config.ini
Labels: review-requested, python

#29785 Add libgravatar
  recipes/libgravatar/recipe.yaml
Labels: review-requested, python

#29781 Add testscenarios
  recipes/testscenarios/recipe.yaml
  recipes/testscenarios/remove-fix-tests.patch
Labels: review-requested, python

#29779 Add flask-paranoid
  recipes/flask-paranoid/recipe.yaml
Labels: review-requested, python

#29784 Add azure-mgmt-rdbms
  recipes/azure-mgmt-rdbms/recipe.yaml
Labels: review-requested, python

#29772 feat: add rustac from pypi via grayskull
  recipes/rustac/meta.yaml
Labels: review-requested, python

#29777 Adding csp-bot-commands
  recipes/csp-bot-commands/recipe.yaml
Labels: review-requested, python

#29788 Add satchip package
  recipes/satchip/meta.yaml
Labels: review-requested, python

#29789 add jsonschema-rs 0.30.0
  recipes/jsonschema-rs/recipe.yaml
Labels: R, review-requested, python, rust

#29466 Add dayplot & morethemes
  recipes/dayplot/recipe.yaml
  recipes/morethemes/recipe.yaml
Labels: review-requested, python

#29485 Adding trame-vtklocal recipes for conda-forge
  recipes/trame-vtklocal/meta.yaml
Labels: staged-recipes, review-requested, python

#29802 Add LiberTEM-holo
  recipes/libertem-holo/meta.yaml
Labels: review-requested, python

#29787 add cjdk
  recipes/cjdk/meta.yaml
Labels: review-requested, python

#29790 Add bioio
  recipes/bioio/recipe.yaml
Labels: review-requested, python

#29812 Add `mountainsort5`
  recipes/mountainsort5/meta.yaml
Labels: review-requested, python

#29820 Add mpython-core
  recipes/mpython-core/meta.yaml
Labels: review-requested, python

#29824 Add ParaView-Trame-Components
  recipes/paraview-trame-components/meta.yaml
Labels: review-requested, python

#29828 Add svcs
  recipes/svcs/meta.yaml
Labels: review-requested, python

#29823 Add `larixite` package
  recipes/larixite/meta.yaml
Labels: staged-recipes, review-requested, python

#29830 add noaa-cdo-api
  recipes/noaa-cdo-api/meta.yaml
Labels: review-requested, python

#24774 add kessler
  recipes/kessler/meta.yaml
Labels: Awaiting author contribution, python

#29836 Adds recipe for the "genericache" package (already in pypi)
  recipes/genericache/meta.yaml
Labels: review-requested, python

#29834 feat: add mt2 pypi package
  recipes/mt2/meta.yaml
Labels: review-requested, python

#29799 Add New recipe : pdf-reports
  recipes/pdf-reports/meta.yaml
Labels: staged-recipes, review-requested

#29525 add r-easy.utils
  recipes/r-easy.utils/bld.bat
  recipes/r-easy.utils/build.sh
  recipes/r-easy.utils/meta.yaml
Labels: R, review-requested

#29837 add cacts
  recipes/cacts/license
  recipes/cacts/meta.yaml
Labels: review-requested, python

#29638 Adding `fed-rag` recipe
  recipes/fed-rag/meta.yaml
Labels: staged-recipes, review-requested, python

#29841 Add python-workflow-definition
  recipes/python-workflow-definition/LICENSE
  recipes/python-workflow-definition/meta.yaml
  recipes/python-workflow-definition/pyproject.patch
Labels: staged-recipes, review-requested, python

#29839 Add redis-logs recipe
  recipes/redis-logs/meta.yaml
Labels: review-requested, python

#29831 New recipe for cdsetool
  recipes/cdsetool/meta.yaml
Labels: review-requested, python

#29514 add hdf5r.extra using grayskull-cran
  recipes/r-hdf5r.extra/bld.bat
  recipes/r-hdf5r.extra/build.sh
  recipes/r-hdf5r.extra/meta.yaml
Labels: R, review-requested

#29844 add trame-common from PyPI
  recipes/trame-common/meta.yaml
Labels: review-requested, python

#29842 Adding Python package cartogram
  recipes/cartogram/meta.yaml
Labels: review-requested, python

#29049 Add Recipe r-lasr
  recipes/r-lasr/build.sh
  recipes/r-lasr/meta.yaml
Labels: R, review-requested

#29751 Add tinkr
  recipes/r-tinkr/bld.bat
  recipes/r-tinkr/build.sh
  recipes/r-tinkr/meta.yaml
Labels: R, review-requested

#29822 Add robust-laplacian
  recipes/robust-laplacian/meta.yaml
Labels: review-requested, python-c

#29766 Add pysdf
  recipes/pysdf/meta.yaml
Labels: review-requested, python-c

#29724 Add Tree sitter language pack
  recipes/tree-sitter-language-pack/patches/comment-out-manylinux.patch
  recipes/tree-sitter-language-pack/recipe.yaml
Labels: review-requested, python-c

#29851 Adding libmodplug
  recipes/libmodplug/001-fix-non-const-stack-alloc.patch
  recipes/libmodplug/002-fix-dll-export-mismatch.patch
  recipes/libmodplug/CMakeLists.txt
  recipes/libmodplug/build.bat
  recipes/libmodplug/build.sh
  recipes/libmodplug/recipe.yaml
Labels: review-requested, c-cpp

#29762 Add `casatools` and `casatasks`, pieces of the CASA suite
  recipes/casatasks/build.sh
  recipes/casatasks/meta.yaml
  recipes/casatasks/versioning.patch
  recipes/casatools/build.sh
  recipes/casatools/macos-not-gcc.patch
  recipes/casatools/meta.yaml
Labels: review-requested, python-c

#29846 added jsonspice recipe
  recipes/jsonspice/meta.yaml
Labels: review-requested, python

#29852 add splunk_opentelemetry
  recipes/splunk-opentelemetry/meta.yaml
Labels: review-requested, python

#29854 Add recipe for docstrfmt python package
  recipes/docstrfmt/meta.yaml
Labels: review-requested, python
