Repository conda-forge/staged-recipes, pull requests merged in 2025-08, with the labels that each got.

#30697 Add karney
  recipes/karney/meta.yaml
Labels: review-requested, python

#30693 Adding `tom-tns`
  recipes/tom-tns/meta.yaml
Labels: review-requested, python

#30461 paktxt: Add version 1.0.0
  recipes/paktxt/recipe.yaml
Labels: review-requested, go

#30459 Add secretinit v1.0.0
  recipes/secretinit/recipe.yaml
Labels: review-requested, go

#30707 Add the quak package
  recipes/quak/meta.yaml
Labels: review-requested, python

#30712 Add fairical Python package
  recipes/fairical/recipe.yaml
Labels: review-requested, python

#30665 add py-videodev2 recipe
  recipes/py-videodev2/LICENSE
  recipes/py-videodev2/recipe.yaml
Labels: staged-recipes, review-requested, python-c

#30717 Adding vidigi recipe
  recipes/vidigi/meta.yaml
Labels: review-requested, python

#27550 Add wrapspawner
  recipes/wrapspawner/meta.yaml
Labels: review-requested, python

#30720 Package anychange
  recipes/anychange/recipe.yaml
Labels: review-requested, python

#30678 add pixi-build-mojo recipe
  recipes/pixi-build-mojo/recipe.yaml
Labels: R, review-requested, rust

#30710 Add PLAnT (`plant`) to conda-forge
  recipes/plant/meta.yaml
Labels: review-requested, python

#30663 add font-ttf-opensans font
  recipes/font-ttf-opensans/recipe.yaml
Labels: staged-recipes, review-requested

#30731 Add package fps-file-watcher
  recipes/fps-file-watcher/recipe.yaml
Labels: review-requested, python

#30736 Add recipe for xdg-dbus-proxy
  recipes/xdg-dbus-proxy/recipe.yaml
Labels: staged-recipes, review-requested, c-cpp

#30705 Add excel-mcp-server
  recipes/excel-mcp-server/patches/fix-package-location.patch
  recipes/excel-mcp-server/recipe.yaml
Labels: review-requested, python

#30723 Add crush
  recipes/crush/recipe.yaml
Labels: review-requested, go

#30733 Add PhySO package
  recipes/physo/meta.yaml
Labels: review-requested, python

#30744 Add python-cvmfsutils package
  recipes/python-cvmfsutils/40.patch
  recipes/python-cvmfsutils/recipe.yaml
Labels: review-requested, python

#30750 pathfinder2e_stats
  recipes/pathfinder2e-stats/meta.yaml
Labels: review-requested, python

#30754 Add Oracle Instant Client Basic Lite package
  recipes/instantclient-basiclite/recipe.yaml
Labels: staged-recipes, review-requested

#30756 Add torchvista recipe
  recipes/torchvista/meta.yaml
Labels: staged-recipes, review-requested, python

#30755 Add: `pals-schema`
  recipes/pals-schema/recipe.yaml
Labels: review-requested, python

#30753 Adding pymaxspots
  recipes/pymaxspots/meta.yaml
Labels: review-requested, python

#30008 Create AM3 package
  recipes/am3/meta.yaml
Labels: review-requested, c-cpp, python

#30758 add linkml 1.9.3 and dependencies
  recipes/jsonasobj2/recipe.yaml
  recipes/linkml-runtime/recipe.yaml
  recipes/linkml/recipe.yaml
  recipes/linkml/run_test.py
  recipes/prefixcommons/0000-no-pytest-logging.patch
  recipes/prefixcommons/recipe.yaml
Labels: review-requested, python

#30764 Add lia-web
  recipes/lia-web/recipe.yaml
  recipes/lia-web/run_test.py
Labels: review-requested, python

#30759 add numpy-typing-compat
  recipes/numpy-typing-compat/recipe.yaml
Labels: review-requested, python

#30773 add `any-llm-sdk`
  recipes/any-llm-sdk/recipe.yaml
Labels: review-requested, python

#30786 Add mkdocs-drawio
  recipes/mkdocs-drawio/recipe.yaml
Labels: review-requested, python

#30779 add islp
  recipes/islp/meta.yaml
Labels: review-requested, python

#30789 Adding `delaynet` recipe
  recipes/delaynet/meta.yaml
Labels: review-requested, python

#30792 Adding lintquarto to conda-forge
  recipes/lintquarto/meta.yaml
Labels: staged-recipes, review-requested, python

#30766 Add citation-compass
  recipes/citation-compass/meta.yaml
Labels: review-requested, python

#30794 Add recipe for Optiland
  recipes/optiland/meta.yaml
Labels: review-requested, python

#30598 Add monitors4codegen 0.0.1 recipe
  recipes/monitors4codegen/meta.yaml
Labels: staged-recipes, review-requested, python

#30822 Add recipe for samply
  recipes/samply/recipe.yaml
Labels: R, review-requested, rust

#29689 Add recipe for omnicloudmask
  recipes/omnicloudmask/meta.yaml
Labels: review-requested, python

#30826 Add qgridnext Python package
  recipes/qgridnext/meta.yaml
Labels: review-requested, python

#30781 Add dask-iclx
  recipes/dask-iclx/meta.yaml
Labels: staged-recipes, review-requested, python

#30797 Add supabase-auth, supabase-functions
  recipes/supabase-auth/recipe.yaml
  recipes/supabase-functions/recipe.yaml
Labels: review-requested, python

#30842 Adding hypertransform
  recipes/hypertransform/meta.yaml
Labels: staged-recipes, review-requested, python

#30823 add libtommath
  recipes/libtommath/recipe.yaml
Labels: review-requested, c-cpp

#30844 Add healpix-geo
  recipes/healpix-geo/recipe.yaml
Labels: R, review-requested, rust

#30551 add recipe for python package flyr
  recipes/flyr/meta.yaml
Labels: review-requested, python

#30569 Adding temporalio
  recipes/temporalio/meta.yaml
Labels: R, review-requested, python, rust

#30748 Add mapchete-eo 2025.8.1 recipe
  recipes/mapchete-eo/meta.yaml
Labels: staged-recipes, review-requested, python

#30856 Add Forte2 recipe
  recipes/forte2/build.sh
  recipes/forte2/meta.yaml
Labels: staged-recipes, review-requested

#30833 Adding virteng package
  recipes/virteng/meta.yaml
Labels: review-requested, python

#30859 Add create-forwarder-dll
  recipes/create-forwarder-dll/conda-forge.yml
  recipes/create-forwarder-dll/meta.yaml
Labels: review-requested, python

#23901 Add rapidgzip
  recipes/rapidgzip/conda_build_config.yaml
  recipes/rapidgzip/meta.yaml
Labels: staged-recipes, review-requested, python-c

#30867 Avoid misfiring labels
  .github/workflows/automate-review-labels.yml
Labels: maintenance, R, review-requested, rust

#30860 Add recipe for gifski version 1.34.0
  recipes/gifski/recipe.yaml
Labels: R, review-requested, rust

#30829 Added maptide recipe
  recipes/maptide/meta.yaml
Labels: review-requested, python

#30871 Added dashlab as a package
  recipes/dashlab/recipe.yaml
Labels: review-requested, python

#30866 Adding bahamas
  recipes/bahamas/meta.yaml
Labels: staged-recipes, review-requested, python

#30521 Adding `komplot`
  recipes/komplot/meta.yaml
Labels: staged-recipes, review-requested, python

#30799 Add composio-client
  recipes/composio-client/meta.yaml
  recipes/composio-openai/LICENSE
  recipes/composio-openai/meta.yaml
  recipes/composio/LICENSE
  recipes/composio/meta.yaml
Labels: staged-recipes, review-requested, python

#30868 Add mkdocs-exporter
  recipes/mkdocs-exporter/recipe.yaml
Labels: review-requested, python

#30876 Add EnFROSP
  recipes/enfrosp/meta.yaml
Labels: review-requested, python

#30877 Add fmodpy
  recipes/fmodpy/recipe.yaml
Labels: review-requested, python

#30646 Add `torchao`
  recipes/torchao/build.sh
  recipes/torchao/conda_build_config.yaml
  recipes/torchao/recipe.yaml
Labels: review-requested, python-c

#30880 add cppcheck-codequality
  recipes/cppcheck-codequality/recipe.yaml
Labels: review-requested, python

#30881 Adding pythtb
  recipes/pythtb/meta.yaml
Labels: staged-recipes, review-requested, python

#30837 New feedstock for lm-sensors - ready for review
  recipes/lm-sensors/build.sh
  recipes/lm-sensors/meta.yaml
Labels: review-requested, c-cpp

#30891 Add mkdocs-section-index to conda-forge
  recipes/mkdocs-section-index/meta.yaml
Labels: review-requested, python

#30806 Initial libssr
  recipes/libssr-py/meta.yaml
Labels: review-requested, python

#30892 Add shs-cxi-drivers recipe
  recipes/shs-cxi-driver/build.sh
  recipes/shs-cxi-driver/recipe.yaml
Labels: review-requested, c-cpp

#30905 Add recipe for pure python package vcs2l
  recipes/vcs2l/recipe.yaml
Labels: staged-recipes, review-requested, python

#30896 Add universal-mcp-markitdown
  recipes/universal-mcp-markitdown/recipe.yaml
Labels: review-requested, python

#30883 Add redis-om recipe
  recipes/redis-om/include-redis_om-package.patch
  recipes/redis-om/python-ulid-version-upper-bound.patch
  recipes/redis-om/recipe.yaml
Labels: review-requested, python

#30908 Add lsapy package
  recipes/lsapy/meta.yaml
Labels: review-requested, python

#30912 add mathics_pygments
  recipes/mathics_pygments/meta.yaml
Labels: review-requested, python

#30916 Add Columnize package
  recipes/columnize/meta.yaml
Labels: review-requested, python
