Repository conda-forge/staged-recipes, pull requests merged in 2025-01, with the labels that each got.

#25438 Sortmerna conda recipe
  recipes/sortmerna/LICENSE.LESSER.txt
  recipes/sortmerna/LICENSE.txt
  recipes/sortmerna/RocksDB.LICENSE.Apache
  recipes/sortmerna/ZLib.LICENSE
  recipes/sortmerna/bld.bat
  recipes/sortmerna/build.sh
  recipes/sortmerna/conda_build_config.yaml
  recipes/sortmerna/meta.yaml
Labels: review-requested, python-c

#28673 Add libplacebo
  recipes/libplacebo/build.sh
  recipes/libplacebo/recipe.yaml
Labels: review-requested, c-cpp

#28690 add apswutils
  recipes/apswutils/meta.yaml
Labels: review-requested, python

#28733 Add better-optimize
  recipes/better-optimize/meta.yaml
Labels: review-requested, python

#28736 Add minio-client
  recipes/minio-client/manual-licenses/github.com/minio/colorjson/UNLICENSE
  recipes/minio-client/manual-licenses/github.com/minio/filepath/UNLICENSE
  recipes/minio-client/recipe.yaml
Labels: review-requested, go

#28732 Add subfinder
  recipes/subfinder/recipe.yaml
Labels: review-requested, go

#28433 Add recipe for mattersim
  recipes/mattersim/meta.yaml
Labels: review-requested, python

#28197 Add Fortuno unit testing framework
  recipes/fortuno/build.sh
  recipes/fortuno/conda_build_config.yaml
  recipes/fortuno/meta.yaml
  recipes/fortuno/run_test.sh
Labels: Awaiting author contribution, staged-recipes, c-cpp

#28678 Add Posting
  recipes/posting/change-xdg-package-name.patch
  recipes/posting/recipe.yaml
Labels: review-requested, python

#28602 perl-autovivification
  recipes/perl-autovivification/meta.yaml
Labels: staged-recipes, review-requested, perl

#28604 perl-business-issn
  recipes/perl-business-issn/meta.yaml
Labels: staged-recipes, review-requested, perl

#28652 Added moka-py as a package
  recipes/moka-py/meta.yaml
Labels: R, review-requested, python, rust

#28716 Add a2wsgi for BentoML Feedstock
  recipes/a2wsgi/meta.yaml
Labels: review-requested, python

#28723 Add recipe for google-cloud-alloydb
  recipes/google-cloud-alloydb/meta.yaml
Labels: review-requested, python

#28717 add jupyterlite-pyodide-lock
  recipes/jupyterlite-pyodide-lock/conda_build_config.yaml
  recipes/jupyterlite-pyodide-lock/meta.yaml
Labels: staged-recipes, review-requested, python

#28707 Package asphalt-redis
  recipes/asphalt-redis/meta.yaml
Labels: review-requested, python

#28708 Package asphalt-mailer
  recipes/asphalt-mailer/meta.yaml
Labels: review-requested, python

#28710 Package asphalt-templating
  recipes/asphalt-templating/meta.yaml
Labels: review-requested, python

#28709 Package asphalt-exceptions
  recipes/asphalt-exceptions/meta.yaml
Labels: review-requested, python

#28711 Package asphalt-py4j
  recipes/asphalt-py4j/meta.yaml
Labels: review-requested, python

#28675 Add sphinx-parser to conda
  recipes/sphinx_parser/meta.yaml
Labels: review-requested, python

#28706 Package asphalt-serialization
  recipes/asphalt-serialization/meta.yaml
Labels: review-requested, python

#28712 Package asphalt-mongodb
  recipes/asphalt-mongodb/meta.yaml
Labels: review-requested, python

#28642 Add recipy for xcube-zenodo
  recipes/xcube-zenodo/meta.yaml
Labels: staged-recipes, review-requested, python

#28754 Add ema-pytorch
  recipes/ema-pytorch/meta.yaml
Labels: review-requested, python

#28755 Add torch-tb-profiler
  recipes/torch-tb-profiler/meta.yaml
Labels: review-requested, python

#24053 Add topfarm
  recipes/topfarm/meta.yaml
Labels: review-requested, python

#28752 Add pyexr
  recipes/pyexr/meta.yaml
Labels: review-requested, python

#28768 Add ndjson
  recipes/ndjson/meta.yaml
Labels: staged-recipes, review-requested, python

#28713 Adding package recipe for `Chartlets`
  recipes/chartlets/meta.yaml
Labels: review-requested, python

#28702 Added browserforge as a package
  recipes/browserforge/meta.yaml
Labels: review-requested, python

#28747 Add qiskit-sphinx-theme
  recipes/qiskit-sphinx-theme/meta.yaml
Labels: review-requested, python

#28725 Add precision-recall-gain package
  recipes/precision-recall-gain/meta.yaml
Labels: review-requested, python

#28743 Add python-abi3
  recipes/python-abi3/LICENSE.txt
  recipes/python-abi3/bld.bat
  recipes/python-abi3/build.sh
  recipes/python-abi3/conda-forge.yml
  recipes/python-abi3/conda_build_config.yaml
  recipes/python-abi3/example-meta.yaml
  recipes/python-abi3/meta.yaml
  recipes/python-abi3/scripts/activate.sh
  recipes/python-abi3/scripts/deactivate.sh
Labels: staged-recipes, review-requested

#28625 Add `marray-python` recipe
  recipes/marray-python/meta.yaml
Labels: review-requested, python

#28760 added paramak package
  recipes/paramak/meta.yaml
  recipes/paramak/yum_requirements.txt
Labels: review-requested, python

#28674 Add igwn-segments
  recipes/igwn-segments/meta.yaml
  recipes/igwn-segments/run_test.py
Labels: review-requested, python

#28703 Add recipe for thevenin package
  recipes/thevenin/meta.yaml
  recipes/thevenin/run_test.py
Labels: review-requested, python

#28777 add synspace
  recipes/synspace/recipe.yaml
Labels: review-requested, python

#28782 adding folktables
  recipes/folktables/meta.yaml
Labels: review-requested, python

#28784 Add ptufile
  recipes/ptufile/meta.yaml
Labels: staged-recipes, review-requested, python

#28757 Add elmfire
  recipes/elmfire/LICENSE.md
  recipes/elmfire/build.sh
  recipes/elmfire/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#28785 Add seamless-3dep
  recipes/seamless-3dep/meta.yaml
Labels: review-requested, python

#28786 Add `ngio` recipe from PyPI
  recipes/ngio/meta.yaml
Labels: review-requested, python

#28699 Add ochre and stransi
  recipes/ochre/recipe.yaml
  recipes/stransi/recipe.yaml
Labels: review-requested, python

#28788 add mplotutils python package
  recipes/mplotutils/meta.yaml
Labels: review-requested, python

#28783 Add phasorpy
  recipes/phasorpy/meta.yaml
Labels: review-requested, python

#28695 Add cuequivariance family
  recipes/cuequivariance-jax/meta.yaml
  recipes/cuequivariance-torch/meta.yaml
  recipes/cuequivariance/meta.yaml
Labels: review-requested, python

#28672 Adding cvat-sdk python package
  recipes/cvat-sdk/LICENSE
  recipes/cvat-sdk/meta.yaml
Labels: staged-recipes, review-requested, python

#28734 Package `xrlint` recipe added
  recipes/xrlint/meta.yaml
Labels: review-requested, python

#28683 Add repo2rocrate
  recipes/repo2rocrate/meta.yaml
Labels: review-requested, python

#28793 Add partial-json-parser
  recipes/partial-json-parser/meta.yaml
Labels: review-requested, python

#28799 Add xproj
  recipes/xproj/meta.yaml
Labels: review-requested, python

#28769 Adding shell package
  recipes/shell/recipe.yaml
Labels: review-requested, rust

#28810 add hatch-cpp
  recipes/hatch-cpp/meta.yaml
Labels: review-requested, python

#28811 Add fh-llm-client
  recipes/h-llm-client/meta.yaml
Labels: staged-recipes, review-requested, python

#28767 Adding gopass package
  recipes/gopass/meta.yaml
Labels: review-requested, go

#22293 Adding serialio_package
  recipes/serialio/LICENSE
  recipes/serialio/meta.yaml
Labels: review-requested, python

#28387 Adding Autogrid4 to conda-forge
  recipes/autogrid/build.sh
  recipes/autogrid/meta.yaml
Labels: review-requested, c-cpp

#28821 Add hyper-connections
  recipes/hyper-connections/meta.yaml
Labels: review-requested, python

#28796 Add cvat-cli for administrating computer vision annotation projects
  recipes/cvat-cli/LICENSE
  recipes/cvat-cli/meta.yaml
Labels: review-requested, python

#28809 Add airflow-common-operators
  recipes/airflow-common-operators/meta.yaml
Labels: review-requested, python

#28696 add autogen-agentchat
  recipes/autogen-agentchat/recipe.yaml
Labels: staged-recipes, review-requested, python

#28820 Add variconfig
  recipes/variconfig/meta.yaml
Labels: staged-recipes, review-requested, python

#28113 Initial recipe for toil
  recipes/toil/meta.yaml
Labels: review-requested, python

#28181 Add skelly_viewer
  recipes/skelly-viewer/conda-forge.yml
  recipes/skelly-viewer/meta.yaml
  recipes/skelly-viewer/yum_requirements.txt
Labels: review-requested, python

#28252 Add vsg
  recipes/vsg/conda-forge.yml
  recipes/vsg/meta.yaml
Labels: review-requested, python

#28822 Adding `deferrer`
  recipes/deferrer/meta.yaml
Labels: staged-recipes, review-requested

#28824 add ggeet and somacore
  recipes/gget/recipe.yaml
  recipes/somacore/recipe.yaml
Labels: review-requested, python

#28816 Adding geometamaker recipe
  recipes/geometamaker/meta.yaml
Labels: review-requested, python

#28679 Add AdaptiveCpp
  recipes/AdaptiveCpp/bld.bat
  recipes/AdaptiveCpp/build.sh
  recipes/AdaptiveCpp/conda_build_config.yaml
  recipes/AdaptiveCpp/meta.yaml
  recipes/AdaptiveCpp/patches/fallback-missing-functions.patch
  recipes/AdaptiveCpp/run_test.bat
  recipes/AdaptiveCpp/run_test.sh
  recipes/AdaptiveCpp/tests/CMakeLists.txt
  recipes/AdaptiveCpp/tests/main.cpp
Labels: review-requested, c-cpp

#28813 New receipt/ai traineree
  recipes/ai-traineree/meta.yaml
Labels: review-requested, python

#28830 [MNT] Support `TARGET_ARCH` for local osx build
  .scripts/run_osx_build.sh
Labels: maintenance

#28832 Add hbreader
  recipes/hbreader/meta.yaml
Labels: review-requested, python

#28739 ADD: emd-signal
  recipes/emd-signal/meta.yaml
Labels: review-requested, python

#28792 Adding PyMUST to conda
  recipes/pymust/meta.yaml
Labels: review-requested, python

#28781 add easysnowdata package
  recipes/easysnowdata/meta.yaml
Labels: review-requested, python

#28835 Add recipe for conda-spawn
  recipes/conda-spawn/meta.yaml
Labels: staged-recipes, review-requested, python

#28823 Add hffix
  recipes/hffix/bld.bat
  recipes/hffix/build.sh
  recipes/hffix/conda-forge.yml
  recipes/hffix/meta.yaml
  recipes/hffix/ssize_t_win.diff
Labels: staged-recipes, review-requested

#28839 Add recipe for sagemaker-core
  recipes/sagemaker-core/meta.yaml
Labels: review-requested, python

#28844 Add distmetrics
  recipes/distmetrics/meta.yaml
Labels: review-requested, python

#28841 Add dist_s1_enumerator
  recipes/dist_s1_enumerator/meta.yaml
Labels: review-requested, python

#28556 Add py-crude-resource-monitor
  recipes/py-crude-resource-monitor/0001-pnpm-bat.patch
  recipes/py-crude-resource-monitor/build.bat
  recipes/py-crude-resource-monitor/build.sh
  recipes/py-crude-resource-monitor/recipe.yaml
Labels: R, review-requested, rust

#28778 Add compressed-tensors
  recipes/compressed-tensors/meta.yaml
Labels: review-requested, python

#28794 NEW: Add cf-nvidia-tools
  recipes/cf-nvidia-tools/LICENSE
  recipes/cf-nvidia-tools/README.md
  recipes/cf-nvidia-tools/bin/check-glibc
  recipes/cf-nvidia-tools/recipe.yaml
Labels: staged-recipes, review-requested

#28749 New recipe for geomodels
  recipes/geomodels/meta.yaml
Labels: review-requested, python

#28806 Add presidio-evaluator package
  recipes/presidio-evaluator/meta.yaml
Labels: review-requested, python

#28856 Add ipython_pygments_lexers
  recipes/ipython_pygments_lexers/meta.yaml
Labels: review-requested, python

#28858 Add notebook-intelligence
  recipes/notebook_intelligence/meta.yaml
Labels: staged-recipes, review-requested, python

#28861 Add airportsdata
  recipes/airportsdata/meta.yaml
Labels: review-requested, python

#28862 add ndv package
  recipes/ndv/meta.yaml
Labels: review-requested, python

#28851 add feedrattler
  recipes/feedrattler/recipe.yaml
Labels: review-requested, python

#28857 Add recipe for playground PyPI package
  recipes/playground/meta.yaml
Labels: review-requested, python

#28865 Add depyf
  recipes/depyf/meta.yaml
Labels: review-requested, python

#28868 Add hiyapyco
  recipes/hiyapyco/recipe.yaml
Labels: review-requested, python

#28863 Outlines core
  recipes/outlines-core/recipe.yaml
Labels: R, review-requested, rust

#28779 Add pytest-textual-snapshot
  recipes/pytest-textual-snapshot/meta.yaml
  recipes/pytest-textual-snapshot/test.py
Labels: review-requested, python

#28875 add autogen-core
  recipes/autogen-core/recipe.yaml
Labels: staged-recipes, review-requested, python

#24702 ✨ Add calcam package
  recipes/calcam/recipe.yaml
Labels: review-requested, python

#28859 Add chart-testing
  recipes/chart-testing/activate.bat
  recipes/chart-testing/activate.sh
  recipes/chart-testing/conda_build_config.yaml
  recipes/chart-testing/meta.yaml
Labels: review-requested, go

#28828 add tiledbsoma
  recipes/tiledbsoma/fix-lib-build.patch
  recipes/tiledbsoma/recipe.yaml
Labels: review-requested, c-cpp, python-c

#28826 Add krew
  recipes/krew/conda_build_config.yaml
  recipes/krew/meta.yaml
Labels: staged-recipes, review-requested, go

#27982 Arborx recipe
  recipes/arborx/bld.bat
  recipes/arborx/build.sh
  recipes/arborx/findcuda.patch
  recipes/arborx/meta.yaml
Labels: review-requested, c-cpp

#28838 add sqlite_zstd_vfs package
  recipes/sqlite_zstd_vfs/build.sh
  recipes/sqlite_zstd_vfs/meta.yaml
  recipes/sqlite_zstd_vfs/update.diff
Labels: review-requested, c-cpp

#28676 Pypalettes
  recipes/pypalettes/recipe.yaml
Labels: review-requested, python

#28880 Add igwn-ligolw
  recipes/igwn-ligolw/meta.yaml
Labels: review-requested, python

#28825 add cellxgene-census
  recipes/cellxgene-census/fix-deps.patch
  recipes/cellxgene-census/recipe.yaml
Labels: review-requested, python

#28893 Add lbCta
  recipes/lbcta/recipe.yaml
Labels: staged-recipes, review-requested

#28890 Add `canonicaljson` package
  recipes/canonicaljson/meta.yaml
Labels: staged-recipes, review-requested, python

#28894 add id 1.5.0
  recipes/id/recipe.yaml
Labels: review-requested, python

#28787 Add Bagels
  recipes/bagels/change-xdg-package-name.patch
  recipes/bagels/recipe.yaml
Labels: review-requested, python

#25198 Add recipe for xrst (extract rst files and run sphinx)
  recipes/xrst/meta.yaml
  recipes/xrst/run_test.py
Labels: review-requested, python

#28871 add quantity-array recipe
  recipes/quantity-array/recipe.yaml
Labels: review-requested, python

#28892 add pytopocomplexity package
  recipes/pytopocomplexity/meta.yaml
Labels: review-requested, python

#28666 Add aerc package
  recipes/aerc/conda_build_config.yaml
  recipes/aerc/recipe.yaml
Labels: staged-recipes, review-requested, go

#28842 Adding cherab
  recipes/cherab/recipe.yaml
Labels: review-requested, python-c

#28730 Add VulkanSceneGraph and vsgXchange
  recipes/VulkanSceneGraph/bld.bat
  recipes/VulkanSceneGraph/build.sh
  recipes/VulkanSceneGraph/meta.yaml
  recipes/VulkanSceneGraph/patches/ignore-vulkan-version.patch
  recipes/vsgXchange/bld.bat
  recipes/vsgXchange/build.sh
  recipes/vsgXchange/meta.yaml
  recipes/vsgXchange/run_test.bat
  recipes/vsgXchange/run_test.sh
  recipes/vsgXchange/tests/CMakeLists.txt
  recipes/vsgXchange/tests/main.cpp
Labels: review-requested, c-cpp

#28763 Add implot
  recipes/implot/CMakeLists.txt
  recipes/implot/bld.bat
  recipes/implot/build.sh
  recipes/implot/meta.yaml
  recipes/implot/run_test.bat
  recipes/implot/run_test.sh
  recipes/implot/tests/CMakeLists.txt
  recipes/implot/tests/main.cpp
Labels: review-requested, c-cpp

#28663 Add ndcurves
  recipes/ndcurves/LICENSE
  recipes/ndcurves/build_ndcurves.bat
  recipes/ndcurves/build_ndcurves.sh
  recipes/ndcurves/build_ndcurves_python.bat
  recipes/ndcurves/build_ndcurves_python.sh
  recipes/ndcurves/conda_build_config.yaml
  recipes/ndcurves/meta.yaml
  recipes/ndcurves/patches/0001-cmake-Fix-Windows-build.patch
  recipes/ndcurves/patches/0002-cmake-Don-t-link-with-all-pinocchio.patch
Labels: Awaiting author contribution, staged-recipes, c-cpp

#28795 Add a recipe for swan (https://swanmodel.sourceforge.io/)
  recipes/swan/build.sh
  recipes/swan/recipe.yaml
Labels: review-requested, c-cpp

#28684 Adding faster-coco-eval
  recipes/faster-coco-eval/meta.yaml
Labels: review-requested, python-c

#28756 Add pillow-avif-plugin
  recipes/pillow-avif-plugin/meta.yaml
Labels: review-requested, python-c

#28700 Added pybmoore as a package
  recipes/pybmoore/meta.yaml
Labels: review-requested, python-c

#28751 Add pillow-heif
  recipes/pillow-heif/meta.yaml
Labels: review-requested, python-c

#28587 add aurelia-cli, framework7-cli, preact-cli, pwa-builder
  recipes/aurelia-cli/build.sh
  recipes/aurelia-cli/meta.yaml
  recipes/framework7-cli/build.sh
  recipes/framework7-cli/meta.yaml
  recipes/preact-cli/LICENCE
  recipes/preact-cli/build.sh
  recipes/preact-cli/meta.yaml
  recipes/pwabuilder-cli/LICENSE.txt
  recipes/pwabuilder-cli/build.sh
  recipes/pwabuilder-cli/meta.yaml
Labels: nodejs, staged-recipes, review-requested

#28902 feat: Add pyhs3 recipe
  recipes/pyhs3/recipe.yaml
Labels: review-requested, python

#28899 add recipe MAPIT
  recipes/MAPIT/meta.yaml
Labels: review-requested, python

#28881 build: add autogam (Python package)
  recipes/autogam/meta.yaml
Labels: review-requested, python

#28720 Add YAPSS to conda-forge
  recipes/yapss/meta.yaml
Labels: staged-recipes, review-requested, python

#28726 Add a recipe for SU2
  recipes/su2/build.sh
  recipes/su2/meta.yaml
  recipes/su2/su2-meson.patch
Labels: review-requested, c-cpp

#28644 Add a recipe for openlb 1.7
  recipes/openlb/build.sh
  recipes/openlb/openlb-makefile.patch
  recipes/openlb/recipe.yaml
Labels: review-requested, c-cpp

#28895 Add `django-cryptography`, `django-dramatiq`, and `dramatiq-abort`.
  recipes/django-cryptography/meta.yaml
  recipes/django-dramatiq/meta.yaml
  recipes/dramatiq-abort/meta.yaml
Labels: review-requested, python

#28911 Move scipp to conda-forge
  recipes/scipp/LLNL_UNITS_LICENSE
  recipes/scipp/conda_build_config.yaml
  recipes/scipp/meta.yaml
Labels: review-requested, c-cpp

#28909 Add a recipe for Z3 Theorem Solver
  recipes/z3prover/build.sh
  recipes/z3prover/recipe.yaml
Labels: review-requested, c-cpp

#28925 fix: pygithub misses some unknown object exceptions
  .github/workflows/scripts/create_feedstocks.py
  .github/workflows/scripts/linter.py
Labels: maintenance

#28930 Add libnacl
  recipes/libnacl-python-bindings/recipe.yaml
Labels: review-requested, python

#28905 Adding R package `poolfstat` v3.0.0
  recipes/r-poolfstat/bld.bat
  recipes/r-poolfstat/build.sh
  recipes/r-poolfstat/meta.yaml
Labels: R, staged-recipes, review-requested

#28932 Add tensorizer
  recipes/tensorizer/recipe.yaml
Labels: review-requested, python

#28935 Add liffile package
  recipes/liffile/meta.yaml
Labels: review-requested, python

#28927 Adding prometheus-async
  recipes/prometheus-async/recipe.yaml
Labels: review-requested, python

#28926 Adding hf-transfer
  recipes/hf-transfer/001-cargo.patch
  recipes/hf-transfer/recipe.yaml
Labels: review-requested, python, python-c

#28928 Add `runiq`
  recipes/runiq/bld.bat
  recipes/runiq/build.sh
  recipes/runiq/meta.yaml
Labels: R, review-requested, rust

#28919 Add pispy-client
  recipes/pispy/recipe.yaml
Labels: review-requested, python

#28937 Add msgraph-sdk
  recipes/msgraph-sdk/meta.yaml
Labels: review-requested, python

#28936 Add r-geoarrow
  recipes/r-geoarrow/LICENSE.md
  recipes/r-geoarrow/bld.bat
  recipes/r-geoarrow/build.sh
  recipes/r-geoarrow/meta.yaml
Labels: R, review-requested

#28942 Add radar-api conda recipe
  recipes/radar-api/meta.yaml
Labels: review-requested, python

#28920 add `aichat`
  recipes/aichat/build.bat
  recipes/aichat/build.sh
  recipes/aichat/recipe.yaml
Labels: R, review-requested, rust

#28929 Add pixi-diff
  recipes/pixi-diff/build.bat
  recipes/pixi-diff/build.sh
  recipes/pixi-diff/recipe.yaml
Labels: R, review-requested, rust

#28939 Add skypilot
  recipes/skypilot/recipe.yaml
Labels: review-requested, python

#28948 Add Mathics-Scanner package
  recipes/Mathics-Scanner-feedstock/meta.yaml
Labels: review-requested, python
