Repository conda-forge/staged-recipes, pull requests merged in 2025-05, with the labels that each got.

#29661 add r-qrng, r-rcppclock, r-rferns, r-vcpen
  recipes/r-qrng/bld.bat
  recipes/r-qrng/build.sh
  recipes/r-qrng/meta.yaml
  recipes/r-rcppclock/bld.bat
  recipes/r-rcppclock/build.sh
  recipes/r-rcppclock/meta.yaml
  recipes/r-rferns/bld.bat
  recipes/r-rferns/build.sh
  recipes/r-rferns/meta.yaml
  recipes/r-vcpen/bld.bat
  recipes/r-vcpen/build.sh
  recipes/r-vcpen/meta.yaml
Labels: R, staged-recipes, review-requested

#29900 Add recipe for lib4sbom
  recipes/lib4sbom/recipe.yaml
Labels: review-requested, python

#29899 Add r-mockr
  recipes/r-mockr/bld.bat
  recipes/r-mockr/build.sh
  recipes/r-mockr/meta.yaml
Labels: R, review-requested

#29866 Add r-varnish
  recipes/r-varnish/bld.bat
  recipes/r-varnish/build.sh
  recipes/r-varnish/meta.yaml
Labels: R, review-requested

#29403 Add NVIDIA TransformerEngine
  recipes/transformer-engine/001-cmake.patch
  recipes/transformer-engine/activate.sh
  recipes/transformer-engine/build_te.sh
  recipes/transformer-engine/deactivate.sh
  recipes/transformer-engine/meta.yaml
Labels: review-requested, python-c

#29906 Add r-sandpaper
  recipes/r-sandpaper/add-lesson-example-to-config-template-source.patch
  recipes/r-sandpaper/bld.bat
  recipes/r-sandpaper/build.sh
  recipes/r-sandpaper/meta.yaml
Labels: R, review-requested

#29864 Add pgadmin4-python
  recipes/pgadmin4-python/build.bat
  recipes/pgadmin4-python/build.sh
  recipes/pgadmin4-python/building/build-functions.sh
  recipes/pgadmin4-python/building/generate_pyproject.py
  recipes/pgadmin4-python/patches/psycopg-requirements.txt.patch
  recipes/pgadmin4-python/patches/remove-pywinpty-requirements.txt.patch
  recipes/pgadmin4-python/patches/speaklater-requirements.txt.patch
  recipes/pgadmin4-python/recipe.yaml
  recipes/pgadmin4-python/testing/config_local.py
  recipes/pgadmin4-python/testing/pgadmin_test_utils.py
  recipes/pgadmin4-python/testing/run_complex_tests.py
  recipes/pgadmin4-python/testing/run_simple_pgadmin4.py
  recipes/pgadmin4-python/testing/run_simple_setup.py
  recipes/pgadmin4-python/testing/test_config.json
Labels: nodejs, review-requested, python

#29897 Create meta.yaml for advection package
  recipes/advection/meta.yaml
Labels: review-requested, python

#29826 Add figanos
  recipes/figanos/meta.yaml
Labels: review-requested, python

#29911 add ruamel-yaml-line-info 0.1.2
  recipes/ruamel-yaml-line-info/recipe.yaml
Labels: review-requested, python

#29908 add wis2downloader
  recipes/wis2downloader/meta.yaml
Labels: review-requested, python

#29135 Make build-locally.py executable
  build-locally.py
Labels: maintenance

#29792 Adding external-systems package
  recipes/external-systems/meta.yaml
Labels: review-requested, python

#29882 Add per4m
  recipes/per4m/LICENSE.txt
  recipes/per4m/meta.yaml
Labels: review-requested, python-c

#29915 Add curl-cffi
  recipes/curl-cffi/meta.yaml
Labels: staged-recipes, review-requested, python-c

#29912 add moyopy
  recipes/moyopy/LICENSE-MIT
  recipes/moyopy/meta.yaml
Labels: review-requested, python

#29878 Add recipe for apache-airflow-task-sdk
  recipes/apache-airflow-task-sdk/meta.yaml
Labels: review-requested, python

#29918 add `pylate`
  recipes/pylate/recipe.yaml
Labels: review-requested, python

#29923 New recipe for s1aux
  recipes/s1aux/meta.yaml
Labels: review-requested, python

#29845 Add package dranspose
  recipes/dranspose/meta.yaml
Labels: staged-recipes, review-requested, python

#29921 Recipe for Micromet meta.yaml
  recipes/micromet/meta.yaml
Labels: review-requested, python

#29926 add setuptools-reproducible
  recipes/setuptools_reproducible/meta.yaml
Labels: review-requested, python

#29934 Add xncml recipe
  recipes/xncml/meta.yaml
Labels: review-requested, python

#29941 Add `alibabacloud_credentials_api`
  recipes/alibabacloud_credentials_api/LICENSE
  recipes/alibabacloud_credentials_api/meta.yaml
Labels: review-requested, python

#29791 Adding pan3D
  recipes/pan3d/meta.yaml
Labels: review-requested, python

#29949 Add xmlhelpy
  recipes/xmlhelpy/meta.yaml
Labels: staged-recipes, review-requested, python

#29933 Add model2vec
  recipes/model2vec/meta.yaml
Labels: review-requested, python

#29932 Add mostlyai-engine
  recipes/mostlyai-engine/meta.yaml
Labels: review-requested, python

#29951 add ty
  recipes/ty/conda_build_config.yaml
  recipes/ty/recipe.yaml
Labels: review-requested, python

#29955 Add fast-array-utils
  recipes/fast-array-utils/meta.yaml
Labels: review-requested, python

#29953 Added desc_bpz
  recipes/desc_bpz/meta.yaml
Labels: review-requested, python

#29957 Added pz-rail-bpz
  recipes/pz-rail-bpz/meta.yaml
Labels: review-requested, python

#29927 Add shareplum 0.5.1
  recipes/shareplum/LICENSE.txt
  recipes/shareplum/meta.yaml
Labels: review-requested, python

#29940 add opentelemetry-instrumentation-mcp from pypi, apache 2.0 license
  recipes/opentelemetry-instrumentation-mcp/LICENSE
  recipes/opentelemetry-instrumentation-mcp/meta.yaml
Labels: review-requested, python

#29954 Add nldi-flowtools
  recipes/nldi-flowtools/meta.yaml
Labels: staged-recipes, review-requested, python

#29754 adding curryreader
  recipes/curryreader/meta.yaml
  recipes/curryreader/yum_requirements.txt
Labels: staged-recipes, review-requested, python

#29977 Add rstream
  recipes/rstream/meta.yaml
Labels: review-requested, python

#29971 Adding ecmwf-datastores-client
  recipes/ecmwf-datastores-client/meta.yaml
Labels: staged-recipes, review-requested, python

#29976 Add gaspype recipe
  recipes/gaspype/meta.yaml
  recipes/gaspype/tests/test_data/cycle_temp_matlab_ref.csv
  recipes/gaspype/tests/test_data/test_data_h2.tsv
  recipes/gaspype/tests/test_data/test_data_nh3.tsv
  recipes/gaspype/tests/test_data/test_data_nh3_ht.tsv
Labels: staged-recipes, review-requested, python

#29924 Adding warpfield
  recipes/warpfield/meta.yaml
Labels: review-requested, python

#26727 Add hydrology model Hydrological Simulation Program-Python (HSPsquared)
  recipes/hsp2/conda_build_config.yaml
  recipes/hsp2/meta.yaml
Labels: staged-recipes, review-requested, python

#29947 add r-baizer recipe
  recipes/r-baizer/bld.bat
  recipes/r-baizer/build.sh
  recipes/r-baizer/meta.yaml
Labels: R, review-requested

#29983 add fs.onedatarestfs and the client
  recipes/fs.onedatarestfs/meta.yaml
  recipes/onedatafilerestclient/meta.yaml
Labels: review-requested, python

#29984 add fs.dropboxfs
  recipes/fs.dropboxfs/meta.yaml
Labels: review-requested, python

#29985 add rspace client
  recipes/rspace-client/meta.yaml
Labels: review-requested, python

#29987 add fs-azureblob
  recipes/fs-azureblob/meta.yaml
Labels: review-requested, python

#29996 add pyclimo recipe
  recipes/pyclimo/meta.yaml
Labels: review-requested, python

#29993 Add pymarkovclustering
  recipes/pymarkovclustering/meta.yaml
Labels: review-requested, python

#29502 opensees first recipe
  recipes/opensees/build.sh
  recipes/opensees/meta.yaml
Labels: review-requested, c-cpp

#29965 Add mostlyai-qa
  recipes/mostlyai-qa/recipe.yaml
Labels: review-requested, python

#29952 Add recipe for bomctl
  recipes/bomctl/recipe.yaml
Labels: staged-recipes, review-requested, go

#29988 Adding the `picaso` and `virga-exo` packages
  recipes/picaso/meta.yaml
  recipes/virga-exo/LICENSE
  recipes/virga-exo/meta.yaml
Labels: review-requested, python

#29821 Add causal-conv1d
  recipes/causal-conv1d/meta.yaml
Labels: review-requested, python-c

#29501 Add recipe for openusd package
  recipes/openusd/build.bat
  recipes/openusd/build.sh
  recipes/openusd/link_python_to_executables.patch
  recipes/openusd/recipe.yaml
Labels: staged-recipes, review-requested, c-cpp, python-c

#29991 Add `valkey-py`
  recipes/valkey-py/recipe.yaml
Labels: review-requested, python

#29944 Add suffix-tree
  recipes/suffix-tree/meta.yaml
Labels: review-requested, python

#29671 Add floability recipe
  recipes/floability/meta.yaml
Labels: review-requested, python

#30001 Add recipe for orcestra-downloader version 0.13.0
  recipes/orcestra-downloader/recipe.yaml
Labels: review-requested, python

#29973 Add `fractal-task-tools`
  recipes/fractal-task-tools/meta.yaml
Labels: review-requested, python

#29879 Add recipe for apache-airflow-core
  recipes/apache-airflow-core/install_airflow_core.sh
  recipes/apache-airflow-core/meta.yaml
Labels: review-requested, python

#29997 Add wait_for2
  recipes/wait_for2/meta.yaml
Labels: review-requested, python

#30025 Added glyphx as a package
  recipes/glyphx/recipe.yaml
Labels: review-requested, python

#29705 Added nbrefactor as a package
  recipes/nbrefactor/recipe.yaml
Labels: review-requested, python

#30026 Add recipe for cargo-auditable
  recipes/cargo-auditable/recipe.yaml
Labels: staged-recipes, review-requested

#30013 add amzn-sagemaker-aiops-jupyterlab-extension recipe to conda forge
  recipes/amzn-sagemaker-aiops-jupyterlab-extension/meta.yaml
Labels: review-requested, python

#30027 Add recipe for cargo-audit
  recipes/cargo-audit/recipe.yaml
Labels: staged-recipes, review-requested

#30004 Add jsongrapher
  recipes/jsongrapher/meta.yaml
Labels: review-requested, python

#30029 Add ase-db-backends
  recipes/ase-db-backends/meta.yaml
Labels: staged-recipes, review-requested, python

#30022 Add amp-rsl-rl recipe
  recipes/amp-rsl-rl/meta.yaml
Labels: review-requested, python

#30032 Add recipe for json-flatten
  recipes/json-flatten/recipe.yaml
Labels: review-requested, python

#30030 Add recipe for symbolic
  recipes/symbolic/meta.yaml
Labels: review-requested, python

#30034 added sympy_equation recipe
  recipes/sympy_equation/LICENSE
  recipes/sympy_equation/meta.yaml
Labels: review-requested, python

#30010 Add pytorch-frame recipe
  recipes/pytorch-frame/LICENSE
  recipes/pytorch-frame/meta.yaml
Labels: review-requested, python

#30035 Add recipe for custom-json-diff
  recipes/custom-json-diff/meta.yaml
Labels: review-requested, python

#30028 Added flowshow as a package, missing license
  recipes/flowshow/LICENSE
  recipes/flowshow/recipe.yaml
Labels: review-requested, python

#29701 Added dockerpyze as a package
  recipes/dockerpyze/recipe.yaml
Labels: review-requested, python

#30009 Add recipe for nputop
  recipes/nputop/meta.yaml
Labels: review-requested, python

#29208 Add metplus
  recipes/metplus/build.sh
  recipes/metplus/meta.yaml
Labels: review-requested, c-cpp, python-c

#29817 Add hf-xet from PyPI via Grayskull
  recipes/hf-xet/LICENSE
  recipes/hf-xet/bld.bat
  recipes/hf-xet/build.sh
  recipes/hf-xet/meta.yaml
Labels: R, review-requested, python, rust

#29065 Adding qfit
  recipes/qfit/meta.yaml
Labels: staged-recipes, review-requested, python

#30016 Adding PEUQSE
  recipes/PEUQSE/meta.yaml
Labels: review-requested, python

#30044 Add panel-material-ui recipe
  recipes/panel-material-ui/meta.yaml
Labels: review-requested, python

#29974 Adding pytcube
  recipes/pytcube/meta.yaml
Labels: review-requested, python

#29904 Add quicfire-tools
  recipes/quicfire-tools/meta.yaml
Labels: review-requested, python

#29992 Add `libvalkey-py`
  recipes/libvalkey-py/recipe.yaml
Labels: review-requested, python-c

#30048 New package: anaconda-ai
  recipes/anaconda-ai/meta.yaml
Labels: review-requested, python

#30050 add msgpack-tools
  recipes/msgpack-tools/build.sh
  recipes/msgpack-tools/recipe.yaml
Labels: review-requested, c-cpp

#30057 Add GLODAP
  recipes/glodap/meta.yaml
Labels: review-requested, python

#30055 Added neapolitan as a package
  recipes/neapolitan/recipe.yaml
Labels: review-requested, python

#30053 Added stealthkit as a package
  recipes/stealthkit/LICENSE
  recipes/stealthkit/recipe.yaml
Labels: review-requested, python

#30052 Added patito as a package
  recipes/patito/recipe.yaml
Labels: review-requested, python

#30051 Added django-action-triggers as a package
  recipes/django-action-triggers/recipe.yaml
Labels: review-requested, python

#29352 Added vsketch as a package
  recipes/vsketch/meta.yaml
Labels: review-requested, python

#30056 new package r-dotty
  recipes/r-dotty/bld.bat
  recipes/r-dotty/build.sh
  recipes/r-dotty/meta.yaml
Labels: R, review-requested

#30063 Add json2ast
  recipes/json2ast/meta.yaml
Labels: staged-recipes, review-requested, python

#30061 Add ast2json
  recipes/ast2json/LICENSE
  recipes/ast2json/meta.yaml
Labels: staged-recipes, review-requested, python

#30062 add elicito package to conda-forge
  recipes/elicito/meta.yaml
Labels: staged-recipes, review-requested

#30006 Add sess_i v0.2.1
  recipes/sess_i/meta.yaml
Labels: review-requested, python

#30049 Adding polyglotdb, conch_sounds and pyraat
  recipes/conch-sounds/meta.yaml
  recipes/polyglotdb/meta.yaml
  recipes/pyraat/meta.yaml
Labels: review-requested, python

#30068 Adding loro 1.5.1
  recipes/loro/recipe.yaml
Labels: review-requested, python

#30081 Add recipe for conda-rattler-solver
  recipes/conda-rattler-solver/recipe.yaml
Labels: review-requested, python

#30075 add rb-prawn-icon
  recipes/rb-prawn-icon/COPYING
  recipes/rb-prawn-icon/GPLv2
  recipes/rb-prawn-icon/GPLv3
  recipes/rb-prawn-icon/LICENSE
  recipes/rb-prawn-icon/conda_build_config.yaml
  recipes/rb-prawn-icon/meta.yaml
Labels: R, review-requested, ruby

#29963 Add canopy tools
  recipes/canopy-tools/meta.yaml
Labels: staged-recipes, review-requested, python

#30070 Add several missing apache-airflow providers
  recipes/apache-airflow-providers-apache-impala/meta.yaml
  recipes/apache-airflow-providers-common-messaging/meta.yaml
  recipes/apache-airflow-providers-edge3/meta.yaml
  recipes/apache-airflow-providers-git/meta.yaml
  recipes/apache-airflow-providers-openai/meta.yaml
  recipes/apache-airflow-providers-opensearch/meta.yaml
  recipes/apache-airflow-providers-pgvector/meta.yaml
  recipes/apache-airflow-providers-pinecone/meta.yaml
  recipes/apache-airflow-providers-qdrant/meta.yaml
Labels: review-requested, python

#30082 add bobleesj.utils
  recipes/bobleesj/meta.yaml
Labels: review-requested, python

#30086 Added setuptools-changelog-shortener as a package
  recipes/setuptools-changelog-shortener/recipe.yaml
Labels: review-requested, python

#30083 Adding volta v2.0.2
  recipes/volta/recipe.yaml
Labels: R, review-requested, rust

#29444 Add pygments.rb
  recipes/rb-pygments.rb/LICENSE
  recipes/rb-pygments.rb/conda_build_config.yaml
  recipes/rb-pygments.rb/meta.yaml
Labels: R, review-requested, ruby

#30090 Add `pagerduty` recipe
  recipes/pagerduty/meta.yaml
Labels: review-requested, python

#30089 add pystray 0.19.5
  recipes/pystray/conda_build_config.yaml
  recipes/pystray/recipe.yaml
  recipes/pystray/yum_requirements.txt
Labels: review-requested, python

#29972 Add keyring-pass v0.9.3
  recipes/keyring-pass/meta.yaml
Labels: review-requested, python

#30094 Add authzed
  recipes/authzed-py/meta.yaml
Labels: review-requested, python

#29491 Add rb-rexml
  recipes/rb-rexml/LICENSE.txt
  recipes/rb-rexml/conda_build_config.yaml
  recipes/rb-rexml/meta.yaml
Labels: R, review-requested, ruby

#30095 Add pybars3 (with its dependency pymeta3)
  recipes/pybars3/meta.yaml
  recipes/pymeta3/meta.yaml
Labels: review-requested, python

#30092 Add uncompresspy
  recipes/uncompresspy/meta.yaml
Labels: review-requested, python

#30093 Add package xmodem
  recipes/xmodem/meta.yaml
Labels: review-requested, python

#29492 Add rb-ruby-rc4
  recipes/rb-ruby-rc4/LICENSE
  recipes/rb-ruby-rc4/conda_build_config.yaml
  recipes/rb-ruby-rc4/meta.yaml
Labels: R, review-requested, ruby

#30097 Add pyserial-labgrid package
  recipes/pyserial-labgrid/meta.yaml
Labels: review-requested, python

#30102 Add botier
  recipes/botier/meta.yaml
Labels: staged-recipes, review-requested, python

#30104 Add `apache-airflow-providers-weaviate` and dependencies
  recipes/apache-airflow-providers-weaviate/meta.yaml
  recipes/weaviate-client/meta.yaml
Labels: review-requested, python

#30105 Add `apache-airflow-providers-ydb` and dependencies
  recipes/apache-airflow-providers-ydb/meta.yaml
  recipes/ydb-dbapi/meta.yaml
  recipes/ydb/meta.yaml
Labels: review-requested, python

#30107 add climkern
  recipes/climkern/meta.yaml
Labels: review-requested, python

#30085 Add norwegianblue
  recipes/norwegianblue/recipe.yaml
Labels: review-requested, python

#30112 Add jupyter-drives
  recipes/jupyter-drives/meta.yaml
Labels: review-requested, python

#30111 Adding fnm v1.38.1
  recipes/fnm/recipe.yaml
Labels: R, review-requested, rust

#30114 Adding SHARPlib_rc package
  recipes/SHARPlib/conda_build_config.yaml
  recipes/SHARPlib/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#30117 Add recipe for cacheout
  recipes/cacheout/meta.yaml
Labels: review-requested, python

#30101 Add r-celltrackr from CRAN
  recipes/r-celltrackr/bld.bat
  recipes/r-celltrackr/build.sh
  recipes/r-celltrackr/meta.yaml
Labels: R, staged-recipes, review-requested

#29892 Adding love2d
  recipes/love2d/build.bat
  recipes/love2d/build.sh
  recipes/love2d/patches/0001-increase-minimum-cmake-version.patch
  recipes/love2d/patches/0002-allow-using-cmake-on-windows.patch
  recipes/love2d/patches/0003-install-binaries-in-right-locations.patch
  recipes/love2d/patches/0004-find-correct-openal-library-on-windows.patch
  recipes/love2d/patches/0005-fix-ssize_t-usage.patch
  recipes/love2d/recipe.yaml
Labels: review-requested, c-cpp

#30137 Add psdtags package
  recipes/psdtags/meta.yaml
Labels: review-requested, python

#30125 Add rpm-sequoia
  recipes/rpm-sequoia/recipe.yaml
Labels: staged-recipes, review-requested, rust

#30142 Add tof to conda-forge
  recipes/tof/recipe.yaml
Labels: review-requested, python

#29956 Add pertpy
  recipes/pertpy/meta.yaml
Labels: review-requested, python

#28988 Adding mimosa
  recipes/mimosa/build.sh
  recipes/mimosa/meta.yaml
Labels: review-requested, c-cpp

#30157 add pytest-reraise
  recipes/pytest-reraise/license
  recipes/pytest-reraise/meta.yaml
Labels: review-requested, python

#30165 add owa-env-desktop
  recipes/owa-env-desktop/LICENSE
  recipes/owa-env-desktop/conda-forge.yml
  recipes/owa-env-desktop/meta.yaml
Labels: review-requested, python

#30166 add owa-cli
  recipes/owa-cli/LICENSE
  recipes/owa-cli/meta.yaml
Labels: review-requested, python

#30147 Adding exejs
  recipes/exejs/meta.yaml
Labels: review-requested, python

#30130 Add fenicsx-ldrb
  recipes/fenicsx-ldrb/meta.yaml
Labels: review-requested, python

#30139 Add recipe for fastdfe
  recipes/fastdfe/meta.yaml
Labels: review-requested, python

#30168 add napari-tiff recipe
  recipes/napari-tiff/meta.yaml
Labels: review-requested, python

#30170 Add vizro-mcp
  recipes/vizro-mcp/meta.yaml
Labels: review-requested, python

#30171 Add django-pydantic-models
  recipes/django-pydantic-models/recipe.yaml
Labels: review-requested, python

#30172 add django-oidc-provider
  recipes/django-oidc-provider/recipe.yaml
Labels: review-requested, python

#30182 add libscrypt
  recipes/libscrypt/recipe.yaml
Labels: review-requested, c-cpp

#30184 add arti
  recipes/arti/recipe.yaml
Labels: R, review-requested, rust

#30185 add seaweedfs
  recipes/seaweedfs/recipe.yaml
Labels: review-requested, go

#30189 Add ckmutil
  recipes/ckmutil/recipe.yaml
Labels: review-requested, python

#30195 Add jupyter-marimo-proxy
  recipes/jupyter-marimo-proxy/meta.yaml
Labels: review-requested, python

#30136 Kedro init
  recipes/kedro-init/recipe.yaml
  recipes/pygetimportables/recipe.yaml
Labels: review-requested, python
