Repository conda-forge/staged-recipes, pull requests merged in 2025-07, with the labels that each got.

#30439 add asf_enumeration
  recipes/asf_enumeration/meta.yaml
Labels: review-requested, python

#30440 add polars-xdt
  recipes/polars-xdt/recipe.yaml
Labels: review-requested, python

#30447 Add clusterscope
  recipes/clusterscope/meta.yaml
Labels: staged-recipes, review-requested, python

#30451 Add collate-sqlfluff
  recipes/collate-sqlfluff/recipe.yaml
Labels: review-requested, python

#30455 Adding `betacal`
  recipes/betacal/recipe.yaml
Labels: review-requested, python

#30464 Add httpx-retries
  recipes/httpx-retries/recipe.yaml
Labels: review-requested, python

#30441 Add fans-dashboard
  recipes/fans_dashboard/recipe.yaml
Labels: review-requested, python

#30471 Add confluence-markdown-exporter
  recipes/confluence-markdown-exporter/recipe.yaml
Labels: review-requested, python

#30473 Add segment-analytics-python
  recipes/segment-analytics-python/meta.yaml
Labels: review-requested, python

#30476 Add Mopaint
  recipes/mopaint/recipe.yaml
Labels: review-requested, python

#30386 Added recipe for easychem
  recipes/easychem/meta.yaml
Labels: review-requested, python-c

#30453 Adding dmqclib
  recipes/dmqclib/meta.yaml
Labels: review-requested, python

#29019 Adding vois package
  recipes/vois/meta.yaml
Labels: review-requested, go, python

#29950 add r-plutor recipe
  recipes/r-plutor/bld.bat
  recipes/r-plutor/build.sh
  recipes/r-plutor/meta.yaml
Labels: R, review-requested

#30462 Add diffpy.morph
  recipes/diffpy.morph/meta.yaml
Labels: review-requested, python

#30141 add lenapy recipe
  recipes/lenapy/meta.yaml
Labels: review-requested, python

#29769 Add jupyter-fsspec
  recipes/jupyter-fsspec/meta.yaml
Labels: review-requested, python

#29450 Adding pado-optics - Pytorch Automatic Differentiable Optics framework
  recipes/pado-optics/meta.yaml
Labels: staged-recipes, review-requested, python

#30486 Add mcrpy
  recipes/mcrpy/meta.yaml
Labels: staged-recipes, review-requested, python

#30490 Add pyvoro-mmalahe
  recipes/pyvoro-mmalahe/meta.yaml
Labels: staged-recipes, review-requested, python-c

#30484 Package fps-kernel-subprocess
  recipes/fps-kernel-subprocess/meta.yaml
Labels: review-requested, python

#30491 Package fps-akernel-task
  recipes/fps-akernel-task/meta.yaml
Labels: review-requested, python

#30488 Add lsq-ellipse
  recipes/lsq-ellipse/meta.yaml
Labels: staged-recipes, review-requested, python

#30507 added recipe for `lungmask`
  recipes/lungmask/meta.yaml
Labels: review-requested, python

#30514 Add shadows
  recipes/shadows/conda_build_config.yaml
  recipes/shadows/meta.yaml
Labels: review-requested, python

#30513 Add addr2line-rust
  recipes/addr2line-rust/recipe.yaml
Labels: R, review-requested, rust

#30506 add pyror
  recipes/pyror/meta.yaml
Labels: staged-recipes, review-requested

#29623 Recipe for the fastemriwaveforms package
  recipes/fastemriwaveforms/meta.yaml
  recipes/fastemriwaveforms/update_name.py
Labels: review-requested, python, python-c

#30218 Add lzlib, pax, pixz
  recipes/lzlib/0001-make-shared-lib-work-on-macOS.patch
  recipes/lzlib/build.sh
  recipes/lzlib/recipe.yaml
  recipes/pax/LICENSE
  recipes/pax/build.sh
  recipes/pax/recipe.yaml
  recipes/pixz/build.sh
  recipes/pixz/recipe.yaml
Labels: review-requested, c-cpp

#30485 Add microstructpy
  recipes/microstructpy/meta.yaml
Labels: staged-recipes, review-requested, python

#30515 Add city2graph
  recipes/city2graph/meta.yaml
Labels: review-requested, python

#30525 Add asimtools
  recipes/asimtools/meta.yaml
Labels: staged-recipes, review-requested, python

#30517 Adding newuoa-cpp v0.1.2
  recipes/newuoa-cpp/fix_dll_install.patch
  recipes/newuoa-cpp/recipe.yaml
Labels: review-requested, c-cpp

#30526 Add sphinx-llm
  recipes/sphinx-llm/meta.yaml
Labels: staged-recipes, review-requested, python

#30511 Adding libzeep v7.0.3
  recipes/libzeep/recipe.yaml
  recipes/libzeep/variants.yaml
Labels: review-requested, c-cpp

#30520 Add pytest-sphinx
  recipes/pytest-sphinx/meta.yaml
Labels: review-requested, python

#30529 added recipe for `torchtitan`
  recipes/torchtitan/meta.yaml
Labels: review-requested, python

#30519 feat: add `scipyconference` python package
  recipes/scipyconference/meta.yaml
Labels: review-requested, python

#30535 Package PyActiveStorage
  recipes/pyactivestorage/meta.yaml
Labels: review-requested, python

#30537 Add pyvers
  recipes/pyvers/meta.yaml
Labels: staged-recipes, review-requested, python

#30538 Add dbetto
  recipes/dbetto/recipe.yaml
Labels: review-requested, python

#30534 Adding maartens_resource_compiler v1.3.16
  recipes/maartens_resource_compiler/recipe.yaml
Labels: review-requested, c-cpp

#30543 Add hatch-multi
  recipes/hatch-multi/recipe.yaml
Labels: review-requested, python

#30539 Add legend-pydataobj
  recipes/legend-pydataobj/recipe.yaml
Labels: review-requested, python

#30544 Add dspeed
  recipes/dspeed/recipe.yaml
Labels: review-requested, python

#30552 Add onnxscript
  recipes/onnx-ir/meta.yaml
  recipes/onnxscript/meta.yaml
Labels: review-requested, python

#30554 Add opentelemetry-instrumentation-openai-agents
  recipes/opentelemetry-instrumentation-openai-agents/LICENSE
  recipes/opentelemetry-instrumentation-openai-agents/meta.yaml
Labels: review-requested, python

#30561 Adds nexus-rpc
  recipes/nexus-rpc/meta.yaml
Labels: review-requested, python

#28069 Add greedy
  recipes/greedy/build.sh
  recipes/greedy/meta.yaml
Labels: review-requested, c-cpp

#30576 Add html-to-markdown
  recipes/html-to-markdown/recipe.yaml
Labels: review-requested, python

#30562 Request to Add ufs2arco Python Package to conda-forge
  recipes/ufs2arco/meta.yaml
Labels: review-requested, python

#30558 add witty
  recipes/witty/meta.yaml
Labels: review-requested, python

#30426 Recipe for diffpy.srfit package
  recipes/diffpy.srfit/meta.yaml
Labels: review-requested, python

#30508 Add aimz
  recipes/aimz/meta.yaml
Labels: staged-recipes, review-requested, python

#30559 Add trackastra
  recipes/trackastra/meta.yaml
Labels: review-requested, python

#30571 Add SageMakerGenAIJupyterlabExtension recipe
  recipes/sagemaker-gen-ai-jupyterlab-extension/meta.yaml
Labels: review-requested, python

#30580 added recipes for `wsidata`, `lazyslide` and `openslide-bin`
  recipes/lazyslide/meta.yaml
  recipes/wsidata/meta.yaml
  recipes/wsidata/openslide.patch
Labels: review-requested, python

#30588 Add recipe for csvw
  recipes/csvw/conda-forge.yml
  recipes/csvw/meta.yaml
Labels: review-requested, python

#30585 Add sardana-config recipe
  recipes/sardana-config/recipe.yaml
Labels: review-requested, python

#30604 Add xsdata-pydantic
  recipes/xsdata-pydantic/meta.yaml
Labels: review-requested, python

#30592 adding recipe for nexus2srs
  recipes/nexus2srs/meta.yaml
Labels: review-requested, python

#30597 Adding recipe for BiaPy
  recipes/biapy/meta.yaml
Labels: review-requested, python

#30549 add backports.asyncio.runner
  recipes/backports.asyncio.runner/conda_build_config.yaml
  recipes/backports.asyncio.runner/recipe.yaml
Labels: review-requested, python

#30607 Add recipe for hydra-joblib-launcher
  recipes/hydra-joblib-launcher/LICENSE
  recipes/hydra-joblib-launcher/LICENSE-antlr4
  recipes/hydra-joblib-launcher/LICENSE-sample-namespace-packages
  recipes/hydra-joblib-launcher/meta.yaml
Labels: review-requested, python

#30611 Add recipe for tree-sitter-sql
  recipes/tree-sitter-sql/recipe.yaml
Labels: review-requested, python

#30619 Add cyclebane to conda-forge
  recipes/cyclebane/recipe.yaml
Labels: review-requested, python

#30618 Add scippneutron to conda-forge
  recipes/scippneutron/recipe.yaml
Labels: review-requested, python

#30565 Add recipe for `cuda-pathfinder`
  recipes/cuda-pathfinder/recipe.yaml
Labels: review-requested, python

#30629 Add recipe for mpl-data-containers
  recipes/mpl-data-containers/build_base.sh
  recipes/mpl-data-containers/meta.yaml
Labels: review-requested, python

#30626 Add paper-qa-pypdf
  recipes/paper-qa-pypdf/meta.yaml
Labels: staged-recipes, review-requested, python

#30617 Add recipe for mattergen
  recipes/mattergen/gh-197.patch
  recipes/mattergen/meta.yaml
Labels: review-requested, python

#30642 Add `zhconv` (Initialized through Grayskull)
  recipes/zhconv/meta.yaml
Labels: review-requested, python

#30648 Adding scoringrules
  recipes/scoringrules/meta.yaml
Labels: review-requested, python

#29515 add simplejpeg
  recipes/simplejpeg/recipe.yaml
  recipes/simplejpeg/setup.py
Labels: staged-recipes, review-requested

#30662 add copyparty
  recipes/copyparty/recipe.yaml
Labels: review-requested, python

#30641 Add `modelscope` (Initialized with Grayskull)
  recipes/modelscope/meta.yaml
Labels: review-requested, python

#30661 Add synthatdelays recipe
  recipes/synthatdelays/meta.yaml
Labels: review-requested, python

#30673 Add flowrep
  recipes/flowrep/meta.yaml
Labels: staged-recipes, review-requested, python

#30644 added recipe for `pyRMT`
  recipes/pyRMT/LICENSE
  recipes/pyRMT/fix-sklearn.patch
  recipes/pyRMT/meta.yaml
Labels: review-requested, python

#30676 Adding r-legendry
  recipes/r-legendry/bld.bat
  recipes/r-legendry/build.sh
  recipes/r-legendry/meta.yaml
Labels: R, review-requested

#30677 Add pyrxiv
  recipes/pyrxiv/meta.yaml
Labels: staged-recipes, review-requested, python

#30566 Add recipe for `tfv_get_tools`
  recipes/tfv_get_tools/meta.yaml
Labels: review-requested, python

#30680 add recipe for pysonar
  recipes/pysonar/meta.yaml
Labels: review-requested, python
