Repository conda-forge/staged-recipes, pull requests merged in 2025-02, with the labels that each got.

#28993 Add carapace package
  recipes/carapace/recipe.yaml
Labels: review-requested, go

#29009 Add jupyter-ruff
  recipes/jupyter-ruff/meta.yaml
Labels: review-requested, python

#29002 Add meteofetch recipe
  recipes/meteofetch/meta.yaml
Labels: review-requested, python

#28979 create swapfiles also for CUDA jobs
  .azure-pipelines/azure-pipelines-linux.yml
Labels: maintenance

#29014 Add QCDLoop Fortran
  recipes/qcdloop-fortran/LICENSE
  recipes/qcdloop-fortran/meta.yaml
Labels: staged-recipes, review-requested

#28803 add icechunk recipe
  recipes/icechunk/meta.yaml
Labels: staged-recipes, review-requested, python

#29012 Add recipe for resolve-robotics-uri-cpp C++ library
  recipes/resolve-robotics-uri-cpp/bld.bat
  recipes/resolve-robotics-uri-cpp/build.sh
  recipes/resolve-robotics-uri-cpp/meta.yaml
Labels: staged-recipes, review-requested, c-cpp

#29018 adding dejaq
  recipes/dejaq/meta.yaml
Labels: review-requested, python

#28982 Add recipe for molecule-signature 2.0.1
  recipes/molecule-signature/meta.yaml
Labels: review-requested, python

#29026 Add package anyioutils
  recipes/anyioutils/meta.yaml
Labels: review-requested, python

#28994 Add `xcube-clms` recipe
  recipes/xcube-clms/meta.yaml
Labels: review-requested, python

#28791 Adding light-curve-python
  recipes/light-curve-python/LICENSE
  recipes/light-curve-python/meta.yaml
Labels: staged-recipes, review-requested, python

#29027 Add qiskit-qasm3-import
  recipes/qiskit-qasm3-import/meta.yaml
Labels: review-requested, python

#29032 add google-genai
  recipes/google-genai/recipe.yaml
Labels: review-requested, python

#29034 Add cmudict
  recipes/cmudict/meta.yaml
Labels: review-requested, python

#29035 Add pysmithchart recipe
  recipes/pysmithchart/meta.yaml
Labels: review-requested, python

#29036 Add CutTools
  recipes/cuttools/LICENSE.txt
  recipes/cuttools/build-only-cuttools-in-makefile.patch
  recipes/cuttools/meta.yaml
Labels: staged-recipes, review-requested

#29042 add swat
  recipes/swat/recipe.yaml
Labels: review-requested, python

#29044 add `trafilatura`, `justext`, `htmldate`, `courlan`
  recipes/courlan/recipe.yaml
  recipes/htmldate/recipe.yaml
  recipes/justext/recipe.yaml
  recipes/trafilatura/recipe.yaml
Labels: review-requested, python

#29038 Add a recipe for torchsort
  recipes/torchsort/build.bat
  recipes/torchsort/build.sh
  recipes/torchsort/recipe.yaml
Labels: review-requested, python-c

#27732 Adding cellfinder
  recipes/cellfinder/meta.yaml
Labels: review-requested, python

#29047 Add organizeit2 - engage with zorp
  recipes/organizeit2/recipe.yaml
Labels: review-requested, python

#29052 Add llama-cloud-services
  recipes/llama-cloud-services/meta.yaml
Labels: staged-recipes, review-requested, python

#29054 Add MadGraph5_aMC@NLO
  recipes/mg5amcnlo/allow-for-shared-libraries.patch
  recipes/mg5amcnlo/meta.yaml
  recipes/mg5amcnlo/mg5_configuration.txt
  recipes/mg5amcnlo/tutorial.mg5
Labels: staged-recipes, review-requested

#29046 Add acro
  recipes/acro/LICENSE
  recipes/acro/meta.yaml
Labels: review-requested, python

#29063 Adding conspire recipe
  recipes/conspire/meta.yaml
Labels: review-requested, python

#29071 Add eyed3
  recipes/eyed3/recipe.yaml
Labels: review-requested, python

#29039 add dedupe_Levenshtein_search
  recipes/dedupe_Levenshtein_search/recipe.yaml
Labels: review-requested, python

#29070 Add IREGI
  recipes/iregi/makefile_ML5_lib.patch
  recipes/iregi/meta.yaml
  recipes/iregi/use-avh_olo.patch
Labels: staged-recipes, review-requested

#28538 Add recipe for odc-loader
  recipes/odc-loader/meta.yaml
Labels: review-requested, python

#29073 Add dp-accounting
  recipes/dp-accounting/LICENSE
  recipes/dp-accounting/meta.yaml
  recipes/dp-accounting/set_requirements.patch
  recipes/dp-accounting/set_version.patch
Labels: review-requested, python

#29066 add recipe for gstools-cython
  recipes/gstools-cython/meta.yaml
Labels: review-requested, python

#28897 adding acryl-datahub
  recipes/acryl-datahub/meta.yaml
Labels: review-requested, python

#29079 Add rustshed
  recipes/rustshed/recipe.yaml
Labels: review-requested, python

#29080 Add antares-client to conda-forge.
  recipes/antares-client/meta.yaml
Labels: review-requested, python

#29064 Adding xgrammar
  recipes/xgrammar/001-fix-macos-no-triton.patch
  recipes/xgrammar/recipe.yaml
Labels: review-requested, python, python-c

#29017 Add `maeparser`
  recipes/maeparser/bld.bat
  recipes/maeparser/build.sh
  recipes/maeparser/cmake_test/CMakeLists.txt
  recipes/maeparser/cmake_test/test.cpp
  recipes/maeparser/meta.yaml
  recipes/maeparser/patches/001-patch-cmake-config-path.patch
Labels: review-requested, c-cpp

#29087 Adding pyfqmr (3D mesh simplification library)
  recipes/pyfqmr/LICENSE-Fast-Quadric-Mesh-Simplification
  recipes/pyfqmr/LICENSE-pyfqmr
  recipes/pyfqmr/meta.yaml
Labels: review-requested, python

#29082 Add diffdist via Grayskull
  recipes/diffdist/LICENSE
  recipes/diffdist/recipe.yaml
Labels: review-requested, python

#29000 Adding recipe for uv-secure
  recipes/uv-secure/meta.yaml
Labels: review-requested, python

#28985 added package py_ecc
  recipes/py_ecc/meta.yaml
Labels: staged-recipes, review-requested

#29092 Add snowmaus
  recipes/snowmaus/meta.yaml
Labels: review-requested, python

#29023 add lib-detect-testenv
  recipes/lib-detect-testenv/meta.yaml
Labels: review-requested, python

#29077 feat: add dependency-groups recipe
  recipes/dependency-groups/recipe.yaml
Labels: review-requested, python

#29029 Add reprostim
  recipes/reprostim/meta.yaml
Labels: staged-recipes, review-requested, python

#29055 add pyudunits2
  recipes/pyudunits2/meta.yaml
Labels: staged-recipes, review-requested

#29084 get dist-s1 into conda-forge
  recipes/dist-s1/meta.yaml
Labels: review-requested, python

#29088 Add recipe for `synchronicity`
  recipes/synchronicity/meta.yaml
Labels: staged-recipes, review-requested

#29098 Add pixcdust
  recipes/pixcdust/meta.yaml
Labels: review-requested, python

#27843 Add asciidoctor-reducer
  recipes/asciidoctor-reducer/asciidoctor-reducer.bat
  recipes/asciidoctor-reducer/conda_build_config.yaml
  recipes/asciidoctor-reducer/meta.yaml
Labels: R, staged-recipes, review-requested, ruby

#29102 Add tiny-retriever
  recipes/tiny-retriever/meta.yaml
Labels: review-requested, python

#29101 Add supervisor-pydantic
  recipes/supervisor-pydantic/recipe.yaml
Labels: review-requested, python

#29106 add pydeb
  recipes/pydeb/meta.yaml
Labels: review-requested, python

#29108 Add package zmq-anyio
  recipes/zmq-anyio/meta.yaml
Labels: review-requested, python

#29099 Add astro-datalab and pycurl-requests.
  recipes/astro-datalab/meta.yaml
  recipes/pycurl-requests/meta.yaml
Labels: review-requested, python

#28987 Add multipers
  recipes/multipers/meta.yaml
Labels: review-requested, python-c

#29068 Adding automesh recipe
  recipes/automesh/meta.yaml
Labels: review-requested, python

#29111 Add `rip2`
  recipes/rip2/bld.bat
  recipes/rip2/build.sh
  recipes/rip2/meta.yaml
Labels: R, review-requested, rust

#29109 Add SageMaker Studio SDK and SageMaker Studio CLI recipes
  recipes/sagemaker-studio-cli/meta.yaml
  recipes/sagemaker-studio/meta.yaml
Labels: review-requested, python

#29117 add unsloth and dependencies
  recipes/cut_cross_entropy/meta.yaml
  recipes/unsloth/meta.yaml
  recipes/unsloth_zoo/meta.yaml
Labels: review-requested, python

#29119 add `jtd`
  recipes/jtd/recipe.yaml
Labels: review-requested, python

#29121 add hatch-semver
  recipes/hatch-semver/meta.yaml
Labels: staged-recipes, review-requested

#29021 add `httptap`
  recipes/httptap/build.sh
  recipes/httptap/recipe.yaml
Labels: staged-recipes, review-requested, go

#29126 add `baml`
  recipes/baml-py/build.bat
  recipes/baml-py/build.sh
  recipes/baml-py/recipe.yaml
Labels: R, review-requested, python, rust

#29127 add `pydantic-ai`, `logfire-api`
  recipes/logfire-api/recipe.yaml
  recipes/pydantic-ai/recipe.yaml
Labels: review-requested, python

#28967 add `fastembed`
  recipes/fastembed/recipe.yaml
Labels: review-requested, python

#29110 Add `intervalues`
  recipes/intervalues/meta.yaml
Labels: review-requested, python

#29134 Add cronsim
  recipes/cronsim/meta.yaml
Labels: review-requested, python

#28744 add rb-polyglot
  recipes/polyglot/LICENSE
  recipes/polyglot/conda_build_config.yaml
  recipes/polyglot/meta.yaml
Labels: R, review-requested, ruby

#29132 add timefold (and build dependency stubgenj)
  recipes/stubgenj/recipe.yaml
  recipes/timefold/recipe.yaml
Labels: review-requested, java, python

#29129 Add `modal-client` recipe
  recipes/modal/meta.yaml
Labels: staged-recipes, review-requested

#29139 Adding csbschema
  recipes/csbschema/meta.yaml
Labels: review-requested, python

#29144 Add `csvlens`
  recipes/csvlens/bld.bat
  recipes/csvlens/build.sh
  recipes/csvlens/meta.yaml
Labels: R, review-requested, rust

#29137 Adding micov
  recipes/micov/meta.yaml
Labels: review-requested, python

#29154 add `openapi-llm`
  recipes/openapi-llm/recipe.yaml
Labels: review-requested, python

#29140 Add csp-gateway
  recipes/csp-gateway/recipe.yaml
Labels: review-requested, python

#29157 Add display3d
  recipes/display3d/build.bat
  recipes/display3d/build.sh
  recipes/display3d/recipe.yaml
Labels: R, review-requested, rust

#29158 Add httm
  recipes/httm/build.sh
  recipes/httm/recipe.yaml
Labels: R, review-requested, rust

#29141 Adding my CRAN package: `r-jobqueue`
  recipes/r-jobqueue/bld.bat
  recipes/r-jobqueue/build.sh
  recipes/r-jobqueue/meta.yaml
Labels: R, review-requested

#29156 add `llama-index-vector-stores-qdrant`
  recipes/llama-index-vector-stores-qdrant/recipe.yaml
Labels: review-requested, python

#28685 add rb-pdf-core
  recipes/pdf-core/GPLv2
  recipes/pdf-core/GPLv3
  recipes/pdf-core/LICENSE
  recipes/pdf-core/conda_build_config.yaml
  recipes/pdf-core/meta.yaml
Labels: R, review-requested, ruby

#29183 Add airflow-pydantic
  recipes/airflow-pydantic/recipe.yaml
Labels: review-requested, python

#29095 Add r monobin
  recipes/r-monobin/bld.bat
  recipes/r-monobin/build.sh
  recipes/r-monobin/meta.yaml
Labels: R, staged-recipes, review-requested

#29180 add tinygrad
  recipes/tinygrad/patches/0001-also-install-tinygrad.viz.patch
  recipes/tinygrad/patches/0002-downgrade-default-metal-standard.patch
  recipes/tinygrad/recipe.yaml
Labels: review-requested, python

#29184 Add tibi and tibi-python
  recipes/tibi/build_tibi.sh
  recipes/tibi/conda_build_config.yaml
  recipes/tibi/meta.yaml
Labels: staged-recipes, review-requested

#29187 add r-pdtoolkit
  recipes/r-pdtoolkit/bld.bat
  recipes/r-pdtoolkit/build.sh
  recipes/r-pdtoolkit/meta.yaml
Labels: R, review-requested

#28914 Add papylio
  recipes/papylio/meta.yaml
  recipes/papylio/yum_requirements.txt
Labels: review-requested, python

#29194 Add `databricks-sqlalchemy`
  recipes/databricks-sqlalchemy/recipe.yaml
Labels: review-requested, python

#29195 Add plopp to conda-forge
  recipes/plopp/recipe.yaml
Labels: review-requested, python

#29197 add `llama-index-{embeddings,llms}-azure-openai`
  recipes/llama-index-embeddings-azure-openai/recipe.yaml
  recipes/llama-index-llms-azure-openai/recipe.yaml
Labels: review-requested, python

#29200 Add roman-numerals-py
  recipes/roman-numerals-py/meta.yaml
Labels: review-requested, python

#29191 add french-cities package
  recipes/french-cities/LICENSE.md
  recipes/french-cities/meta.yaml
Labels: staged-recipes, review-requested

#29204 Add panel-graphic-walker recipe
  recipes/panel-graphic-walker/meta.yaml
Labels: review-requested, python

#29203 Adding metatrain
  recipes/metatrain/meta.yaml
Labels: review-requested, python

#29190 add ``selfeeg``
  recipes/selfeeg/meta.yaml
Labels: review-requested, python

#29196 add xsdba recipe
  recipes/xsdba/meta.yaml
Labels: review-requested, python

#29148 Add `lyteidl`
  recipes/lyteidl/meta.yaml
Labels: review-requested, python

#29209 add arize-phoenix-client
  recipes/arize-phoenix-client/meta.yaml
Labels: review-requested, python

#29155 add `llama-index-retrievers-bm25`
  recipes/llama-index-retrievers-bm25/recipe.yaml
Labels: review-requested, python

#29120 Contribute stimulus-py
  recipes/stimulus-py/meta.yaml
Labels: review-requested, python

#29216 Add znflow
  recipes/znflow/meta.yaml
Labels: staged-recipes, review-requested, python

#29221 Add sacroml
  recipes/sacroml/LICENSE
  recipes/sacroml/meta.yaml
Labels: review-requested, python

#29218 Add znfields
  recipes/znfields/meta.yaml
Labels: staged-recipes, review-requested, python

#29219 Add splines
  recipes/splines/meta.yaml
Labels: staged-recipes, review-requested, python

#29227 adding pythonradex
  recipes/pythonradex/meta.yaml
Labels: staged-recipes, review-requested

#29224 Add zndraw
  recipes/zndraw/meta.yaml
Labels: staged-recipes, review-requested, python

#29202 Adding FESTIM package
  recipes/festim/meta.yaml
Labels: review-requested, python

#29205 Adding xcube-stac
  recipes/xcube-stac/meta.yaml
Labels: review-requested, python

#29226 DOC: Add instruction to make a new branch from 'main'
  README.md
Labels: staged-recipes, review-requested

#29225 Add ZnTrack
  recipes/zntrack/meta.yaml
Labels: staged-recipes, review-requested, python

#29149 Add `latch-persistence`
  recipes/latch-persistence/meta.yaml
Labels: review-requested, python

#29189 Add cerberecontrib-ghrsst recipe
  recipes/cerberecontrib_ghrsst/meta.yaml
Labels: staged-recipes, review-requested, python

#29234 Adding dram-viz
  recipes/dram_viz/meta.yaml
Labels: staged-recipes, review-requested, python

#29232 Add recipe for Python package acres
  recipes/acres/meta.yaml
Labels: staged-recipes, review-requested, python

#29201 Add fenics-oasis recipe
  recipes/fenics-oasis/meta.yaml
Labels: review-requested, python

#29231 add s3-proxy
  recipes/s3-proxy/LICENSE-go-chi-httptracer
  recipes/s3-proxy/recipe.yaml
Labels: review-requested, go

#29233 add streamlit-pydantic
  recipes/streamlit-pydantic/recipe.yaml
Labels: review-requested, python

#29217 add scaleway-cli
  recipes/scaleway-cli/recipe.yaml
Labels: review-requested, go

#29236 Adding pylsp-rope
  recipes/pylsp-rope/meta.yaml
Labels: review-requested, python

#29240 Add envyaml package from pip
  recipes/envyaml/meta.yaml
Labels: staged-recipes, review-requested, python

#29238 Xmacis2py
  recipes/xmacis2py/meta.yaml
Labels: review-requested, python

#29243 Add znh5md
  recipes/znh5md/meta.yaml
Labels: staged-recipes, review-requested, python

#29244 Add tqdm-logging-wrapper recipe
  recipes/tqdm-logging-wrapper/meta.yaml
Labels: review-requested, python

#29242 Add fhlmi
  recipes/fhlmi/LICENSE
  recipes/fhlmi/meta.yaml
Labels: staged-recipes, review-requested, python

#29003 add meta.yaml for chemotools
  recipes/chemotools/meta.yaml
Labels: review-requested, python

#29247 Add pylib-essentials recipe
  recipes/pylib-essentials/LICENSE.txt
  recipes/pylib-essentials/meta.yaml
Labels: review-requested, python

#29192 Add datview package
  recipes/datview/meta.yaml
Labels: review-requested, python

#29229 Add mlipx
  recipes/mlipx/meta.yaml
Labels: staged-recipes, review-requested, python

#29249 Add tex2pix
  recipes/tex2pix/LICENSE
  recipes/tex2pix/add-python_requires.patch
  recipes/tex2pix/meta.yaml
  recipes/tex2pix/use-setuptools-over-distutils.patch
Labels: review-requested, python

#29250 Add Unum
  recipes/unum/meta.yaml
Labels: review-requested, python

#29028 Add StructuralGT package
  recipes/StructuralGT/meta.yaml
Labels: staged-recipes, review-requested, python-c

#29022 add new package `altair-aitools-runtime`
  recipes/altair-aitools-runtime/conda_build_config.yaml
  recipes/altair-aitools-runtime/recipe.yaml
Labels: review-requested, python

#29207 Add parsnip-cif package
  recipes/parsnip-cif/meta.yaml
Labels: review-requested, python

#29260 Adding qwen-vl-utils
  recipes/qwen-vl-utils/LICENSE
  recipes/qwen-vl-utils/recipe.yaml
Labels: review-requested, python

#29261 Add qt-niu recipe
  recipes/qt-niu/meta.yaml
Labels: review-requested, python

#29198 adds r-pnwcolors
  recipes/r-pnwcolors/LICENSE-CC0
  recipes/r-pnwcolors/bld.bat
  recipes/r-pnwcolors/build.sh
  recipes/r-pnwcolors/meta.yaml
Labels: R, review-requested

#28831 Add WindNinja
  recipes/windninja/LICENSE.txt
  recipes/windninja/build.sh
  recipes/windninja/meta.yaml
Labels: review-requested, c-cpp

#29276 add psims pymzml pyteomics python-idzip
  recipes/psims/recipe.yaml
  recipes/pymzml/recipe.yaml
  recipes/pyteomics/recipe.yaml
  recipes/python-idzip/recipe.yaml
Labels: review-requested, python

#29272 Add styro
  recipes/styro/meta.yaml
Labels: review-requested, python

#29283 Add grace-tensorpotential
  recipes/grace-tensorpotential/meta.yaml
Labels: staged-recipes, review-requested, python

#29286 Add recipe for `r-bimets`
  recipes/r-bimets/recipe.yaml
Labels: R, staged-recipes, review-requested

#29269 Add vectorscan
  recipes/vectorscan/0001-fix-the-pcre-versio-check-error-on-clang-16.patch
  recipes/vectorscan/recipe.yaml
Labels: staged-recipes, review-requested, c-cpp

#29290 add tach 0.27.0
  recipes/tach/build-tach.bat
  recipes/tach/build-tach.sh
  recipes/tach/recipe.yaml
Labels: R, review-requested, python, rust

#29305 add rattler-index
  recipes/rattler-index/build.bat
  recipes/rattler-index/build.sh
  recipes/rattler-index/recipe.yaml
Labels: R, review-requested, rust

#29266 Adding stack-pr
  recipes/stack-pr/recipe.yaml
Labels: staged-recipes, review-requested, python

#29291 add `colbert`
  recipes/colbert-ai/recipe.yaml
Labels: review-requested, python

#29288 add `voyager`
  recipes/voyager/recipe.yaml
Labels: review-requested, python

#29309 add `rank-bm25`
  recipes/rank-bm25/recipe.yaml
Labels: review-requested, python

#29310 add `tf-playwright-stealth` and `fake-http-header`
  recipes/fake-http-header/recipe.yaml
  recipes/tf-playwright-stealth/recipe.yaml
Labels: review-requested, python

#29316 Add tytanic
  recipes/tytanic/bld.bat
  recipes/tytanic/build.sh
  recipes/tytanic/meta.yaml
Labels: R, review-requested, rust
