Repository conda-forge/staged-recipes, pull requests merged in 2025-03, with the labels that each got.

#29340 add rloop 0.1.0
  recipes/rloop/build-rloop.bat
  recipes/rloop/build-rloop.sh
  recipes/rloop/recipe.yaml
Labels: R, review-requested, python, rust

#29332 Add hatch-conda
  recipes/hatch-conda/recipe.yaml
Labels: review-requested, python

#29331 add parse-changelog
  recipes/parse-changelog/recipe.yaml
Labels: R, staged-recipes, review-requested, rust

#29329 Add `hierarchicalsoftmax`
  recipes/hierarchicalsoftmax/meta.yaml
Labels: review-requested, python

#29336 add `flagembedding`
  recipes/flag-embedding/recipe.yaml
Labels: review-requested, python

#29335 Add `fast-pytorch-kmeans`
  recipes/fast-pytorch-kmeans/recipe.yaml
Labels: review-requested, python

#29349 Add cffi-buildtool
  recipes/cffi-buildtool/recipe.yaml
Labels: review-requested, python

#29241 add sagemaker studio data engineering sessions and extensions package recipes
  recipes/sagemaker-studio-dataengineering-extensions/meta.yaml
  recipes/sagemaker-studio-dataengineering-sessions/meta.yaml
Labels: review-requested, python

#29328 Add wagtail-flexible-forms
  recipes/wagtail-flexible-forms/meta.yaml
Labels: review-requested, python

#29346 Add pynanoflann
  recipes/pynanoflann/meta.yaml
Labels: staged-recipes, review-requested, python-c

#29341 Add clio-tools
  recipes/clio-tools/meta.yaml
Labels: review-requested, python

#28740 Adding `agentarium` from PyPI
  recipes/agentarium/meta.yaml
Labels: review-requested, python

#29258 Add pyiron-database package
  recipes/pyiron_database/meta.yaml
Labels: review-requested, python

#29357 Add pydantic-xml
  recipes/pydantic-xml/recipe.yaml
Labels: review-requested, python

#29338 Add metatensor-operations
  recipes/metatensor-operations/meta.yaml
Labels: review-requested, python

#29353 Adding recipe for langgraph-checkpoint-aws
  recipes/langgraph-checkpoint-aws/meta.yaml
Labels: review-requested, python

#29351 Added vpype as a package
  recipes/vpype/meta.yaml
Labels: review-requested, python

#29274 Adding `scikit-package`
  recipes/scikit-package/meta.yaml
Labels: review-requested, python

#29143 Add `sequin`
  recipes/sequin/bld.bat
  recipes/sequin/build.sh
  recipes/sequin/meta.yaml
Labels: review-requested, go

#29123 Add jujutsu
  recipes/jujutsu/build.bat
  recipes/jujutsu/build.sh
  recipes/jujutsu/recipe.yaml
Labels: R, review-requested, rust

#29094 Add `pymaeparser`
  recipes/pymaeparser/meta.yaml
  recipes/pymaeparser/methane.mae
Labels: review-requested, python-c

#29188 Add `nativefiledialog-extended`
  recipes/nativefiledialog-extended/build.bat
  recipes/nativefiledialog-extended/build.sh
  recipes/nativefiledialog-extended/recipe.yaml
  recipes/nativefiledialog-extended/run_test.bat
  recipes/nativefiledialog-extended/run_test.sh
  recipes/nativefiledialog-extended/test/CMakeLists.txt
  recipes/nativefiledialog-extended/test/test.cpp
Labels: review-requested, c-cpp

#28588 add awk-language-server, gatsby-cli, spago
  recipes/awk-language-server/LICENSE
  recipes/awk-language-server/build.sh
  recipes/awk-language-server/meta.yaml
  recipes/gatsby-cli/build.sh
  recipes/gatsby-cli/meta.yaml
  recipes/spago/build.sh
  recipes/spago/meta.yaml
Labels: nodejs, staged-recipes, review-requested

#29145 Add `mods`
  recipes/mods/bld.bat
  recipes/mods/build.sh
  recipes/mods/license-files/github.com/mattn/go-localereader/LICENSE
  recipes/mods/license-files/modernc.org/mathutil/LICENSE
  recipes/mods/meta.yaml
Labels: review-requested, go

#29153 Add `gomi`
  recipes/gomi/bld.bat
  recipes/gomi/build.sh
  recipes/gomi/license-files/github.com/mattn/go-localereader/LICENSE
  recipes/gomi/license-files/modernc.org/mathutil/LICENSE
  recipes/gomi/meta.yaml
Labels: review-requested, go

#29142 Add `freeze`
  recipes/freeze/bld.bat
  recipes/freeze/build.sh
  recipes/freeze/license-files/github.com/mattn/go-localereader/LICENSE
  recipes/freeze/meta.yaml
Labels: review-requested, go

#29146 Add `goreleaser`
  recipes/goreleaser/bld.bat
  recipes/goreleaser/build.sh
  recipes/goreleaser/license-files/github.com/cloudflare/circl/dh/x25519/LICENSE
  recipes/goreleaser/license-files/github.com/ipfs/bbloom/LICENSE
  recipes/goreleaser/license-files/github.com/mattn/go-localereader/LICENSE
  recipes/goreleaser/license-files/github.com/multiformats/go-base36/LICENSE
  recipes/goreleaser/license-files/golang.org/x/crypto/blake2b/LICENSE
  recipes/goreleaser/license-files/golang.org/x/crypto/blake2s/LICENSE
  recipes/goreleaser/license-files/golang.org/x/crypto/salsa20/salsa/LICENSE
  recipes/goreleaser/license-files/golang.org/x/crypto/sha3/LICENSE
  recipes/goreleaser/license-files/golang.org/x/sys/cpu/LICENSE
  recipes/goreleaser/license-files/golang.org/x/sys/unix/LICENSE
  recipes/goreleaser/meta.yaml
Labels: review-requested, go

#28721 Adding chafa package
  recipes/chafa/build.sh
  recipes/chafa/meta.yaml
Labels: review-requested, c-cpp

#29368 Adding endf-parserpy
  recipes/endf-parserpy/meta.yaml
Labels: review-requested, python-c

#29152 Add `superfile`
  recipes/superfile/recipe.yaml
Labels: review-requested, go

#28837 Add Windmapper
  recipes/windmapper/meta.yaml
Labels: review-requested, python

#29339 Add metatensor-learn
  recipes/metatensor-learn/meta.yaml
Labels: review-requested, python

#29345 Add xcube eopf
  recipes/xcube-eopf/meta.yaml
Labels: review-requested, python

#29011 Add pythonfmu3 package
  recipes/pythonfmu3/bld.bat
  recipes/pythonfmu3/build.sh
  recipes/pythonfmu3/meta.yaml
Labels: review-requested, python, python-c

#29369 add PythiaLabelGenerator
  recipes/pythialabelgenerator/meta.yaml
Labels: review-requested, python

#29376 Add typing-inspection
  recipes/typing-inspection/meta.yaml
Labels: staged-recipes, review-requested, python

#28705 Add litestream recipe
  recipes/litestream/build.sh
  recipes/litestream/conda_build_config.yaml
  recipes/litestream/recipe.yaml
Labels: review-requested, go

#28912 Add vsgImGui
  recipes/vsgimgui/bld.bat
  recipes/vsgimgui/build.sh
  recipes/vsgimgui/meta.yaml
  recipes/vsgimgui/patches/0001-Add-options-to-use-system-dependencies.patch
  recipes/vsgimgui/patches/0003-Find-imgui-and-implot-in-package-config-when-system-.patch
  recipes/vsgimgui/run_test.bat
  recipes/vsgimgui/run_test.sh
  recipes/vsgimgui/tests/CMakeLists.txt
  recipes/vsgimgui/tests/main.cpp
Labels: review-requested, c-cpp

#28639 Add proxychains-ng recipe
  recipes/proxychains-ng/build.sh
  recipes/proxychains-ng/meta.yaml
Labels: staged-recipes, review-requested

#28689 Add sphericart
  recipes/sphericart/build.sh
  recipes/sphericart/meta.yaml
Labels: review-requested, python-c

#29222 Add recipe for the "multispline" package
  recipes/multispline/meta.yaml
Labels: review-requested, python, python-c

#29347 Add package `cargo-insta`
  recipes/cargo-insta/build.bat
  recipes/cargo-insta/build.sh
  recipes/cargo-insta/recipe.yaml
Labels: R, review-requested, rust

#29295 Add `awk`
  recipes/awk/build.sh
  recipes/awk/meta.yaml
Labels: review-requested, c-cpp

#29013 Add dlt-pendulum
  recipes/dlt-pendulum/0001-remove-tzdata-dep-for-pip-check.patch
  recipes/dlt-pendulum/LICENSE
  recipes/dlt-pendulum/bld.bat
  recipes/dlt-pendulum/build.sh
  recipes/dlt-pendulum/meta.yaml
Labels: review-requested, python, python-c

#28950 Add dialog
  recipes/dialog/meta.yaml
Labels: review-requested, c-cpp

#28958 Adding cppad_mixed to conda-forge
  recipes/cppad-mixed/bld.bat
  recipes/cppad-mixed/build.sh
  recipes/cppad-mixed/meta.yaml
  recipes/cppad-mixed/run_test.py
Labels: review-requested, c-cpp

#29324 Adding lazyjournal
  recipes/lazyjournal/build.bat
  recipes/lazyjournal/build.sh
  recipes/lazyjournal/recipe.yaml
Labels: review-requested, go

#29150 Add `lytekit`
  recipes/lytekit/LICENSE
  recipes/lytekit/meta.yaml
Labels: review-requested, python

#29380 Add `wadler-lindig` package
  recipes/wadler-lindig/recipe.yaml
Labels: review-requested, python

#29363 add anaconda-auth
  recipes/anaconda-auth/meta.yaml
Labels: staged-recipes, review-requested, python

#29379 Add ccxt-py: non-unix fail is expected
  recipes/ccxt-py/fix-README.rst.patch
  recipes/ccxt-py/recipe.yaml
Labels: review-requested, python

#29151 Add `lytekitplugins-pods`
  recipes/lytekitplugins-pods/meta.yaml
Labels: review-requested, python

#29383 Adding geohexgrid python package
  recipes/geohexgrid/LICENSE
  recipes/geohexgrid/meta.yaml
Labels: review-requested, python

#29391 Add daft-pgm
  recipes/daft-pgm/recipe.yaml
Labels: review-requested, python

#29388 Add mcp (Model Context Protocol Python SDK)
  recipes/mcp/meta.yaml
Labels: review-requested, python

#28640 Add recipe for rte-rrtmgp
  recipes/rte-rrtmgp/LICENSE.txt
  recipes/rte-rrtmgp/build.sh
  recipes/rte-rrtmgp/meta.yaml
Labels: review-requested, python

#29371 Add hvsampledata
  recipes/hvsampledata/meta.yaml
Labels: review-requested, python

#29393 add fastapi-zitadel-auth
  recipes/fastapi-zitadel-auth/recipe.yaml
Labels: review-requested, python

#29252 Add poethepoet
  recipes/poethepoet/meta.yaml
Labels: review-requested, python

#29010 Add a recipe for dbcsr
  recipes/dbcsr/build.sh
  recipes/dbcsr/dbcsr-shared.patch
  recipes/dbcsr/recipe.yaml
Labels: review-requested, c-cpp

#29320 Add opensearch
  recipes/opensearch/build.sh
  recipes/opensearch/meta.yaml
Labels: staged-recipes, review-requested, java

#29402 add SCE-UA
  recipes/sceua/meta.yaml
Labels: review-requested, python

#29398 Add session-info2
  recipes/session-info2/conda_build_config.yaml
  recipes/session-info2/meta.yaml
Labels: review-requested, python

#29404 add `openai-agents`
  recipes/openai-agents/recipe.yaml
Labels: review-requested, python

#29381 Add `reportengine`
  recipes/reportengine/recipe.yaml
Labels: review-requested, python

#29385 Add rlic
  recipes/rlic/bld.bat
  recipes/rlic/build.sh
  recipes/rlic/meta.yaml
Labels: R, review-requested, python, rust

#28917 Adding mypy-boto3-kinesis
  recipes/mypy-boto3-kinesis/recipe.yaml
Labels: review-requested, python

#28918 Adding mypy-boto3-sts
  recipes/mypy-boto3-sts/recipe.yaml
Labels: review-requested, python

#29405 Add svg2tikz (and inkex dep) to conda-forge
  recipes/inkex/meta.yaml
  recipes/svg2tikz/meta.yaml
Labels: review-requested, python

#29400 Dead batteries packages: standard-aifc, standard-sunau, standard-chunk, and audioop-lts
  recipes/audioop-lts/meta.yaml
  recipes/standard-aifc/meta.yaml
  recipes/standard-chunk/meta.yaml
  recipes/standard-sunau/meta.yaml
Labels: review-requested, python

#29397 Adding slidecna
  recipes/slidecna/bld.bat
  recipes/slidecna/build.sh
  recipes/slidecna/meta.yaml
Labels: R, review-requested

#29259 Adding veg2hab
  recipes/veg2hab/meta.yaml
Labels: staged-recipes, review-requested, python

#29361 Added r-yyjsonr as a package
  recipes/r-yyjsonr/bld.bat
  recipes/r-yyjsonr/build.sh
  recipes/r-yyjsonr/meta.yaml
Labels: R, review-requested

#29408 add hypothesmith
  recipes/hypothesmith/recipe.yaml
Labels: review-requested, python

#29297 Adding new project felyx-distributed
  recipes/felyx-distributed/LICENSE.md
  recipes/felyx-distributed/meta.yaml
Labels: staged-recipes, review-requested, python

#29364 add conda-managed-env
  recipes/conda-managed-env/EXTERNALLY-MANAGED
  recipes/conda-managed-env/LICENSE.txt
  recipes/conda-managed-env/meta.yaml
Labels: review-requested, python

#29409 add tools4rdf
  recipes/tools4rdf/meta.yaml
Labels: review-requested, python

#29386 Add hazardous 0.1.0
  recipes/hazardous/meta.yaml
Labels: review-requested, python

#29412 First attempt at publishing 'prismatique' on conda-forge.
  recipes/prismatique/meta.yaml
Labels: review-requested, python

#29417 add `batched`
  recipes/batched/recipe.yaml
Labels: review-requested, python

#29326 Adding Yash
  recipes/yash/recipe.yaml
Labels: review-requested, c-cpp

#29273 Adding rainfrog
  recipes/rainfrog/recipe.yaml
Labels: R, review-requested, rust

#28965 Add a recipe for AFNI
  recipes/afni/Makefile.patch
  recipes/afni/build.sh
  recipes/afni/recipe.yaml
Labels: review-requested, c-cpp

#28855 Adding hatch-cython
  recipes/hatch-cython/recipe.yaml
Labels: review-requested, python, python-c

#29416 Add cherab-lhd
  recipes/cherab-lhd/recipe.yaml
Labels: review-requested, python-c

#29422 add bicep, fsdgenfsd
  recipes/bicep/build.sh
  recipes/bicep/recipe.yaml
  recipes/fsdgenfsd/build.sh
  recipes/fsdgenfsd/recipe.yaml
Labels: staged-recipes, review-requested

#29419 add charasay, lightningcss, mandown, schema-engine-cli, turbopack-cli
  recipes/charasay/build.bat
  recipes/charasay/build.sh
  recipes/charasay/recipe.yaml
  recipes/lightingcss/build.bat
  recipes/lightingcss/build.sh
  recipes/lightingcss/recipe.yaml
  recipes/mandown/build.bat
  recipes/mandown/build.sh
  recipes/mandown/recipe.yaml
  recipes/schema-engine-cli/build.bat
  recipes/schema-engine-cli/build.sh
  recipes/schema-engine-cli/recipe.yaml
  recipes/turbopack-cli/build.sh
  recipes/turbopack-cli/recipe.yaml
  recipes/turbopack-cli/variants.yaml
Labels: R, staged-recipes, review-requested, rust

#29421 add ejson, hcp, osc
  recipes/ejson/bld.bat
  recipes/ejson/build.sh
  recipes/ejson/meta.yaml
  recipes/hcp/bld.bat
  recipes/hcp/build.sh
  recipes/hcp/meta.yaml
  recipes/osc/bld.bat
  recipes/osc/build.sh
  recipes/osc/meta.yaml
Labels: staged-recipes, review-requested, go

#29420 add aqua, botsay, doppler-cli
  recipes/aqua/bld.bat
  recipes/aqua/build.sh
  recipes/aqua/meta.yaml
  recipes/botsay/build.sh
  recipes/botsay/meta.yaml
  recipes/doppler-cli/bld.bat
  recipes/doppler-cli/build.sh
  recipes/doppler-cli/meta.yaml
Labels: staged-recipes, review-requested, go

#27801 Add QEMU-user with execve: Requires sysroot 2.28
  recipes/qemu-user-execve/conda_build_config.yaml
  recipes/qemu-user-execve/helpers/_build_install_qemu.sh
  recipes/qemu-user-execve/helpers/build-install.sh
  recipes/qemu-user-execve/meta.yaml
  recipes/qemu-user-execve/patches/apply-execve-JH.patch
  recipes/qemu-user-execve/patches/set-qemu-name.patch
  recipes/qemu-user-execve/scripts/activate.sh
  recipes/qemu-user-execve/scripts/deactivate.sh
  recipes/qemu-user-execve/tests/execve_call.c
  recipes/qemu-user-execve/tests/hello_from.c
Labels: review-requested, c-cpp

#29418 add `mxbai-rerank`
  recipes/mxbai-rerank/recipe.yaml
Labels: review-requested, python

#29425 add csp-adapter-discord
  recipes/csp-adapter-discord/recipe.yaml
Labels: review-requested, python

#29355 Adding tailestim
  recipes/tailestim/meta.yaml
Labels: staged-recipes, review-requested, python

#28555 Add libjaylink
  recipes/libjaylink/build.bat
  recipes/libjaylink/build.sh
  recipes/libjaylink/helpers/verify_dll_def.py
  recipes/libjaylink/patches/add-jaylink.def.patch
  recipes/libjaylink/patches/add-jaylink.lib-meson.build.patch
  recipes/libjaylink/patches/enable-dynamic-library.patch
  recipes/libjaylink/patches/fix-types-discovery_tcp.c.patch
  recipes/libjaylink/patches/fix-types-discovery_usb.c.patch
  recipes/libjaylink/patches/fix-types-fileio.c.patch
  recipes/libjaylink/patches/fix-types-socket.c.patch
  recipes/libjaylink/patches/fix-types-strutil.c.patch
  recipes/libjaylink/patches/fix-types-transport_tcp.c.patch
  recipes/libjaylink/patches/fix-types-transport_usb.c.patch
  recipes/libjaylink/patches/fix-uninitialized.patch
  recipes/libjaylink/recipe.yaml
Labels: review-requested, c-cpp

#29410 Add isim package
  recipes/isim/meta.yaml
Labels: review-requested, python

#29343 Adding `femtoscope`
  recipes/femtoscope/meta.yaml
Labels: review-requested, python

#28746 add rb-matrix
  recipes/matrix/LICENSE
  recipes/matrix/conda_build_config.yaml
  recipes/matrix/meta.yaml
Labels: R, review-requested, ruby

#29426 add dxfuse
  recipes/dxfuse/build.sh
  recipes/dxfuse/recipe.yaml
Labels: staged-recipes, review-requested, go

#29427 add kotlin-debug-adapter
  recipes/kotlin-debug-adapter/build.sh
  recipes/kotlin-debug-adapter/recipe.yaml
Labels: staged-recipes, review-requested, java

#29429 add purescript-language-server, purs-backend-erl, purs-backend-es, purs-tidy
  recipes/purescript-language-server/build.sh
  recipes/purescript-language-server/recipe.yaml
  recipes/purs-backend-erl/build.sh
  recipes/purs-backend-erl/recipe.yaml
  recipes/purs-backend-es/build.sh
  recipes/purs-backend-es/recipe.yaml
  recipes/purs-tidy/build.sh
  recipes/purs-tidy/recipe.yaml
Labels: nodejs, staged-recipes, review-requested

#29432 add (python-)blockbuster
  recipes/python-blockbuster/recipe.yaml
Labels: review-requested, python

#29436 add cmigemo, iqplot, maison, pycp
  recipes/cmigemo/LICENSE
  recipes/cmigemo/meta.yaml
  recipes/iqplot/meta.yaml
  recipes/maison/meta.yaml
  recipes/pycp/meta.yaml
Labels: staged-recipes, review-requested, python

#29435 add ansicolor, cmake-language-server, gersemi, pyhpo, torch-geometric
  recipes/ansicolor/LICENSE
  recipes/ansicolor/meta.yaml
  recipes/cmake-language-server/meta.yaml
  recipes/gersemi/meta.yaml
  recipes/pyhpo/meta.yaml
  recipes/torch-geometric/LICENSE
  recipes/torch-geometric/meta.yaml
Labels: staged-recipes, review-requested, python

#29433 add dtrx, ffi-navigator, multicor_fa, neovim-remote, parq2csv
  recipes/dtrx/meta.yaml
  recipes/ffi-navigator/LICENSE
  recipes/ffi-navigator/meta.yaml
  recipes/multicor_fa/meta.yaml
  recipes/neovim-remote/meta.yaml
  recipes/parq2csv/LICENSE
  recipes/parq2csv/meta.yaml
Labels: staged-recipes, review-requested, python

#29437 add bibparse, django-template-lsp, gitlint-core, ocdc, xmlformatter
  recipes/bibparse/meta.yaml
  recipes/django-template-lsp/meta.yaml
  recipes/gitlint-core/meta.yaml
  recipes/ocdc/meta.yaml
  recipes/xmlformatter/meta.yaml
Labels: staged-recipes, review-requested, python

#29441 add mkcert
  recipes/mkcert/recipe.yaml
Labels: review-requested, go

#29443 Adding protarrow
  recipes/protarrow/meta.yaml
Labels: staged-recipes, review-requested, python

#29449 Add sympytensor recipe
  recipes/sympytensor/meta.yaml
Labels: review-requested, python

#29452 add crossplane, djhtml, hydra-lsp, qc2tsv, torch-fftconv
  recipes/crossplane/meta.yaml
  recipes/djhtml/meta.yaml
  recipes/hydra-lsp/meta.yaml
  recipes/qc2tsv/LICENSE
  recipes/qc2tsv/meta.yaml
  recipes/torch-fftconv/LICENSE
  recipes/torch-fftconv/meta.yaml
Labels: staged-recipes, review-requested, python

#29454 add datazets, dmslogo, pyinter, uncertainty-calibration
  recipes/datazets/meta.yaml
  recipes/dmslogo/meta.yaml
  recipes/pyinter/meta.yaml
  recipes/uncertainty-calibration/meta.yaml
Labels: staged-recipes, review-requested, python

#29455 add commanderline, python-help2man
  recipes/commanderline/LICENSE.txt
  recipes/commanderline/meta.yaml
  recipes/python-help2man/meta.yaml
Labels: staged-recipes, review-requested, python

#29459 Add chainlit
  recipes/chainlit/LICENSE
  recipes/chainlit/meta.yaml
Labels: review-requested, python

#29470 add git-imerge, isolearn, py-pcha, setuptools-gettext
  recipes/git-imerge/meta.yaml
  recipes/isolearn/LICENSE
  recipes/isolearn/meta.yaml
  recipes/py-pcha/LICENCE
  recipes/py-pcha/meta.yaml
  recipes/setuptools-gettext/meta.yaml
Labels: staged-recipes, review-requested, python

#29474 add pokeget
  recipes/pokeget/build.bat
  recipes/pokeget/build.sh
  recipes/pokeget/recipe.yaml
Labels: R, review-requested, rust

#29472 add aioice, colt5-attention, keeper-secrets-manager, pykeepass
  recipes/aioice/meta.yaml
  recipes/colt5-attention/meta.yaml
  recipes/keeper-secrets-manager-core/meta.yaml
  recipes/pykeepass/meta.yaml
Labels: staged-recipes, review-requested, python

#29469 Adding gEconpy
  recipes/gEconpy/meta.yaml
Labels: review-requested, python

#29463 Add sxscatalog
  recipes/sxscatalog/meta.yaml
Labels: review-requested, python

#29478 add python-taplo
  recipes/python-taplo/0000-no-rust.patch
  recipes/python-taplo/patch_pyproject.py
  recipes/python-taplo/recipe.yaml
Labels: review-requested, python

#29056 Add khiops recipe
  recipes/khiops-core/bld.bat
  recipes/khiops-core/build.sh
  recipes/khiops-core/conda_build_config.yaml
  recipes/khiops-core/meta.yaml
Labels: Awaiting author contribution, c-cpp

#29465 Add `mplcairo`
  recipes/mplcairo/meta.yaml
Labels: review-requested, python-c

#29483 Add pyzipper
  recipes/pyzipper/meta.yaml
Labels: staged-recipes, review-requested

#29461 build-locally: use argparse option instead of env var
  build-locally.py
  pixi.toml
Labels: maintenance

#29462 Warn about running build-locally on main
  build-locally.py
Labels: maintenance

#29488 add dictionaryutils, drsclient, gen3users, scatterd
  recipes/dictionaryutils/meta.yaml
  recipes/drsclient/meta.yaml
  recipes/gen3users/meta.yaml
  recipes/scatterd/meta.yaml
Labels: staged-recipes, review-requested, python

#29490 add merge3, percol, product-key-memory, pykeepass_cache
  recipes/merge3/meta.yaml
  recipes/percol/LICENSE
  recipes/percol/meta.yaml
  recipes/product-key-memory/meta.yaml
  recipes/pykeepass_cache/LICENSE
  recipes/pykeepass_cache/meta.yaml
Labels: staged-recipes, review-requested, python

#29493 recipe for efficient-apriori
  recipes/efficient-apriori/meta.yaml
Labels: review-requested, python

#29182 add rb-treetop
  recipes/treetop/LICENSE
  recipes/treetop/conda_build_config.yaml
  recipes/treetop/meta.yaml
Labels: R, review-requested, ruby

#29482 Add vampy recipe
  recipes/vampy/meta.yaml
  recipes/vampy/yum_requirements.txt
Labels: review-requested, python

#29484 Add fedfred package
  recipes/fedfred/meta.yaml
Labels: staged-recipes, review-requested, python

#29479 Add opengeotech recipe
  recipes/opengeotech/meta.yaml
  recipes/opengeotech/run_test.py
Labels: review-requested, python

#29498 Add dicttoxml2
  recipes/dicttoxml2/LICENCE.txt
  recipes/dicttoxml2/meta.yaml
Labels: staged-recipes, review-requested

#29499 Add recipe for edgar-sec
  recipes/edgar-sec/meta.yaml
Labels: review-requested, python

#29506 Add ipserver
  recipes/ipserver/meta.yaml
Labels: review-requested, python

#29507 add robotframework-ghareports
  recipes/robotframework-ghareports/recipe.yaml
Labels: review-requested, python

#29451 Add hippogriffe
  recipes/hippogriffe/recipe.yaml
Labels: review-requested, python

#29508 Add dict2xml
  recipes/dict2xml/meta.yaml
Labels: review-requested, python

#29510 add fhirclient, gen3dictionary, pca
  recipes/fhirclient/meta.yaml
  recipes/gen3dictionary/meta.yaml
  recipes/pca/meta.yaml
Labels: staged-recipes, review-requested, python

#29512 add breezy
  recipes/breezy/meta.yaml
Labels: staged-recipes, review-requested, python-c

#29494 Added ecbdata
  recipes/ecbdata/meta.yaml
Labels: review-requested, python

#29500 Add fenicsx-beat
  recipes/fenicsx-beat/meta.yaml
Labels: review-requested, python

#29521 add gradient-aware-harmonisation a harmonisation of two timeseries
  recipes/gradient-aware-harmonisation/meta.yaml
Labels: review-requested, python

#29517 add pidng
  recipes/pidng/meta.yaml
Labels: staged-recipes, review-requested

#29527 add djangocms-link
  recipes/djangocms-link/meta.yaml
Labels: review-requested, python

#29530 Add xcube-multistore
  recipes/xcube-multistore/meta.yaml
Labels: staged-recipes, review-requested, python

#29531 Add Pyone (OpenNebula Python bindings)
  recipes/pyone/meta.yaml
Labels: review-requested, python

#28944 Add renode-cli
  recipes/renode-cli/build.bat
  recipes/renode-cli/build.sh
  recipes/renode-cli/helpers/renode_build_with_dotnet.ps1
  recipes/renode-cli/patches/update-cores.template_NET.csproj.patch
  recipes/renode-cli/recipe.yaml
  recipes/renode-cores/build.bat
  recipes/renode-cores/build.sh
  recipes/renode-cores/helpers/renode_build_with_cmake.ps1
  recipes/renode-cores/recipe.yaml
Labels: staged-recipes, review-requested

#28728 added recipe for `gradient-agreement-filtering`
  recipes/gradient-agreement-filtering/meta.yaml
Labels: review-requested, python

#29540 Add recipe for `openfl`
  recipes/openfl/meta.yaml
Labels: review-requested, python

#29537 add tree-sitter-make
  recipes/tree-sitter-make/meta.yaml
Labels: staged-recipes, review-requested, python-c

#29536 add curlylint, qvalue
  recipes/curlylint/meta.yaml
  recipes/qvalue/0001-use-numpy-import.patch
  recipes/qvalue/LICENSE.txt
  recipes/qvalue/meta.yaml
Labels: staged-recipes, review-requested, python
